# AP BIOLOGY 8.2 Energy Flow Through Ecosystems
# CED effective Fall 2025, Unit 8 Ecology, Big Idea 2 Energetics.
# Learning objectives 8.2.A (describe the strategies organisms use to acquire
# and use energy), 8.2.B (explain how energy flows and matter cycles through
# trophic levels), 8.2.C (explain how changes in energy availability affect
# populations, communities, and ecosystems) and 8.2.D (explain how the
# activities of autotrophs and heterotrophs enable the flow of energy within an
# ecosystem).
# Suggested skill 6.D, explain the relationship between experimental results
# and larger biological concepts, processes, or theories.
#
# Essential knowledge relied on, in the framework's own terms:
#   8.2.A.1  organisms use energy to ORGANIZE, GROW, REPRODUCE, AND MAINTAIN
#            HOMEOSTASIS.
#              i. ENDOTHERMS use thermal energy generated by metabolism to
#                 maintain homeostatic body temperatures. ECTOTHERMS lack
#                 efficient internal mechanisms for maintaining body
#                 temperature, although they may regulate their temperature
#                 BEHAVIORALLY by moving into the sun or shade or by
#                 aggregating with other individuals.
#             ii. a NET GAIN in energy results in energy storage, the growth of
#                 an organism, and increased reproductive output.
#            iii. a NET LOSS of energy results in loss of mass, a decrease in
#                 reproductive output, and, eventually, death.
#   8.2.A.2  different organisms use various reproductive strategies in response
#            to energy availability; some ALTERNATE BETWEEN ASEXUAL AND SEXUAL
#            reproduction in response to energy availability.
#   8.2.B.1  ecological levels of organization include POPULATIONS,
#            COMMUNITIES, ECOSYSTEMS, AND BIOMES.
#   8.2.B.2  ENERGY FLOWS through ecosystems, while MATTER AND NUTRIENTS CYCLE
#            between the environment and organisms via biogeochemical cycles.
#            The cycles are essential for life, EACH DEMONSTRATES THE
#            CONSERVATION OF MATTER, and THE CYCLES ARE INTERDEPENDENT.
#   8.2.B.3  biogeochemical cycles include ABIOTIC AND BIOTIC RESERVOIRS, as
#            well as PROCESSES that cycle matter between reservoirs.
#   8.2.B.4  the hydrologic cycle: reservoirs include OCEANS, SURFACE WATER,
#            THE ATMOSPHERE, AND LIVING ORGANISMS; processes include
#            EVAPORATION, CONDENSATION, PRECIPITATION, AND TRANSPIRATION.
#   8.2.B.5  the carbon cycle recycles carbon through the biosphere into
#            organisms AS CARBOHYDRATES and back into the atmosphere AS CARBON
#            DIOXIDE, and simplifies at the highest level into four parts:
#            PHOTOSYNTHESIS, CELLULAR RESPIRATION, DECOMPOSITION, COMBUSTION.
#   8.2.B.6  the nitrogen cycle involves NITROGEN FIXATION, ASSIMILATION,
#            AMMONIFICATION, NITRIFICATION, AND DENITRIFICATION, performed by
#            MICROORGANISMS IN THE SOIL. THE LARGEST RESERVOIR OF NITROGEN IS
#            THE ATMOSPHERE. In nitrogen fixation, nitrogen gas is fixed into
#            AMMONIA, which IONIZES TO AMMONIUM by acquiring hydrogen ions from
#            the soil solution.
#   8.2.B.7  the phosphorus cycle: WEATHERING ROCKS release PHOSPHATE into soil
#            and groundwater; producers take it up into biological molecules;
#            consumers eat producers; phosphorus returns to the soil via
#            DECOMPOSITION of biomass or EXCRETION.
#   8.2.C.1  changes in energy availability can result in changes in POPULATION
#            SIZE.
#   8.2.C.2  changes in energy availability can result in DISRUPTIONS to an
#            ecosystem. A change in a resource such as sunlight can affect the
#            NUMBER AND SIZE OF THE TROPHIC LEVELS, which include PRODUCERS;
#            PRIMARY, SECONDARY, TERTIARY AND QUATERNARY CONSUMERS; AND
#            DECOMPOSERS. A change in the biomass or number of producers can
#            affect the number and size of other trophic levels.
#   8.2.D.1  AUTOTROPHS capture energy from PHYSICAL OR CHEMICAL sources.
#            Photosynthetic organisms capture energy in sunlight, contributing
#            to primary productivity; CHEMOSYNTHETIC organisms capture energy
#            from SMALL INORGANIC MOLECULES, WHICH CAN OCCUR IN THE ABSENCE OF
#            OXYGEN.
#   8.2.D.2  HETEROTROPHS -- CARNIVORES, HERBIVORES, OMNIVORES, DECOMPOSERS AND
#            SCAVENGERS -- metabolize CARBOHYDRATES, LIPIDS AND PROTEINS as
#            sources of energy, capturing energy in carbon compounds by
#            consuming organic matter derived from autotrophs.
#
# ON THE DATA. All three tables are hypothetical and say so, and every number a
# key states about one is recomputed in verify_b8_2.py from that table alone.
# The trophic table's numbers are the STIMULUS, not a rule to be recalled: the
# CED prints no fixed percentage of energy transferred between trophic levels,
# so no item here asks a student to remember one.
#
# DELIBERATE OMISSIONS. Carrying capacity and density-dependent limits are
# EK 8.4.A and are asked in b8_4; population growth equations are EK 8.3.A and
# are asked in b8_3. The single item here about energy availability and
# population size is keyed to EK 8.2.C.1, which is this topic's own statement
# and mentions neither a rate nor a limit. Species diversity and community
# interactions are EK 8.5 and are asked in b8_5.
#
# FIVE choices (A-E) per SCIENCE_BRIEF.md. No LaTeX: this bank is exported
# untypeset.
TOPIC = ("8.2", "Energy Flow Through Ecosystems", 8)

_T_BUDGET = dict(
    headers=["Group of organisms in a hypothetical study",
             "Change in total body mass over the study, in grams",
             "Mean number of offspring produced per individual"],
    rows=[["Group receiving more food than it uses", "180", "6"],
          ["Group receiving as much food as it uses", "4", "3"],
          ["Group receiving less food than it uses", "-120", "1"]])

_T_TROPHIC = dict(
    headers=["Trophic level", "Biomass in a hypothetical study area, in kilograms"],
    rows=[["Producers", "10000"],
          ["Primary consumers", "1000"],
          ["Secondary consumers", "100"],
          ["Tertiary consumers", "10"]])

_T_PROCESSES = dict(
    headers=["Process", "Cycle in which the framework lists this process"],
    rows=[["Transpiration", "Hydrologic"],
          ["Combustion", "Carbon"],
          ["Denitrification", "Nitrogen"],
          ["Weathering of rock releasing phosphate", "Phosphorus"],
          ["Nitrification", "Nitrogen"]])

QUESTIONS = [
 dict(q="According to the course framework, organisms use energy to do which of the following?",
   choices=[
     "Organize, grow, reproduce, and maintain homeostasis",
     "Grow only, since organization and reproduction require no energy",
     "Reproduce only, since maintenance requires no energy",
     "Maintain homeostasis only, since growth is a passive process",
     "Cycle matter between reservoirs rather than to do any work of their own"], ans=0,
   why="EK 8.2.A.1 states that organisms use energy to organize, grow, reproduce, and maintain homeostasis. Each distractor keeps one item from that list and discards the rest."),

 dict(q="According to the framework, how do endotherms maintain homeostatic body temperatures?",
   choices=[
     "By using thermal energy generated by their own metabolism",
     "By moving into the sun or shade as conditions change",
     "By aggregating with other individuals when it is cold",
     "By allowing body temperature to match the surroundings",
     "By reducing their metabolic rate to that of the surroundings"], ans=0,
   why="EK 8.2.A.1 states that endotherms use thermal energy generated by metabolism to maintain homeostatic body temperatures. Moving into sun or shade and aggregating are the BEHAVIORAL routes the same statement assigns to ectotherms."),

 dict(q="According to the framework, what is true of ectotherms?",
   choices=[
     "They lack efficient internal mechanisms for maintaining body temperature",
     "They generate all their body heat from metabolism",
     "They cannot influence their body temperature in any way",
     "They maintain a constant body temperature independent of their surroundings",
     "They have no metabolism at all"], ans=0,
   why="EK 8.2.A.1 states that ectotherms lack efficient internal mechanisms for maintaining body temperature, ALTHOUGH they may regulate their temperature behaviorally. The word although is why the option denying them any influence is wrong."),

 dict(q="Which of the following does the framework name as a way an ectotherm may regulate its temperature?",
   choices=[
     "Moving into the sun or shade, or aggregating with other individuals",
     "Raising its metabolic rate until its temperature is constant",
     "Generating heat internally as an endotherm does",
     "Altering the temperature of its whole habitat",
     "Ceasing to use energy for any purpose"], ans=0,
   why="EK 8.2.A.1 states that ectotherms may regulate their temperature behaviorally by moving into the sun or shade or by aggregating with other individuals. Those are the two behavioural routes the statement names."),

 dict(q="According to the framework, what results from a net gain in energy for an organism?",
   choices=[
     "Energy storage, growth of the organism, and increased reproductive output",
     "Loss of mass and a decrease in reproductive output",
     "An immediate change in the species to which the organism belongs",
     "A decrease in the organism's metabolic activity to zero",
     "No change of any kind, because surplus energy is discarded"], ans=0,
   why="EK 8.2.A.1 states that a net gain in energy results in energy storage, the growth of an organism, and increased reproductive output. The first distractor is the same statement's account of a net LOSS."),

 dict(q="According to the framework, what results from a net loss of energy for an organism?",
   choices=[
     "Loss of mass, a decrease in reproductive output, and eventually death",
     "Energy storage and growth of the organism",
     "An increase in reproductive output",
     "An immediate increase in body temperature",
     "A permanent gain in body mass"], ans=0,
   why="EK 8.2.A.1 states that a net loss of energy results in loss of mass, a decrease in reproductive output, and, eventually, the death of an organism. The word eventually is why death is the last consequence rather than the first."),

 dict(q="What does the framework say about reproductive strategies and energy availability?",
   choices=[
     "Different organisms use various strategies in response to energy availability, and some alternate between asexual and sexual reproduction",
     "Every organism uses the same reproductive strategy regardless of energy availability",
     "Reproductive strategy is fixed at birth and cannot respond to conditions",
     "Only asexual reproduction responds to energy availability",
     "Energy availability affects growth but never reproduction"], ans=0,
   why="EK 8.2.A.2 states that different organisms use various reproductive strategies in response to energy availability and that some alternate between asexual and sexual reproduction in response to it. Both halves are in the statement."),

 dict(q="Which list names the ecological levels of organization the framework includes?",
   choices=[
     "Populations, communities, ecosystems, and biomes",
     "Cells, tissues, organs, and organ systems",
     "Producers, consumers, and decomposers",
     "Reservoirs, processes, and cycles",
     "Species, genera, families, and orders"], ans=0,
   why="EK 8.2.B.1 states that ecological levels of organization include populations, communities, ecosystems, and biomes. The other lists name levels of organization within an organism, trophic roles, parts of a cycle, or taxonomic ranks."),

 dict(q="Which statement correctly distinguishes what happens to energy from what happens to matter in an ecosystem?",
   choices=[
     "Energy flows through the ecosystem, while matter and nutrients cycle between the environment and organisms",
     "Matter flows through the ecosystem, while energy cycles between the environment and organisms",
     "Both energy and matter cycle, so neither ever leaves the ecosystem",
     "Both energy and matter flow through, so neither is ever reused",
     "Energy and matter are the same quantity described in two ways"], ans=0,
   why="EK 8.2.B.2 states that energy flows through ecosystems while matter and nutrients cycle between the environment and organisms via biogeochemical cycles. The distinction between flowing and cycling is the whole content of the statement."),

 dict(q="What does the framework say about the biogeochemical cycles taken together?",
   choices=[
     "They are essential for life, each demonstrates the conservation of matter, and they are interdependent",
     "They operate independently of one another",
     "They allow matter to be created and destroyed within an ecosystem",
     "They are optional for life in most ecosystems",
     "They apply only to carbon"], ans=0,
   why="EK 8.2.B.2 states all three properties: the cycles are essential for life, each cycle demonstrates the conservation of matter, and the cycles are interdependent. Conservation of matter is why the third option is wrong."),

 dict(q="According to the framework, what do biogeochemical cycles include?",
   choices=[
     "Abiotic and biotic reservoirs, and processes that cycle matter between them",
     "Biotic reservoirs only, since matter is stored only in living things",
     "Abiotic reservoirs only, since living things do not store matter",
     "Processes only, with no reservoirs",
     "A single reservoir shared by every cycle"], ans=0,
   why="EK 8.2.B.3 states that biogeochemical cycles include abiotic and biotic reservoirs as well as processes that cycle matter between reservoirs. Both kinds of reservoir and the processes are named."),

 dict(q="Which of the following does the framework name as a reservoir of the hydrologic cycle?",
   choices=["The atmosphere", "Rock that has not yet weathered",
            "Ammonium in the soil solution", "Carbohydrates in producers",
            "Phosphate in groundwater"], ans=0,
   why="EK 8.2.B.4 names oceans, surface water, the atmosphere and living organisms as reservoirs of the hydrologic cycle. The other options are reservoirs or forms belonging to the phosphorus, nitrogen and carbon cycles."),

 dict(q="Which of the following does the framework name as a process of the hydrologic cycle?",
   choices=["Transpiration", "Nitrification", "Combustion", "Ammonification", "Weathering of rock"], ans=0,
   why="EK 8.2.B.4 names evaporation, condensation, precipitation and transpiration as processes of the hydrologic cycle. Nitrification and ammonification belong to the nitrogen cycle, combustion to the carbon cycle and weathering to the phosphorus cycle."),

 dict(q="At the highest levels of organization, the framework simplifies the carbon cycle into which four parts?",
   choices=[
     "Photosynthesis, cellular respiration, decomposition, and combustion",
     "Evaporation, condensation, precipitation, and transpiration",
     "Fixation, assimilation, nitrification, and denitrification",
     "Weathering, uptake, consumption, and excretion",
     "Growth, reproduction, homeostasis, and organization"], ans=0,
   why="EK 8.2.B.5 states that at the highest levels of organization the carbon cycle can be simplified into four parts: photosynthesis, cellular respiration, decomposition, and combustion. The other lists are the hydrologic and nitrogen cycles, the phosphorus cycle, and the uses of energy."),

 dict(q="According to the framework, in what forms does carbon move into organisms and back into the atmosphere?",
   choices=[
     "Into organisms as carbohydrates and back into the atmosphere as carbon dioxide",
     "Into organisms as carbon dioxide and back into the atmosphere as carbohydrates",
     "Into organisms as ammonium and back into the atmosphere as nitrogen gas",
     "Into organisms as phosphate and back into the soil as phosphate",
     "Into organisms as water vapour and back into the atmosphere as rain"], ans=0,
   why="EK 8.2.B.5 states that the carbon cycle recycles carbon atoms through Earth's biosphere into organisms as carbohydrates and back into the atmosphere as carbon dioxide. Reversing the two forms is what the first distractor does."),

 dict(q="Which list names steps of the nitrogen cycle as the framework gives them?",
   choices=[
     "Nitrogen fixation, assimilation, ammonification, nitrification, and denitrification",
     "Photosynthesis, cellular respiration, decomposition, and combustion",
     "Evaporation, condensation, precipitation, and transpiration",
     "Weathering, uptake by producers, consumption, and excretion",
     "Organization, growth, reproduction, and homeostasis"], ans=0,
   why="EK 8.2.B.6 lists nitrogen fixation, assimilation, ammonification, nitrification and denitrification as steps of the nitrogen cycle, and adds that these steps are performed by microorganisms in the soil."),

 dict(q="According to the framework, what is the largest reservoir of nitrogen?",
   choices=["The atmosphere", "The oceans", "Soil organic matter",
            "The tissues of living organisms", "Weathering rock"], ans=0,
   why="EK 8.2.B.6 states that the largest reservoir of nitrogen is the atmosphere. Rock is the reservoir the framework identifies for phosphorus, in EK 8.2.B.7."),

 dict(q="According to the framework, what happens in nitrogen fixation?",
   choices=[
     "Nitrogen gas is fixed into ammonia, which ionizes to ammonium by acquiring hydrogen ions from the soil solution",
     "Ammonium is converted into nitrogen gas and released to the atmosphere",
     "Phosphate is released from rock into soil and groundwater",
     "Carbon dioxide is converted into carbohydrates",
     "Water moves from living organisms into the atmosphere"], ans=0,
   why="EK 8.2.B.6 states that in nitrogen fixation nitrogen gas is fixed into ammonia, which ionizes to ammonium by acquiring hydrogen ions from the soil solution. Returning nitrogen to the atmosphere is denitrification, a different step in the same list."),

 dict(q="According to the framework, how does phosphorus enter the soil and groundwater?",
   choices=[
     "Weathering of rocks releases phosphate",
     "Microorganisms fix phosphorus from the atmosphere",
     "Phosphorus precipitates from the atmosphere as rain",
     "Producers release phosphate during photosynthesis",
     "Combustion releases phosphate from fossil fuels"], ans=0,
   why="EK 8.2.B.7 states that the phosphorus cycle involves weathering rocks releasing phosphate into soil and groundwater. Fixation from the atmosphere is a nitrogen process, and combustion belongs to the carbon cycle."),

 dict(q="According to the framework, by what routes does phosphorus return to the soil?",
   choices=[
     "Decomposition of biomass, and excretion",
     "Evaporation and condensation",
     "Denitrification and nitrification",
     "Combustion and photosynthesis",
     "Transpiration from producers"], ans=0,
   why="EK 8.2.B.7 states that phosphorus returns to the soil via decomposition of biomass, or excretion, and that phosphate can also be incorporated back into the environment via decomposition of decaying organic matter. The other options name processes of the hydrologic, nitrogen and carbon cycles."),

 dict(q="According to the framework, what can a change in energy availability result in for a population?",
   choices=["A change in population size", "A change in the number of chromosomes carried",
            "An immediate change of species", "A change in the age of the surrounding rocks",
            "No change of any kind"], ans=0,
   why="EK 8.2.C.1 states that changes in energy availability can result in changes in population size. EK 8.2.C.2 adds that such changes can also result in disruptions to an ecosystem."),

 dict(q="Which list names trophic levels as the framework gives them?",
   choices=[
     "Producers; primary, secondary, tertiary, and quaternary consumers; and decomposers",
     "Populations, communities, ecosystems, and biomes",
     "Autotrophs and heterotrophs only",
     "Reservoirs, processes, and cycles",
     "Endotherms and ectotherms"], ans=0,
   why="EK 8.2.C.2 states that trophic levels include producers; primary, secondary, tertiary, and quaternary consumers; and decomposers. Populations through biomes are the ecological levels of organization in EK 8.2.B.1, which is a different list."),

 dict(q="According to the framework, from what do autotrophs capture energy?",
   choices=[
     "Physical or chemical sources in the environment",
     "Organic matter derived from other organisms",
     "The tissues of heterotrophs only",
     "Decaying organic matter only",
     "Nothing, since autotrophs do not require energy"], ans=0,
   why="EK 8.2.D.1 states that autotrophs capture energy from physical or chemical sources in the environment. Capturing energy present in carbon compounds by consuming organic matter is what EK 8.2.D.2 assigns to heterotrophs."),

 dict(q="What does the framework say about chemosynthetic organisms?",
   choices=[
     "They capture energy from small inorganic molecules, which can occur in the absence of oxygen",
     "They capture energy present in sunlight",
     "They obtain energy by consuming organic matter derived from autotrophs",
     "They require oxygen in every case",
     "They are a kind of heterotroph"], ans=0,
   why="EK 8.2.D.1 states that chemosynthetic organisms capture energy from small inorganic molecules present in their environment, which can occur in the absence of oxygen. They are autotrophs in the same statement, and capturing sunlight is what the photosynthetic organisms of that statement do."),

 dict(q="Which group does the framework identify as heterotrophs, and what do they metabolize as sources of energy?",
   choices=[
     "Carnivores, herbivores, omnivores, decomposers, and scavengers, metabolizing carbohydrates, lipids, and proteins",
     "Photosynthetic and chemosynthetic organisms, metabolizing sunlight and inorganic molecules",
     "Producers only, metabolizing carbon dioxide",
     "Decomposers only, metabolizing water and minerals",
     "Endotherms only, metabolizing thermal energy"], ans=0,
   why="EK 8.2.D.2 names carnivores, herbivores, omnivores, decomposers and scavengers as heterotrophs and states that they metabolize carbohydrates, lipids and proteins as sources of energy. Photosynthetic and chemosynthetic organisms are the autotrophs of EK 8.2.D.1."),

 dict(q="The table reports three groups of one species in a hypothetical study, their change in total body mass, and their mean reproductive output. Which group's results match what the framework predicts for a net gain in energy?",
   table=_T_BUDGET,
   choices=[
     "The group receiving more food than it uses",
     "The group receiving as much food as it uses",
     "The group receiving less food than it uses",
     "All three groups equally",
     "None of the groups, because mass and reproduction are unrelated"], ans=0,
   why="EK 8.2.A.1 states that a net gain in energy results in energy storage, growth of the organism, and increased reproductive output. The row combining the largest gain in mass with the largest reproductive output is the one that matches."),

 dict(q="Using the same three groups, which results match what the framework predicts for a net loss of energy?",
   table=_T_BUDGET,
   choices=[
     "A loss of body mass together with the lowest reproductive output",
     "A gain in body mass together with the lowest reproductive output",
     "A loss of body mass together with the highest reproductive output",
     "No change in body mass together with the highest reproductive output",
     "A gain in body mass together with the highest reproductive output"], ans=0,
   why="EK 8.2.A.1 states that a net loss of energy results in loss of mass and a decrease in reproductive output. Exactly one row of the table records a negative change in mass, and that row also records the smallest number of offspring."),

 dict(q="The table gives the biomass at four trophic levels in a hypothetical study area. What is the ratio of the biomass at each level to the biomass at the level immediately above it in the table?",
   table=_T_TROPHIC,
   choices=["10 to 1", "2 to 1", "5 to 1", "100 to 1", "1 to 10"], ans=0,
   why="Skill 5.A includes ratios. Dividing each level's biomass by that of the level below it in the table gives the same value at every step, which is what makes a single ratio the right description of these particular data."),

 dict(q="Using the same trophic biomass data, what does the framework predict would happen if the biomass of producers in that area fell sharply?",
   table=_T_TROPHIC,
   choices=[
     "The number and size of the other trophic levels could be affected",
     "Only the producers would be affected, since each level is independent",
     "The consumers would increase, because less competition would remain",
     "The ratio between levels would be unaffected because it is fixed by law",
     "The area would gain an additional trophic level"], ans=0,
   why="EK 8.2.C.2 states that a change in the biomass or number of producers in a given geographic area can affect the number and size of other trophic levels. The table shows every level above the producers holding less biomass than the level below it, which is the dependence that statement describes."),

 dict(q="The table lists five processes and the cycle in which the framework places each. How many of the listed processes are steps of the nitrogen cycle?",
   table=_T_PROCESSES,
   choices=["Two", "One", "Three", "Four", "Five"], ans=0,
   why="EK 8.2.B.6 lists nitrogen fixation, assimilation, ammonification, nitrification and denitrification as steps of the nitrogen cycle. Counting the rows the table assigns to that cycle gives the answer, and the remaining rows belong to the hydrologic, carbon and phosphorus cycles."),
]
