# CALC 5.12 Exploring Behaviors of Implicit Relations — 25 questions
# Answers verified with sympy; see verify_c5_12.py, which uses sympy's idiff
# to differentiate each relation implicitly and then solves for the points
# where the tangent is horizontal (dy/dx = 0) or vertical (the denominator
# vanishes while the numerator does not).
TOPIC = ("5.12", "Exploring Behaviors of Implicit Relations", 5)
QUESTIONS = [
 dict(q="For the circle x^2 + y^2 = 25, dy/dx equals",
   choices=["-x/y", "x/y", "-y/x", "-2x"], ans=0,
   why="Differentiating gives 2x + 2y dy/dx = 0."),
 dict(q="For x^2 + y^2 = 25, the tangent line is horizontal at",
   choices=[
   "(0, 5) and (0, -5)",
   "(5, 0) and (-5, 0)",
   "(3, 4) and (-3, -4)",
   "no point of the circle"], ans=0,
   why="dy/dx = -x/y is zero when x = 0, and the corresponding y-values are +/- 5."),
 dict(q="For x^2 + y^2 = 25, the tangent line is vertical at",
   choices=[
   "(5, 0) and (-5, 0)",
   "(0, 5) and (0, -5)",
   "(4, 3) and (-4, -3)",
   "no point of the circle"], ans=0,
   why="dy/dx = -x/y is undefined where y = 0, and those points are (+/- 5, 0)."),
 dict(q="For x^2 + y^2 = 25, the slope of the tangent line at the point (3, 4) is",
   choices=["-3/4", "3/4", "-4/3", "4/3"], ans=0,
   why="dy/dx = -x/y = -3/4 at that point."),
 dict(q="For x^2 + y^2 = 25, the slope of the line normal to the curve at (3, 4) is",
   choices=["4/3", "-3/4", "-4/3", "3/4"], ans=0,
   why="The normal is perpendicular to the tangent, whose slope is -3/4, so the normal slope is 4/3, and indeed the normal passes through the center."),
 dict(q="For x^2 + y^2 = 8, the tangent line has slope 1 at",
   choices=[
   "(2, -2) and (-2, 2)",
   "(2, 2) and (-2, -2)",
   "(2 sqrt(2), 0) and (-2 sqrt(2), 0)",
   "no point of the curve"], ans=0,
   why="-x/y = 1 gives y = -x, and substituting gives 2x^2 = 8, so x = +/- 2."),
 dict(q="For x^2 + y^2 = 25, the second derivative d^2y/dx^2 equals",
   choices=["-25/y^3", "-1/y", "25/y^3", "-x^2/y^3"], ans=0,
   why="Differentiating dy/dx = -x/y gives (-y + x dy/dx)/y^2 = -(x^2 + y^2)/y^3 = -25/y^3."),
 dict(q="On the upper half of the circle x^2 + y^2 = 25, where y > 0, the curve is",
   choices=[
   "concave down, since d^2y/dx^2 = -25/y^3 < 0",
   "concave up, since d^2y/dx^2 = 25/y^3 > 0",
   "concave down for x < 0 and concave up for x > 0",
   "straight"], ans=0,
   why="With y > 0 the expression -25/y^3 is negative everywhere on that arc, which matches the shape of the upper semicircle."),
 dict(q="For the ellipse x^2/9 + y^2/4 = 1, dy/dx equals",
   choices=["-4x/(9y)", "-9x/(4y)", "-x/y", "-2x/(3y)"], ans=0,
   why="Differentiating gives 2x/9 + (y/2) dy/dx = 0, so dy/dx = -4x/(9y)."),
 dict(q="For x^2 + 4y^2 = 16, the tangent line is vertical at",
   choices=[
   "(4, 0) and (-4, 0)",
   "(0, 2) and (0, -2)",
   "(0, 4) and (0, -4)",
   "(2, 0) and (-2, 0)"], ans=0,
   why="dy/dx = -x/(4y) is undefined when y = 0, which gives x^2 = 16."),
 dict(q="For the hyperbola x^2 - y^2 = 1, dy/dx equals",
   choices=["x/y", "-x/y", "y/x", "-y/x"], ans=0,
   why="Differentiating gives 2x - 2y dy/dx = 0."),
 dict(q="The hyperbola x^2 - y^2 = 1 has",
   choices=[
   "vertical tangents at (1, 0) and (-1, 0) and no horizontal tangent",
   "horizontal tangents at (1, 0) and (-1, 0)",
   "both horizontal and vertical tangents",
   "neither horizontal nor vertical tangents"], ans=0,
   why="dy/dx = x/y is zero only if x = 0, which no point of the curve satisfies, and it is undefined where y = 0."),
 dict(q="For xy = 1, dy/dx equals",
   choices=["-y/x", "y/x", "-x/y", "1/x"], ans=0,
   why="Differentiating the product gives y + x dy/dx = 0."),
 dict(q="The curve xy = 1 has",
   choices=[
   "no horizontal or vertical tangents, and it is decreasing on each branch",
   "a horizontal tangent at (1, 1)",
   "a vertical tangent at the origin",
   "a horizontal tangent at (-1, -1)"], ans=0,
   why="dy/dx = -y/x = -1/x^2 is negative and never zero on the curve, and x = 0 is not on the curve."),
 dict(q="For x^2 + xy + y^2 = 3, dy/dx equals",
   choices=[
   "-(2x + y)/(x + 2y)",
   "-(2x + y)/(2y)",
   "(2x + y)/(x + 2y)",
   "-(x + 2y)/(2x + y)"], ans=0,
   why="Differentiating gives 2x + y + x dy/dx + 2y dy/dx = 0."),
 dict(q="For x^2 + xy + y^2 = 3, the tangent line is horizontal at",
   choices=[
   "(1, -2) and (-1, 2)",
   "(1, 2) and (-1, -2)",
   "(sqrt(3), 0) and (-sqrt(3), 0)",
   "no point of the curve"], ans=0,
   why="Setting 2x + y = 0 gives y = -2x, and substituting gives 3x^2 = 3, so x = +/- 1."),
 dict(q="For x^3 + y^3 = 6xy, dy/dx equals",
   choices=[
   "(6y - 3x^2)/(3y^2 - 6x)",
   "(3x^2 - 6y)/(3y^2 - 6x)",
   "(6y - 3x^2)/(6x - 3y^2)",
   "(6x - 3y^2)/(3y^2 - 6x)"], ans=0,
   why="Differentiating gives 3x^2 + 3y^2 dy/dx = 6y + 6x dy/dx, and collecting the dy/dx terms gives that quotient."),
 dict(q="For x^3 + y^3 = 6xy, the tangent line is horizontal at points where",
   choices=[
   "y = x^2/2, provided 3y^2 - 6x is not also zero",
   "y = 2x^2",
   "x = y^2/2",
   "x = y"], ans=0,
   why="The numerator 6y - 3x^2 vanishes when y = x^2/2, and a horizontal tangent also requires the denominator to be nonzero."),
 dict(q="For y^3 - y = x^2, the tangent line is horizontal at",
   choices=[
   "three points, all with x = 0",
   "two points, both with y = 0",
   "one point only",
   "no point"], ans=0,
   why="dy/dx = 2x/(3y^2 - 1) is zero only when x = 0, and then y^3 - y = 0 gives y = 0, 1, and -1."),
 dict(q="For the astroid x^(2/3) + y^(2/3) = 1, dy/dx equals",
   choices=[
   "-(y/x)^(1/3)",
   "-(x/y)^(1/3)",
   "(y/x)^(1/3)",
   "-(y/x)^(2/3)"], ans=0,
   why="Differentiating gives (2/3)x^(-1/3) + (2/3)y^(-1/3) dy/dx = 0, so dy/dx = -(y/x)^(1/3)."),
 dict(q="For x^2 y + y^2 = 5, dy/dx equals",
   choices=[
   "-2xy/(x^2 + 2y)",
   "-2xy/(x^2 + y)",
   "2xy/(x^2 + 2y)",
   "-(2xy + x^2)/(2y)"], ans=0,
   why="Differentiating gives 2xy + x^2 dy/dx + 2y dy/dx = 0."),
 dict(q="For the circle x^2 + y^2 - 2x - 4y = 0, the tangent line is horizontal at",
   choices=[
   "(1, 2 + sqrt(5)) and (1, 2 - sqrt(5))",
   "(1 + sqrt(5), 2) and (1 - sqrt(5), 2)",
   "(0, 0) and (2, 4)",
   "(1, 2) only"], ans=0,
   why="dy/dx = (2 - 2x)/(2y - 4) is zero when x = 1, and the circle has center (1, 2) and radius sqrt(5)."),
 dict(q="A point (a, b) can be a point of vertical tangency on an implicitly defined curve when",
   choices=[
   "the denominator of dy/dx is zero there while the numerator is not",
   "both the numerator and the denominator of dy/dx are zero there",
   "dy/dx equals zero there",
   "the point fails to satisfy the equation"], ans=0,
   why="A vanishing denominator with a nonzero numerator makes the slope blow up, which is a vertical tangent; if both vanish the behavior needs a closer look."),
 dict(q="Before using a point in an implicit differentiation problem, it is essential to",
   choices=[
   "check that the point actually satisfies the original equation",
   "check that the point makes dy/dx zero",
   "solve the equation explicitly for y",
   "check that the point is in the first quadrant"], ans=0,
   why="A slope formula evaluated at a point that is not on the curve describes nothing; for x^2 + y^2 = 25 the point (3, 5) gives a number but is not on the circle."),
 dict(q="The relation y^2 = x defines",
   choices=[
   "a curve that is not the graph of a single function of x, with a vertical tangent at the origin",
   "a function of x with a horizontal tangent at the origin",
   "a curve with no tangent line at the origin at all",
   "a parabola opening upward"], ans=0,
   why="Each positive x gives two y-values, and dy/dx = 1/(2y) is undefined at y = 0, where the tangent is the vertical line x = 0."),
]
