# CALC 5.11 Solving Optimization Problems — 25 questions
# Answers verified with sympy; see verify_c5_11.py, which solves each model,
# confirms the critical number, and checks the sign of the second derivative
# (or compares candidate values) so that every optimum is proved to be a
# maximum or a minimum rather than merely a stationary point.
TOPIC = ("5.11", "Solving Optimization Problems", 5)
QUESTIONS = [
 dict(q="Among all rectangles with perimeter 40, the largest possible area is",
   choices=["80", "100", "120", "400"], ans=1,
   why="A(w) = w(20 - w) has A'(w) = 20 - 2w = 0 at w = 10, where A'' = -2 < 0, giving A = 100."),
 dict(q="Among all rectangles with a fixed perimeter, the one of largest area is",
   choices=[
   "a square",
   "a rectangle twice as long as it is wide",
   "the one whose width approaches zero",
   "not determined by the perimeter"], ans=0,
   why="Maximizing w(P/2 - w) gives w = P/4, so the two dimensions are equal."),
 dict(q="A rectangular field is fenced on three sides with 600 feet of fence, the fourth side being a river. The largest area that can be enclosed is",
   choices=["45,000 square feet", "22,500 square feet", "90,000 square feet", "30,000 square feet"], ans=0,
   why="A(x) = x(600 - 2x) has A'(x) = 600 - 4x = 0 at x = 150, where A'' = -4 < 0, giving A = 150 * 300 = 45,000."),
 dict(q="Two positive numbers have a sum of 20. Their largest possible product is",
   choices=["80", "96", "100", "400"], ans=2,
   why="P(x) = x(20 - x) has P'(x) = 20 - 2x = 0 at x = 10, and P'' = -2 < 0, so the numbers are 10 and 10."),
 dict(q="Two positive numbers have a product of 100. Their smallest possible sum is",
   choices=["20", "25", "50", "101"], ans=0,
   why="S(x) = x + 100/x has S'(x) = 1 - 100/x^2 = 0 at x = 10, where S'' = 200/x^3 > 0, giving 10 + 10 = 20."),
 dict(q="Two numbers have a sum of 20. The smallest possible value of the sum of their squares is",
   choices=["50", "100", "200", "400"], ans=2,
   why="f(x) = x^2 + (20 - x)^2 has f'(x) = 4x - 40 = 0 at x = 10, where f'' = 4 > 0, giving 100 + 100 = 200."),
 dict(q="An open-top box is made from a 12-inch square sheet by cutting squares of side x from the corners. The maximum volume is",
   choices=["128 cubic inches", "144 cubic inches", "108 cubic inches", "64 cubic inches"], ans=0,
   why="V(x) = x(12 - 2x)^2 has V'(x) = 12(x - 2)(x - 6), and only x = 2 lies in (0, 6), where V(2) = 2 * 64 = 128."),
 dict(q="A closed cylindrical can must hold 16 pi cubic inches. The radius that minimizes its surface area is",
   choices=["2 inches", "4 inches", "1 inch", "8 inches"], ans=0,
   why="With h = 16/r^2, S(r) = 2 pi r^2 + 32 pi/r and S'(r) = 4 pi r - 32 pi/r^2 = 0 gives r^3 = 8."),
 dict(q="For the closed cylinder of least surface area holding a given volume, the height and radius satisfy",
   choices=["h = 2r", "h = r", "h = 4r", "h = pi r"], ans=0,
   why="Minimizing 2 pi r^2 + 2V/r gives r^3 = V/(2 pi), and substituting into h = V/(pi r^2) gives h = 2r."),
 dict(q="An open-top box with a square base must hold 32 cubic inches. The least surface area it can have is",
   choices=["48 square inches", "32 square inches", "64 square inches", "96 square inches"], ans=0,
   why="S(x) = x^2 + 128/x has S'(x) = 2x - 128/x^2 = 0 at x = 4, where S'' > 0, and S(4) = 16 + 32 = 48."),
 dict(q="A rectangle has its base on the x-axis and its upper vertices on y = 9 - x^2. Its largest possible area is",
   choices=["12 sqrt(3)", "18", "9 sqrt(3)", "36"], ans=0,
   why="A(x) = 2x(9 - x^2) has A'(x) = 18 - 6x^2 = 0 at x = sqrt(3), giving A = 2 sqrt(3) * 6 = 12 sqrt(3)."),
 dict(q="A rectangle with sides parallel to the axes is inscribed in the circle x^2 + y^2 = 25. Its largest possible area is",
   choices=["50", "25", "100", "25 pi"], ans=0,
   why="A(x) = 4x sqrt(25 - x^2) is largest at x = 5/sqrt(2), where the rectangle is a square of side 5 sqrt(2) and area 50."),
 dict(q="The point on the curve y = sqrt(x) closest to (3, 0) has x-coordinate",
   choices=["5/2", "3", "2", "9/4"], ans=0,
   why="Minimizing D(x) = (x - 3)^2 + x gives D'(x) = 2x - 5 = 0, and D'' = 2 > 0."),
 dict(q="The shortest distance from the point (0, 2) to the parabola y = x^2 is",
   choices=["sqrt(7)/2", "2", "sqrt(3)/2", "3/2"], ans=0,
   why="Minimizing x^2 + (x^2 - 2)^2 gives 2x(2x^2 - 3) = 0, and x^2 = 3/2 gives squared distance 3/2 + 1/4 = 7/4."),
 dict(q="A 60-inch wire is cut into two pieces, one bent into a square and the other into a circle. The total enclosed area is smallest when the piece bent into the square has length",
   choices=["240/(pi + 4) inches", "60/(pi + 4) inches", "30 inches", "0 inches"], ans=0,
   why="A(x) = x^2/16 + (60 - x)^2/(4 pi) has A'(x) = x/8 - (60 - x)/(2 pi) = 0, which rearranges to x(pi + 4) = 240."),
 dict(q="With price per unit p = 100 - 2x when x units are sold, revenue is greatest when x equals",
   choices=["20", "25", "50", "100"], ans=1,
   why="R(x) = 100x - 2x^2 has R'(x) = 100 - 4x = 0 at x = 25, where R'' = -4 < 0."),
 dict(q="With revenue R(x) = x(100 - 2x) and cost C(x) = 20x + 200, the maximum profit is",
   choices=["400", "600", "800", "1250"], ans=1,
   why="P(x) = 80x - 2x^2 - 200 has P'(x) = 80 - 4x = 0 at x = 20, and P(20) = 1600 - 800 - 200 = 600."),
 dict(q="A rectangular pen of area 200 square feet is split into two equal parts by a fence parallel to one pair of sides. The least total length of fencing is",
   choices=["40 sqrt(3) feet", "60 feet", "20 sqrt(3) feet", "80 feet"], ans=0,
   why="F(x) = 3x + 400/x has F'(x) = 3 - 400/x^2 = 0 at x = 20/sqrt(3), and F there equals 20 sqrt(3) + 20 sqrt(3)."),
 dict(q="A Norman window (a rectangle topped by a semicircle) has perimeter 30 feet. The radius of the semicircle that maximizes the area is",
   choices=["30/(pi + 4)", "15/(pi + 4)", "30/(pi + 2)", "15/pi"], ans=0,
   why="A(r) = 30r - 2r^2 - (pi r^2)/2 has A'(r) = 30 - 4r - pi r = 0."),
 dict(q="A poster must contain 24 square inches of print with 1-inch side margins and 2-inch top and bottom margins. The least possible total area of the poster is",
   choices=[
   "32 + 16 sqrt(3) square inches",
   "24 + 16 sqrt(3) square inches",
   "56 square inches",
   "48 square inches"], ans=0,
   why="A(x) = 4x + 48/x + 32 has A'(x) = 4 - 48/x^2 = 0 at x = 2 sqrt(3), giving 8 sqrt(3) + 8 sqrt(3) + 32."),
 dict(q="For x > 0, the minimum value of f(x) = x^2 + 16/x is",
   choices=["8", "10", "12", "16"], ans=2,
   why="f'(x) = 2x - 16/x^2 = 0 gives x^3 = 8, and f(2) = 4 + 8 = 12 with f'' > 0."),
 dict(q="A boat is 2 km from the nearest point A on a straight shore, and a village lies 6 km down the shore from A. If the boat is rowed at 3 km/h and the passenger walks at 5 km/h, the landing point that minimizes total travel time is",
   choices=[
   "1.5 km from A",
   "2 km from A",
   "3 km from A",
   "at A itself"], ans=0,
   why="T(x) = sqrt(4 + x^2)/3 + (6 - x)/5 gives x/(3 sqrt(4 + x^2)) = 1/5, hence 25x^2 = 9(4 + x^2) and x = 3/2."),
 dict(q="A farmer uses 100 feet of fence to build a rectangular pen with one side along an existing barn wall. The largest area is",
   choices=["1250 square feet", "625 square feet", "2500 square feet", "1000 square feet"], ans=0,
   why="A(x) = x(100 - 2x) has A'(x) = 100 - 4x = 0 at x = 25, giving 25 * 50 = 1250."),
 dict(q="A rectangle is to satisfy x + 2y = 12 with x and y positive. The largest possible value of xy is",
   choices=["12", "18", "24", "36"], ans=1,
   why="With y = (12 - x)/2 the product is x(12 - x)/2, largest at x = 6, giving 6 * 3 = 18."),
 dict(q="After finding the only critical number of an objective function on an open interval, the way to confirm it gives a maximum is to",
   choices=[
   "check that f'' is negative there, or that f' changes from positive to negative",
   "check that the constraint is satisfied",
   "evaluate the objective at the endpoints, which are not in the interval",
   "confirm that f is positive there"], ans=0,
   why="On an open interval there are no endpoints to compare, so the conclusion has to come from one of the two derivative tests."),
]
