# CALC 5.10 Introduction to Optimization Problems — 25 questions
# Answers verified with sympy; see verify_c5_10.py.
# This topic is about setting a problem up: naming the quantity to be
# optimized, using the constraint to reduce it to one variable, and stating
# the domain. Every algebraic model below is confirmed by eliminating the
# constrained variable symbolically. Questions 1, 2 and 3 describe the method
# itself and carry no computation.
TOPIC = ("5.10", "Introduction to Optimization Problems", 5)
QUESTIONS = [
 dict(q="In an optimization problem, the first step after naming the variables is to",
   choices=[
   "write the quantity to be optimized as a function of one variable, using the constraint to eliminate the others",
   "differentiate the constraint equation",
   "set the constraint equal to zero",
   "find the second derivative of the constraint"], ans=0,
   why="Only after the objective is a function of a single variable can its derivative be used to locate the optimum."),
 dict(q="In an optimization problem, the constraint equation is",
   choices=[
   "the relationship among the variables that is fixed by the problem, used to eliminate a variable",
   "the quantity being maximized or minimized",
   "always the perimeter",
   "the derivative set equal to zero"], ans=0,
   why="The constraint is the fixed condition, and the objective is the quantity to be optimized; they play different roles."),
 dict(q="Stating the domain of the objective function matters because",
   choices=[
   "the physical situation restricts the variable, and the endpoints of that interval are candidates for the extremum",
   "the derivative is undefined outside it",
   "the constraint is only true on that interval",
   "it determines whether f is continuous"], ans=0,
   why="A length or a radius cannot be negative, and the candidates test needs the interval's endpoints as well as its critical numbers."),
 dict(q="A rectangle has perimeter 40. If its width is w, its area as a function of w is",
   choices=["A(w) = w(20 - w)", "A(w) = w(40 - w)", "A(w) = w(40 - 2w)", "A(w) = (20 - w)^2"], ans=0,
   why="The perimeter gives 2w + 2L = 40, so L = 20 - w and A = wL = w(20 - w)."),
 dict(q="For the rectangle of perimeter 40 with width w, the domain of the area function is",
   choices=["0 < w < 20", "0 < w < 40", "0 < w < 10", "all real w"], ans=0,
   why="Both the width w and the length 20 - w must be positive."),
 dict(q="A rectangular field is fenced on three sides, the fourth side being a straight river, using 600 feet of fence. If x is the length of each of the two sides perpendicular to the river, the enclosed area is",
   choices=["A(x) = x(600 - 2x)", "A(x) = x(600 - x)", "A(x) = 2x(600 - x)", "A(x) = x(300 - x)"], ans=0,
   why="The side parallel to the river uses the remaining 600 - 2x feet of fence."),
 dict(q="An open-top box is made from a 12-inch by 12-inch sheet by cutting a square of side x from each corner and folding up the sides. The volume is",
   choices=["V(x) = x(12 - 2x)^2", "V(x) = x(12 - x)^2", "V(x) = x^2(12 - 2x)", "V(x) = 2x(12 - 2x)^2"], ans=0,
   why="The base is a square of side 12 - 2x and the height is x."),
 dict(q="For that open-top box, the domain of V is",
   choices=["0 < x < 6", "0 < x < 12", "0 < x < 3", "x > 0"], ans=0,
   why="The cut must be positive and the remaining side 12 - 2x must also be positive."),
 dict(q="A closed cylindrical can must hold 355 cubic centimeters. Its surface area as a function of the base radius r is",
   choices=[
   "S(r) = 2 pi r^2 + 710/r",
   "S(r) = 2 pi r^2 + 355/r",
   "S(r) = pi r^2 + 710/r",
   "S(r) = 2 pi r^2 + 710 pi/r"], ans=0,
   why="From pi r^2 h = 355 we get h = 355/(pi r^2), and S = 2 pi r^2 + 2 pi r h = 2 pi r^2 + 710/r."),
 dict(q="An open-top box with a square base must have volume 32 cubic inches. Its surface area as a function of the base edge x is",
   choices=[
   "S(x) = x^2 + 128/x",
   "S(x) = x^2 + 32/x",
   "S(x) = 4x^2 + 128/x",
   "S(x) = x^2 + 128/x^2"], ans=0,
   why="From x^2 h = 32 we get h = 32/x^2, and S = x^2 + 4xh = x^2 + 128/x."),
 dict(q="Two positive numbers have a sum of 20. Their product as a function of the smaller number x is",
   choices=["P(x) = x(20 - x)", "P(x) = 20 - x^2", "P(x) = 20x", "P(x) = x^2 - 20x"], ans=0,
   why="The second number is 20 - x, so the product is x(20 - x)."),
 dict(q="Two positive numbers have a product of 100. Their sum as a function of one of them, x, is",
   choices=["S(x) = x + 100/x on x > 0", "S(x) = x + 100 on x > 0", "S(x) = 100/x on x > 0", "S(x) = x(100 - x)"], ans=0,
   why="The other number is 100/x, and both must be positive."),
 dict(q="A rectangle has its base on the x-axis and its two upper vertices on the parabola y = 9 - x^2. If the upper right vertex is (x, 9 - x^2), the area is",
   choices=["A(x) = 2x(9 - x^2) on 0 < x < 3", "A(x) = x(9 - x^2) on 0 < x < 3", "A(x) = 2x(9 - x^2) on 0 < x < 9", "A(x) = (9 - x^2)^2"], ans=0,
   why="The rectangle runs from -x to x, so its width is 2x and its height is 9 - x^2, which stays positive only for x < 3."),
 dict(q="A rectangle is inscribed in a circle of radius 5 centered at the origin, with sides parallel to the axes. If the upper right corner is (x, y), the area is",
   choices=[
   "A(x) = 4x sqrt(25 - x^2) on 0 < x < 5",
   "A(x) = 2x sqrt(25 - x^2) on 0 < x < 5",
   "A(x) = x sqrt(25 - x^2) on 0 < x < 25",
   "A(x) = 4x(25 - x^2)"], ans=0,
   why="The rectangle has width 2x and height 2y with y = sqrt(25 - x^2)."),
 dict(q="To find the point on the curve y = sqrt(x) closest to the point (3, 0), it is enough to minimize",
   choices=[
   "the squared distance D(x) = (x - 3)^2 + x for x >= 0",
   "the distance x - 3",
   "the function y = sqrt(x)",
   "the squared distance (x - 3)^2 + x^2"], ans=0,
   why="Squaring removes the radical without moving the minimum, since the square root is increasing, and y^2 = x on the curve."),
 dict(q="Minimizing the square of a distance rather than the distance itself is legitimate because",
   choices=[
   "the squaring function is increasing on the nonnegative numbers, so both are smallest at the same point",
   "distance and squared distance are equal",
   "the derivative of the square root is always zero",
   "the square root of a minimum is a minimum of the square root only at endpoints"], ans=0,
   why="A monotone transformation cannot move the location of a minimum, and it makes the derivative far easier."),
 dict(q="A wire of length 60 inches is cut into two pieces. One piece of length x is bent into a square and the rest into a circle. The total enclosed area is",
   choices=[
   "A(x) = x^2/16 + (60 - x)^2/(4 pi) on 0 <= x <= 60",
   "A(x) = x^2/16 + (60 - x)^2/(2 pi) on 0 <= x <= 60",
   "A(x) = x^2/4 + pi (60 - x)^2 on 0 <= x <= 60",
   "A(x) = x^2/16 + (60 - x)^2/(4 pi) on 0 < x < 30"], ans=0,
   why="A square of perimeter x has area (x/4)^2, and a circle of circumference 60 - x has radius (60 - x)/(2 pi) and area (60 - x)^2/(4 pi)."),
 dict(q="A demand relationship gives the price per unit as p = 100 - 2x when x units are sold. The revenue function is",
   choices=["R(x) = x(100 - 2x)", "R(x) = 100 - 2x", "R(x) = 100x - 2x", "R(x) = (100 - 2x)/x"], ans=0,
   why="Revenue is price times quantity."),
 dict(q="If revenue is R(x) = x(100 - 2x) and cost is C(x) = 20x + 200, the profit function to be maximized is",
   choices=[
   "P(x) = 80x - 2x^2 - 200",
   "P(x) = 100x - 2x^2 + 20x + 200",
   "P(x) = 120x - 2x^2 + 200",
   "P(x) = 80x - 2x^2 + 200"], ans=0,
   why="P = R - C = 100x - 2x^2 - 20x - 200."),
 dict(q="A rectangular pen of area 200 square feet is divided into two equal parts by a fence parallel to one pair of sides. If x is the length of that dividing fence, the total length of fencing is",
   choices=[
   "F(x) = 3x + 400/x on x > 0",
   "F(x) = 2x + 400/x on x > 0",
   "F(x) = 3x + 200/x on x > 0",
   "F(x) = 4x + 200/x on x > 0"], ans=0,
   why="With the other dimension y = 200/x, the fence consists of three sides of length x and two of length y, giving 3x + 400/x."),
 dict(q="A Norman window is a rectangle topped by a semicircle. If the perimeter is 30 feet and the rectangle's width is 2r, the area as a function of r is",
   choices=[
   "A(r) = 30r - 2r^2 - (pi r^2)/2",
   "A(r) = 30r - 2r^2 + (pi r^2)/2",
   "A(r) = 30r - r^2 - pi r^2",
   "A(r) = 15r - 2r^2 - (pi r^2)/2"], ans=0,
   why="The perimeter 2r + 2h + pi r = 30 gives h = (30 - 2r - pi r)/2, and A = 2rh + (pi r^2)/2 = 30r - 2r^2 - (pi r^2)/2."),
 dict(q="A poster has 24 square inches of printed area, with 1-inch margins at the sides and 2-inch margins at the top and bottom. If the printed area is x inches wide, the total area of the poster is",
   choices=[
   "A(x) = (x + 2)(24/x + 4)",
   "A(x) = (x + 1)(24/x + 2)",
   "A(x) = (x + 2)(24/x + 2)",
   "A(x) = x(24/x + 4)"], ans=0,
   why="The printed height is 24/x, and the poster measures x + 2 by 24/x + 4."),
 dict(q="Once the objective has been written as a function of one variable on a closed interval, the optimum is found by",
   choices=[
   "comparing the values of that function at its critical numbers and at the endpoints",
   "comparing the values of its derivative at the endpoints",
   "setting the second derivative equal to zero",
   "maximizing the constraint"], ans=0,
   why="This is the candidates test, and it is what turns a critical number into a proven maximum or minimum."),
 dict(q="A swimmer must reach a point on the far bank. If T(x) is the total travel time as a function of the landing point x, the quantity to be minimized is",
   choices=[
   "T(x), so the equation to solve is T'(x) = 0",
   "T'(x), so the equation to solve is T''(x) = 0",
   "the distance, so the equation to solve is d'(x) = 0 with the speeds ignored",
   "x itself"], ans=0,
   why="The objective is the time, so the critical numbers come from the derivative of the time function."),
 dict(q="A box with a square base and no top must have volume V. Writing the surface area as S(x) = x^2 + 4V/x requires the constraint",
   choices=[
   "x^2 h = V, so that h = V/x^2",
   "4x h = V",
   "x^2 + 4xh = V",
   "x h = V"], ans=0,
   why="The volume of a box with square base x and height h is x^2 h, and substituting h = V/x^2 into x^2 + 4xh gives x^2 + 4V/x."),
]
