# CALC 5.1 Using the Mean Value Theorem — 25 questions
# Answers verified with sympy; see verify_c5_1.py.
# Questions 1, 2, 3, 13, 14, 22 and 23 are statements of the theorem's
# hypotheses or corollaries and admit no sympy check; their reasoning is
# stated in `why` and was checked by hand against the standard statement of
# the Mean Value Theorem.
TOPIC = ("5.1", "Using the Mean Value Theorem", 5)
QUESTIONS = [
 dict(q="The Mean Value Theorem applies to a function f on the interval [a, b] provided that",
   choices=[
   "f is continuous on [a, b] and differentiable on (a, b)",
   "f is differentiable on [a, b] and continuous on (a, b)",
   "f is continuous on (a, b) only",
   "f is increasing on [a, b]"], ans=0,
   why="The hypotheses are continuity on the closed interval together with differentiability on the open interval."),
 dict(q="If f satisfies the hypotheses of the Mean Value Theorem on [a, b], the theorem guarantees the existence of a number c in (a, b) such that",
   choices=[
   "f'(c) = (f(b) - f(a))/(b - a)",
   "f'(c) = 0",
   "f(c) = (f(a) + f(b))/2",
   "f'(c) = f(b) - f(a)"], ans=0,
   why="The conclusion equates the instantaneous rate of change at c with the average rate of change across the interval."),
 dict(q="Rolle's Theorem is the special case of the Mean Value Theorem in which",
   choices=[
   "f(a) = f(b), so the guaranteed value satisfies f'(c) = 0",
   "f is a polynomial",
   "the interval has length 1",
   "f'(a) = f'(b)"], ans=0,
   why="When the endpoint values are equal the average rate of change is 0, so the guaranteed c has f'(c) = 0."),
 dict(q="For f(x) = x^2 on [1, 5], the value of c guaranteed by the Mean Value Theorem is",
   choices=["c = 2", "c = 3", "c = 4", "c = 6"], ans=1,
   why="The average rate of change is (25 - 1)/4 = 6 and f'(c) = 2c = 6 gives c = 3."),
 dict(q="For f(x) = x^3 on [0, 3], the Mean Value Theorem guarantees a value c equal to",
   choices=["sqrt(3)", "3/2", "9", "1"], ans=0,
   why="The average rate of change is 27/3 = 9, and 3c^2 = 9 gives c = sqrt(3) in (0, 3)."),
 dict(q="For f(x) = sqrt(x) on [0, 4], the value of c guaranteed by the Mean Value Theorem is",
   choices=["c = 1", "c = 2", "c = 1/2", "c = 4"], ans=0,
   why="The average rate of change is 2/4 = 1/2 and f'(c) = 1/(2 sqrt(c)) = 1/2 gives c = 1."),
 dict(q="For f(x) = 1/x on [1, 4], the value of c guaranteed by the Mean Value Theorem is",
   choices=["c = 2", "c = 5/2", "c = 3", "c = 1/2"], ans=0,
   why="The average rate of change is (1/4 - 1)/3 = -1/4, and -1/c^2 = -1/4 gives c = 2 in (1, 4)."),
 dict(q="For f(x) = ln(x) on [1, e], the value of c guaranteed by the Mean Value Theorem is",
   choices=["c = e - 1", "c = 1", "c = e/2", "c = e"], ans=0,
   why="The average rate of change is 1/(e - 1), and 1/c = 1/(e - 1) gives c = e - 1, which lies in (1, e)."),
 dict(q="For f(x) = sin(x) on [0, pi], the value of c guaranteed by the Mean Value Theorem is",
   choices=["c = pi/2", "c = pi/4", "c = pi/3", "c = pi"], ans=0,
   why="The average rate of change is 0 and cos(c) = 0 gives c = pi/2 in (0, pi)."),
 dict(q="For f(x) = x^2 - 6x + 8 on [2, 4], Rolle's Theorem guarantees a value c equal to",
   choices=["c = 3", "c = 2", "c = 5/2", "c = 7/2"], ans=0,
   why="f(2) = f(4) = 0, and f'(c) = 2c - 6 = 0 gives c = 3."),
 dict(q="For f(x) = x^3 - x on [0, 2], the value of c guaranteed by the Mean Value Theorem is",
   choices=[
   "2 sqrt(3)/3",
   "sqrt(3)/3",
   "1",
   "4/3"], ans=0,
   why="The average rate of change is (6 - 0)/2 = 3, and 3c^2 - 1 = 3 gives c^2 = 4/3, so c = 2/sqrt(3) = 2 sqrt(3)/3."),
 dict(q="How many values of c in (-2, 2) satisfy the conclusion of the Mean Value Theorem for f(x) = x^3 - 3x on [-2, 2]?",
   choices=["Two", "One", "Three", "None"], ans=0,
   why="The average rate of change is (2 - (-2))/4 = 1, and 3c^2 - 3 = 1 gives c = +/- 2/sqrt(3), both of which lie in (-2, 2)."),
 dict(q="On which interval does f(x) = 1/x FAIL to satisfy the hypotheses of the Mean Value Theorem?",
   choices=["[-1, 2]", "[1, 4]", "[2, 5]", "[1/2, 3]"], ans=0,
   why="f is undefined, hence not continuous, at x = 0, which lies in [-1, 2]."),
 dict(q="For f(x) = |x - 1| on [0, 3], which statement is correct?",
   choices=[
   "The Mean Value Theorem does not apply, and no c in (0, 3) satisfies its conclusion",
   "The Mean Value Theorem does not apply, but a value of c satisfying its conclusion exists anyway",
   "The Mean Value Theorem applies and c = 1",
   "The Mean Value Theorem applies and c = 3/2"], ans=0,
   why="f is not differentiable at x = 1, and since f' equals only -1 or 1 while the average rate of change is 1/3, no c works."),
 dict(q="For f(x) = x^(2/3) on [-1, 8], which statement is correct?",
   choices=[
   "The theorem does not apply because f is not differentiable at x = 0, and no c in (-1, 8) satisfies the conclusion",
   "The theorem applies and c = 8",
   "The theorem applies and c = 1",
   "The theorem does not apply, but c = 0 satisfies the conclusion"], ans=0,
   why="The average rate of change is (4 - 1)/9 = 1/3, and 2/(3 x^(1/3)) = 1/3 forces x = 8, which is an endpoint and not interior."),
 dict(q="For f(x) = tan(x) on [0, pi], the Mean Value Theorem",
   choices=[
   "does not apply, because f is not continuous at x = pi/2",
   "applies, and c = pi/4",
   "applies, and c = pi/2",
   "does not apply, because f(0) = f(pi)"], ans=0,
   why="tan(x) has an infinite discontinuity at pi/2, so continuity on the closed interval fails."),
 dict(q="A car travels 120 miles in exactly 2 hours along a straight road, and its position is a differentiable function of time. The Mean Value Theorem guarantees that at some instant the car's speed was exactly",
   choices=["60 miles per hour", "120 miles per hour", "30 miles per hour", "240 miles per hour"], ans=0,
   why="The average velocity is 120/2 = 60 miles per hour, and the theorem guarantees that instantaneous velocity equals it at some instant."),
 dict(q="A function f is continuous on [2, 7] and differentiable on (2, 7), with f(2) = 5 and f(7) = 20. The Mean Value Theorem guarantees a c in (2, 7) with",
   choices=["f'(c) = 3", "f'(c) = 15", "f'(c) = 0", "f(c) = 3"], ans=0,
   why="The average rate of change is (20 - 5)/(7 - 2) = 3."),
 dict(q="A differentiable function f satisfies f(0) = 1 and |f'(x)| <= 3 for all x. The largest value f(4) could possibly have is",
   choices=["13", "12", "4", "3"], ans=0,
   why="By the Mean Value Theorem f(4) - f(0) = 4 f'(c) <= 12, so f(4) <= 13."),
 dict(q="A differentiable function g satisfies g(1) = 8 and g'(x) >= 2 for all x. The smallest possible value of g(6) is",
   choices=["18", "10", "16", "20"], ans=0,
   why="By the Mean Value Theorem g(6) - g(1) = 5 g'(c) >= 10, so g(6) >= 18."),
 dict(q="If f'(x) = 0 for every x in an interval I, then on I the function f",
   choices=[
   "is constant",
   "is zero",
   "is linear with nonzero slope",
   "may still be strictly increasing"], ans=0,
   why="A corollary of the Mean Value Theorem: a zero derivative throughout an interval forces every pair of values to be equal."),
 dict(q="If f'(x) = g'(x) for every x in an interval, then on that interval",
   choices=[
   "f(x) - g(x) is a constant",
   "f(x) = g(x)",
   "f(x)/g(x) is a constant",
   "f and g are both constant"], ans=0,
   why="The difference f - g has derivative 0 throughout the interval, so by the Mean Value Theorem corollary it is constant."),
 dict(q="Let f(x) = x^2 for x <= 1 and f(x) = 2x - 1 for x > 1. On [0, 2], the value of c guaranteed by the Mean Value Theorem is",
   choices=["c = 3/4", "c = 1", "c = 3/2", "No such c exists, since f is not differentiable at x = 1"], ans=0,
   why="The pieces agree in value and in derivative at x = 1, so f is differentiable; the average rate of change is (3 - 0)/2 = 3/2, and 2c = 3/2 gives c = 3/4."),
 dict(q="For f(x) = e^x on [0, ln(4)], the value of c guaranteed by the Mean Value Theorem is",
   choices=[
   "ln(3/ln(4))",
   "ln(3)/ln(4)",
   "ln(2)",
   "3/ln(4)"], ans=0,
   why="The average rate of change is (4 - 1)/ln(4) = 3/ln(4), and e^c = 3/ln(4) gives c = ln(3/ln(4))."),
 dict(q="Rolle's Theorem is used to show that p(x) = x^3 + 4x - 9 has exactly one real zero. The step that rules out a second zero is",
   choices=[
   "p'(x) = 3x^2 + 4 is never zero, so p cannot take the same value twice",
   "p is a cubic, and cubics have one real zero",
   "p(1) = -4 and p(2) = 7, so a zero exists",
   "p'' (x) = 6x changes sign only once"], ans=0,
   why="Two zeros would force a c with p'(c) = 0 by Rolle's Theorem, but 3x^2 + 4 > 0 always, so a second zero is impossible."),
]
