# CALC 5.2 Extreme Value Theorem, Global Versus Local Extrema, and Critical Points — 25 questions
# Answers verified with sympy; see verify_c5_2.py.
# Questions 1, 2, 3, 4, 5, 6, 22 and 23 state the Extreme Value Theorem's
# hypotheses or the definitions of critical point and of local versus global
# extremum; they carry no computation and were checked by hand against the
# standard statements.
TOPIC = ("5.2", "Extreme Value Theorem, Global Versus Local Extrema, and Critical Points", 5)
QUESTIONS = [
 dict(q="The Extreme Value Theorem guarantees that a function attains both an absolute maximum and an absolute minimum provided that the function is",
   choices=[
   "continuous on a closed, bounded interval",
   "differentiable on an open interval",
   "continuous on an open interval",
   "increasing on a closed interval"], ans=0,
   why="Continuity on a closed and bounded interval is exactly the hypothesis of the Extreme Value Theorem."),
 dict(q="A number c in the domain of f is a critical number of f provided that",
   choices=[
   "f'(c) = 0 or f'(c) does not exist",
   "f'(c) = 0 only",
   "f(c) = 0",
   "f''(c) = 0"], ans=0,
   why="A critical number is a domain point where the derivative is either zero or undefined; students routinely forget the second case."),
 dict(q="Which statement about critical points is true?",
   choices=[
   "Every relative extremum of f at an interior point occurs at a critical number, but a critical number need not give an extremum",
   "Every critical number gives a relative extremum",
   "A relative extremum can occur where f' is nonzero and defined",
   "A function with no critical numbers has no absolute extrema on any interval"], ans=0,
   why="Fermat's theorem gives the first half, and f(x) = x^3 at x = 0 shows a critical number need not be an extremum."),
 dict(q="A relative (local) maximum of f at x = c means that",
   choices=[
   "f(c) is at least as large as f(x) for all x in some open interval containing c",
   "f(c) is the largest value of f on its entire domain",
   "f'(c) = 0",
   "f is increasing on both sides of c"], ans=0,
   why="A relative extremum is defined by a comparison on a neighborhood, not on the whole domain."),
 dict(q="An absolute (global) minimum of f on an interval I means that",
   choices=[
   "f(c) <= f(x) for every x in I",
   "f(c) <= f(x) for x near c",
   "f'(c) = 0 and f''(c) > 0",
   "c is an endpoint of I"], ans=0,
   why="A global extremum compares the value at c with every value on the interval."),
 dict(q="Which of these guarantees nothing about the existence of an absolute maximum?",
   choices=[
   "f is continuous on the open interval (0, 4)",
   "f is continuous on [0, 4]",
   "f is a polynomial on [-3, 3]",
   "f is continuous on [1, 1000]"], ans=0,
   why="The Extreme Value Theorem requires a closed interval; on an open interval a continuous function may run off without ever attaining a largest value."),
 dict(q="On the interval (0, 1], the function f(x) = 1/x",
   choices=[
   "has an absolute minimum but no absolute maximum",
   "has both an absolute maximum and an absolute minimum",
   "has an absolute maximum but no absolute minimum",
   "has neither"], ans=0,
   why="f decreases from arbitrarily large values to f(1) = 1, so 1 is attained as a minimum while the values near 0 are unbounded."),
 dict(q="On the open interval (0, 3), the function f(x) = x",
   choices=[
   "has neither an absolute maximum nor an absolute minimum",
   "has an absolute maximum of 3",
   "has an absolute minimum of 0",
   "has both, at the endpoints"], ans=0,
   why="The values approach 0 and 3 without ever reaching them, and the Extreme Value Theorem does not apply on an open interval."),
 dict(q="The critical numbers of f(x) = x^3 - 3x^2 are",
   choices=["x = 0 and x = 2", "x = 0 only", "x = 2 only", "x = -1 and x = 3"], ans=0,
   why="f'(x) = 3x^2 - 6x = 3x(x - 2), which is zero at x = 0 and x = 2 and is defined everywhere."),
 dict(q="The critical numbers of f(x) = x^4 - 8x^2 are",
   choices=[
   "x = -2, x = 0, and x = 2",
   "x = 0 only",
   "x = -2 and x = 2 only",
   "x = -4 and x = 4"], ans=0,
   why="f'(x) = 4x^3 - 16x = 4x(x - 2)(x + 2) is zero at those three numbers."),
 dict(q="The only critical number of f(x) = x^(2/3) is",
   choices=[
   "x = 0, because f'(0) does not exist",
   "x = 0, because f'(0) = 0",
   "x = 1, because f'(1) = 2/3",
   "There are no critical numbers"], ans=0,
   why="f'(x) = 2/(3 x^(1/3)) is undefined at x = 0, which is in the domain of f, so 0 is a critical number."),
 dict(q="The critical number of f(x) = |x - 4| is",
   choices=[
   "x = 4, where the derivative fails to exist",
   "x = 4, where the derivative equals 0",
   "x = 0",
   "There is none, because f is not differentiable"], ans=0,
   why="The corner at x = 4 is a domain point where f' does not exist, so it is a critical number, and it is a minimum."),
 dict(q="The critical numbers of f(x) = x/(x^2 + 1) are",
   choices=["x = -1 and x = 1", "x = 0 only", "x = -1, 0, and 1", "There are none"], ans=0,
   why="f'(x) = (1 - x^2)/(x^2 + 1)^2 is zero exactly at x = -1 and x = 1, and it is defined for every real x."),
 dict(q="The critical number of f(x) = x e^(-x) is",
   choices=["x = 1", "x = 0", "x = -1", "x = e"], ans=0,
   why="f'(x) = e^(-x)(1 - x), and since e^(-x) is never zero the only critical number is x = 1."),
 dict(q="The critical number of f(x) = ln(x)/x on its domain x > 0 is",
   choices=["x = e", "x = 1", "x = 1/e", "x = 0"], ans=0,
   why="f'(x) = (1 - ln(x))/x^2 is zero when ln(x) = 1, that is x = e; x = 0 is not in the domain."),
 dict(q="How many critical numbers does f(x) = x/(x - 2) have?",
   choices=["None", "One, at x = 2", "One, at x = 0", "Two"], ans=0,
   why="f'(x) = -2/(x - 2)^2 is never zero, and x = 2 is not in the domain of f, so it cannot be a critical number."),
 dict(q="The critical numbers of f(x) = sin(x) + cos(x) on (0, 2pi) are",
   choices=[
   "x = pi/4 and x = 5pi/4",
   "x = pi/2 and x = 3pi/2",
   "x = 3pi/4 and x = 7pi/4",
   "x = pi/4 only"], ans=0,
   why="f'(x) = cos(x) - sin(x) = 0 requires tan(x) = 1, giving pi/4 and 5pi/4 in the interval."),
 dict(q="The critical numbers of f(x) = x^2/(x - 1) are",
   choices=["x = 0 and x = 2", "x = 1 only", "x = 0, 1, and 2", "x = 2 only"], ans=0,
   why="f'(x) = (x^2 - 2x)/(x - 1)^2 is zero at x = 0 and x = 2, and x = 1 is excluded from the domain."),
 dict(q="The critical number of f(x) = (x - 5)^(1/3) is",
   choices=[
   "x = 5, where f' is undefined",
   "x = 5, where f' = 0",
   "x = 0",
   "There is none, since f' is never zero"], ans=0,
   why="f'(x) = 1/(3 (x - 5)^(2/3)) is never zero but is undefined at x = 5, a point of the domain, so 5 is critical."),
 dict(q="For f(x) = x^3, the number x = 0 is",
   choices=[
   "a critical number that is neither a relative maximum nor a relative minimum",
   "a relative minimum",
   "a relative maximum",
   "not a critical number"], ans=0,
   why="f'(0) = 0 makes 0 critical, but f' = 3x^2 stays positive on both sides, so f keeps increasing through 0."),
 dict(q="For f(x) = x^4, the number x = 0 is",
   choices=[
   "a critical number and a relative minimum",
   "a critical number but not an extremum",
   "a relative maximum",
   "not a critical number"], ans=0,
   why="f'(x) = 4x^3 is zero at 0 and changes from negative to positive there, so f has a minimum."),
 dict(q="A function f is defined on [0, 4] by f(x) = x for 0 <= x < 4 and f(4) = 0. On [0, 4], f",
   choices=[
   "has an absolute minimum but no absolute maximum",
   "has both an absolute maximum and an absolute minimum",
   "has an absolute maximum of 4",
   "must have both, by the Extreme Value Theorem"], ans=0,
   why="The Extreme Value Theorem does not apply because f is discontinuous at x = 4, and the values approach 4 without attaining it while 0 is attained."),
 dict(q="If f is continuous on [a, b], its absolute extreme values must occur",
   choices=[
   "at a critical number in (a, b) or at an endpoint",
   "only at a critical number in (a, b)",
   "only at an endpoint",
   "wherever f'' = 0"], ans=0,
   why="Interior extrema force f' to be zero or undefined, and the only other candidates on a closed interval are the two endpoints."),
 dict(q="The function f(x) = 3x^5 - 5x^3 has how many critical numbers, and how many of them are relative extrema?",
   choices=[
   "Three critical numbers, two of which are relative extrema",
   "Three critical numbers, all three relative extrema",
   "Two critical numbers, both relative extrema",
   "Three critical numbers, none of them relative extrema"], ans=0,
   why="f'(x) = 15x^2(x^2 - 1) is zero at x = -1, 0, 1, but f' does not change sign at 0, so only x = -1 and x = 1 are extrema."),
 dict(q="On the closed interval [-1, 8], the function f(x) = x^(2/3) attains its absolute maximum at",
   choices=["x = 8", "x = -1", "x = 0", "x = 4"], ans=0,
   why="The candidates are the critical number 0 and the endpoints, and f(0) = 0, f(-1) = 1, f(8) = 4, so the largest value is 4 at x = 8."),
]
