# CALC 5.3 Determining Intervals on Which a Function Is Increasing or Decreasing — 25 questions
# Answers verified with sympy; see verify_c5_3.py.
# Questions 1, 2 and 3 state the increasing/decreasing test itself and admit
# no computation; the rest are confirmed by solving f'(x) = 0 and testing the
# sign of f' on each resulting interval.
# Intervals are written open throughout, the usual AP convention.
TOPIC = ("5.3", "Determining Intervals on Which a Function Is Increasing or Decreasing", 5)
QUESTIONS = [
 dict(q="If f'(x) > 0 for every x in an interval, then on that interval f is",
   choices=["increasing", "decreasing", "concave up", "constant"], ans=0,
   why="A positive derivative throughout an interval forces f(b) > f(a) whenever b > a, by the Mean Value Theorem."),
 dict(q="Which statement is true?",
   choices=[
   "A function can be increasing on an interval even though its derivative is zero at one point of that interval",
   "A function increasing on an interval must have f'(x) > 0 at every point of it",
   "A function whose derivative is zero at a point cannot be increasing near that point",
   "A function is increasing wherever f(x) > 0"], ans=0,
   why="f(x) = x^3 is increasing on every interval even though f'(0) = 0."),
 dict(q="To find where a differentiable function is increasing, you should examine the sign of",
   choices=["f'(x)", "f(x)", "f''(x)", "f'(x) - f(x)"], ans=0,
   why="Increasing and decreasing behavior is governed by the sign of the first derivative."),
 dict(q="The function f(x) = x^2 - 4x is increasing on",
   choices=["(2, infinity)", "(-infinity, 2)", "(0, 4)", "(-infinity, infinity)"], ans=0,
   why="f'(x) = 2x - 4 is positive exactly when x > 2."),
 dict(q="The function f(x) = x^3 - 3x is decreasing on",
   choices=["(-1, 1)", "(-infinity, -1)", "(1, infinity)", "(0, infinity)"], ans=0,
   why="f'(x) = 3x^2 - 3 = 3(x - 1)(x + 1) is negative exactly between the roots -1 and 1."),
 dict(q="The function f(x) = x^3 + 3x^2 - 9x is increasing on",
   choices=[
   "(-infinity, -3) and (1, infinity)",
   "(-3, 1)",
   "(-infinity, 1) and (3, infinity)",
   "(-1, 3)"], ans=0,
   why="f'(x) = 3x^2 + 6x - 9 = 3(x + 3)(x - 1) is positive outside the interval from -3 to 1."),
 dict(q="The function f(x) = x^4 - 4x^3 is increasing on",
   choices=["(3, infinity)", "(0, 3)", "(-infinity, 0)", "(0, infinity)"], ans=0,
   why="f'(x) = 4x^2(x - 3) has the sign of x - 3 because 4x^2 is never negative, so f increases only for x > 3."),
 dict(q="The function f(x) = x^5 - 5x is decreasing on",
   choices=["(-1, 1)", "(-infinity, -1)", "(1, infinity)", "(-5, 5)"], ans=0,
   why="f'(x) = 5x^4 - 5 = 5(x^2 - 1)(x^2 + 1) is negative exactly when x^2 < 1."),
 dict(q="The function f(x) = x/(x^2 + 1) is increasing on",
   choices=["(-1, 1)", "(-infinity, -1) and (1, infinity)", "(0, infinity)", "(-infinity, infinity)"], ans=0,
   why="f'(x) = (1 - x^2)/(x^2 + 1)^2 is positive exactly when x^2 < 1."),
 dict(q="The function f(x) = x e^x is decreasing on",
   choices=["(-infinity, -1)", "(-1, infinity)", "(-infinity, 0)", "(0, infinity)"], ans=0,
   why="f'(x) = e^x(x + 1) has the sign of x + 1 because e^x > 0, so f decreases for x < -1."),
 dict(q="On its domain x > 0, the function f(x) = ln(x) - x is increasing on",
   choices=["(0, 1)", "(1, infinity)", "(0, e)", "(0, infinity)"], ans=0,
   why="f'(x) = 1/x - 1 is positive exactly when 0 < x < 1."),
 dict(q="The function f(x) = x^2 e^(-x) is increasing on",
   choices=["(0, 2)", "(-infinity, 0) and (2, infinity)", "(2, infinity)", "(-infinity, 2)"], ans=0,
   why="f'(x) = x(2 - x) e^(-x) is positive exactly when 0 < x < 2."),
 dict(q="The function f(x) = e^(-x^2) is decreasing on",
   choices=["(0, infinity)", "(-infinity, 0)", "(-1, 1)", "(-infinity, infinity)"], ans=0,
   why="f'(x) = -2x e^(-x^2) has the sign of -x, so f decreases for x > 0."),
 dict(q="On the interval (0, infinity), the function f(x) = sqrt(x) - x is decreasing on",
   choices=["(1/4, infinity)", "(0, 1/4)", "(1/2, infinity)", "(0, 1)"], ans=0,
   why="f'(x) = 1/(2 sqrt(x)) - 1 is negative when 2 sqrt(x) > 1, that is when x > 1/4."),
 dict(q="The function f(x) = x + 1/x is increasing on",
   choices=[
   "(-infinity, -1) and (1, infinity)",
   "(-1, 0) and (0, 1)",
   "(0, infinity)",
   "(-1, 1)"], ans=0,
   why="f'(x) = 1 - 1/x^2 is positive exactly when x^2 > 1, and x = 0 is not in the domain."),
 dict(q="On (0, 2pi), the function f(x) = x - 2 sin(x) is increasing on",
   choices=[
   "(pi/3, 5pi/3)",
   "(0, pi/3) and (5pi/3, 2pi)",
   "(0, pi)",
   "(pi/2, 3pi/2)"], ans=0,
   why="f'(x) = 1 - 2 cos(x) is positive when cos(x) < 1/2, which on (0, 2pi) is the interval from pi/3 to 5pi/3."),
 dict(q="The function f(x) = 1/x is",
   choices=[
   "decreasing on (-infinity, 0) and on (0, infinity), but not on its whole domain taken at once",
   "decreasing on (-infinity, infinity)",
   "increasing on (-infinity, 0) and decreasing on (0, infinity)",
   "increasing on its whole domain"], ans=0,
   why="f'(x) = -1/x^2 is negative wherever f is defined, but f(-1) = -1 is less than f(1) = 1, so no single decreasing claim spans the break at 0."),
 dict(q="The function f(x) = (x - 1)/(x + 2) is",
   choices=[
   "increasing on (-infinity, -2) and on (-2, infinity)",
   "decreasing on (-infinity, -2) and on (-2, infinity)",
   "increasing on (-2, infinity) only",
   "increasing on (1, infinity) only"], ans=0,
   why="f'(x) = 3/(x + 2)^2 is positive everywhere the function is defined."),
 dict(q="The function f(x) = x^2/(x - 1) is decreasing on",
   choices=[
   "(0, 1) and (1, 2)",
   "(0, 2)",
   "(-infinity, 0) and (2, infinity)",
   "(1, 2) only"], ans=0,
   why="f'(x) = x(x - 2)/(x - 1)^2 is negative for 0 < x < 2, and x = 1 must be removed since f is undefined there."),
 dict(q="The function f(x) = x^(2/3) is increasing on",
   choices=["(0, infinity)", "(-infinity, 0)", "(-infinity, infinity)", "It is never increasing"], ans=0,
   why="f'(x) = 2/(3 x^(1/3)) has the sign of x, so f decreases for x < 0 and increases for x > 0."),
 dict(q="A function f has f'(x) = (x - 2)(x + 3)^2. The function f is increasing on",
   choices=[
   "(2, infinity)",
   "(-3, 2)",
   "(-infinity, -3) and (2, infinity)",
   "(-infinity, -3)"], ans=0,
   why="The squared factor is never negative, so f' has the sign of x - 2 and f increases only to the right of 2."),
 dict(q="A function f has f'(x) = (x - 1)^2 (x - 4). The function f is decreasing on",
   choices=[
   "(-infinity, 4)",
   "(1, 4)",
   "(-infinity, 1)",
   "(4, infinity)"], ans=0,
   why="(x - 1)^2 is never negative, so f' is negative for every x < 4 except the single point x = 1, where it is zero."),
 dict(q="A function f has f'(x) = x^2 (x - 3)(x + 1). On which interval is f increasing?",
   choices=[
   "(3, infinity)",
   "(-1, 0)",
   "(0, 3)",
   "(-1, 3)"], ans=0,
   why="The sign of f' is the sign of (x - 3)(x + 1), which is positive for x < -1 and for x > 3; of the choices only (3, infinity) qualifies."),
 dict(q="A continuous function f has f'(x) < 0 on (-infinity, 1), f'(1) = 0, and f'(x) > 0 on (1, 4). On (-infinity, 4), the function f",
   choices=[
   "decreases until x = 1 and increases after it",
   "increases until x = 1 and decreases after it",
   "is increasing throughout",
   "is concave up throughout"], ans=0,
   why="The sign of f' switches from negative to positive at x = 1, so f falls and then rises."),
 dict(q="A differentiable function f has f'(x) = 6 - 2x. If f(1) = 5, on what interval is f both increasing and above the value 5?",
   choices=[
   "(1, 3)",
   "(3, infinity)",
   "(-infinity, 1)",
   "(0, 3)"], ans=0,
   why="f' > 0 for x < 3, and f(x) = 6x - x^2 exceeds 5 for 1 < x < 5, so both conditions hold exactly between 1 and 3."),
]
