# CALC 5.4 Using the First Derivative Test to Determine Relative Extrema — 25 questions
# Answers verified with sympy; see verify_c5_4.py.
# Questions 1, 2, 3 and 4 state the first derivative test itself and carry no
# computation; every other item is confirmed by locating the critical numbers
# and testing the sign of f' on each side of them.
TOPIC = ("5.4", "Using the First Derivative Test to Determine Relative Extrema", 5)
QUESTIONS = [
 dict(q="According to the first derivative test, f has a relative maximum at a critical number c if f'",
   choices=[
   "changes from positive to negative at c",
   "changes from negative to positive at c",
   "equals zero at c",
   "is positive on both sides of c"], ans=0,
   why="A rise followed by a fall puts a peak at c; the test is about the sign change, not the value of f'(c)."),
 dict(q="According to the first derivative test, f has a relative minimum at a critical number c if f'",
   choices=[
   "changes from negative to positive at c",
   "changes from positive to negative at c",
   "is negative on both sides of c",
   "equals zero at c"], ans=0,
   why="A fall followed by a rise puts a valley at c."),
 dict(q="If f'(c) = 0 but f' has the same sign on both sides of c, then at x = c the function f has",
   choices=[
   "no relative extremum",
   "a relative maximum",
   "a relative minimum",
   "a vertical tangent"], ans=0,
   why="Without a sign change the function keeps moving the same direction through c, as f(x) = x^3 does at 0."),
 dict(q="The first derivative test can identify a relative extremum at a critical number where f' is undefined, provided that",
   choices=[
   "f is continuous at that number and f' changes sign there",
   "f' is defined on one side only",
   "f''(c) exists",
   "the number is an endpoint of the domain"], ans=0,
   why="The test needs continuity at c plus a sign change in f' across c; differentiability at c itself is not required."),
 dict(q="For f(x) = x^3 - 3x, the first derivative test shows a relative maximum at",
   choices=["x = -1", "x = 1", "x = 0", "x = 3"], ans=0,
   why="f'(x) = 3(x - 1)(x + 1) is positive left of -1 and negative between -1 and 1, so f peaks at x = -1."),
 dict(q="For f(x) = x^3 - 6x^2 + 9x, the relative minimum occurs at",
   choices=["x = 3", "x = 1", "x = 2", "x = 0"], ans=0,
   why="f'(x) = 3(x - 1)(x - 3) changes from negative to positive at x = 3."),
 dict(q="For f(x) = 2x^3 - 9x^2 + 12x, the relative maximum value of f is",
   choices=["5", "4", "1", "2"], ans=0,
   why="f'(x) = 6(x - 1)(x - 2) changes from positive to negative at x = 1, and f(1) = 5."),
 dict(q="For f(x) = x^4 - 4x^3, the first derivative test shows that",
   choices=[
   "there is a relative minimum at x = 3 and no extremum at x = 0",
   "there are relative minima at x = 0 and x = 3",
   "there is a relative maximum at x = 0 and a relative minimum at x = 3",
   "there is a relative maximum at x = 3"], ans=0,
   why="f'(x) = 4x^2(x - 3) is negative on both sides of 0 and changes from negative to positive at 3."),
 dict(q="For f(x) = x e^(-x), the relative maximum value of f is",
   choices=["1/e", "e", "1", "-1/e"], ans=0,
   why="f'(x) = e^(-x)(1 - x) changes from positive to negative at x = 1, and f(1) = 1/e."),
 dict(q="For f(x) = x^2 e^x, the first derivative test gives",
   choices=[
   "a relative maximum at x = -2 and a relative minimum at x = 0",
   "a relative minimum at x = -2 and a relative maximum at x = 0",
   "relative minima at both x = -2 and x = 0",
   "no relative extrema"], ans=0,
   why="f'(x) = x(x + 2) e^x is positive for x < -2, negative on (-2, 0), and positive for x > 0."),
 dict(q="For f(x) = x/(x^2 + 1), the relative minimum value of f is",
   choices=["-1/2", "1/2", "-1", "0"], ans=0,
   why="f'(x) = (1 - x^2)/(x^2 + 1)^2 changes from negative to positive at x = -1, and f(-1) = -1/2."),
 dict(q="For f(x) = x + 1/x, the first derivative test gives",
   choices=[
   "a relative maximum value of -2 and a relative minimum value of 2",
   "a relative minimum value of -2 and a relative maximum value of 2",
   "a relative minimum at x = 0",
   "no relative extrema"], ans=0,
   why="f'(x) = 1 - 1/x^2 changes from positive to negative at x = -1, where f = -2, and from negative to positive at x = 1, where f = 2; the two branches are separated by the asymptote, so the relative maximum value is below the relative minimum value."),
 dict(q="For f(x) = (x - 2)^2 (x + 1), the relative maximum occurs at",
   choices=["x = 0", "x = 2", "x = -1", "x = 1"], ans=0,
   why="f'(x) = 3x(x - 2) changes from positive to negative at x = 0."),
 dict(q="For f(x) = x - 2 sqrt(x) on [0, infinity), the relative minimum value of f is",
   choices=["-1", "0", "1", "-2"], ans=0,
   why="f'(x) = 1 - 1/sqrt(x) changes from negative to positive at x = 1, and f(1) = 1 - 2 = -1."),
 dict(q="For f(x) = ln(x)/x on x > 0, the first derivative test gives a relative maximum value of",
   choices=["1/e", "e", "0", "1"], ans=0,
   why="f'(x) = (1 - ln(x))/x^2 changes from positive to negative at x = e, and f(e) = 1/e."),
 dict(q="On (0, 2pi), the function f(x) = sin(x) + cos(x) has a relative maximum at",
   choices=["x = pi/4", "x = 5pi/4", "x = pi/2", "x = 3pi/4"], ans=0,
   why="f'(x) = cos(x) - sin(x) is positive just left of pi/4 and negative just right of it."),
 dict(q="For f(x) = x^4 + 4x, the first derivative test gives",
   choices=[
   "a relative minimum at x = -1 and no other extremum",
   "a relative maximum at x = -1",
   "relative extrema at x = -1 and x = 0",
   "no relative extrema"], ans=0,
   why="f'(x) = 4(x^3 + 1) is negative for x < -1 and positive for x > -1, and -1 is the only real root."),
 dict(q="For f(x) = (x + 1)^3, the first derivative test shows",
   choices=[
   "no relative extremum, since f'(x) = 3(x + 1)^2 never changes sign",
   "a relative minimum at x = -1",
   "a relative maximum at x = -1",
   "a relative minimum at x = 0"], ans=0,
   why="The squared factor keeps f' nonnegative on both sides of -1, so f increases through the critical number."),
 dict(q="For f(x) = |x^2 - 4|, the first derivative test gives",
   choices=[
   "relative minima at x = -2 and x = 2 and a relative maximum at x = 0",
   "relative maxima at x = -2 and x = 2 and a relative minimum at x = 0",
   "a relative minimum at x = 0 only",
   "no relative extrema, because f is not differentiable at x = -2 and x = 2"], ans=0,
   why="The graph touches zero at x = -2 and x = 2, where f' changes sign at corners, and it peaks at f(0) = 4."),
 dict(q="A function f has f'(x) = (x - 1)(x - 3)^2. The first derivative test shows",
   choices=[
   "a relative minimum at x = 1 and no extremum at x = 3",
   "relative minima at x = 1 and x = 3",
   "a relative maximum at x = 1 and a relative minimum at x = 3",
   "a relative maximum at x = 3"], ans=0,
   why="The squared factor does not change sign, so only x = 1 sees f' go from negative to positive."),
 dict(q="A function f has f'(x) = x^2 (x + 4). The first derivative test shows a relative",
   choices=[
   "minimum at x = -4 only",
   "minimum at x = 0 only",
   "minimum at x = -4 and a maximum at x = 0",
   "maximum at x = -4 only"], ans=0,
   why="f' has the sign of x + 4, so it changes from negative to positive at -4 and does not change sign at 0."),
 dict(q="A function f is differentiable for x < 1 and has f'(x) = (x + 2)/(x - 1) there. At x = -2 the function f has a relative",
   choices=[
   "maximum, because f' changes from positive to negative there",
   "minimum, because f' changes from negative to positive there",
   "minimum, because f'(-2) = 0 and the denominator is negative",
   "no extremum, because f' does not change sign there"], ans=0,
   why="At x = -3 the quotient is (-1)/(-4) = 1/4 > 0 and at x = 0 it is 2/(-1) = -2 < 0, so f' falls through zero from positive to negative at x = -2."),
 dict(q="For f(x) = x^(2/3)(x - 5), the first derivative test shows a relative maximum at",
   choices=[
   "x = 0, where f' is undefined",
   "x = 2, where f'(2) = 0",
   "x = 5, where f(5) = 0",
   "There is no relative maximum"], ans=0,
   why="f'(x) = 5(x - 2)/(3 x^(1/3)) is positive for x < 0 and negative on (0, 2), so the continuous function f peaks at x = 0."),
 dict(q="A continuous function f has f'(x) > 0 on (-infinity, -3), f'(-3) = 0, f'(x) < 0 on (-3, 2), f'(2) does not exist, and f'(x) < 0 on (2, infinity). The relative extrema of f are",
   choices=[
   "a relative maximum at x = -3 only",
   "a relative maximum at x = -3 and a relative minimum at x = 2",
   "relative minima at x = -3 and x = 2",
   "a relative maximum at x = 2 only"], ans=0,
   why="f' changes from positive to negative at -3 but stays negative across 2, so only x = -3 is an extremum even though 2 is a critical number."),
 dict(q="The values f'(x) = 0 at x = -2, 0, and 4, with f'(x) < 0 on (-infinity, -2), f'(x) > 0 on (-2, 0), f'(x) > 0 on (0, 4), and f'(x) < 0 on (4, infinity). How many relative extrema does f have?",
   choices=[
   "Two: a minimum at x = -2 and a maximum at x = 4",
   "Three, one at each critical number",
   "Two: a maximum at x = -2 and a minimum at x = 4",
   "One, at x = 0"], ans=0,
   why="Only x = -2 and x = 4 see a sign change; f' is positive on both sides of x = 0."),
]
