# CALC 5.5 Using the Candidates Test to Determine Absolute Extrema — 25 questions
# Answers verified with sympy; see verify_c5_5.py.
# Questions 1, 2, 3 and 25 describe the procedure itself and carry no
# computation; every other item is confirmed by evaluating f at each critical
# number and at both endpoints and comparing the resulting list.
TOPIC = ("5.5", "Using the Candidates Test to Determine Absolute Extrema", 5)
QUESTIONS = [
 dict(q="To find the absolute extrema of a continuous function on a closed interval [a, b], the candidates to compare are the values of f at",
   choices=[
   "every critical number in (a, b) together with a and b",
   "every critical number in (a, b) only",
   "a and b only",
   "every point where f''(x) = 0"], ans=0,
   why="An absolute extremum on a closed interval occurs either at an interior critical number or at an endpoint, so those are the only candidates."),
 dict(q="In the candidates test, endpoints must be included because",
   choices=[
   "a largest or smallest value can occur at an endpoint, where f' need not be zero",
   "the derivative is always zero at an endpoint",
   "the Extreme Value Theorem only applies at endpoints",
   "endpoints are always critical numbers"], ans=0,
   why="An endpoint has no neighborhood on both sides, so f' gives no information there, yet the value can still be the largest or smallest."),
 dict(q="The candidates test compares",
   choices=[
   "values of f, not values of f'",
   "values of f', not values of f",
   "values of f''",
   "the widths of the subintervals"], ans=0,
   why="Once the candidate x-values are found from f', the comparison that decides the extrema is a comparison of function values."),
 dict(q="On [-2, 3], the absolute maximum value of f(x) = x^3 - 3x is",
   choices=["-2", "2", "16", "18"], ans=3,
   why="The candidates give f(-2) = -2, f(-1) = 2, f(1) = -2, and f(3) = 18, so the largest value is 18."),
 dict(q="On [-2, 3], the absolute minimum value of f(x) = x^3 - 3x is",
   choices=["-18", "-2", "0", "2"], ans=1,
   why="The candidate values are -2, 2, -2, and 18, so the smallest is -2, attained at both x = -2 and x = 1."),
 dict(q="On [-1, 4], the absolute maximum value of f(x) = x^3 - 3x^2 is",
   choices=["-4", "0", "8", "16"], ans=3,
   why="The candidates are f(-1) = -4, f(0) = 0, f(2) = -4, and f(4) = 16."),
 dict(q="On [-1, 3], the absolute minimum value of f(x) = x^4 - 8x^2 + 3 is",
   choices=["-13", "-4", "3", "12"], ans=0,
   why="The critical numbers in the interval are 0 and 2, and the candidate values are f(-1) = -4, f(0) = 3, f(2) = -13, f(3) = 12."),
 dict(q="On [-2, 3], the absolute maximum value of f(x) = 2x^3 - 3x^2 - 12x + 5 is",
   choices=["-15", "-4", "1", "12"], ans=3,
   why="f'(x) = 6(x - 2)(x + 1), and the candidates are f(-2) = 1, f(-1) = 12, f(2) = -15, f(3) = -4."),
 dict(q="On [-2, 3], the absolute minimum value of f(x) = 2x^3 - 3x^2 - 12x + 5 is",
   choices=["-15", "-12", "-4", "1"], ans=0,
   why="Among the candidate values 1, 12, -15, and -4, the smallest is -15 at x = 2."),
 dict(q="On [1, 4], the absolute minimum value of f(x) = x + 4/x is",
   choices=["2", "4", "5", "8"], ans=1,
   why="The only critical number in the interval is x = 2, and f(2) = 4 while f(1) = f(4) = 5."),
 dict(q="On [0, 3], the absolute maximum value of f(x) = x e^(-x) is",
   choices=["0", "3/e^3", "1/e", "e"], ans=2,
   why="The candidates are f(0) = 0, f(1) = 1/e, and f(3) = 3/e^3, and 1/e is the largest since 3/e^3 is about 0.149."),
 dict(q="On [0, pi], the absolute maximum value of f(x) = sin(x) + cos(x) is",
   choices=["-1", "1", "sqrt(2)", "2"], ans=2,
   why="The only critical number is pi/4, and f(pi/4) = sqrt(2) beats f(0) = 1 and f(pi) = -1."),
 dict(q="On [-8, 1], the absolute maximum value of f(x) = x^(2/3) is",
   choices=["0", "1", "2", "4"], ans=3,
   why="The critical number 0 gives f(0) = 0, and the endpoints give f(-8) = 4 and f(1) = 1."),
 dict(q="On [1, e^2], the absolute maximum value of f(x) = ln(x)/x is",
   choices=["0", "2/e^2", "1/e", "1"], ans=2,
   why="The candidates are f(1) = 0, f(e) = 1/e, and f(e^2) = 2/e^2, and 1/e is about 0.368 against 0.271."),
 dict(q="On [-2, 2], the absolute maximum value of f(x) = x sqrt(4 - x^2) is",
   choices=["0", "sqrt(2)", "2", "4"], ans=2,
   why="The critical numbers are x = +/- sqrt(2), and f(sqrt(2)) = 2 while both endpoints give 0."),
 dict(q="On [-1, 2], the absolute minimum value of f(x) = 1/(x^2 + 1) is",
   choices=["1/5", "1/2", "1", "2"], ans=0,
   why="The critical number 0 gives the maximum value 1, and the candidates f(-1) = 1/2 and f(2) = 1/5 make 1/5 the smallest."),
 dict(q="On [-2, 1], the function f(x) = x^3 attains its absolute extrema",
   choices=[
   "at the two endpoints, with maximum 1 and minimum -8",
   "at x = 0 and x = 1",
   "at x = 0 only",
   "nowhere, since f'(0) = 0 gives no extremum"], ans=0,
   why="The only critical number is 0, where f(0) = 0 lies between f(-2) = -8 and f(1) = 1, so both extrema sit at the endpoints."),
 dict(q="On [0, 5], the absolute maximum value of f(x) = |x - 3| is",
   choices=["0", "2", "3", "5"], ans=2,
   why="The corner at x = 3 gives the minimum 0, and the endpoint values are f(0) = 3 and f(5) = 2."),
 dict(q="On [0, 2], the absolute minimum value of f(x) = x^4 - 2x^2 is",
   choices=["-1", "0", "1", "8"], ans=0,
   why="The critical number in the interval is x = 1, and the candidates are f(0) = 0, f(1) = -1, f(2) = 8."),
 dict(q="On [0, 3pi/2], the absolute minimum value of f(x) = cos(x) is",
   choices=["-1", "0", "1", "3pi/2"], ans=0,
   why="The critical number pi gives f(pi) = -1, below f(0) = 1 and f(3pi/2) = 0."),
 dict(q="On [-1, 2], the absolute maximum value of f(x) = e^x - x is",
   choices=["1", "1/e + 1", "e - 1", "e^2 - 2"], ans=3,
   why="f'(x) = e^x - 1 is zero at x = 0, and the candidates are f(-1) = 1/e + 1 (about 1.368), f(0) = 1, and f(2) = e^2 - 2 (about 5.389)."),
 dict(q="On [0, 4], the absolute maximum value of f(x) = x/(x^2 + 4) is",
   choices=["0", "1/5", "1/4", "1/2"], ans=2,
   why="The critical number in the interval is x = 2, and f(2) = 1/4 exceeds f(0) = 0 and f(4) = 1/5."),
 dict(q="On [0, 9], the absolute maximum value of f(x) = (x - 1)^(2/3) is",
   choices=["0", "1", "2", "4"], ans=3,
   why="The candidates are the point x = 1 where f' is undefined, giving 0, and the endpoints f(0) = 1 and f(9) = 4."),
 dict(q="On [-1, 8], the function f(x) = 3x^(4/3) - 12x^(1/3) has absolute extrema",
   choices=[
   "maximum 24 at x = 8 and minimum -9 at x = 1",
   "maximum 15 at x = -1 and minimum -9 at x = 1",
   "maximum 24 at x = 8 and minimum 0 at x = 0",
   "maximum 15 at x = -1 and minimum 0 at x = 0"], ans=0,
   why="f'(x) = 4(x - 1)/x^(2/3) gives candidates x = 1 and x = 0, and the values are f(-1) = 15, f(0) = 0, f(1) = -9, f(8) = 24."),
 dict(q="A continuous function on a closed interval attains its absolute maximum value",
   choices=[
   "at least once, and possibly at more than one x",
   "exactly once",
   "only at an interior point",
   "only where f'' < 0"], ans=0,
   why="The Extreme Value Theorem guarantees the value is attained but says nothing about uniqueness; f(x) = x^3 - 3x on [-2, 3] attains its minimum at two different x-values."),
]
