# CALC 5.6 Determining Concavity of Functions over Their Domains — 25 questions
# Answers verified with sympy; see verify_c5_6.py.
# Questions 1, 2, 3 and 4 state the definitions of concavity and of an
# inflection point and carry no computation; every other item is confirmed by
# computing f'' and testing its sign on each side of the candidate points.
TOPIC = ("5.6", "Determining Concavity of Functions over Their Domains", 5)
QUESTIONS = [
 dict(q="A twice-differentiable function f is concave up on an interval exactly when",
   choices=[
   "f''(x) > 0 there, equivalently f' is increasing there",
   "f'(x) > 0 there",
   "f(x) > 0 there",
   "f''(x) = 0 there"], ans=0,
   why="Concave up means the slope is increasing, which is exactly a positive second derivative."),
 dict(q="A point on the graph of f is an inflection point provided that f is continuous there and",
   choices=[
   "f'' changes sign there",
   "f''  equals zero there",
   "f' equals zero there",
   "f changes sign there"], ans=0,
   why="Concavity must actually change; f'' = 0 by itself is not enough."),
 dict(q="For f(x) = x^4, the point x = 0",
   choices=[
   "is not an inflection point, because f'' = 12x^2 does not change sign",
   "is an inflection point, because f''(0) = 0",
   "is an inflection point, because f'(0) = 0",
   "is a point where f is concave down"], ans=0,
   why="f''(x) = 12x^2 is positive on both sides of 0, so the graph is concave up throughout and never changes concavity."),
 dict(q="If f''(x) < 0 on an interval, then on that interval",
   choices=[
   "the graph of f lies below its tangent lines and f' is decreasing",
   "f is decreasing",
   "f is negative",
   "f has a relative maximum"], ans=0,
   why="Concave down means the slopes are falling, which puts the curve beneath each tangent line."),
 dict(q="The graph of f(x) = x^3 - 3x^2 is concave up on",
   choices=["(1, infinity)", "(-infinity, 1)", "(0, 2)", "(2, infinity)"], ans=0,
   why="f''(x) = 6x - 6 is positive exactly when x > 1."),
 dict(q="The inflection point of f(x) = x^3 - 3x^2 occurs at",
   choices=["x = 1", "x = 0", "x = 2", "x = 3"], ans=0,
   why="f''(x) = 6x - 6 changes from negative to positive at x = 1."),
 dict(q="The graph of f(x) = x^4 - 6x^2 is concave down on",
   choices=["(-1, 1)", "(-infinity, -1)", "(1, infinity)", "(-sqrt(3), sqrt(3))"], ans=0,
   why="f''(x) = 12x^2 - 12 = 12(x - 1)(x + 1) is negative exactly when x^2 < 1."),
 dict(q="How many inflection points does the graph of f(x) = x^4 - 4x^3 have?",
   choices=["Two", "One", "Three", "None"], ans=0,
   why="f''(x) = 12x(x - 2) changes sign at both x = 0 and x = 2."),
 dict(q="How many inflection points does the graph of f(x) = x^5 - 5x^4 have?",
   choices=["One", "Two", "Three", "None"], ans=0,
   why="f''(x) = 20x^2(x - 3) is zero at x = 0 and x = 3, but the squared factor prevents a sign change at 0, so only x = 3 qualifies."),
 dict(q="How many inflection points does the graph of f(x) = 3x^5 - 5x^3 have?",
   choices=["Three", "Two", "One", "None"], ans=0,
   why="f''(x) = 30x(2x^2 - 1) changes sign at x = 0 and at x = +/- 1/sqrt(2)."),
 dict(q="The graph of f(x) = x^4 + 2x^3 has inflection points at",
   choices=["x = -1 and x = 0", "x = 0 only", "x = -1 only", "x = -3/2 and x = 0"], ans=0,
   why="f''(x) = 12x(x + 1) changes sign at both roots."),
 dict(q="The graph of f(x) = x e^x is concave up on",
   choices=["(-2, infinity)", "(-1, infinity)", "(-infinity, -2)", "(0, infinity)"], ans=0,
   why="f''(x) = e^x(x + 2) has the sign of x + 2 because e^x > 0."),
 dict(q="The inflection points of the graph of f(x) = e^(-x^2) occur at",
   choices=[
   "x = -1/sqrt(2) and x = 1/sqrt(2)",
   "x = 0 only",
   "x = -1 and x = 1",
   "There are none"], ans=0,
   why="f''(x) = (4x^2 - 2) e^(-x^2) changes sign where 4x^2 = 2, that is at x = +/- 1/sqrt(2)."),
 dict(q="On its domain x > 0, the graph of f(x) = ln(x) is",
   choices=[
   "concave down throughout, with no inflection point",
   "concave up throughout",
   "concave up on (0, 1) and concave down on (1, infinity)",
   "concave down with an inflection point at x = 1"], ans=0,
   why="f''(x) = -1/x^2 is negative for every x in the domain."),
 dict(q="On (0, 2pi), the graph of f(x) = sin(x) has an inflection point at",
   choices=["x = pi", "x = pi/2", "x = 3pi/2", "x = 2pi"], ans=0,
   why="f''(x) = -sin(x) changes from negative to positive at x = pi."),
 dict(q="The graph of f(x) = 1/x is",
   choices=[
   "concave down on (-infinity, 0) and concave up on (0, infinity), with no inflection point",
   "concave up on (-infinity, 0) and concave down on (0, infinity)",
   "concave up everywhere except at x = 0, which is an inflection point",
   "concave down on its whole domain"], ans=0,
   why="f''(x) = 2/x^3 has the sign of x, and although concavity differs on the two branches, x = 0 is not in the domain so it cannot be an inflection point."),
 dict(q="The graph of f(x) = x + 1/x is concave up on",
   choices=["(0, infinity)", "(-infinity, 0)", "(-1, 1)", "(1, infinity)"], ans=0,
   why="f''(x) = 2/x^3 is positive exactly when x > 0."),
 dict(q="For f(x) = x^(1/3), the point x = 0",
   choices=[
   "is an inflection point, since f is continuous there and f'' changes sign",
   "is not an inflection point, since f''(0) does not exist",
   "is not an inflection point, since f'' does not change sign",
   "is a relative minimum"], ans=0,
   why="f''(x) = -(2/9) x^(-5/3) is positive for x < 0 and negative for x > 0, and f is continuous at 0, so the concavity genuinely changes there."),
 dict(q="The graph of f(x) = x^(4/3) is",
   choices=[
   "concave up on (-infinity, 0) and on (0, infinity), with no inflection point",
   "concave down everywhere",
   "concave up only for x > 0",
   "concave up with an inflection point at x = 0"], ans=0,
   why="f''(x) = (4/9) x^(-2/3) is positive wherever it is defined, so the concavity never changes."),
 dict(q="The graph of f(x) = arctan(x) is concave up on",
   choices=["(-infinity, 0)", "(0, infinity)", "(-1, 1)", "(-infinity, infinity)"], ans=0,
   why="f''(x) = -2x/(1 + x^2)^2 has the sign of -x, so it is positive for x < 0."),
 dict(q="On its domain x > 0, the graph of f(x) = x^2 ln(x) has an inflection point at",
   choices=["x = e^(-3/2)", "x = 1", "x = e^(-1/2)", "x = e"], ans=0,
   why="f''(x) = 2 ln(x) + 3 changes sign where ln(x) = -3/2."),
 dict(q="The graph of f(x) = x^3 - 6x^2 + 12x - 7 is",
   choices=[
   "concave down on (-infinity, 2) and concave up on (2, infinity)",
   "concave up everywhere, since f'(x) = 3(x - 2)^2 >= 0",
   "concave down everywhere",
   "concave up on (-infinity, 2) and concave down on (2, infinity)"], ans=0,
   why="f''(x) = 6x - 12 changes sign at x = 2, even though f' = 3(x - 2)^2 never becomes negative."),
 dict(q="A function f has f''(x) = (x - 1)(x + 4)^2. The graph of f is concave up on",
   choices=["(1, infinity)", "(-4, 1)", "(-infinity, -4) and (1, infinity)", "(-infinity, -4)"], ans=0,
   why="The squared factor is never negative, so f'' has the sign of x - 1."),
 dict(q="A function f has f''(x) < 0 on (-infinity, 3), f''(3) = 0, and f''(x) < 0 on (3, infinity). The graph of f",
   choices=[
   "has no inflection point, because concavity never changes",
   "has an inflection point at x = 3",
   "is concave up on (3, infinity)",
   "has a relative maximum at x = 3"], ans=0,
   why="An inflection point requires a change of sign in f'', and here f'' is negative on both sides of 3."),
 dict(q="A twice-differentiable function has f'(x) < 0 and f''(x) > 0 on an interval. On that interval the graph is",
   choices=[
   "decreasing and concave up",
   "decreasing and concave down",
   "increasing and concave up",
   "increasing and concave down"], ans=0,
   why="The sign of f' gives the direction and the sign of f'' gives the concavity, and the two are independent."),
]
