# CALC 5.7 Using the Second Derivative Test to Determine Extrema — 25 questions
# Answers verified with sympy; see verify_c5_7.py.
# Questions 1, 2, 3 and 4 state the test itself and carry no computation.
# Every other item is confirmed by solving f'(c) = 0 and evaluating f''(c),
# and each inconclusive case (f''(c) = 0) is settled with the first
# derivative test instead.
TOPIC = ("5.7", "Using the Second Derivative Test to Determine Extrema", 5)
QUESTIONS = [
 dict(q="The second derivative test says that if f'(c) = 0 and f''(c) < 0, then f has",
   choices=[
   "a relative maximum at c",
   "a relative minimum at c",
   "an inflection point at c",
   "no extremum at c"], ans=0,
   why="A horizontal tangent on a concave-down graph is a peak."),
 dict(q="The second derivative test says that if f'(c) = 0 and f''(c) > 0, then f has",
   choices=[
   "a relative minimum at c",
   "a relative maximum at c",
   "an inflection point at c",
   "no extremum at c"], ans=0,
   why="A horizontal tangent on a concave-up graph is a valley."),
 dict(q="If f'(c) = 0 and f''(c) = 0, the second derivative test",
   choices=[
   "is inconclusive, and the first derivative test must be used instead",
   "shows that c is an inflection point",
   "shows that c is not an extremum",
   "shows that c is a relative minimum"], ans=0,
   why="A zero second derivative gives no information about concavity near c; x^4, -x^4, and x^3 all satisfy it at 0 with three different outcomes."),
 dict(q="The second derivative test cannot be applied at a critical number c when",
   choices=[
   "f'(c) does not exist",
   "f''(c) < 0",
   "f(c) = 0",
   "c is not an integer"], ans=0,
   why="The test begins from f'(c) = 0, so a corner or cusp, where f' is undefined, must be handled by the first derivative test."),
 dict(q="For f(x) = x^2 - 4x + 1, the second derivative test shows",
   choices=[
   "a relative minimum at x = 2",
   "a relative maximum at x = 2",
   "a relative minimum at x = 0",
   "no extremum"], ans=0,
   why="f'(x) = 2x - 4 vanishes at x = 2, where f'' = 2 > 0."),
 dict(q="For f(x) = x^3 - 12x, the second derivative test shows a relative maximum at",
   choices=["x = -2", "x = 2", "x = 0", "x = 4"], ans=0,
   why="f'(x) = 3x^2 - 12 vanishes at x = +/- 2, and f''(x) = 6x is negative at x = -2."),
 dict(q="For f(x) = x^3 - 3x^2 - 9x, the second derivative test shows a relative minimum at",
   choices=["x = 3", "x = -1", "x = 1", "x = 0"], ans=0,
   why="f'(x) = 3(x - 3)(x + 1) vanishes at 3 and -1, and f''(x) = 6x - 6 is positive at x = 3."),
 dict(q="For f(x) = x^4 - 2x^2, the second derivative test at x = 0 shows",
   choices=[
   "a relative maximum, since f''(0) = -4",
   "a relative minimum, since f''(0) = 4",
   "nothing, since f''(0) = 0",
   "an inflection point"], ans=0,
   why="f'(x) = 4x^3 - 4x vanishes at 0, and f''(x) = 12x^2 - 4 gives f''(0) = -4 < 0."),
 dict(q="For f(x) = x + 4/x, the second derivative test shows",
   choices=[
   "a relative minimum at x = 2 and a relative maximum at x = -2",
   "a relative maximum at x = 2 and a relative minimum at x = -2",
   "relative minima at both x = 2 and x = -2",
   "no extrema"], ans=0,
   why="f''(x) = 8/x^3 is positive at x = 2 and negative at x = -2."),
 dict(q="For f(x) = x e^(-x), the second derivative test at the critical number x = 1 gives",
   choices=[
   "a relative maximum, since f''(1) = -1/e",
   "a relative minimum, since f''(1) = 1/e",
   "no conclusion, since f''(1) = 0",
   "a relative maximum, since f''(1) = -e"], ans=0,
   why="f''(x) = e^(-x)(x - 2), so f''(1) = -1/e < 0."),
 dict(q="For f(x) = x^2 + 16/x, the second derivative test shows a relative minimum at",
   choices=["x = 2", "x = 4", "x = -2", "x = 8"], ans=0,
   why="f'(x) = 2x - 16/x^2 vanishes when x^3 = 8, and f''(x) = 2 + 32/x^3 gives f''(2) = 6 > 0."),
 dict(q="On (0, 2pi), the second derivative test applied to f(x) = sin(x) shows",
   choices=[
   "a relative maximum at pi/2 and a relative minimum at 3pi/2",
   "a relative minimum at pi/2 and a relative maximum at 3pi/2",
   "relative maxima at both",
   "nothing, since f'' = 0 at both"], ans=0,
   why="f''(x) = -sin(x) equals -1 at pi/2 and 1 at 3pi/2."),
 dict(q="For f(x) = x^2 e^x, the second derivative test shows",
   choices=[
   "a relative maximum at x = -2 and a relative minimum at x = 0",
   "a relative minimum at x = -2 and a relative maximum at x = 0",
   "relative minima at both critical numbers",
   "no extrema, since f'' is zero at both critical numbers"], ans=0,
   why="f''(x) = e^x(x^2 + 4x + 2) gives f''(-2) = -2/e^2 < 0 and f''(0) = 2 > 0."),
 dict(q="For f(x) = x/(x^2 + 1), the second derivative test at x = 1 gives",
   choices=[
   "a relative maximum, since f''(1) = -1/2",
   "a relative minimum, since f''(1) = 1/2",
   "no conclusion, since f''(1) = 0",
   "an inflection point"], ans=0,
   why="f''(x) = (2x^3 - 6x)/(x^2 + 1)^3, so f''(1) = -4/8 = -1/2 < 0."),
 dict(q="On x > 0, the second derivative test applied to f(x) = ln(x) - x shows",
   choices=[
   "a relative maximum at x = 1",
   "a relative minimum at x = 1",
   "a relative maximum at x = e",
   "no extremum"], ans=0,
   why="f'(x) = 1/x - 1 vanishes at x = 1, and f''(x) = -1/x^2 gives f''(1) = -1 < 0."),
 dict(q="For f(x) = 2x + 1/x^2 on x > 0, the relative minimum value found with the second derivative test is",
   choices=["3", "2", "1", "4"], ans=0,
   why="f'(x) = 2 - 2/x^3 vanishes at x = 1, f''(x) = 6/x^4 gives f''(1) = 6 > 0, and f(1) = 3."),
 dict(q="For f(x) = x^4, the second derivative test at x = 0",
   choices=[
   "is inconclusive, but the first derivative test shows a relative minimum",
   "shows a relative minimum, since f''(0) = 12",
   "shows no extremum",
   "shows a relative maximum"], ans=0,
   why="f''(0) = 0 makes the test silent, while f' = 4x^3 changes from negative to positive at 0."),
 dict(q="For f(x) = -x^4, the second derivative test at x = 0",
   choices=[
   "is inconclusive, but the first derivative test shows a relative maximum",
   "shows a relative maximum, since f''(0) < 0",
   "shows a relative minimum",
   "shows no extremum"], ans=0,
   why="f''(0) = 0 gives no conclusion, while f' = -4x^3 changes from positive to negative at 0."),
 dict(q="For f(x) = x^3, the second derivative test at x = 0",
   choices=[
   "is inconclusive, and the first derivative test shows no extremum",
   "shows a relative minimum",
   "shows a relative maximum",
   "shows a relative minimum, since f''(x) = 6x"], ans=0,
   why="Both f'(0) and f''(0) are zero, and f' = 3x^2 stays positive on both sides, so f has no extremum there."),
 dict(q="For f(x) = x^5, the second derivative test at x = 0",
   choices=[
   "is inconclusive, and f has no extremum at 0",
   "shows a relative minimum",
   "shows a relative maximum",
   "does not apply, since f'(0) is undefined"], ans=0,
   why="f'(0) = f''(0) = 0, and f' = 5x^4 is nonnegative on both sides, so f increases through 0."),
 dict(q="For f(x) = (x + 1)^3, the second derivative test at the critical number x = -1",
   choices=[
   "is inconclusive, and the first derivative test shows no extremum",
   "shows a relative minimum",
   "shows a relative maximum",
   "does not apply, since x = -1 is not a critical number"], ans=0,
   why="f''(x) = 6(x + 1) vanishes at -1, and f' = 3(x + 1)^2 does not change sign there."),
 dict(q="For f(x) = x + cos(x), at the critical number x = pi/2 the second derivative test",
   choices=[
   "is inconclusive, and the first derivative test shows no extremum",
   "shows a relative maximum",
   "shows a relative minimum",
   "does not apply, since f is not differentiable there"], ans=0,
   why="f'(x) = 1 - sin(x) vanishes at pi/2 and f''(x) = -cos(x) is zero there, but f' is never negative, so f keeps increasing."),
 dict(q="Which function has a critical number at which the second derivative test is inconclusive but a relative minimum does occur?",
   choices=[
   "f(x) = x^6",
   "f(x) = x^2",
   "f(x) = x^3",
   "f(x) = -x^6"], ans=0,
   why="For x^6 both f'(0) and f''(0) are zero, yet f' changes from negative to positive at 0."),
 dict(q="A twice-differentiable function has f'(4) = 0 and f''(4) = -3. Which statement is true?",
   choices=[
   "f has a relative maximum at x = 4, and the graph is concave down near x = 4",
   "f has a relative minimum at x = 4",
   "f has an inflection point at x = 4",
   "f is decreasing on an interval containing x = 4"], ans=0,
   why="A negative second derivative at a stationary point gives a peak, and by continuity of f'' the graph is concave down nearby."),
 dict(q="For f(x) = x^3 - 3x^2 + 3x, the second derivative test at x = 1",
   choices=[
   "is inconclusive, and f has no relative extremum there",
   "shows a relative minimum",
   "shows a relative maximum",
   "does not apply, since f'(1) is not 0"], ans=0,
   why="f'(x) = 3(x - 1)^2 is zero at 1 and f''(1) = 0, but f' never changes sign, so f is increasing throughout."),
]
