# CALC 5.8 Sketching Graphs of Functions and Their Derivatives — 25 questions
# Answers verified with sympy; see verify_c5_8.py.
# No item refers to a picture: a derivative is either given by a formula or
# described in words, as a sign chart, or as a table of values. The purely
# descriptive items (7, 8, 9, 20, 21, 22) are checked against the standard
# meaning of the signs of f' and f''; every item with a formula in it is
# confirmed with sympy.
TOPIC = ("5.8", "Sketching Graphs of Functions and Their Derivatives", 5)
QUESTIONS = [
 dict(q="For f(x) = x^2 - 6x + 5, the graph of f' is",
   choices=[
   "a line of slope 2 crossing the x-axis at x = 3",
   "a parabola opening upward with vertex at x = 3",
   "a line of slope 2 crossing the x-axis at x = 5",
   "a horizontal line at height 2"], ans=0,
   why="f'(x) = 2x - 6 is linear with slope 2 and a zero at x = 3, the vertex of the parabola."),
 dict(q="For f(x) = x^3 - 3x, the graph of f' is",
   choices=[
   "a parabola opening upward with vertex (0, -3) and x-intercepts at -1 and 1",
   "a parabola opening downward with x-intercepts at -1 and 1",
   "a cubic with three x-intercepts",
   "a line through the origin with slope 3"], ans=0,
   why="f'(x) = 3x^2 - 3 is an upward parabola whose minimum value is -3 at x = 0 and whose zeros are +/- 1."),
 dict(q="If the graph of f' is the horizontal line y = 4, then the graph of f is",
   choices=[
   "a line of slope 4",
   "a horizontal line at height 4",
   "a parabola with vertex on the x-axis",
   "an exponential curve"], ans=0,
   why="A constant derivative means constant slope, so f(x) = 4x + C."),
 dict(q="If the graph of f' is a line with positive slope crossing the x-axis at x = 2, then f",
   choices=[
   "has a relative minimum at x = 2 and is concave up everywhere",
   "has a relative maximum at x = 2 and is concave down everywhere",
   "has an inflection point at x = 2",
   "is increasing everywhere"], ans=0,
   why="f' passes from negative to positive at 2, giving a minimum, and f'' is the positive constant slope of that line."),
 dict(q="The graph of f' is a parabola opening upward with x-intercepts at x = 1 and x = 5. The function f has",
   choices=[
   "a relative maximum at x = 1 and a relative minimum at x = 5",
   "a relative minimum at x = 1 and a relative maximum at x = 5",
   "relative minima at both x = 1 and x = 5",
   "no relative extrema"], ans=0,
   why="An upward parabola is positive outside its roots and negative between them, so f' changes from positive to negative at 1 and back at 5."),
 dict(q="The graph of f' is a parabola opening upward with x-intercepts at x = 1 and x = 5. The graph of f has an inflection point at",
   choices=["x = 3", "x = 1", "x = 5", "x = 0"], ans=0,
   why="f'' changes sign where f' has its minimum, which is at the vertex x = 3, halfway between the roots."),
 dict(q="On an interval where f' is positive and increasing, the graph of f is",
   choices=[
   "increasing and concave up",
   "increasing and concave down",
   "decreasing and concave up",
   "decreasing and concave down"], ans=0,
   why="A positive f' means rising, and an increasing f' means f'' > 0."),
 dict(q="On an interval where f' is positive and decreasing, the graph of f is",
   choices=[
   "increasing and concave down",
   "increasing and concave up",
   "decreasing and concave down",
   "decreasing and concave up"], ans=0,
   why="f' > 0 gives a rising graph, and a falling f' gives f'' < 0."),
 dict(q="On an interval where f' is negative and increasing toward zero, the graph of f is",
   choices=[
   "decreasing and concave up",
   "decreasing and concave down",
   "increasing and concave up",
   "increasing and concave down"], ans=0,
   why="f' < 0 gives a falling graph, and an increasing f' gives f'' > 0, so the fall is flattening out."),
 dict(q="If the graph of f' lies entirely above the x-axis, then f",
   choices=[
   "has no relative extrema and is increasing on its whole domain",
   "has exactly one relative minimum",
   "is concave up everywhere",
   "has an inflection point wherever f' has a minimum value"], ans=0,
   why="f' never changes sign, so f never turns around; the concavity depends on whether f' rises or falls, which is not specified."),
 dict(q="If f'(x) = (x - 2)^2, then the graph of f",
   choices=[
   "is increasing everywhere, with a horizontal tangent but no extremum at x = 2",
   "has a relative minimum at x = 2",
   "has a relative maximum at x = 2",
   "is decreasing for x < 2"], ans=0,
   why="A square is never negative, so f' vanishes at 2 without changing sign."),
 dict(q="For f(x) = |x - 2|, the graph of f' consists of",
   choices=[
   "the horizontal ray y = -1 for x < 2 and the horizontal ray y = 1 for x > 2, with no value at x = 2",
   "a single horizontal line y = 1",
   "the line y = x - 2",
   "a V-shaped graph with vertex at x = 2"], ans=0,
   why="The two straight pieces have slopes -1 and 1, and the corner leaves f'(2) undefined."),
 dict(q="For f(x) = e^x, the graph of f'",
   choices=[
   "is identical to the graph of f",
   "is the line y = x",
   "lies below the x-axis",
   "is the graph of f shifted down one unit"], ans=0,
   why="The derivative of e^x is e^x, so the two graphs coincide."),
 dict(q="On x > 0, the graph of f(x) = ln(x) is",
   choices=[
   "increasing and concave down, since f' = 1/x is positive and decreasing",
   "increasing and concave up, since f' = 1/x is positive and increasing",
   "decreasing and concave down",
   "increasing with an inflection point at x = 1"], ans=0,
   why="f' = 1/x is positive on the domain and falls as x grows, so f'' = -1/x^2 < 0."),
 dict(q="If f'(x) = cos(x) on [0, 2pi] and f(0) = 0, then the graph of f",
   choices=[
   "rises to a maximum at x = pi/2, falls to a minimum at x = 3pi/2, and returns to 0 at 2pi",
   "falls to a minimum at pi/2 and rises to a maximum at 3pi/2",
   "is increasing on the whole interval",
   "has an inflection point only at x = pi/2"], ans=0,
   why="f(x) = sin(x), which peaks where cos changes from positive to negative and bottoms out where it changes back."),
 dict(q="If f'(x) = sin(x) on (0, 2pi), the graph of f has",
   choices=[
   "a relative maximum at x = pi and no other relative extremum in the interval",
   "a relative minimum at x = pi",
   "relative extrema at pi/2 and 3pi/2",
   "no relative extrema"], ans=0,
   why="sin(x) is positive on (0, pi) and negative on (pi, 2pi), so f' changes from positive to negative only at pi."),
 dict(q="A table of values gives f'(0) = -2, f'(1) = 0, f'(2) = 3, f'(3) = 5, and f' is increasing on [0, 3]. On [0, 3] the graph of f",
   choices=[
   "has a relative minimum at x = 1 and is concave up throughout",
   "has a relative maximum at x = 1 and is concave down throughout",
   "is increasing throughout",
   "has an inflection point at x = 1"], ans=0,
   why="An increasing f' that passes through zero at x = 1 changes sign from negative to positive there, and an increasing f' means f'' > 0."),
 dict(q="A sign chart shows f'(x) > 0 on (-infinity, -2), f'(x) < 0 on (-2, 3), and f'(x) > 0 on (3, infinity), with f continuous. The graph of f",
   choices=[
   "has a relative maximum at x = -2 and a relative minimum at x = 3",
   "has a relative minimum at x = -2 and a relative maximum at x = 3",
   "has inflection points at x = -2 and x = 3",
   "is increasing on (-2, 3)"], ans=0,
   why="f' turns from positive to negative at -2 and from negative to positive at 3."),
 dict(q="A sign chart shows f''(x) < 0 on (-infinity, 0) and f''(x) > 0 on (0, infinity), with f twice differentiable. The graph of f",
   choices=[
   "is concave down then concave up, with an inflection point at x = 0",
   "has a relative minimum at x = 0",
   "has a relative maximum at x = 0",
   "is increasing on (0, infinity)"], ans=0,
   why="A change in the sign of f'' is exactly a change of concavity, and it says nothing by itself about rising or falling."),
 dict(q="If the graph of f' has a relative maximum at x = 1, then the graph of f has",
   choices=[
   "an inflection point at x = 1",
   "a relative maximum at x = 1",
   "a relative minimum at x = 1",
   "a vertical tangent at x = 1"], ans=0,
   why="f'' = 0 with a sign change at the peak of f', which is the definition of an inflection point of f."),
 dict(q="If the graph of f is increasing and concave up on an interval, then on that interval the graph of f' is",
   choices=[
   "above the x-axis and rising",
   "above the x-axis and falling",
   "below the x-axis and rising",
   "a horizontal line"], ans=0,
   why="Increasing means f' > 0 and concave up means f' is itself increasing."),
 dict(q="If f is a cubic polynomial with two distinct critical numbers, the graph of f' is",
   choices=[
   "a parabola with two distinct x-intercepts",
   "a line with one x-intercept",
   "a cubic with two x-intercepts",
   "a parabola tangent to the x-axis"], ans=0,
   why="The derivative of a cubic is a quadratic, and two distinct critical numbers are two distinct real roots."),
 dict(q="For f(x) = x^4 - 4x^2, the graph of f has",
   choices=[
   "three critical points and two inflection points",
   "two critical points and one inflection point",
   "three critical points and no inflection point",
   "one critical point and two inflection points"], ans=0,
   why="f'(x) = 4x(x^2 - 2) has three zeros and f''(x) = 12x^2 - 8 changes sign twice."),
 dict(q="For f(x) = x^(1/3), the graph of f at x = 0 has",
   choices=[
   "a vertical tangent, since f'(x) = 1/(3 x^(2/3)) increases without bound as x approaches 0",
   "a corner, since the one-sided derivatives are -1 and 1",
   "a horizontal tangent, since f'(0) = 0",
   "a relative minimum"], ans=0,
   why="The derivative blows up to positive infinity from both sides, which is the signature of a vertical tangent rather than a corner."),
 dict(q="If f'(x) = 2x and f(0) = 1, the graph of f is",
   choices=[
   "a parabola opening upward with vertex at (0, 1)",
   "a parabola opening upward with vertex at (0, 0)",
   "a line of slope 2 through (0, 1)",
   "a parabola opening downward with vertex at (0, 1)"], ans=0,
   why="Antidifferentiating gives f(x) = x^2 + C, and f(0) = 1 makes C = 1."),
]
