# CALC 5.9 Connecting a Function, Its First Derivative, and Its Second Derivative — 25 questions
# Answers verified with sympy; see verify_c5_9.py.
# No item refers to a picture: derivatives are given by formulas, sign charts,
# or tables of values. The items that only combine the meanings of the signs
# of f' and f'' (1, 2, 3, 4, 20, 21, 22, 24) carry no computation; every item
# naming a function or a set of values is confirmed with sympy.
TOPIC = ("5.9", "Connecting a Function, Its First Derivative, and Its Second Derivative", 5)
QUESTIONS = [
 dict(q="A function f is decreasing and concave up on an interval. On that interval f' is",
   choices=[
   "negative and increasing",
   "negative and decreasing",
   "positive and increasing",
   "positive and decreasing"], ans=0,
   why="Decreasing means f' < 0, and concave up means f' is going up."),
 dict(q="A function f is increasing and concave down on an interval. On that interval",
   choices=[
   "f' > 0 and f'' < 0",
   "f' > 0 and f'' > 0",
   "f' < 0 and f'' < 0",
   "f' < 0 and f'' > 0"], ans=0,
   why="Rising gives a positive first derivative and concave down gives a negative second derivative."),
 dict(q="Can a function be increasing on an interval while its derivative is decreasing there?",
   choices=[
   "Yes, that is exactly an increasing, concave-down function",
   "No, because f increasing forces f' increasing",
   "No, because f' decreasing forces f decreasing",
   "Only if f is linear"], ans=0,
   why="f' can stay positive while shrinking, as with f(x) = sqrt(x) on x > 0."),
 dict(q="If f is twice differentiable and has an inflection point at x = c, then",
   choices=[
   "f''(c) = 0",
   "f'(c) = 0",
   "f(c) = 0",
   "f''(c) > 0"], ans=0,
   why="f'' changes sign at c and is continuous there, so it must pass through zero."),
 dict(q="A twice-differentiable function has f(1) = 3, f'(1) = 0, and f''(1) = -2. Then",
   choices=[
   "f has a relative maximum value of 3 at x = 1",
   "f has a relative minimum value of 3 at x = 1",
   "f has an inflection point at x = 1",
   "f is increasing at x = 1"], ans=0,
   why="A stationary point with negative second derivative is a peak, and the value there is f(1) = 3."),
 dict(q="If f'' (x) > 0 for all x and f'(2) = 0, then f(2) is",
   choices=[
   "the absolute minimum value of f",
   "the absolute maximum value of f",
   "a relative maximum value but not an absolute one",
   "neither a maximum nor a minimum"], ans=0,
   why="A function concave up everywhere lies above its tangent line at x = 2, which is horizontal, so f(x) >= f(2) for every x."),
 dict(q="For f(x) = x^3 - 3x^2, the interval on which f is both decreasing and concave up is",
   choices=["(1, 2)", "(0, 1)", "(0, 2)", "(2, infinity)"], ans=0,
   why="f'(x) = 3x(x - 2) is negative on (0, 2) and f''(x) = 6x - 6 is positive for x > 1, and the two overlap on (1, 2)."),
 dict(q="For f(x) = x^3 - 3x^2, the interval on which f is both decreasing and concave down is",
   choices=["(0, 1)", "(1, 2)", "(-infinity, 0)", "(0, 2)"], ans=0,
   why="f' < 0 on (0, 2) and f'' < 0 for x < 1, so both hold exactly on (0, 1)."),
 dict(q="For f(x) = x^4 - 4x^3, the interval on which f is both decreasing and concave down is",
   choices=["(0, 2)", "(2, 3)", "(-infinity, 0)", "(0, 3)"], ans=0,
   why="f'(x) = 4x^2(x - 3) is negative for x < 3 except at 0, and f''(x) = 12x(x - 2) is negative on (0, 2)."),
 dict(q="For f(x) = e^(-x^2), the interval on which f is both increasing and concave down is",
   choices=[
   "(-1/sqrt(2), 0)",
   "(0, 1/sqrt(2))",
   "(-infinity, -1/sqrt(2))",
   "(-1/sqrt(2), 1/sqrt(2))"], ans=0,
   why="f' = -2x e^(-x^2) is positive for x < 0, and f'' = (4x^2 - 2) e^(-x^2) is negative between -1/sqrt(2) and 1/sqrt(2)."),
 dict(q="For f(x) = x + 2 cos(x), at x = 2pi/3 the graph of f is",
   choices=[
   "decreasing and concave up",
   "decreasing and concave down",
   "increasing and concave up",
   "increasing and concave down"], ans=0,
   why="f'(x) = 1 - 2 sin(x) gives f'(2pi/3) = 1 - sqrt(3) < 0, and f''(x) = -2 cos(x) gives f''(2pi/3) = 1 > 0."),
 dict(q="A function f has f'(x) = x^2 - 4 and f''(x) = 2x. At x = -2 the function f has",
   choices=[
   "a relative maximum",
   "a relative minimum",
   "an inflection point",
   "no extremum"], ans=0,
   why="f'(-2) = 0 and f''(-2) = -4 < 0."),
 dict(q="A function f has f'(x) = x^2 - 4 and f''(x) = 2x. The graph of f has an inflection point at",
   choices=["x = 0", "x = -2", "x = 2", "x = 4"], ans=0,
   why="f'' = 2x changes sign only at x = 0."),
 dict(q="A table of values gives f'(1) = 4, f'(2) = 1, and f'(3) = -3, with f' decreasing on [1, 3]. On [1, 3] the graph of f is",
   choices=[
   "concave down, with a relative maximum between x = 2 and x = 3",
   "concave up, with a relative minimum between x = 2 and x = 3",
   "concave down, with a relative minimum between x = 1 and x = 2",
   "increasing throughout"], ans=0,
   why="A decreasing f' means f'' < 0, and f' changes from positive to negative somewhere between 2 and 3."),
 dict(q="A twice-differentiable function has f'(x) < 0 on (0, 5) and f''(x) > 0 on (0, 5). Which ordering of values is correct?",
   choices=[
   "f(1) > f(3) > f(4)",
   "f(1) < f(3) < f(4)",
   "f(3) > f(1) > f(4)",
   "f(4) > f(1) > f(3)"], ans=0,
   why="f is decreasing on the interval, so larger inputs give smaller outputs regardless of the concavity."),
 dict(q="A function f has f''(x) = 6x - 12 and f'(2) = 0. At x = 2 the graph of f has",
   choices=[
   "a horizontal tangent and an inflection point, so no extremum",
   "a relative minimum",
   "a relative maximum",
   "a vertical tangent"], ans=0,
   why="f''(2) = 0 and 6x - 12 changes sign at 2, so the concavity changes at a point where the tangent is horizontal."),
 dict(q="For f(x) = x^3 - 3x^2 + 2, which statement is correct?",
   choices=[
   "f has a relative maximum at x = 0, a relative minimum at x = 2, and an inflection point at x = 1",
   "f has a relative minimum at x = 0 and a relative maximum at x = 2",
   "f has inflection points at x = 0 and x = 2",
   "f is increasing on (0, 2)"], ans=0,
   why="f'(x) = 3x(x - 2) changes sign at 0 and 2, and f''(x) = 6x - 6 changes sign at 1."),
 dict(q="A sign chart shows f'(x) > 0 and f''(x) < 0 on (2, 6), with f(2) = 1 and f(6) = 9. On (2, 6) the graph of f",
   choices=[
   "rises from 1 to 9 while flattening out",
   "rises from 1 to 9 while getting steeper",
   "falls from 9 to 1",
   "has a relative maximum inside the interval"], ans=0,
   why="f' > 0 gives the rise and f'' < 0 means the slopes are shrinking as x increases."),
 dict(q="For f(x) = ln(x^2 + 1), at x = 2 the function is",
   choices=[
   "increasing and concave down",
   "increasing and concave up",
   "decreasing and concave down",
   "decreasing and concave up"], ans=0,
   why="f'(x) = 2x/(x^2 + 1) gives f'(2) = 4/5 > 0, and f''(x) = (2 - 2x^2)/(x^2 + 1)^2 gives f''(2) = -6/25 < 0."),
 dict(q="If f'(c) = 0 and f''(c) = 0, then at x = c the function f",
   choices=[
   "may have a relative maximum, a relative minimum, or neither",
   "must have an inflection point",
   "must have a relative extremum",
   "cannot have an extremum"], ans=0,
   why="At x = 0 the functions -x^4, x^4, and x^3 satisfy both conditions and give a maximum, a minimum, and neither."),
 dict(q="Which pair of conditions describes a graph that falls ever more steeply?",
   choices=[
   "f' < 0 and f'' < 0",
   "f' < 0 and f'' > 0",
   "f' > 0 and f'' < 0",
   "f' > 0 and f'' > 0"], ans=0,
   why="A negative slope becoming more negative is a negative first derivative together with a negative second derivative."),
 dict(q="If f' is continuous and changes from negative to positive at x = c while f'' stays positive near c, then f has",
   choices=[
   "a relative minimum at c, confirmed by both derivative tests",
   "a relative maximum at c",
   "an inflection point at c",
   "no extremum at c"], ans=0,
   why="The sign change gives a minimum by the first derivative test, and f''(c) > 0 gives the same conclusion by the second."),
 dict(q="For f(x) = x/(x^2 + 1), the number of x-values at which f has a horizontal tangent and the number at which the graph has an inflection point are",
   choices=[
   "two horizontal tangents and three inflection points",
   "two horizontal tangents and one inflection point",
   "one horizontal tangent and two inflection points",
   "three horizontal tangents and two inflection points"], ans=0,
   why="f'(x) = (1 - x^2)/(x^2 + 1)^2 is zero at x = +/- 1, and f''(x) = (2x^3 - 6x)/(x^2 + 1)^3 changes sign at x = 0 and x = +/- sqrt(3)."),
 dict(q="A twice-differentiable function has f(0) = 2, f'(0) = -1, and f''(x) > 0 for all x. Which statement must be true?",
   choices=[
   "f(x) > 2 - x for every x other than 0",
   "f is decreasing for all x",
   "f has a relative maximum at x = 0",
   "f(1) < 1"], ans=0,
   why="A function concave up everywhere lies strictly above its tangent line y = 2 - x except at the point of tangency."),
 dict(q="For f(x) = x^4 - 4x^3 + 10, how many x-values give a horizontal tangent, and how many give an inflection point?",
   choices=[
   "Two horizontal tangents and two inflection points",
   "Three horizontal tangents and two inflection points",
   "Two horizontal tangents and one inflection point",
   "One horizontal tangent and two inflection points"], ans=0,
   why="f'(x) = 4x^2(x - 3) is zero at x = 0 and x = 3, and f''(x) = 12x(x - 2) changes sign at x = 0 and x = 2."),
]
