# CALC 9.1 Defining and Differentiating Parametric Equations — 25 questions
# Answers verified with sympy; see verify_c9_1.py.
# Questions 1, 4, 5 and 18 are conceptual (a statement of the parametric slope
# formula and of the horizontal/vertical tangent conditions), so no computation
# can confirm them; verify_c9_1.py pins their keys by content and the reasoning
# is stated in each `why`.
TOPIC = ("9.1", "Defining and Differentiating Parametric Equations", 9)
QUESTIONS = [
 dict(q="A curve is defined by x = f(t) and y = g(t), where f and g are differentiable and f'(t) is not 0. Then dy/dx =",
   choices=[
     "(dy/dt)/(dx/dt)",
     "(dx/dt)/(dy/dt)",
     "(dy/dt)(dx/dt)",
     "dy/dt - dx/dt"], ans=0,
   why="By the chain rule dy/dt = (dy/dx)(dx/dt), so dividing by dx/dt gives dy/dx = (dy/dt)/(dx/dt)."),
 dict(q="A curve is given by x = t^2 + 1 and y = t^3 - t. In terms of t, dy/dx =",
   choices=[
     "(3t^2 - 1)/(2t)",
     "2t/(3t^2 - 1)",
     "(3t^2 - 1)/2",
     "3t^2 - 1"], ans=0,
   why="dy/dt = 3t^2 - 1 and dx/dt = 2t, and dy/dx is their quotient."),
 dict(q="For the curve x = t^2 + 1, y = t^3 - t, the slope of the tangent line at t = 2 is",
   choices=[
     "4/11",
     "11/4",
     "11/2",
     "11"], ans=1,
   why="dy/dx = (3t^2 - 1)/(2t) = (12 - 1)/4 = 11/4 at t = 2."),
 dict(q="The curve x = f(t), y = g(t) has a horizontal tangent line at t = c when",
   choices=[
     "g'(c) = 0 and f'(c) is not 0",
     "f'(c) = 0 and g'(c) is not 0",
     "f'(c) = 0 and g'(c) = 0",
     "f'(c) = g'(c)"], ans=0,
   why="A horizontal tangent needs dy/dx = 0, which requires the numerator dy/dt to vanish while the denominator dx/dt does not."),
 dict(q="The curve x = f(t), y = g(t) has a vertical tangent line at t = c when",
   choices=[
     "f'(c) = 0 and g'(c) is not 0",
     "g'(c) = 0 and f'(c) is not 0",
     "f'(c) = 0 and g'(c) = 0",
     "f'(c) and g'(c) are both nonzero"], ans=0,
   why="A vertical tangent needs dy/dx to be undefined, which happens when dx/dt = 0 while dy/dt is not 0."),
 dict(q="For the curve x = t^3 - 3t, y = t^2 - 4, the tangent line is horizontal at",
   choices=[
     "t = 0 only",
     "t = 1 and t = -1",
     "t = 0, t = 1, and t = -1",
     "no value of t"], ans=0,
   why="dy/dt = 2t is 0 only at t = 0, where dx/dt = -3 is not 0."),
 dict(q="For the curve x = t^3 - 3t, y = t^2 - 4, the tangent line is vertical at",
   choices=[
     "t = 1 and t = -1",
     "t = 0 only",
     "t = 3 only",
     "no value of t"], ans=0,
   why="dx/dt = 3t^2 - 3 = 0 at t = 1 and t = -1, and dy/dt = 2t is not 0 at either value."),
 dict(q="For the curve x = cos(t), y = sin(t) with 0 < t < pi, dy/dx =",
   choices=[
     "-cos(t)/sin(t)",
     "cos(t)/sin(t)",
     "-sin(t)/cos(t)",
     "sin(t)/cos(t)"], ans=0,
   why="dy/dt = cos(t) and dx/dt = -sin(t), so the quotient is -cos(t)/sin(t)."),
 dict(q="For the curve x = cos(t), y = sin(t), the slope of the tangent line at t = pi/6 is",
   choices=[
     "-sqrt(3)",
     "sqrt(3)",
     "-sqrt(3)/3",
     "sqrt(3)/3"], ans=0,
   why="dy/dx = -cos(t)/sin(t) = -(sqrt(3)/2)/(1/2) = -sqrt(3) at t = pi/6."),
 dict(q="For the curve x = 3cos(t), y = 2sin(t), dy/dx =",
   choices=[
     "-(2cos(t))/(3sin(t))",
     "-(3sin(t))/(2cos(t))",
     "(2cos(t))/(3sin(t))",
     "-(2sin(t))/(3cos(t))"], ans=0,
   why="dy/dt = 2cos(t) and dx/dt = -3sin(t), so dy/dx = -(2cos(t))/(3sin(t))."),
 dict(q="At which of the following points does the curve x = 3cos(t), y = 2sin(t), 0 <= t < 2pi, have a horizontal tangent line?",
   choices=[
     "(0, 2)",
     "(3, 0)",
     "(-3, 0)",
     "(0, 0)"], ans=0,
   why="dy/dt = 2cos(t) = 0 at t = pi/2, where dx/dt = -3 is not 0 and the point is (0, 2); at (3, 0) and (-3, 0) the tangent is vertical."),
 dict(q="For the curve x = e^(2t), y = e^(3t), dy/dx =",
   choices=[
     "(3/2)e^t",
     "(3/2)e^(5t)",
     "(2/3)e^(-t)",
     "(3/2)e^(-t)"], ans=0,
   why="dy/dt = 3e^(3t) and dx/dt = 2e^(2t), and the quotient is (3/2)e^(3t - 2t) = (3/2)e^t."),
 dict(q="The curve x = t^2, y = t^3 - 3t is at the point (4, 2) when t = 2. An equation of the tangent line there is",
   choices=[
     "y - 2 = (9/4)(x - 4)",
     "y - 2 = (4/9)(x - 4)",
     "y - 4 = (9/4)(x - 2)",
     "y - 2 = 9(x - 4)"], ans=0,
   why="dy/dx = (3t^2 - 3)/(2t) = 9/4 at t = 2, and the point of tangency is (4, 2)."),
 dict(q="A curve is given by x = 2t + 1 and y = t^2 - t. Expressed as a function of x, dy/dx =",
   choices=[
     "(x - 2)/2",
     "(x - 1)/2",
     "(x - 2)/4",
     "2x - 2"], ans=0,
   why="dy/dx = (2t - 1)/2 and t = (x - 1)/2, so 2t - 1 = x - 2 and dy/dx = (x - 2)/2."),
 dict(q="A particle moves along a curve so that at t = 3 its rates of change are dx/dt = 4 and dy/dt = -6. The slope of the curve at t = 3 is",
   choices=[
     "-3/2",
     "-2/3",
     "2/3",
     "3/2"], ans=0,
   why="dy/dx = (dy/dt)/(dx/dt) = -6/4 = -3/2."),
 dict(q="For the cycloid x = t - sin(t), y = 1 - cos(t), dy/dx =",
   choices=[
     "sin(t)/(1 - cos(t))",
     "(1 - cos(t))/sin(t)",
     "sin(t)/(1 + cos(t))",
     "-sin(t)/(1 - cos(t))"], ans=0,
   why="dy/dt = sin(t) and dx/dt = 1 - cos(t), so dy/dx is their quotient."),
 dict(q="For the cycloid x = t - sin(t), y = 1 - cos(t), the slope of the tangent line at t = pi/2 is",
   choices=[
     "-1",
     "0",
     "1",
     "2"], ans=2,
   why="dy/dx = sin(t)/(1 - cos(t)) = 1/(1 - 0) = 1 at t = pi/2."),
 dict(q="For a parametric curve, dx/dt = 0 and dy/dt = 0 at t = c. Which of the following is true?",
   choices=[
     "The parametric slope formula gives 0/0 at t = c, so it determines nothing there; the curve may have a cusp",
     "The tangent line at t = c is horizontal",
     "The tangent line at t = c is vertical",
     "The curve has no point corresponding to t = c"], ans=0,
   why="Both derivatives vanishing makes (dy/dt)/(dx/dt) indeterminate, and curves such as x = t^3, y = t^2 have a cusp at such a value."),
 dict(q="For the curve x = ln(t), y = t^2 with t > 0, dy/dx =",
   choices=[
     "2t^2",
     "2t",
     "2/t",
     "1/(2t^2)"], ans=0,
   why="dy/dt = 2t and dx/dt = 1/t, so dy/dx = 2t / (1/t) = 2t^2."),
 dict(q="For the curve x = t^2 - 2t, y = t^3 - 12t, the tangent line is horizontal at",
   choices=[
     "t = 2 and t = -2",
     "t = 1 only",
     "t = 0 and t = 2",
     "t = 2 only"], ans=0,
   why="dy/dt = 3t^2 - 12 = 0 at t = 2 and t = -2, and dx/dt = 2t - 2 is 2 and -6 there, both nonzero."),
 dict(q="For the curve x = t^2 - 2t, y = t^3 - 12t, the tangent line is vertical at",
   choices=[
     "t = 1",
     "t = 0",
     "t = 2 and t = -2",
     "t = -1"], ans=0,
   why="dx/dt = 2t - 2 = 0 at t = 1, where dy/dt = 3 - 12 = -9 is not 0."),
 dict(q="At which points does the curve x = t^2, y = t^3 - 3t have a horizontal tangent line?",
   choices=[
     "(1, -2) and (1, 2)",
     "(1, -2) only",
     "(0, 0) only",
     "(-1, 2) and (1, -2)"], ans=0,
   why="dy/dt = 3t^2 - 3 = 0 at t = 1 and t = -1, giving the points (1, -2) and (1, 2), and dx/dt = 2t is nonzero at both."),
 dict(q="The curve x = t^2 + t, y = t^3 - t passes through the point (2, 0). The slope of the tangent line at that point is",
   choices=[
     "-2/3",
     "1/3",
     "2/3",
     "2"], ans=2,
   why="x = 2 and y = 0 force t = 1, where dy/dx = (3t^2 - 1)/(2t + 1) = 2/3."),
 dict(q="For the curve x = t^3, y = t^2 with t not equal to 0, dy/dx =",
   choices=[
     "2/(3t)",
     "(3t)/2",
     "2/(3t^2)",
     "6t^5"], ans=0,
   why="dy/dt = 2t and dx/dt = 3t^2, so dy/dx = 2t/(3t^2) = 2/(3t), which grows without bound as t approaches 0."),
 dict(q="For the curve x = t^2 - 4t, y = t^2 + 2t, the tangent line is parallel to the line y = 3x when t =",
   choices=[
     "1/2",
     "5/2",
     "3",
     "7/2"], ans=3,
   why="dy/dx = (2t + 2)/(2t - 4) = 3 gives 2t + 2 = 6t - 12, so t = 7/2, where dx/dt = 3 is not 0."),
]
