# CALC 9.2 Second Derivatives of Parametric Equations — 25 questions
# Answers verified with sympy; see verify_c9_2.py.
# Questions 1, 2, 3, 16, 18, 24 and 25 turn on a statement or a sign rather than
# a single computed expression; verify_c9_2.py pins each key by content AND
# confirms the underlying derivative or its sign with sympy.
TOPIC = ("9.2", "Second Derivatives of Parametric Equations", 9)
QUESTIONS = [
 dict(q="For a curve given parametrically by x = f(t) and y = g(t), d^2y/dx^2 is equal to",
   choices=[
     "d/dt(dy/dx) divided by dx/dt",
     "d/dt(dy/dx) divided by dy/dt",
     "(d^2y/dt^2) divided by (d^2x/dt^2)",
     "d/dt(dy/dx) multiplied by dx/dt"], ans=0,
   why="d^2y/dx^2 = d/dx(dy/dx), and converting the x-derivative to a t-derivative divides by dx/dt."),
 dict(q="A student computes d^2y/dx^2 for a parametric curve as (d^2y/dt^2)/(d^2x/dt^2). This is incorrect because",
   choices=[
     "d^2y/dx^2 is the t-derivative of dy/dx divided by dx/dt, not a ratio of second t-derivatives",
     "second derivatives of parametric curves do not exist",
     "the two second derivatives must be multiplied instead of divided",
     "dx/dt must be squared before dividing"], ans=0,
   why="Only the first derivative is a ratio of t-derivatives; the second requires differentiating dy/dx with respect to t and then dividing by dx/dt once."),
 dict(q="For x = f(t) and y = g(t) with f'(t) not 0, d^2y/dx^2 written in terms of f and g is",
   choices=[
     "(g''(t)f'(t) - g'(t)f''(t))/(f'(t))^3",
     "(g''(t)f'(t) - g'(t)f''(t))/(f'(t))^2",
     "g''(t)/f''(t)",
     "(g'(t)f''(t) - g''(t)f'(t))/(f'(t))^3"], ans=0,
   why="Differentiating g'/f' by the quotient rule gives (g''f' - g'f'')/(f')^2, and dividing once more by f' raises the power to 3."),
 dict(q="For the curve x = t^2, y = t^3 with t not equal to 0, d^2y/dx^2 =",
   choices=[
     "3/(4t)",
     "3/2",
     "3t",
     "3/(2t)"], ans=0,
   why="dy/dx = 3t/2, its t-derivative is 3/2, and dividing by dx/dt = 2t gives 3/(4t)."),
 dict(q="For the curve x = t^2, y = t^3, the value of d^2y/dx^2 at t = 1 is",
   choices=[
     "3/4",
     "3/2",
     "2",
     "3"], ans=0,
   why="d^2y/dx^2 = 3/(4t), which is 3/4 at t = 1."),
 dict(q="For the curve x = t^2 + 1, y = t^3 - t with t not equal to 0, d^2y/dx^2 =",
   choices=[
     "(3t^2 + 1)/(4t^3)",
     "(3t^2 + 1)/(2t^2)",
     "3t",
     "(3t^2 - 1)/(4t^3)"], ans=0,
   why="dy/dx = (3t^2 - 1)/(2t) has t-derivative (3t^2 + 1)/(2t^2), and dividing by dx/dt = 2t gives (3t^2 + 1)/(4t^3)."),
 dict(q="For the curve x = t^2 + 1, y = t^3 - t, the value of d^2y/dx^2 at t = 1 is",
   choices=[
     "1/2",
     "1",
     "2",
     "6"], ans=1,
   why="d^2y/dx^2 = (3t^2 + 1)/(4t^3) = 4/4 = 1 at t = 1."),
 dict(q="For the curve x = t^3, y = t^2 with t not equal to 0, d^2y/dx^2 =",
   choices=[
     "-2/(9t^4)",
     "-2/(3t^2)",
     "2/(9t^4)",
     "2/(3t^2)"], ans=0,
   why="dy/dx = 2/(3t) has t-derivative -2/(3t^2), and dividing by dx/dt = 3t^2 gives -2/(9t^4)."),
 dict(q="For the curve x = e^t, y = e^(2t), d^2y/dx^2 =",
   choices=[
     "2",
     "2e^t",
     "4e^(2t)",
     "e^t"], ans=0,
   why="dy/dx = 2e^t, whose t-derivative 2e^t divided by dx/dt = e^t is the constant 2, as expected since the curve is y = x^2 for x > 0."),
 dict(q="For the curve x = 2t, y = t^2, d^2y/dx^2 =",
   choices=[
     "1/2",
     "1",
     "t",
     "2"], ans=0,
   why="dy/dx = 2t/2 = t, whose t-derivative 1 divided by dx/dt = 2 gives 1/2, matching y = x^2/4."),
 dict(q="For the curve x = sin(t), y = cos(t) with cos(t) not 0, d^2y/dx^2 =",
   choices=[
     "-1/cos(t)^3",
     "-1/cos(t)^2",
     "1/cos(t)^3",
     "-sin(t)/cos(t)^3"], ans=0,
   why="dy/dx = -tan(t), whose t-derivative -1/cos(t)^2 divided by dx/dt = cos(t) gives -1/cos(t)^3."),
 dict(q="For the cycloid x = t - sin(t), y = 1 - cos(t) with cos(t) not 1, d^2y/dx^2 =",
   choices=[
     "-1/(1 - cos(t))^2",
     "1/(1 - cos(t))^2",
     "-1/(1 - cos(t))",
     "cos(t)/(1 - cos(t))^2"], ans=0,
   why="dy/dx = sin(t)/(1 - cos(t)) has t-derivative -1/(1 - cos(t)), and dividing by dx/dt = 1 - cos(t) gives -1/(1 - cos(t))^2."),
 dict(q="A curve satisfies dy/dx = t^2 + 1 and dx/dt = 4t for t > 0. Then d^2y/dx^2 =",
   choices=[
     "1/2",
     "2t",
     "(t^2 + 1)/(4t)",
     "8t"], ans=0,
   why="d/dt(dy/dx) = 2t, and dividing by dx/dt = 4t gives 1/2."),
 dict(q="A curve satisfies dy/dx = 3t and x = t^2 with t > 0. Then d^2y/dx^2 =",
   choices=[
     "3/(2t)",
     "3",
     "6t",
     "3/(2t^2)"], ans=0,
   why="d/dt(dy/dx) = 3, and dividing by dx/dt = 2t gives 3/(2t)."),
 dict(q="A curve satisfies dy/dx = t^3 and dx/dt = 3. The value of d^2y/dx^2 at t = 2 is",
   choices=[
     "4/3",
     "4",
     "8",
     "12"], ans=1,
   why="d/dt(dy/dx) = 3t^2, and dividing by dx/dt = 3 gives t^2, which is 4 at t = 2."),
 dict(q="At t = 1 the curve x = t^2 + 1, y = t^3 - t is",
   choices=[
     "concave up, because d^2y/dx^2 = 1 there",
     "concave down, because d^2y/dx^2 = -1 there",
     "concave up, because dy/dx = 1 there",
     "neither concave up nor concave down, because d^2y/dx^2 = 0 there"], ans=0,
   why="d^2y/dx^2 = (3t^2 + 1)/(4t^3) equals 1 at t = 1, and a positive second derivative means concave up."),
 dict(q="For the curve x = t^2, y = t^3, the value of d^2y/dx^2 at t = -1 is",
   choices=[
     "-3/4",
     "-3/2",
     "3/4",
     "3/2"], ans=0,
   why="d^2y/dx^2 = 3/(4t) = -3/4 at t = -1, so the curve is concave down there."),
 dict(q="The curve x = 2t, y = t^3 - 3t has a point of inflection at",
   choices=[
     "t = 0",
     "t = 1 and t = -1",
     "t = 1",
     "no value of t"], ans=0,
   why="dy/dx = (3t^2 - 3)/2 and d^2y/dx^2 = 3t/2, which changes sign only at t = 0."),
 dict(q="For x = t^2 + 1, y = t^4, a student finds dy/dx = 2t^2, differentiates it with respect to t to get 4t, and reports that as d^2y/dx^2. The correct value of d^2y/dx^2 is",
   choices=[
     "2",
     "4t",
     "2t",
     "4"], ans=0,
   why="The student omitted the final division by dx/dt = 2t, and 4t/(2t) = 2."),
 dict(q="For the curve x = 3t, y = ln(t) with t > 0, d^2y/dx^2 =",
   choices=[
     "-1/(9t^2)",
     "-1/(3t^2)",
     "1/(9t^2)",
     "-1/(9t)"], ans=0,
   why="dy/dx = 1/(3t) has t-derivative -1/(3t^2), and dividing by dx/dt = 3 gives -1/(9t^2)."),
 dict(q="For the curve x = t^2, y = ln(t) with t > 0, d^2y/dx^2 =",
   choices=[
     "-1/(2t^4)",
     "-1/t^3",
     "1/(2t^4)",
     "-1/(4t^4)"], ans=0,
   why="dy/dx = 1/(2t^2) has t-derivative -1/t^3, and dividing by dx/dt = 2t gives -1/(2t^4)."),
 dict(q="For the curve x = t^2 + t, y = t^3, the value of d^2y/dx^2 at t = 1 is",
   choices=[
     "4/9",
     "4/3",
     "2/3",
     "2"], ans=0,
   why="dy/dx = 3t^2/(2t + 1) has t-derivative (6t^2 + 6t)/(2t + 1)^2 = 4/3 at t = 1, and dividing by dx/dt = 3 gives 4/9."),
 dict(q="For a curve x = f(t), y = g(t), f'(2) = 2, f''(2) = 1, g'(2) = 6, and g''(2) = 4. The value of d^2y/dx^2 at t = 2 is",
   choices=[
     "1/4",
     "1/2",
     "2",
     "3"], ans=0,
   why="(g''f' - g'f'')/(f')^3 = (4(2) - 6(1))/8 = 2/8 = 1/4."),
 dict(q="The curve x = t^2, y = t^3 is concave up for",
   choices=[
     "t > 0",
     "t < 0",
     "all t not equal to 0",
     "no value of t"], ans=0,
   why="d^2y/dx^2 = 3/(4t) is positive exactly when t is positive."),
 dict(q="For the cycloid x = t - sin(t), y = 1 - cos(t), which of the following is true wherever d^2y/dx^2 is defined?",
   choices=[
     "The curve is concave down everywhere, since d^2y/dx^2 = -1/(1 - cos(t))^2 is always negative",
     "The curve is concave up everywhere, since d^2y/dx^2 is a square",
     "The curve changes concavity at t = pi",
     "The curve has an inflection point wherever sin(t) = 0"], ans=0,
   why="The second derivative is the negative of a positive square, so it is negative for every t with cos(t) not equal to 1."),
]
