# CALC 9.3 Finding Arc Lengths of Curves Given by Parametric Equations — 25 questions
# Answers verified with sympy; see verify_c9_3.py.
# Questions 1, 12, 13 and 20 state or compare a formula rather than compute a
# number; verify_c9_3.py pins each key by content and checks the mathematics
# behind it (including that the rejected formulas really do give other values).
TOPIC = ("9.3", "Finding Arc Lengths of Curves Given by Parametric Equations", 9)
QUESTIONS = [
 dict(q="The length of the curve x = f(t), y = g(t) for a <= t <= b, traced once, is given by",
   choices=[
     "int from a to b of sqrt((dx/dt)^2 + (dy/dt)^2) dt",
     "int from a to b of sqrt(x^2 + y^2) dt",
     "int from a to b of ((dx/dt)^2 + (dy/dt)^2) dt",
     "int from a to b of (dx/dt + dy/dt) dt"], ans=0,
   why="A short piece of the curve has length sqrt((dx)^2 + (dy)^2), and factoring dt out of the radical gives the stated integrand."),
 dict(q="Which of the following is the length of the curve x = t^2, y = t^3 for 0 <= t <= 2?",
   choices=[
     "int from 0 to 2 of sqrt(4t^2 + 9t^4) dt",
     "int from 0 to 2 of sqrt(2t + 3t^2) dt",
     "int from 0 to 2 of sqrt(t^4 + t^6) dt",
     "int from 0 to 2 of (2t + 3t^2) dt"], ans=0,
   why="dx/dt = 2t and dy/dt = 3t^2, and the integrand is the square root of the sum of their squares."),
 dict(q="To three decimal places, the length of the curve x = t^2, y = t^3 for 0 <= t <= 2 is",
   choices=[
     "6.667",
     "9.073",
     "10.198",
     "12.000"], ans=1,
   why="int from 0 to 2 of t sqrt(4 + 9t^2) dt = (40^(3/2) - 8)/27 = 9.073."),
 dict(q="The length of the curve x = 3t, y = 4t for 0 <= t <= 2 is",
   choices=[
     "5",
     "10",
     "14",
     "20"], ans=1,
   why="The integrand is sqrt(9 + 16) = 5, so the length is 5(2) = 10, the distance from (0, 0) to (6, 8)."),
 dict(q="The length of the curve x = cos(t), y = sin(t) for 0 <= t <= pi/2 is",
   choices=[
     "pi/2",
     "pi",
     "1",
     "2"], ans=0,
   why="The integrand is sqrt(sin^2(t) + cos^2(t)) = 1, so the length is the quarter-circle arc pi/2."),
 dict(q="The length of the curve x = 3cos(t), y = 3sin(t) for 0 <= t <= 2pi is",
   choices=[
     "6pi",
     "3pi",
     "9pi",
     "2pi"], ans=0,
   why="The integrand is sqrt(9sin^2(t) + 9cos^2(t)) = 3, and 3(2pi) = 6pi is the circumference of a circle of radius 3."),
 dict(q="Which of the following gives the length of the curve x = t, y = t^2 for 0 <= t <= 1?",
   choices=[
     "int from 0 to 1 of sqrt(1 + 4t^2) dt",
     "int from 0 to 1 of sqrt(1 + 2t) dt",
     "int from 0 to 1 of sqrt(t^2 + t^4) dt",
     "int from 0 to 1 of (1 + 4t^2) dt"], ans=0,
   why="dx/dt = 1 and dy/dt = 2t, so the integrand is sqrt(1 + 4t^2)."),
 dict(q="To three decimal places, the length of the curve x = t, y = t^2 for 0 <= t <= 1 is",
   choices=[
     "1.155",
     "1.333",
     "1.479",
     "2.958"], ans=2,
   why="int from 0 to 1 of sqrt(1 + 4t^2) dt = sqrt(5)/2 + ln(2 + sqrt(5))/4 = 1.479."),
 dict(q="The length of the curve x = t^2/2, y = (2t + 1)^(3/2)/3 for 0 <= t <= 4 is",
   choices=[
     "8",
     "12",
     "16",
     "20"], ans=1,
   why="dx/dt = t and dy/dt = sqrt(2t + 1), so the integrand is sqrt(t^2 + 2t + 1) = t + 1, whose integral from 0 to 4 is 12."),
 dict(q="Which of the following gives the length of one arch of the cycloid x = t - sin(t), y = 1 - cos(t), 0 <= t <= 2pi?",
   choices=[
     "int from 0 to 2pi of sqrt(2 - 2cos(t)) dt",
     "int from 0 to 2pi of sqrt(2 + 2cos(t)) dt",
     "int from 0 to 2pi of sqrt(1 - 2cos(t)) dt",
     "int from 0 to 2pi of (1 - cos(t) + sin(t)) dt"], ans=0,
   why="(1 - cos t)^2 + sin^2(t) = 1 - 2cos(t) + cos^2(t) + sin^2(t) = 2 - 2cos(t)."),
 dict(q="The length of one arch of the cycloid x = t - sin(t), y = 1 - cos(t), 0 <= t <= 2pi, is",
   choices=[
     "8",
     "2pi",
     "4",
     "4pi"], ans=0,
   why="sqrt(2 - 2cos(t)) = 2|sin(t/2)|, and int from 0 to 2pi of 2sin(t/2) dt = 8."),
 dict(q="A student writes the length of a parametric curve as int from a to b of sqrt(dx/dt + dy/dt) dt. The error is that",
   choices=[
     "the two derivatives must be squared before they are added and the root taken",
     "the derivatives must be added after the square root, not before",
     "the integrand should be dx/dt + dy/dt with no square root",
     "the limits must be x-values rather than t-values"], ans=0,
   why="Arc length comes from the Pythagorean relation (ds)^2 = (dx)^2 + (dy)^2, so each derivative is squared inside the radical."),
 dict(q="For a particle whose position at time t is (x(t), y(t)), the length of the path travelled from t = a to t = b, with no retracing, equals",
   choices=[
     "the integral from a to b of the particle's speed",
     "the integral from a to b of the particle's velocity vector",
     "the magnitude of the displacement from t = a to t = b",
     "the integral from a to b of the particle's acceleration"], ans=0,
   why="Speed is sqrt((dx/dt)^2 + (dy/dt)^2), which is exactly the arc-length integrand."),
 dict(q="Which of the following gives the length of the curve x = e^t cos(t), y = e^t sin(t) for 0 <= t <= 1?",
   choices=[
     "int from 0 to 1 of sqrt(2) e^t dt",
     "int from 0 to 1 of e^t dt",
     "int from 0 to 1 of sqrt(2) e^(2t) dt",
     "int from 0 to 1 of 2 e^t dt"], ans=0,
   why="dx/dt = e^t(cos t - sin t) and dy/dt = e^t(sin t + cos t), whose squares add to 2e^(2t)."),
 dict(q="To three decimal places, the length of the curve x = e^t cos(t), y = e^t sin(t) for 0 <= t <= 1 is",
   choices=[
     "1.718",
     "2.430",
     "2.718",
     "3.844"], ans=1,
   why="The length is sqrt(2)(e - 1) = 2.430."),
 dict(q="Which of the following gives the length of the curve x = t^3, y = t^2 for 0 <= t <= 1?",
   choices=[
     "int from 0 to 1 of sqrt(9t^4 + 4t^2) dt",
     "int from 0 to 1 of sqrt(3t^2 + 2t) dt",
     "int from 0 to 1 of sqrt(t^6 + t^4) dt",
     "int from 0 to 1 of sqrt(9t^4 - 4t^2) dt"], ans=0,
   why="dx/dt = 3t^2 and dy/dt = 2t, so the integrand is sqrt(9t^4 + 4t^2)."),
 dict(q="To three decimal places, the length of the curve x = t^3, y = t^2 for 0 <= t <= 1 is",
   choices=[
     "1.106",
     "1.333",
     "1.440",
     "2.879"], ans=2,
   why="int from 0 to 1 of t sqrt(9t^2 + 4) dt = (13^(3/2) - 8)/27 = 1.440."),
 dict(q="The length of the curve x = cos(t), y = sin(t) for 0 <= t <= 4pi is",
   choices=[
     "4pi",
     "2pi",
     "0",
     "8pi"], ans=0,
   why="The integrand is 1 and the interval has length 4pi; the arc-length integral measures the whole path even though the unit circle is traced twice."),
 dict(q="For what value of b > 0 does the curve x = 3t, y = 4t, 0 <= t <= b, have length 20?",
   choices=[
     "20/7",
     "4",
     "5",
     "10"], ans=1,
   why="The speed is a constant 5, so the length is 5b, and 5b = 20 gives b = 4."),
 dict(q="Curve I is x = 2t, y = 4t^2 for 0 <= t <= 1, and curve II is x = t, y = t^2 for 0 <= t <= 2. Which statement is true?",
   choices=[
     "They have the same length, because they trace the same arc of y = x^2",
     "Curve I is half as long as curve II",
     "Curve I is twice as long as curve II",
     "Their lengths cannot be compared without evaluating both integrals"], ans=0,
   why="Both parametrizations sweep x from 0 to 2 along y = x^2 exactly once, and arc length does not depend on the parametrization."),
 dict(q="The length of the curve x = sin(2t), y = cos(2t) for 0 <= t <= pi/2 is",
   choices=[
     "pi",
     "pi/2",
     "2pi",
     "4"], ans=0,
   why="dx/dt = 2cos(2t) and dy/dt = -2sin(2t) give a constant speed of 2, and 2(pi/2) = pi."),
 dict(q="To three decimal places, the length of the curve x = t^3/3, y = t^2 for 1 <= t <= 2 is",
   choices=[
     "2.333",
     "3.000",
     "3.816",
     "4.667"], ans=2,
   why="The integrand is sqrt(t^4 + 4t^2) = t sqrt(t^2 + 4) for t > 0, and its integral from 1 to 2 is (8^(3/2) - 5^(3/2))/3 = 3.816."),
 dict(q="The length of the curve x = cos(t) + t sin(t), y = sin(t) - t cos(t) for 0 <= t <= pi is",
   choices=[
     "pi^2/2",
     "pi^2",
     "pi",
     "pi^2/4"], ans=0,
   why="dx/dt = t cos(t) and dy/dt = t sin(t), so the integrand is t and the length is pi^2/2."),
 dict(q="The length of the curve x = 5cos(t), y = 5sin(t) for 0 <= t <= pi/3 is",
   choices=[
     "5pi/3",
     "5pi/6",
     "pi/3",
     "10pi/3"], ans=0,
   why="The speed is a constant 5, so the length is 5(pi/3), matching the arc-length formula r*theta."),
 dict(q="A curve is given by x = 4t + 1, y = 3t - 2 for 0 <= t <= 5. Its length is",
   choices=[
     "5",
     "7",
     "25",
     "35"], ans=2,
   why="The speed is sqrt(16 + 9) = 5 and the interval has length 5, so the length is 25 — the straight-line distance between the endpoints."),
]
