# CALC 9.4 Defining and Differentiating Vector-Valued Functions — 25 questions
# Answers verified with sympy; see verify_c9_4.py.
# Vectors are written in angle brackets, as <x-component, y-component>.
# Questions 1, 7, 12 and 24 state a definition rather than compute a value;
# verify_c9_4.py pins each key by content and checks the fact behind it.
TOPIC = ("9.4", "Defining and Differentiating Vector-Valued Functions", 9)
QUESTIONS = [
 dict(q="If r(t) = <f(t), g(t)> with f and g differentiable, then r'(t) =",
   choices=[
     "<f'(t), g'(t)>",
     "<f'(t)g(t), f(t)g'(t)>",
     "f'(t) + g'(t)",
     "sqrt(f'(t)^2 + g'(t)^2)"], ans=0,
   why="A vector-valued function is differentiated component by component."),
 dict(q="If r(t) = <t^2, t^3>, then r'(t) =",
   choices=[
     "<2t, 3t^2>",
     "<2t, 3t>",
     "<t^3/3, t^4/4>",
     "<2, 6t>"], ans=0,
   why="Differentiating each component gives <2t, 3t^2>."),
 dict(q="If r(t) = <t^2, t^3>, then r'(1) =",
   choices=[
     "<2, 3>",
     "<1, 1>",
     "<2, 6>",
     "<3, 2>"], ans=0,
   why="r'(t) = <2t, 3t^2>, and substituting t = 1 gives <2, 3>."),
 dict(q="If r(t) = <sin(t), cos(t)>, then r'(t) =",
   choices=[
     "<cos(t), -sin(t)>",
     "<cos(t), sin(t)>",
     "<-cos(t), sin(t)>",
     "<-sin(t), -cos(t)>"], ans=0,
   why="The derivative of sin is cos and the derivative of cos is -sin."),
 dict(q="If r(t) = <e^(2t), ln(t)> for t > 0, then r'(t) =",
   choices=[
     "<2e^(2t), 1/t>",
     "<e^(2t), 1/t>",
     "<2e^(2t), t>",
     "<2e^(2t), ln(t)/t>"], ans=0,
   why="The chain rule gives 2e^(2t) and the derivative of ln(t) is 1/t."),
 dict(q="If r(t) = <t^3, t^2>, then r''(t) =",
   choices=[
     "<6t, 2>",
     "<3t^2, 2t>",
     "<6, 2>",
     "<6t, 2t>"], ans=0,
   why="r'(t) = <3t^2, 2t>, and differentiating again gives <6t, 2>."),
 dict(q="For a curve traced by r(t), the vector r'(t) (when it is not the zero vector)",
   choices=[
     "is tangent to the curve at r(t) and points in the direction of increasing t",
     "is perpendicular to the curve at r(t)",
     "always has length 1",
     "points from the origin to the point r(t)"], ans=0,
   why="The difference quotient (r(t + h) - r(t))/h approaches a vector along the curve, so the limit is tangent and points forward in t."),
 dict(q="If r(t) = <3t^2 - t, t^4>, then r'(1) =",
   choices=[
     "<5, 4>",
     "<6, 4>",
     "<5, 1>",
     "<2, 1>"], ans=0,
   why="r'(t) = <6t - 1, 4t^3>, which is <5, 4> at t = 1."),
 dict(q="A curve is traced by r(t) = <t^2 + 1, t^3>. The slope dy/dx of the curve at t = 2 is",
   choices=[
     "2/3",
     "3/2",
     "3",
     "12"], ans=2,
   why="dy/dx = (dy/dt)/(dx/dt) = 3t^2/(2t) = 3t/2, which is 3 at t = 2."),
 dict(q="If r(t) = <cos(2t), sin(3t)>, then r'(t) =",
   choices=[
     "<-2sin(2t), 3cos(3t)>",
     "<-sin(2t), cos(3t)>",
     "<2sin(2t), -3cos(3t)>",
     "<-2sin(t), 3cos(t)>"], ans=0,
   why="Each component needs the chain rule, giving factors of 2 and 3."),
 dict(q="If r(t) = <t^2, 2t>, the length of r'(1) is",
   choices=[
     "2sqrt(2)",
     "4",
     "sqrt(5)",
     "2"], ans=0,
   why="r'(1) = <2, 2>, whose length is sqrt(4 + 4) = 2sqrt(2)."),
 dict(q="For a vector-valued function r(t), which of the following is a scalar rather than a vector?",
   choices=[
     "|r'(t)|",
     "r'(t)",
     "r''(t)",
     "r(t) - r(0)"], ans=0,
   why="Taking the magnitude of a vector produces a number; the other three expressions are vectors."),
 dict(q="If r(t) = <t, t^2>, the unit vector in the direction of r'(1) is",
   choices=[
     "<1/sqrt(5), 2/sqrt(5)>",
     "<1, 2>",
     "<1/sqrt(3), 2/sqrt(3)>",
     "<2/sqrt(5), 1/sqrt(5)>"], ans=0,
   why="r'(1) = <1, 2> has length sqrt(5), so dividing each component by sqrt(5) gives the unit vector."),
 dict(q="If r(t) = <tan(t), sec(t)>, then r'(t) =",
   choices=[
     "<sec(t)^2, sec(t)tan(t)>",
     "<sec(t)^2, sec(t)^2>",
     "<sec(t)tan(t), sec(t)^2>",
     "<sec(t)^2, -sec(t)tan(t)>"], ans=0,
   why="The derivative of tan is sec^2 and the derivative of sec is sec tan."),
 dict(q="For which value of t is r'(t) the zero vector, where r(t) = <t^3, t^2>?",
   choices=[
     "t = 0",
     "t = 1",
     "t = 0 and t = 1",
     "no value of t"], ans=0,
   why="r'(t) = <3t^2, 2t> has both components zero only at t = 0."),
 dict(q="If r(t) = <sin(t^2), cos(t^2)>, then r'(t) =",
   choices=[
     "<2t cos(t^2), -2t sin(t^2)>",
     "<cos(t^2), -sin(t^2)>",
     "<2t cos(t^2), 2t sin(t^2)>",
     "<cos(2t), -sin(2t)>"], ans=0,
   why="Each component needs the chain rule with inner derivative 2t."),
 dict(q="If r(t) = <ln(t^2 + 1), arctan(t)>, then r'(t) =",
   choices=[
     "<2t/(t^2 + 1), 1/(t^2 + 1)>",
     "<1/(t^2 + 1), 1/(t^2 + 1)>",
     "<2t/(t^2 + 1), 1/(1 + t)>",
     "<2t, 1/(t^2 + 1)>"], ans=0,
   why="The chain rule gives 2t/(t^2 + 1), and the derivative of arctan(t) is 1/(t^2 + 1)."),
 dict(q="A curve is traced by r(t) = <t^2, t^3 - 3t>. The tangent vector is horizontal at",
   choices=[
     "t = 1 and t = -1",
     "t = 0",
     "t = 0 and t = 1",
     "t = 3"], ans=0,
   why="The y-component of r'(t) is 3t^2 - 3, which is 0 at t = 1 and t = -1, where the x-component 2t is not 0."),
 dict(q="A curve is traced by r(t) = <t^2, t^3 - 3t>. The tangent vector is vertical at",
   choices=[
     "t = 0",
     "t = 1 and t = -1",
     "t = 3",
     "no value of t"], ans=0,
   why="The x-component of r'(t) is 2t, which is 0 at t = 0, where the y-component is -3 and not 0."),
 dict(q="For which positive value of t is r'(t) parallel to the vector <1, 1>, where r(t) = <t^2, t^3>?",
   choices=[
     "1/3",
     "2/3",
     "1",
     "3/2"], ans=1,
   why="Parallel to <1, 1> means 3t^2 = 2t, so t = 2/3 for t > 0."),
 dict(q="If r(t) = <t^4, e^t>, then r''(t) =",
   choices=[
     "<12t^2, e^t>",
     "<4t^3, e^t>",
     "<12t^2, te^(t-1)>",
     "<24t, e^t>"], ans=0,
   why="Differentiating <4t^3, e^t> gives <12t^2, e^t>."),
 dict(q="If r(t) = <te^t, t^2 e^t>, then r'(t) =",
   choices=[
     "<(t + 1)e^t, (t^2 + 2t)e^t>",
     "<e^t, 2te^t>",
     "<(t + 1)e^t, (t^2 + t)e^t>",
     "<te^t, t^2 e^t>"], ans=0,
   why="Each component needs the product rule: (te^t)' = (t + 1)e^t and (t^2 e^t)' = (t^2 + 2t)e^t."),
 dict(q="A curve is traced by r(t) = <t^2, t^3>. The tangent line to the curve has slope 6 when t =",
   choices=[
     "2",
     "4",
     "6",
     "12"], ans=1,
   why="dy/dx = 3t^2/(2t) = 3t/2, and 3t/2 = 6 gives t = 4."),
 dict(q="The derivative of a vector-valued function r at t is defined as",
   choices=[
     "the limit as h approaches 0 of (r(t + h) - r(t))/h",
     "the limit as h approaches 0 of |r(t + h) - r(t)|/h",
     "the limit as t approaches 0 of r(t)/t",
     "the vector from r(0) to r(t) divided by t"], ans=0,
   why="The definition is the same difference quotient as for scalar functions, applied to vectors; taking the magnitude first would give a number, not the derivative vector."),
 dict(q="If r(t) = <sqrt(t), 1/t> for t > 0, then r'(4) =",
   choices=[
     "<1/4, -1/16>",
     "<1/4, 1/16>",
     "<2, -1/4>",
     "<1/2, -1/16>"], ans=0,
   why="r'(t) = <1/(2sqrt(t)), -1/t^2>, which at t = 4 is <1/4, -1/16>."),
]
