# CALC 9.5 Integrating Vector-Valued Functions — 25 questions
# Answers verified with sympy; see verify_c9_5.py.
# Vectors are written in angle brackets, as <x-component, y-component>, and C
# denotes a vector constant of integration.
# Questions 1, 6 and 14 state a definition or distinguish displacement from
# distance rather than compute a value; verify_c9_5.py pins each key by content
# and checks the fact behind it with a worked example.
TOPIC = ("9.5", "Integrating Vector-Valued Functions", 9)
QUESTIONS = [
 dict(q="If r(t) = <f(t), g(t)>, then the indefinite integral of r(t) with respect to t is",
   choices=[
     "<int f(t) dt, int g(t) dt>",
     "int sqrt(f(t)^2 + g(t)^2) dt",
     "<int f(t) dt> + <int g(t) dt>, added as numbers",
     "(int f(t) dt)(int g(t) dt)"], ans=0,
   why="A vector-valued function is antidifferentiated component by component, just as it is differentiated."),
 dict(q="int <2t, 3t^2> dt =",
   choices=[
     "<t^2, t^3> + C",
     "<t^2, t^3/3> + C",
     "<2, 6t> + C",
     "<t^2/2, t^3/3> + C"], ans=0,
   why="Antidifferentiating each component gives <t^2, t^3>, plus a vector constant."),
 dict(q="int from 0 to 1 of <2t, 3t^2> dt =",
   choices=[
     "<1, 1>",
     "<2, 3>",
     "<1/2, 1/3>",
     "<2, 1>"], ans=0,
   why="Each component is evaluated separately: t^2 and t^3 both go from 0 to 1."),
 dict(q="int <cos(t), sin(t)> dt =",
   choices=[
     "<sin(t), -cos(t)> + C",
     "<-sin(t), cos(t)> + C",
     "<sin(t), cos(t)> + C",
     "<-cos(t), -sin(t)> + C"], ans=0,
   why="The antiderivative of cos is sin and the antiderivative of sin is -cos."),
 dict(q="int from 0 to pi/2 of <cos(t), sin(t)> dt =",
   choices=[
     "<1, 1>",
     "<0, 1>",
     "<1, -1>",
     "<0, 0>"], ans=0,
   why="sin(t) goes from 0 to 1 and -cos(t) goes from -1 to 0, so each component is 1."),
 dict(q="When an antiderivative of a vector-valued function is written, the constant of integration",
   choices=[
     "is a vector, since each component contributes its own arbitrary constant",
     "is a single number added to both components",
     "may be omitted, since vectors have no constant term",
     "must be the zero vector"], ans=0,
   why="Each component is antidifferentiated separately and each carries its own constant, so the constants together form a vector."),
 dict(q="For t > 0, int <e^t, 1/t> dt =",
   choices=[
     "<e^t, ln(t)> + C",
     "<e^t, -1/t^2> + C",
     "<e^t/t, ln(t)> + C",
     "<te^t, ln(t)> + C"], ans=0,
   why="The antiderivative of e^t is e^t and, for t > 0, the antiderivative of 1/t is ln(t)."),
 dict(q="int <sec(t)^2, 2t> dt =",
   choices=[
     "<tan(t), t^2> + C",
     "<sec(t)tan(t), t^2> + C",
     "<tan(t), 2> + C",
     "<sec(t)^3/3, t^2> + C"], ans=0,
   why="The antiderivative of sec^2 is tan and the antiderivative of 2t is t^2."),
 dict(q="int from 0 to 2 of <3t^2, 4t^3> dt =",
   choices=[
     "<8, 16>",
     "<12, 32>",
     "<8, 8>",
     "<4, 8>"], ans=0,
   why="t^3 goes from 0 to 8 and t^4 goes from 0 to 16."),
 dict(q="int from 1 to 2 of <1/t, 1/t^2> dt =",
   choices=[
     "<ln(2), 1/2>",
     "<ln(2), -1/2>",
     "<1/2, ln(2)>",
     "<ln(2), 3/2>"], ans=0,
   why="ln(t) goes from 0 to ln(2), and -1/t evaluated from 1 to 2 is -1/2 + 1 = 1/2."),
 dict(q="A particle has velocity v(t) = <3t^2, 2t> and position r(1) = <2, 5>. Then r(t) =",
   choices=[
     "<t^3 + 1, t^2 + 4>",
     "<t^3, t^2>",
     "<t^3 + 2, t^2 + 5>",
     "<6t, 2>"], ans=0,
   why="Antidifferentiating gives <t^3 + C1, t^2 + C2>, and r(1) = <2, 5> forces C1 = 1 and C2 = 4."),
 dict(q="A particle has velocity v(t) = <2, 6t> and position r(0) = <1, -3>. Its position at t = 2 is",
   choices=[
     "<5, 9>",
     "<4, 12>",
     "<5, 12>",
     "<2, 9>"], ans=0,
   why="r(t) = <1 + 2t, 3t^2 - 3>, so r(2) = <5, 9>."),
 dict(q="A particle has velocity v(t) = <t, t^2>. Its displacement from t = 0 to t = 3 is",
   choices=[
     "<9/2, 9>",
     "<3, 9>",
     "<9/2, 27>",
     "<9, 27>"], ans=0,
   why="The displacement is the integral of velocity: t^2/2 gives 9/2 and t^3/3 gives 9."),
 dict(q="For a particle in the plane with velocity v(t), the integral from a to b of v(t) dt gives",
   choices=[
     "the displacement vector from r(a) to r(b)",
     "the total distance travelled between t = a and t = b",
     "the speed at time b",
     "the average velocity on [a, b]"], ans=0,
   why="Integrating velocity componentwise gives the net change in position; total distance requires integrating the speed |v(t)|, which is never negative."),
 dict(q="A particle has acceleration a(t) = <0, -32> and velocity v(0) = <10, 20>. Then v(t) =",
   choices=[
     "<10, 20 - 32t>",
     "<10t, 20 - 32t>",
     "<0, 20 - 32t>",
     "<10, -32t>"], ans=0,
   why="Antidifferentiating each component and applying v(0) = <10, 20> gives a constant x-component of 10 and 20 - 32t."),
 dict(q="A particle has acceleration a(t) = <0, -32>, velocity v(0) = <10, 20>, and position r(0) = <0, 5>. Then r(t) =",
   choices=[
     "<10t, 5 + 20t - 16t^2>",
     "<10t, 20t - 32t^2>",
     "<10t + 5, 20t - 16t^2>",
     "<10, 5 + 20t - 16t^2>"], ans=0,
   why="Integrating v(t) = <10, 20 - 32t> gives <10t, 20t - 16t^2> plus the initial position <0, 5>."),
 dict(q="A ball is thrown so that its acceleration is a(t) = <0, -32>, with v(0) = <30, 40> and r(0) = <0, 6>. Its position at t = 2 is",
   choices=[
     "<60, 22>",
     "<60, 86>",
     "<60, 16>",
     "<30, 22>"], ans=0,
   why="r(t) = <30t, 6 + 40t - 16t^2>, so r(2) = <60, 6 + 80 - 64> = <60, 22>."),
 dict(q="A particle has velocity v(t) = <cos(t), sin(t)> and position r(0) = <0, 1>. Its position at t = pi/2 is",
   choices=[
     "<1, 2>",
     "<1, 1>",
     "<0, 2>",
     "<1, 0>"], ans=0,
   why="r(t) = <sin(t), 2 - cos(t)>, so r(pi/2) = <1, 2>."),
 dict(q="A particle has acceleration a(t) = <6t, 12t^2> and velocity v(0) = <1, 2>. Then v(t) =",
   choices=[
     "<3t^2 + 1, 4t^3 + 2>",
     "<3t^2, 4t^3>",
     "<6t + 1, 12t^2 + 2>",
     "<3t^2 + 1, 4t^3>"], ans=0,
   why="Antidifferentiating gives <3t^2, 4t^3> plus the initial velocity <1, 2>."),
 dict(q="int from 0 to pi of <sin(t), t> dt =",
   choices=[
     "<2, pi^2/2>",
     "<0, pi^2/2>",
     "<2, pi^2>",
     "<-2, pi^2/2>"], ans=0,
   why="-cos(t) from 0 to pi is 2, and t^2/2 from 0 to pi is pi^2/2."),
 dict(q="A particle's velocity has y-component 4t - 8. Its displacement in the y-direction from t = 0 to t = 3 is",
   choices=[
     "-24",
     "-6",
     "6",
     "18"], ans=1,
   why="int from 0 to 3 of (4t - 8) dt = 2t^2 - 8t evaluated at 3, which is 18 - 24 = -6."),
 dict(q="A particle has velocity v(t) = <4t, 3t^2> and position r(2) = <10, 3>. Then r(0) =",
   choices=[
     "<2, -5>",
     "<10, 3>",
     "<-2, 5>",
     "<0, 0>"], ans=0,
   why="r(t) = <2t^2 + C1, t^3 + C2> with 8 + C1 = 10 and 8 + C2 = 3, so r(t) = <2t^2 + 2, t^3 - 5> and r(0) = <2, -5>."),
 dict(q="int <1/(1 + t^2), e^(2t)> dt =",
   choices=[
     "<arctan(t), e^(2t)/2> + C",
     "<arctan(t), 2e^(2t)> + C",
     "<ln(1 + t^2), e^(2t)/2> + C",
     "<arctan(t), e^(2t)> + C"], ans=0,
   why="The antiderivative of 1/(1 + t^2) is arctan(t), and substitution gives e^(2t)/2."),
 dict(q="int from -1 to 1 of <3t^2, t> dt =",
   choices=[
     "<2, 0>",
     "<0, 0>",
     "<2, 1>",
     "<0, 1/2>"], ans=0,
   why="t^3 from -1 to 1 is 2, while t^2/2 gives 1/2 - 1/2 = 0 because the second integrand is odd."),
 dict(q="A particle has velocity v(t) = <2t, 4>. Its displacement from t = 1 to t = 3 is",
   choices=[
     "<8, 8>",
     "<9, 12>",
     "<8, 12>",
     "<6, 8>"], ans=0,
   why="t^2 goes from 1 to 9, a change of 8, and 4t goes from 4 to 12, a change of 8."),
]
