# CALC 9.6 Solving Motion Problems Using Parametric and Vector-Valued Functions
# — 25 questions.  Answers verified with sympy; see verify_c9_6.py.
# Vectors are written in angle brackets, as <x-component, y-component>.
# Questions 1, 2, 19 and 25 state a definition or a general fact rather than
# compute a value; verify_c9_6.py pins each key by content and confirms the
# fact with a worked example (including a constant-speed motion whose
# acceleration is not zero).
TOPIC = ("9.6", "Solving Motion Problems Using Parametric and Vector-Valued Functions", 9)
QUESTIONS = [
 dict(q="A particle in the plane has position (x(t), y(t)). Its speed at time t is",
   choices=[
     "sqrt((dx/dt)^2 + (dy/dt)^2)",
     "<dx/dt, dy/dt>",
     "dx/dt + dy/dt",
     "(dy/dt)/(dx/dt)"], ans=0,
   why="Speed is the magnitude of the velocity vector, so it is a nonnegative number, not a vector."),
 dict(q="The total distance travelled by a particle between t = a and t = b is",
   choices=[
     "int from a to b of sqrt((dx/dt)^2 + (dy/dt)^2) dt",
     "the magnitude of the vector r(b) - r(a)",
     "int from a to b of (dx/dt + dy/dt) dt",
     "sqrt((x(b) - x(a))^2 + (y(b) - y(a))^2)"], ans=0,
   why="Distance travelled is the integral of speed; the other expressions give displacement, which ignores any doubling back."),
 dict(q="A particle has velocity v(t) = <3, 4> for all t. Its speed is",
   choices=[
     "5",
     "7",
     "12",
     "25"], ans=0,
   why="The speed is |<3, 4>| = sqrt(9 + 16) = 5."),
 dict(q="A particle's position is given by r(t) = <t^2, t^3>. Its speed at t = 1 is",
   choices=[
     "sqrt(13)",
     "5",
     "sqrt(5)",
     "13"], ans=0,
   why="v(1) = <2, 3>, so the speed is sqrt(4 + 9) = sqrt(13)."),
 dict(q="A particle's position is given by r(t) = <t^2, 2t>. Its speed at t = 2 is",
   choices=[
     "2sqrt(5)",
     "sqrt(6)",
     "6",
     "4sqrt(2)"], ans=0,
   why="v(2) = <4, 2>, so the speed is sqrt(16 + 4) = 2sqrt(5)."),
 dict(q="A particle has velocity v(t) = <3, 4>. The total distance it travels from t = 0 to t = 2 is",
   choices=[
     "5",
     "10",
     "14",
     "25"], ans=1,
   why="The speed is a constant 5, so the distance is 5(2) = 10."),
 dict(q="A particle's position is r(t) = <t^2, 2t^3>. Which of the following gives the total distance it travels from t = 0 to t = 1?",
   choices=[
     "int from 0 to 1 of sqrt(4t^2 + 36t^4) dt",
     "int from 0 to 1 of sqrt(2t + 6t^2) dt",
     "int from 0 to 1 of (2t + 6t^2) dt",
     "int from 0 to 1 of sqrt(t^4 + 4t^6) dt"], ans=0,
   why="v(t) = <2t, 6t^2>, so the speed is sqrt(4t^2 + 36t^4) and distance is its integral."),
 dict(q="A particle's position is r(t) = <t^3, t^2>. Its acceleration vector is",
   choices=[
     "<6t, 2>",
     "<3t^2, 2t>",
     "sqrt(36t^2 + 4)",
     "<6t^2, 2t>"], ans=0,
   why="Acceleration is the second derivative of position, taken component by component."),
 dict(q="A particle's position is r(t) = <t^2 - 4t, t^3>. The particle is moving to the left when",
   choices=[
     "t < 2",
     "t > 2",
     "t < 0",
     "never"], ans=0,
   why="Moving left means dx/dt = 2t - 4 < 0, which holds for t < 2."),
 dict(q="A particle has velocity v(t) = <t^2 - 1, t - 1>. The particle is at rest when",
   choices=[
     "t = 1 only",
     "t = 1 and t = -1",
     "t = -1 only",
     "never"], ans=0,
   why="Both components must vanish; t^2 - 1 = 0 at t = 1 and t = -1, but t - 1 = 0 only at t = 1."),
 dict(q="A particle has velocity v(t) = <cos(t), sin(t)>. The total distance it travels from t = 0 to t = pi is",
   choices=[
     "pi",
     "2",
     "0",
     "2pi"], ans=0,
   why="The speed is sqrt(cos^2 + sin^2) = 1, so the distance is the length of the time interval."),
 dict(q="A particle has velocity v(t) = <t - 3, 0> for 0 <= t <= 5. The total distance it travels is",
   choices=[
     "-5/2",
     "5/2",
     "13/2",
     "25/2"], ans=2,
   why="The distance is int from 0 to 5 of |t - 3| dt = 9/2 + 2 = 13/2, larger than the displacement of -5/2 because the particle reverses direction at t = 3."),
 dict(q="A particle has velocity v(t) = <0, 2t - 6> for 0 <= t <= 4. Its displacement is",
   choices=[
     "<0, -8>",
     "<0, 10>",
     "<0, 8>",
     "<0, -10>"], ans=0,
   why="int from 0 to 4 of (2t - 6) dt = 16 - 24 = -8; the total distance travelled is 10, which is different."),
 dict(q="A particle's position is r(t) = <2cos(t), 3sin(t)>. Its speed at t = pi/2 is",
   choices=[
     "2",
     "3",
     "sqrt(13)",
     "0"], ans=0,
   why="v(t) = <-2sin(t), 3cos(t)>, so v(pi/2) = <-2, 0> and the speed is 2."),
 dict(q="A particle has velocity v(t) = <2t, sqrt(8t + 4)> for t >= 0. The total distance it travels from t = 0 to t = 3 is",
   choices=[
     "9",
     "12",
     "15",
     "21"], ans=2,
   why="The speed is sqrt(4t^2 + 8t + 4) = 2(t + 1), whose integral from 0 to 3 is 15."),
 dict(q="A particle has velocity v(t) = <2t, t^2 - 4> for t >= 0. Its minimum speed is",
   choices=[
     "2sqrt(3)",
     "4",
     "2sqrt(2)",
     "0"], ans=0,
   why="The speed squared is t^4 - 4t^2 + 16, which is smallest at t^2 = 2, giving speed sqrt(12) = 2sqrt(3)."),
 dict(q="A particle's position is r(t) = <t^3, t^2>. The magnitude of its acceleration at t = 1 is",
   choices=[
     "2sqrt(10)",
     "8",
     "sqrt(13)",
     "6"], ans=0,
   why="a(t) = <6t, 2>, so a(1) = <6, 2> and its magnitude is sqrt(36 + 4) = 2sqrt(10)."),
 dict(q="A particle has velocity v(t) = <3e^t, 4e^t>. The total distance it travels from t = 0 to t = ln(2) is",
   choices=[
     "5",
     "10",
     "5ln(2)",
     "7"], ans=0,
   why="The speed is 5e^t, and int from 0 to ln(2) of 5e^t dt = 5(2 - 1) = 5."),
 dict(q="A particle has velocity v(t) = <-6, 8> at time t = 2. Which statement is correct?",
   choices=[
     "Its speed at t = 2 is 10, a positive number even though a component is negative",
     "Its speed at t = 2 is -10, because the x-component is negative",
     "Its speed at t = 2 is 2, the sum of the components",
     "Its speed at t = 2 is the vector <-6, 8>"], ans=0,
   why="Speed is the magnitude sqrt(36 + 64) = 10, and a magnitude is never negative."),
 dict(q="To three decimal places, the total distance travelled by a particle with position r(t) = <t^2, 2t^3> from t = 0 to t = 1 is",
   choices=[
     "1.000",
     "2.268",
     "2.828",
     "3.162"], ans=1,
   why="int from 0 to 1 of 2t sqrt(1 + 9t^2) dt = (2/27)(10^(3/2) - 1) = 2.268."),
 dict(q="A particle has velocity v(t) = <4t, 3> and position r(0) = <1, 2>. Its position at t = 2 is",
   choices=[
     "<9, 8>",
     "<8, 6>",
     "<9, 6>",
     "<17, 8>"], ans=0,
   why="r(t) = <1 + 2t^2, 2 + 3t>, so r(2) = <9, 8>."),
 dict(q="To three decimal places, the total distance travelled by a particle with velocity v(t) = <2, 2t> from t = 0 to t = 2 is",
   choices=[
     "4.000",
     "4.472",
     "5.916",
     "8.944"], ans=2,
   why="The speed is 2sqrt(1 + t^2), and int from 0 to 2 of 2sqrt(1 + t^2) dt = 2sqrt(5) + ln(2 + sqrt(5)) = 5.916."),
 dict(q="A particle's position is r(t) = <t^2 - 4t, t^2 - 2t>. The particle is moving up and to the left when",
   choices=[
     "1 < t < 2",
     "t < 1",
     "t > 2",
     "0 < t < 1"], ans=0,
   why="Up means dy/dt = 2t - 2 > 0, so t > 1, and left means dx/dt = 2t - 4 < 0, so t < 2."),
 dict(q="A particle's position is r(t) = <t^2 - 4, 3t> for t >= 0. Its speed at the moment it crosses the y-axis is",
   choices=[
     "5",
     "3",
     "4",
     "sqrt(7)"], ans=0,
   why="The particle crosses the y-axis when t^2 - 4 = 0, that is t = 2, where v = <4, 3> and the speed is 5."),
 dict(q="A particle moves so that its speed is the constant 5 for all t. Which of the following must be true?",
   choices=[
     "Its acceleration may be a nonzero vector, since the direction of motion can change",
     "Its acceleration is the zero vector",
     "Its velocity vector is constant",
     "It travels in a straight line"], ans=0,
   why="Motion around a circle at constant speed, such as r(t) = <5cos(t), 5sin(t)>, has speed 5 and nonzero acceleration."),
]
