# CALC 9.7 Defining Polar Coordinates and Differentiating in Polar Form
# — 25 questions.  Answers verified with sympy; see verify_c9_7.py.
# Polar points are written (r, theta) and rectangular points (x, y).
# Questions 3, 4, 5, 6, 11, 13, 15, 18, 21, 23 and 24 name a curve, a formula or
# a condition rather than a single value; verify_c9_7.py pins each key by
# content and confirms the mathematics behind it with sympy.
TOPIC = ("9.7", "Defining Polar Coordinates and Differentiating in Polar Form", 9)
QUESTIONS = [
 dict(q="The point with polar coordinates (2, pi/3) has rectangular coordinates",
   choices=[
     "(1, sqrt(3))",
     "(sqrt(3), 1)",
     "(2, sqrt(3))",
     "(1/2, sqrt(3)/2)"], ans=0,
   why="x = 2cos(pi/3) = 1 and y = 2sin(pi/3) = sqrt(3)."),
 dict(q="The point with rectangular coordinates (1, 1) has polar coordinates, with r > 0 and 0 <= theta < 2pi,",
   choices=[
     "(sqrt(2), pi/4)",
     "(2, pi/4)",
     "(sqrt(2), pi/2)",
     "(sqrt(2), 3pi/4)"], ans=0,
   why="r = sqrt(1 + 1) = sqrt(2) and tan(theta) = 1 with the point in the first quadrant, so theta = pi/4."),
 dict(q="The graph of the polar equation r = 3 is",
   choices=[
     "a circle of radius 3 centered at the origin",
     "a line through the origin",
     "a circle of radius 3 centered at (3, 0)",
     "a spiral"], ans=0,
   why="Every point at distance 3 from the origin satisfies it, and x^2 + y^2 = 9."),
 dict(q="The graph of the polar equation theta = pi/4 is",
   choices=[
     "a line through the origin with slope 1",
     "a circle of radius pi/4",
     "a ray of length pi/4",
     "the single point (pi/4, pi/4)"], ans=0,
   why="Every point whose direction from the origin is pi/4 (with r allowed to be negative) lies on the line y = x."),
 dict(q="For a curve r = f(theta), the slope dy/dx of the tangent line is",
   choices=[
     "((dr/dtheta)sin(theta) + r cos(theta))/((dr/dtheta)cos(theta) - r sin(theta))",
     "dr/dtheta",
     "((dr/dtheta)cos(theta) - r sin(theta))/((dr/dtheta)sin(theta) + r cos(theta))",
     "(r sin(theta))/(r cos(theta))"], ans=0,
   why="With x = r cos(theta) and y = r sin(theta), each derivative needs the product rule, and dy/dx = (dy/dtheta)/(dx/dtheta)."),
 dict(q="A student claims that the slope of the tangent line to r = f(theta) is dr/dtheta. This is wrong because",
   choices=[
     "dr/dtheta measures how the distance from the origin changes, while the slope is (dy/dtheta)/(dx/dtheta) with x = r cos(theta) and y = r sin(theta)",
     "dr/dtheta is always zero",
     "the slope is dtheta/dr",
     "polar curves have no tangent lines"], ans=0,
   why="Slope is a rate of change of y with respect to x, so both coordinates must first be written in terms of theta and differentiated with the product rule."),
 dict(q="For the polar curve r = 2, the slope of the tangent line at theta = pi/4 is",
   choices=[
     "-1",
     "0",
     "1",
     "2"], ans=0,
   why="The curve is the circle x = 2cos(theta), y = 2sin(theta), whose slope is -cos(theta)/sin(theta) = -1 at theta = pi/4."),
 dict(q="For the polar curve r = theta, dy/dx =",
   choices=[
     "(sin(theta) + theta cos(theta))/(cos(theta) - theta sin(theta))",
     "1",
     "(cos(theta) - theta sin(theta))/(sin(theta) + theta cos(theta))",
     "(theta cos(theta))/(theta sin(theta))"], ans=0,
   why="With dr/dtheta = 1, the numerator is sin(theta) + theta cos(theta) and the denominator is cos(theta) - theta sin(theta)."),
 dict(q="For the polar curve r = theta, the slope of the tangent line at theta = pi/2 is",
   choices=[
     "-2/pi",
     "-pi/2",
     "0",
     "2/pi"], ans=0,
   why="The numerator is 1 + 0 = 1 and the denominator is 0 - pi/2, so the slope is -2/pi."),
 dict(q="For the cardioid r = 1 + cos(theta), the slope of the tangent line at theta = pi/2 is",
   choices=[
     "-2",
     "-1",
     "0",
     "1"], ans=3,
   why="dy/dtheta = -1 and dx/dtheta = -1 at theta = pi/2, so the slope is 1."),
 dict(q="For the polar curve r = 2sin(theta), the tangent line at theta = pi/2 is",
   choices=[
     "horizontal, because dy/dtheta = 0 and dx/dtheta is not 0 there",
     "vertical, because dx/dtheta = 0 there",
     "undefined, because r = 0 there",
     "of slope 1"], ans=0,
   why="The curve is the circle x^2 + (y - 1)^2 = 1, and theta = pi/2 gives its top point, where y is momentarily stationary."),
 dict(q="Written in rectangular form, the polar equation r = 4cos(theta) is",
   choices=[
     "x^2 + y^2 = 4x",
     "x^2 + y^2 = 4y",
     "x^2 + y^2 = 16",
     "x = 4"], ans=0,
   why="Multiplying both sides by r gives r^2 = 4r cos(theta), that is x^2 + y^2 = 4x, a circle of radius 2 centered at (2, 0)."),
 dict(q="The graph of the polar equation r = 2sec(theta) is",
   choices=[
     "the vertical line x = 2",
     "the horizontal line y = 2",
     "the circle x^2 + y^2 = 4",
     "the line y = 2x"], ans=0,
   why="r = 2/cos(theta) gives r cos(theta) = 2, and r cos(theta) is x."),
 dict(q="The point with polar coordinates (-2, pi/3) is the same as the point with polar coordinates",
   choices=[
     "(2, 4pi/3)",
     "(2, pi/3)",
     "(2, 2pi/3)",
     "(-2, 4pi/3)"], ans=0,
   why="A negative r reflects the point through the origin, which adds pi to the direction."),
 dict(q="For a polar curve r = f(theta), dx/dtheta =",
   choices=[
     "(dr/dtheta)cos(theta) - r sin(theta)",
     "(dr/dtheta)cos(theta) + r sin(theta)",
     "-r sin(theta)",
     "(dr/dtheta)sin(theta) + r cos(theta)"], ans=0,
   why="x = r cos(theta) is a product of two functions of theta, so the product rule gives r' cos(theta) - r sin(theta)."),
 dict(q="The point with rectangular coordinates (-3, 3) has polar coordinates, with r > 0 and 0 <= theta < 2pi,",
   choices=[
     "(3sqrt(2), 3pi/4)",
     "(3sqrt(2), pi/4)",
     "(3sqrt(2), 5pi/4)",
     "(6, 3pi/4)"], ans=0,
   why="r = sqrt(9 + 9) = 3sqrt(2), and the point is in the second quadrant, so theta = 3pi/4."),
 dict(q="For the polar curve r = e^theta, the slope of the tangent line at theta = 0 is",
   choices=[
     "1",
     "0",
     "-1",
     "undefined"], ans=0,
   why="dy/dtheta = e^theta(sin(theta) + cos(theta)) = 1 and dx/dtheta = e^theta(cos(theta) - sin(theta)) = 1 at theta = 0."),
 dict(q="A polar curve r = f(theta) has a horizontal tangent line at theta = c when",
   choices=[
     "dy/dtheta = 0 and dx/dtheta is not 0 at theta = c",
     "dr/dtheta = 0 at theta = c",
     "dx/dtheta = 0 and dy/dtheta is not 0 at theta = c",
     "r = 0 at theta = c"], ans=0,
   why="Horizontal means the slope (dy/dtheta)/(dx/dtheta) is 0, so the numerator vanishes while the denominator does not."),
 dict(q="For the cardioid r = 1 + cos(theta), the tangent line is horizontal at which value of theta in the open interval (0, pi)?",
   choices=[
     "pi/3",
     "pi/6",
     "pi/2",
     "2pi/3"], ans=0,
   why="dy/dtheta = cos(theta) + cos(2theta) = (2cos(theta) - 1)(cos(theta) + 1), which vanishes in (0, pi) only where cos(theta) = 1/2."),
 dict(q="For the polar curve r = sin(2theta), the slope of the tangent line at theta = pi/4 is",
   choices=[
     "-1",
     "0",
     "1",
     "2"], ans=0,
   why="At theta = pi/4, dr/dtheta = 2cos(2theta) = 0 and r = 1, so the slope is (r cos(theta))/(-r sin(theta)) = -1."),
 dict(q="The distance from the origin to the point with polar coordinates (r, theta) is",
   choices=[
     "|r|",
     "r, which is never negative",
     "r + theta",
     "sqrt(r^2 + theta^2)"], ans=0,
   why="r may be negative in polar coordinates, and the distance is its absolute value."),
 dict(q="For the polar curve r = 3 + 2sin(theta), the value of dy/dtheta at theta = 0 is",
   choices=[
     "0",
     "2",
     "3",
     "5"], ans=2,
   why="y = (3 + 2sin(theta))sin(theta), so dy/dtheta = 2cos(theta)sin(theta) + (3 + 2sin(theta))cos(theta), which is 3 at theta = 0."),
 dict(q="If a point has polar coordinates (r, theta) and rectangular coordinates (x, y), then",
   choices=[
     "x = r cos(theta) and y = r sin(theta)",
     "x = r sin(theta) and y = r cos(theta)",
     "x = r/cos(theta) and y = r/sin(theta)",
     "x = cos(theta) and y = sin(theta)"], ans=0,
   why="The definitions come from the right triangle with hypotenuse r and angle theta measured from the positive x-axis."),
 dict(q="For the cardioid r = 1 + cos(theta), what happens at theta = pi?",
   choices=[
     "Both dx/dtheta and dy/dtheta are 0, so the slope formula gives 0/0 and the curve has a cusp at the origin",
     "The tangent line is horizontal",
     "The tangent line is vertical",
     "The slope is 1"], ans=0,
   why="r = 0 and dr/dtheta = 0 at theta = pi, so both coordinate derivatives vanish and no slope is determined by the formula alone."),
 dict(q="For the rose r = sin(3theta), the curve passes through the origin at theta = pi/3. The slope of the tangent line there is",
   choices=[
     "sqrt(3)",
     "1/sqrt(3)",
     "0",
     "-sqrt(3)"], ans=0,
   why="Where r = 0 the slope formula collapses to (r' sin(theta))/(r' cos(theta)) = tan(theta), and tan(pi/3) = sqrt(3)."),
]
