# CALC 9.8 Finding the Area of a Region Bounded by a Single Polar Curve
# — 25 questions.  Answers verified with sympy; see verify_c9_8.py.
# The area formula is A = (1/2) int r^2 dtheta; several questions turn on the
# factor 1/2, on squaring r, and on the correct limits.
# Questions 1, 6, 13, 14, 19, 20 and 23 state a formula, a limit or an error
# rather than compute a number; verify_c9_8.py pins each key by content and
# confirms the mathematics behind it with sympy.
TOPIC = ("9.8", "Finding the Area of a Region Bounded by a Single Polar Curve", 9)
QUESTIONS = [
 dict(q="The area of the region swept out by the polar curve r = f(theta) from theta = a to theta = b is",
   choices=[
     "(1/2) int from a to b of r^2 dtheta",
     "int from a to b of r^2 dtheta",
     "(1/2) int from a to b of r dtheta",
     "int from a to b of r dtheta"], ans=0,
   why="A thin sector of angle dtheta and radius r has area (1/2)r^2 dtheta, and the areas add up to the integral."),
 dict(q="The area of the region inside r = 4 between theta = 0 and theta = pi/3 is",
   choices=[
     "8pi/3",
     "4pi/3",
     "16pi/3",
     "2pi/3"], ans=0,
   why="(1/2)(16)(pi/3) = 8pi/3, which is one sixth of the circle of radius 4."),
 dict(q="The area enclosed by the polar curve r = 2 is",
   choices=[
     "4pi",
     "2pi",
     "8pi",
     "16pi"], ans=0,
   why="(1/2) int from 0 to 2pi of 4 dtheta = 4pi, the area of a circle of radius 2."),
 dict(q="Which of the following gives the area enclosed by the cardioid r = 1 + cos(theta)?",
   choices=[
     "(1/2) int from 0 to 2pi of (1 + cos(theta))^2 dtheta",
     "int from 0 to 2pi of (1 + cos(theta))^2 dtheta",
     "(1/2) int from 0 to 2pi of (1 + cos(theta)) dtheta",
     "(1/2) int from 0 to pi of (1 + cos(theta))^2 dtheta"], ans=0,
   why="The whole cardioid is traced once as theta runs from 0 to 2pi, and the integrand is half the square of r."),
 dict(q="The area enclosed by the cardioid r = 1 + cos(theta) is",
   choices=[
     "3pi/2",
     "3pi",
     "pi",
     "2pi"], ans=0,
   why="(1/2) int from 0 to 2pi of (1 + 2cos(theta) + cos^2(theta)) dtheta = (1/2)(2pi + 0 + pi) = 3pi/2."),
 dict(q="The circle r = 2sin(theta) is traced exactly once as theta runs from",
   choices=[
     "0 to pi",
     "0 to 2pi",
     "0 to pi/2",
     "-pi to pi"], ans=0,
   why="By theta = pi the whole circle has been drawn, so integrating to 2pi would count its area twice."),
 dict(q="The area enclosed by the circle r = 2sin(theta) is",
   choices=[
     "pi",
     "2pi",
     "4pi",
     "pi/2"], ans=0,
   why="(1/2) int from 0 to pi of 4sin^2(theta) dtheta = pi, the area of a circle of radius 1."),
 dict(q="Which of the following gives the area of one petal of the rose r = cos(2theta)?",
   choices=[
     "(1/2) int from -pi/4 to pi/4 of cos(2theta)^2 dtheta",
     "(1/2) int from 0 to 2pi of cos(2theta)^2 dtheta",
     "(1/2) int from -pi/4 to pi/4 of cos(2theta) dtheta",
     "int from -pi/4 to pi/4 of cos(2theta)^2 dtheta"], ans=0,
   why="One petal is traced as theta runs between the consecutive zeros -pi/4 and pi/4 of cos(2theta)."),
 dict(q="The area of one petal of the rose r = cos(2theta) is",
   choices=[
     "pi/8",
     "pi/4",
     "pi/2",
     "pi/16"], ans=0,
   why="(1/2) int from -pi/4 to pi/4 of cos^2(2theta) dtheta = (1/2)(pi/4) = pi/8."),
 dict(q="The total area enclosed by all four petals of the rose r = cos(2theta) is",
   choices=[
     "pi/2",
     "pi/8",
     "pi",
     "2pi"], ans=0,
   why="Each of the four petals has area pi/8."),
 dict(q="The area of one petal of the rose r = sin(3theta) is",
   choices=[
     "pi/12",
     "pi/6",
     "pi/3",
     "pi/4"], ans=0,
   why="One petal runs from theta = 0 to theta = pi/3, and (1/2) int of sin^2(3theta) over that interval is pi/12."),
 dict(q="The area of the region swept out by the spiral r = 2theta from theta = 0 to theta = pi is",
   choices=[
     "2pi^3/3",
     "pi^3/3",
     "4pi^3/3",
     "2pi^3"], ans=0,
   why="(1/2) int from 0 to pi of 4theta^2 dtheta = 2pi^3/3."),
 dict(q="A student computes the area enclosed by r = 3 as int from 0 to 2pi of 9 dtheta = 18pi. The error is that",
   choices=[
     "the factor of 1/2 was dropped; the area is 9pi",
     "the limits should be 0 to pi",
     "r should not have been squared",
     "there is no error"], ans=0,
   why="The sector element is (1/2)r^2 dtheta, so the correct value is half of 18pi, which is the area 9pi of a circle of radius 3."),
 dict(q="A student computes the area enclosed by r = 1 + cos(theta) as (1/2) int from 0 to 2pi of (1 + cos(theta)) dtheta = pi. The error is that",
   choices=[
     "r was not squared before integrating",
     "the factor 1/2 should not be there",
     "the limits should be 0 to pi",
     "there is no error"], ans=0,
   why="The integrand must be r^2 = (1 + cos(theta))^2, which gives the correct area 3pi/2."),
 dict(q="The area of the region swept out by r = e^theta from theta = 0 to theta = 1 is",
   choices=[
     "(e^2 - 1)/4",
     "(e^2 - 1)/2",
     "e^2/4",
     "(e - 1)/2"], ans=0,
   why="(1/2) int from 0 to 1 of e^(2theta) dtheta = (1/4)(e^2 - 1)."),
 dict(q="The area enclosed by the cardioid r = 1 + sin(theta) is",
   choices=[
     "3pi/2",
     "pi",
     "2pi",
     "3pi"], ans=0,
   why="The computation matches the cosine cardioid: (1/2)(2pi + 0 + pi) = 3pi/2."),
 dict(q="The area enclosed by the limacon r = 2 + cos(theta) is",
   choices=[
     "9pi/2",
     "4pi",
     "5pi",
     "9pi/4"], ans=0,
   why="(1/2) int from 0 to 2pi of (4 + 4cos(theta) + cos^2(theta)) dtheta = (1/2)(8pi + 0 + pi) = 9pi/2."),
 dict(q="The area enclosed by the circle r = 3cos(theta) is",
   choices=[
     "9pi/4",
     "9pi/2",
     "3pi",
     "9pi"], ans=0,
   why="The curve is a circle of radius 3/2, and (1/2) int from -pi/2 to pi/2 of 9cos^2(theta) dtheta = 9pi/4."),
 dict(q="Integrating (1/2)(3cos(theta))^2 from theta = 0 to theta = 2pi gives 9pi/2, which is twice the area enclosed by r = 3cos(theta). The reason is that",
   choices=[
     "the circle is traced twice as theta runs from 0 to 2pi, so its area is counted twice",
     "the factor 1/2 must be applied a second time",
     "cos^2 is negative on part of the interval",
     "the curve is not closed"], ans=0,
   why="r = 3cos(theta) completes the circle by theta = pi and retraces it (with negative r) from pi to 2pi."),
 dict(q="The inner loop of the limacon r = 1 + 2cos(theta) is traced for theta in",
   choices=[
     "2pi/3 to 4pi/3",
     "0 to 2pi/3",
     "pi/3 to 2pi/3",
     "0 to pi"], ans=0,
   why="The inner loop occurs where r < 0, that is between the consecutive zeros theta = 2pi/3 and theta = 4pi/3 of 1 + 2cos(theta)."),
 dict(q="The area of the inner loop of the limacon r = 1 + 2cos(theta) is",
   choices=[
     "pi - 3sqrt(3)/2",
     "pi + 3sqrt(3)/2",
     "2pi - 3sqrt(3)",
     "pi/2 - 3sqrt(3)/4"], ans=0,
   why="(1/2) int from 2pi/3 to 4pi/3 of (1 + 2cos(theta))^2 dtheta = pi - 3sqrt(3)/2."),
 dict(q="To three decimal places, the area swept out by the spiral r = theta from theta = 0 to theta = pi/2 is",
   choices=[
     "0.308",
     "0.646",
     "1.292",
     "2.467"], ans=1,
   why="(1/2) int from 0 to pi/2 of theta^2 dtheta = pi^3/48 = 0.646."),
 dict(q="Using the symmetry of the cardioid r = 1 + cos(theta) about the x-axis, its area can be written as",
   choices=[
     "int from 0 to pi of (1 + cos(theta))^2 dtheta",
     "(1/2) int from 0 to pi of (1 + cos(theta))^2 dtheta",
     "2 int from 0 to pi of (1 + cos(theta))^2 dtheta",
     "(1/4) int from 0 to 2pi of (1 + cos(theta))^2 dtheta"], ans=0,
   why="Twice the half-area 2 times (1/2) int from 0 to pi of r^2 dtheta leaves a coefficient of 1, and the value is again 3pi/2."),
 dict(q="The area enclosed by the curve r = sqrt(cos(theta)), for -pi/2 <= theta <= pi/2, is",
   choices=[
     "1",
     "2",
     "pi/2",
     "1/2"], ans=0,
   why="(1/2) int from -pi/2 to pi/2 of cos(theta) dtheta = (1/2)(2) = 1; squaring r removes the radical."),
 dict(q="The area of one petal of the rose r = 2cos(3theta) is",
   choices=[
     "pi/3",
     "pi/6",
     "2pi/3",
     "pi/12"], ans=0,
   why="One petal runs from theta = -pi/6 to theta = pi/6, and (1/2) int of 4cos^2(3theta) over that interval is pi/3."),
]
