# AP ENVIRONMENTAL SCIENCE 9.5 Global Climate Change
# CED effective Fall 2026, Unit 9 Global Change.
# Enduring understanding STB-4: Local and regional human activities can have impacts at
# the global level.
# Learning objective STB-4.F: explain how changes in climate, both short- and long-term,
# impact ecosystems. Suggested skill 5.D, interpret experimental data and results in
# relation to a given hypothesis.
#
# Essential knowledge relied on, in the framework's own words:
#   STB-4.F.1   The Earth has undergone climate change throughout geologic time, with
#               major shifts in global temperatures causing periods of warming and
#               cooling as recorded with CO2 data and ice cores.
#   STB-4.F.2   Effects of climate change include rising temperatures, melting permafrost
#               and sea ice, rising sea levels, and displacement of coastal populations.
#   STB-4.F.3   Marine ecosystems are affected by changes in sea level, some positively,
#               such as in newly created habitats on now-flooded continental shelves, and
#               some negatively, such as deeper communities that may no longer be in the
#               photic zone of seawater.
#   STB-4.F.4   Winds generated by atmospheric circulation help transport heat throughout
#               the Earth. Climate change may change circulation patterns, as temperature
#               changes may impact Hadley cells and the jet stream.
#   STB-4.F.5   Oceanic currents, or the ocean conveyor belt, carry heat throughout the
#               world. When these currents change, it can have a big impact on global
#               climate, especially in coastal regions.
#   STB-4.F.6   Climate change can affect soil through changes in temperature and
#               rainfall, which can impact soil's viability and potentially increase
#               erosion.
#   STB-4.F.7   Earth's polar regions are showing faster response times to global climate
#               change because ice and snow in these regions reflect the most energy back
#               out to space, leading to a positive feedback loop.
#   STB-4.F.8   As the Earth warms, this ice and snow melts, meaning less solar energy is
#               radiated back into space and instead is absorbed by the Earth's surface.
#               This in turn causes more warming of the polar regions.
#   STB-4.F.9   Global climate change response time in the Arctic is due to positive
#               feedback loops involving melting sea ice and thawing tundra, and the
#               subsequent release of greenhouse gases like methane.
#   STB-4.F.10  One consequence of the loss of ice and snow in polar regions is the effect
#               on species that depend on the ice for habitat and food.
#
# THIS TOPIC IS NORMALLY TAUGHT FROM TWO CURVES -- carbon dioxide and temperature against
# time -- AND THE BANK CANNOT CARRY A PICTURE. So both curves are supplied as tables,
# sampled closely enough that the feature each stem asks about can actually be read from
# the rows: the ice core record carries layers both colder and warmer than the present, so
# the alternation STB-4.F.1 describes is visible, and the modern record carries five
# readings, so a rise at every step is visible rather than merely asserted between two
# endpoints. No stem points at a picture.
#
# BOUNDARIES. The principal greenhouse gases and their warming potentials are STB-4.C and
# STB-4.D (topic 9.3); the problems posed by an INCREASE in greenhouse gases -- rising
# seas from melting ice sheets and ocean expansion, and disease vectors moving from the
# tropics toward the poles -- are STB-4.E.1 (topic 9.4). Ocean warming's effects on marine
# species and coral bleaching are STB-4.G (topic 9.6) and acidification is STB-4.H (topic
# 9.7). No key here reaches into any of them: the sea level claims used are STB-4.F.2's
# and STB-4.F.3's, and no item mentions coral or pH.
#
# FIVE choices (A-E) per SCIENCE_BRIEF.md. No LaTeX: export_units.py does not typeset
# Environmental Science. Year ranges are written with "to".
TOPIC = ("9.5", "Global Climate Change", 9)

_T_ICECORE = dict(
    headers=["Age of the ice layer (thousands of years before the present)",
             "Carbon dioxide in the trapped air (parts per million)",
             "Reconstructed temperature relative to today (degrees Celsius)"],
    rows=[["160", "195", "-8.4"],
          ["130", "285", "1.2"],
          ["100", "230", "-4.1"],
          ["60", "205", "-6.9"],
          ["20", "190", "-9.2"],
          ["0", "280", "0.0"]])

_T_MODERN = dict(
    headers=["Year of the reading", "Atmospheric carbon dioxide (parts per million)",
             "Global temperature relative to the 1900 reading (degrees Celsius)"],
    rows=[["1900", "295", "0.00"],
          ["1940", "311", "0.15"],
          ["1980", "339", "0.40"],
          ["2000", "369", "0.62"],
          ["2020", "413", "1.02"]])

_T_ARCTIC = dict(
    headers=["Region", "Temperature rise since 1900 (degrees Celsius)"],
    rows=[["Arctic", "3.1"],
          ["Northern mid latitudes", "1.4"],
          ["Tropics", "0.8"],
          ["Southern mid latitudes", "1.1"]])

_T_SEAICE = dict(
    headers=["Decade of the record",
             "Summer sea ice extent (millions of square kilometres)",
             "Percent of incoming sunlight reflected back to space by the surface",
             "Mean summer surface temperature (degrees Celsius)"],
    rows=[["Decade 1", "7.8", "62", "-1.4"],
          ["Decade 2", "6.9", "56", "-0.9"],
          ["Decade 3", "5.6", "48", "-0.2"],
          ["Decade 4", "4.1", "39", "0.6"]])

_T_PERMAFROST = dict(
    headers=["Year of the survey",
             "Area of thawed tundra (thousands of square kilometres)",
             "Methane leaving the thawed ground (thousands of tonnes per year)"],
    rows=[["Year 1", "40", "60"],
          ["Year 2", "68", "104"],
          ["Year 3", "115", "171"],
          ["Year 4", "182", "268"]])

_T_SPECIES = dict(
    headers=["Species", "Percent of its feeding done from sea ice",
             "Percent change in its population across the record"],
    rows=[["Species 1", "92", "-41"],
          ["Species 2", "70", "-28"],
          ["Species 3", "35", "-11"],
          ["Species 4", "5", "2"]])

_T_SHELF = dict(
    headers=["Site", "Rise in sea level across the record (centimetres)",
             "New shallow habitat on the flooded shelf (square kilometres)",
             "Sea floor community carried below the photic zone (square kilometres)"],
    rows=[["Site 1", "12", "40", "9"],
          ["Site 2", "24", "85", "21"],
          ["Site 3", "37", "130", "34"],
          ["Site 4", "50", "175", "46"]])

_T_SOIL = dict(
    headers=["Plot", "Rise in mean temperature (degrees Celsius)",
             "Change in yearly rainfall (millimetres)",
             "Soil lost to erosion (tonnes per hectare each year)"],
    rows=[["Plot 1", "0.4", "-30", "2.1"],
          ["Plot 2", "1.1", "-95", "5.4"],
          ["Plot 3", "1.8", "-160", "9.7"],
          ["Plot 4", "2.6", "-240", "14.8"]])

_T_CURRENT = dict(
    headers=["Period of the record",
             "Strength of the ocean current reaching one coast (relative index)",
             "Mean winter temperature of that coastal region (degrees Celsius)"],
    rows=[["Period 1", "100", "6.2"],
          ["Period 2", "88", "5.1"],
          ["Period 3", "71", "3.6"],
          ["Period 4", "54", "1.9"]])

QUESTIONS = [

 dict(q="What does the framework say about the Earth's climate through geologic time?",
      choices=[
        "It has undergone change, with major shifts in global temperatures causing periods "
        "of warming and of cooling.",
        "It has held steady until the present century, when change began.",
        "It has warmed continuously and has never cooled.",
        "It has cooled continuously and has never warmed.",
        "It cannot be described, because no record of it survives."],
      ans=0,
      why="STB-4.F.1 states that the Earth has undergone climate change throughout "
          "geologic time, with major shifts in global temperatures causing periods of "
          "warming and cooling, so both directions of change are in the statement."),

 dict(q="From what does the framework say those past shifts in global temperature are "
        "recorded?",
      choices=[
        "Carbon dioxide data and ice cores.",
        "Written weather records kept over the last two centuries.",
        "The number of species alive at each time.",
        "The area of farmland under cultivation at each time.",
        "The distance of the Earth from the Sun at each time."],
      ans=0,
      why="STB-4.F.1 states that the major shifts in global temperatures are recorded with "
          "CO2 data and ice cores, which is the whole of the evidence the statement "
          "names."),

 dict(q="Which effects of climate change does the framework name in STB-4.F.2?",
      choices=[
        "Rising temperatures, melting permafrost and sea ice, rising sea levels, and "
        "displacement of coastal populations.",
        "Falling temperatures, thickening permafrost, falling sea levels, and the return "
        "of coastal populations.",
        "Rising temperatures alone, with no consequence for ice, seas or people.",
        "Melting permafrost alone, with no consequence for temperature or sea level.",
        "A change in the number of hours of daylight received at each latitude."],
      ans=0,
      why="STB-4.F.2 lists rising temperatures, melting permafrost and sea ice, rising sea "
          "levels, and displacement of coastal populations, which is exactly the set the "
          "keyed option names."),

 dict(q="A revision card lists five effects and calls all five framework effects from "
        "STB-4.F.2. Which one is not?",
      choices=[
        "A change in the number of hours of daylight at each latitude.",
        "Rising temperatures.",
        "Melting permafrost and sea ice.",
        "Rising sea levels.",
        "Displacement of coastal populations."],
      ans=0,
      why="STB-4.F.2 names four effects, each of which the four rejected options restates. "
          "Hours of daylight appear nowhere in the statement."),

 dict(q="What does the framework say about how changes in sea level affect marine "
        "ecosystems?",
      choices=[
        "Some are affected positively and some negatively.",
        "All are affected positively.",
        "All are affected negatively.",
        "None is affected at all.",
        "Only ecosystems on land are affected."],
      ans=0,
      why="STB-4.F.3 states that marine ecosystems are affected by changes in sea level, "
          "some positively and some negatively, and gives an example of each."),

 dict(q="Which positive example does the framework give of a marine ecosystem affected by "
        "a change in sea level?",
      choices=[
        "Newly created habitats on now flooded continental shelves.",
        "Deeper communities carried out of the photic zone of seawater.",
        "The thickening of permafrost along the coast.",
        "The strengthening of the ocean conveyor belt.",
        "The reflection of sunlight by newly formed sea ice."],
      ans=0,
      why="STB-4.F.3 gives newly created habitats on now-flooded continental shelves as "
          "its example of a positive effect, and reserves the photic zone case for the "
          "negative side."),

 dict(q="And which negative example does the framework give in the same statement?",
      choices=[
        "Deeper communities that may no longer lie within the photic zone of seawater.",
        "New habitats appearing on continental shelves that have been flooded.",
        "Winds transporting heat away from the equator.",
        "Soil losing its viability as rainfall changes.",
        "Species losing the ice they depend on for habitat and food."],
      ans=0,
      why="STB-4.F.3 gives deeper communities that may no longer be in the photic zone of "
          "seawater as its example of a negative effect of a change in sea level. The soil "
          "and polar species cases belong to STB-4.F.6 and STB-4.F.10 instead."),

 dict(q="What does the framework say winds generated by atmospheric circulation do?",
      choices=[
        "They help transport heat throughout the Earth.",
        "They remove heat from the Earth entirely.",
        "They prevent heat from moving away from the equator.",
        "They generate the ocean conveyor belt.",
        "They determine the amount of carbon dioxide in the atmosphere."],
      ans=0,
      why="STB-4.F.4 states that winds generated by atmospheric circulation help transport "
          "heat throughout the Earth, which is a movement of heat rather than a removal or "
          "a blockage of it."),

 dict(q="Which two features of atmospheric circulation does the framework say temperature "
        "changes may impact?",
      choices=[
        "Hadley cells and the jet stream.",
        "The ocean conveyor belt and the photic zone.",
        "Permafrost and sea ice.",
        "Continental shelves and coastal populations.",
        "Soil viability and erosion."],
      ans=0,
      why="STB-4.F.4 states that climate change may change circulation patterns, as "
          "temperature changes may impact Hadley cells and the jet stream, and names no "
          "other feature of circulation."),

 dict(q="STB-4.F.4 says climate change MAY change circulation patterns. What does that "
        "wording establish?",
      choices=[
        "A possibility the framework raises rather than an outcome it guarantees.",
        "An outcome the framework says is certain in every case.",
        "An outcome the framework says has already been ruled out.",
        "A claim about the ocean conveyor belt rather than about the winds.",
        "A claim that circulation patterns cannot change at all."],
      ans=0,
      why="The word MAY in STB-4.F.4 marks the change in circulation patterns as something "
          "the framework raises as possible, so nothing there promises it will happen or "
          "denies that it could."),

 dict(q="What does the framework say oceanic currents do, and where does it say a change "
        "in them is felt most?",
      choices=[
        "They carry heat throughout the world, and a change has a big impact especially in "
        "coastal regions.",
        "They carry heat throughout the world, and a change is felt only far inland.",
        "They carry carbon dioxide throughout the world, and a change is felt in coastal "
        "regions.",
        "They prevent heat from moving between hemispheres, and a change is felt "
        "everywhere equally.",
        "They have no effect on global climate, whatever they do."],
      ans=0,
      why="STB-4.F.5 states that oceanic currents, or the ocean conveyor belt, carry heat "
          "throughout the world, and that when these currents change it can have a big "
          "impact on global climate, especially in coastal regions."),

 dict(q="Through which two changes does the framework say climate change can affect soil?",
      choices=[
        "Changes in temperature and in rainfall.",
        "Changes in sea level and in wind direction.",
        "Changes in the number of species present and in the area farmed.",
        "Changes in the strength of the ocean conveyor belt and in the photic zone.",
        "Changes in the hours of daylight and in the distance to the sea."],
      ans=0,
      why="STB-4.F.6 states that climate change can affect soil through changes in "
          "temperature and rainfall, and names no other route to the soil."),

 dict(q="What does the framework say those changes in temperature and rainfall can do to "
        "soil?",
      choices=[
        "Affect the soil's viability and potentially increase erosion.",
        "Affect the soil's viability and reliably decrease erosion.",
        "Leave the soil's viability untouched while decreasing erosion.",
        "Convert the soil into rock over a single season.",
        "Remove the need for rainfall in that region."],
      ans=0,
      why="STB-4.F.6 states that changes in temperature and rainfall can impact soil's "
          "viability and potentially increase erosion, so both halves of the keyed option "
          "are in the statement and the direction of the erosion claim is upward."),

 dict(q="Why does the framework say the Earth's polar regions show faster response times "
        "to global climate change?",
      choices=[
        "Because ice and snow there reflect the most energy back out to space, which sets "
        "up a positive feedback loop.",
        "Because ice and snow there absorb the most energy, which sets up a negative "
        "feedback loop.",
        "Because those regions receive the most direct sunlight of anywhere on Earth.",
        "Because those regions hold the largest human populations.",
        "Because those regions lie closest to the ocean conveyor belt."],
      ans=0,
      why="STB-4.F.7 states that the polar regions show faster response times because ice "
          "and snow in these regions reflect the most energy back out to space, leading to "
          "a positive feedback loop."),

 dict(q="What does the framework say follows as that polar ice and snow melts?",
      choices=[
        "Less solar energy is radiated back into space and more is absorbed by the "
        "surface, causing further warming of the polar regions.",
        "More solar energy is radiated back into space and less is absorbed by the "
        "surface, cooling the polar regions.",
        "The same amount of solar energy is radiated back into space as before, so nothing "
        "changes.",
        "Solar energy stops reaching the polar regions altogether.",
        "The polar regions begin to receive their heat from the ocean conveyor belt "
        "instead."],
      ans=0,
      why="STB-4.F.8 states that as the Earth warms this ice and snow melts, meaning less "
          "solar energy is radiated back into space and instead is absorbed by the Earth's "
          "surface, which in turn causes more warming of the polar regions."),

 dict(q="What does the framework attribute the Arctic's response time to?",
      choices=[
        "Positive feedback loops involving melting sea ice and thawing tundra, and the "
        "release of greenhouse gases such as methane that follows.",
        "Negative feedback loops involving freezing sea ice and hardening tundra, and the "
        "capture of greenhouse gases that follows.",
        "The distance of the Arctic from the equator alone.",
        "The strength of the winds generated by Hadley cells alone.",
        "The number of species that depend on ice for habitat and food."],
      ans=0,
      why="STB-4.F.9 states that global climate change response time in the Arctic is due "
          "to positive feedback loops involving melting sea ice and thawing tundra, and "
          "the subsequent release of greenhouse gases like methane."),

 dict(q="What consequence of the loss of ice and snow in polar regions does STB-4.F.10 "
        "name?",
      choices=[
        "The effect on species that depend on the ice for habitat and food.",
        "The effect on species that avoid ice altogether.",
        "The creation of new habitat for species that live in the deep ocean.",
        "The strengthening of the winds generated by atmospheric circulation.",
        "The recovery of soil viability in the regions concerned."],
      ans=0,
      why="STB-4.F.10 names as one consequence of the loss of ice and snow in polar "
          "regions the effect on species that depend on the ice for habitat and food."),

 dict(q="Which of these does the framework NOT claim in this topic?",
      choices=[
        "The Earth's climate was unchanging until human activity began to alter it.",
        "The Earth has undergone climate change throughout geologic time.",
        "Winds generated by atmospheric circulation help transport heat throughout the "
        "Earth.",
        "Oceanic currents carry heat throughout the world.",
        "The polar regions are showing faster response times to global climate change."],
      ans=0,
      why="STB-4.F.1 states that the Earth has undergone climate change throughout "
          "geologic time with periods of both warming and cooling, so a claim that the "
          "climate was unchanging until recently contradicts the framework rather than "
          "extending it."),

 dict(q="An ice core was sampled at six depths and each layer's trapped air and "
        "reconstructed temperature recorded. What does the record establish?",
      table=_T_ICECORE,
      choices=[
        "Carbon dioxide and temperature move together across the layers, and the record "
        "holds layers both colder and warmer than today.",
        "Carbon dioxide and temperature move in opposite directions across the layers.",
        "Carbon dioxide varies across the layers while temperature does not.",
        "Every layer in the record is colder than today.",
        "Every layer in the record is warmer than today."],
      ans=0,
      why="Sorting the layers by their trapped carbon dioxide leaves the reconstructed "
          "temperature strictly increasing, and the temperature column carries entries on "
          "both sides of today's value. STB-4.F.1 states that major shifts in global "
          "temperatures caused periods of warming and cooling, as recorded with carbon "
          "dioxide data and ice cores."),

 dict(q="Across those same six ice layers, how far apart are the warmest and the coldest "
        "reconstructed temperatures?",
      table=_T_ICECORE,
      choices=[
        "10.4 degrees Celsius.",
        "9.2 degrees Celsius.",
        "8.4 degrees Celsius.",
        "1.2 degrees Celsius.",
        "12.8 degrees Celsius."],
      ans=0,
      why="The largest and smallest entries in the reconstructed temperature column are "
          "subtracted. STB-4.F.1 describes major shifts in global temperatures across "
          "geologic time, which is the size this record puts on one such range."),

 dict(q="Atmospheric carbon dioxide and global temperature were read five times across the "
        "last century and a quarter. What does the record establish?",
      table=_T_MODERN,
      choices=[
        "Both rise at every successive reading.",
        "Both fall at every successive reading.",
        "Carbon dioxide rises at every reading while temperature falls.",
        "Temperature rises at every reading while carbon dioxide falls.",
        "Neither changes appreciably across the five readings."],
      ans=0,
      why="Reading down both columns in year order, each entry exceeds the one before it. "
          "STB-4.F.1 makes carbon dioxide data one of the two records by which shifts in "
          "global temperature are traced."),

 dict(q="Across those same five readings, by what percent did atmospheric carbon dioxide "
        "rise?",
      table=_T_MODERN,
      choices=[
        "By 40 percent.",
        "By 118 percent.",
        "By 29 percent.",
        "By 71 percent.",
        "By 4 percent."],
      ans=0,
      why="The rise in the carbon dioxide column is divided by its first reading and "
          "expressed as a percentage. STB-4.F.1 names carbon dioxide data among the "
          "records by which change in the climate is traced."),

 dict(q="Four regions were recorded for how much they have warmed since 1900. Which has "
        "warmed most, and by how much more than the tropics?",
      table=_T_ARCTIC,
      choices=[
        "The Arctic, by 2.3 degrees Celsius more than the tropics.",
        "The Arctic, by 0.8 degrees Celsius more than the tropics.",
        "The tropics, by 2.3 degrees Celsius more than the Arctic.",
        "The northern mid latitudes, by 0.6 degrees Celsius more than the tropics.",
        "All four regions have warmed by the same amount."],
      ans=0,
      why="The largest entry in the warming column is identified and the tropical entry "
          "subtracted from it. STB-4.F.7 states that the Earth's polar regions are showing "
          "faster response times to global climate change."),

 dict(q="Summer sea ice, the sunlight reflected by the surface and the summer temperature "
        "were recorded over four decades. What does the record establish?",
      table=_T_SEAICE,
      choices=[
        "As the ice shrinks, less sunlight is reflected and the surface grows warmer, "
        "which is a positive feedback loop.",
        "As the ice shrinks, more sunlight is reflected and the surface grows cooler, "
        "which is a negative feedback loop.",
        "The ice shrinks while the reflected sunlight and the temperature both hold "
        "steady.",
        "The ice grows while the reflected sunlight falls and the temperature rises.",
        "None of the three columns changes across the four decades."],
      ans=0,
      why="Reading down the three columns in decade order, the ice extent and the "
          "reflected share both fall while the temperature rises. STB-4.F.7 and STB-4.F.8 "
          "describe exactly that chain, in which melting ice reflects less energy back to "
          "space so that more is absorbed and the region warms further."),

 dict(q="Thawed tundra and the methane leaving it were surveyed in four years. What does "
        "the record establish?",
      table=_T_PERMAFROST,
      choices=[
        "The methane leaving the ground rises as the thawed area rises.",
        "The methane leaving the ground falls as the thawed area rises.",
        "The methane leaving the ground holds steady while the thawed area rises.",
        "The thawed area falls across the four surveys.",
        "Neither column changes across the four surveys."],
      ans=0,
      why="Reading down both columns in survey order, each entry exceeds the one before "
          "it. STB-4.F.9 attributes the Arctic's response time to positive feedback loops "
          "involving thawing tundra and the subsequent release of greenhouse gases like "
          "methane."),

 dict(q="Four species were recorded for how much of their feeding is done from sea ice and "
        "for how their populations changed. What does the record establish?",
      table=_T_SPECIES,
      choices=[
        "The species that feed most from the ice are the species whose populations fell "
        "most.",
        "The species that feed most from the ice are the species whose populations rose "
        "most.",
        "Dependence on the ice and change in population are unrelated in this record.",
        "Every one of the four species grew in number across the record.",
        "Every one of the four species fell in number across the record."],
      ans=0,
      why="Sorting the species by the share of their feeding done from ice leaves the "
          "change in population strictly falling. STB-4.F.10 names as one consequence of "
          "the loss of polar ice and snow the effect on species that depend on the ice for "
          "habitat and food."),

 dict(q="Four coastal sites were recorded for a rise in sea level and for two areas of "
        "sea floor. What does the record establish?",
      table=_T_SHELF,
      choices=[
        "The same rise both creates new shallow habitat and carries other communities "
        "below the photic zone.",
        "The same rise creates new shallow habitat and leaves every existing community "
        "where it was.",
        "The same rise carries communities below the photic zone and creates no new "
        "habitat at all.",
        "The larger rises create less new shallow habitat than the smaller ones.",
        "Neither area changes as the rise in sea level grows."],
      ans=0,
      why="Sorting the sites by the rise in sea level leaves both the new shallow habitat "
          "and the area carried below the photic zone strictly increasing. STB-4.F.3 "
          "states that marine ecosystems are affected by changes in sea level, some "
          "positively and some negatively, and gives those two as its examples."),

 dict(q="Four plots were recorded for a rise in temperature, a change in rainfall and the "
        "soil they lost. What does the record establish?",
      table=_T_SOIL,
      choices=[
        "The plots that warmed most and lost most rainfall are the plots that lost most "
        "soil.",
        "The plots that warmed most and lost most rainfall are the plots that lost least "
        "soil.",
        "Soil loss is unrelated to either the temperature or the rainfall column here.",
        "Rainfall rose on every plot across the record.",
        "Every plot lost the same amount of soil."],
      ans=0,
      why="Sorting the plots by the rise in temperature, and then by the fall in rainfall, "
          "leaves the soil lost strictly increasing each time. STB-4.F.6 states that "
          "climate change can affect soil through changes in temperature and rainfall, "
          "which can impact its viability and potentially increase erosion."),

 dict(q="One coast was recorded over four periods for the strength of the current reaching "
        "it and for its winter temperature. What does the record establish?",
      table=_T_CURRENT,
      choices=[
        "As the current weakens, the coastal region grows colder.",
        "As the current weakens, the coastal region grows warmer.",
        "The current weakens while the coastal temperature holds steady.",
        "The current strengthens while the coastal temperature falls.",
        "Neither column changes across the four periods."],
      ans=0,
      why="Reading down both columns in period order, the current index and the winter "
          "temperature fall together. STB-4.F.5 states that oceanic currents carry heat "
          "throughout the world and that a change in them can have a big impact on global "
          "climate, especially in coastal regions."),

 dict(q="Which single sentence collects what this topic's statements assert and nothing "
        "further?",
      choices=[
        "The Earth has warmed and cooled through geologic time as recorded in carbon "
        "dioxide data and ice cores; climate change raises temperatures, melts permafrost "
        "and sea ice, raises seas and displaces coastal people; it affects marine "
        "ecosystems both positively and negatively, may alter winds and ocean currents "
        "that carry heat, can damage soil, and drives polar feedback loops that harm "
        "species depending on ice.",
        "The Earth's climate held steady until the present century; climate change lowers "
        "temperatures and sea levels; marine ecosystems are affected only negatively; and "
        "the polar regions respond more slowly than anywhere else.",
        "Climate change affects only the polar regions, where melting ice reflects more "
        "energy back to space and cools the surface further.",
        "Climate change affects soil and nothing else, and the framework names no effect "
        "on marine ecosystems, winds or currents.",
        "The framework states that circulation patterns are certain to change and gives "
        "the year in which each change will occur."],
      ans=0,
      why="STB-4.F.1 supplies the geologic record and its evidence, STB-4.F.2 the four "
          "named effects, STB-4.F.3 the two directions for marine ecosystems, STB-4.F.4 "
          "and STB-4.F.5 the winds and currents that carry heat, STB-4.F.6 the soil, and "
          "STB-4.F.7 through STB-4.F.10 the polar feedback loops and the species that "
          "depend on ice."),
]
