# MACRO 1.1 Scarcity — 50 questions
TOPIC = ("1.1", "Scarcity", 1)
QUESTIONS = [
 dict(q="Scarcity exists because", choices=[
   "governments mismanage resources",
   "human wants are unlimited while the resources to satisfy them are limited",
   "some countries are poor",
   "prices are too high",
   "people are greedy"], ans=1,
   why="Scarcity is the gap between unlimited wants and limited means, and it applies to every economy."),
 dict(q="Economics is best defined as the study of", choices=[
   "how to make money",
   "how societies allocate scarce resources among competing uses",
   "government budgets",
   "the stock market",
   "business management"], ans=1,
   why="Allocation under scarcity is the subject of the discipline."),
 dict(q="Macroeconomics studies", choices=[
   "the behavior of individual firms and consumers",
   "the economy as a whole, including output, unemployment, and inflation",
   "a single market's price",
   "one household's budget",
   "the pricing decisions of a monopolist"], ans=1,
   why="Macroeconomics looks at economy-wide aggregates."),
 dict(q="Microeconomics studies", choices=[
   "national income",
   "the decisions of individual households and firms and outcomes in particular markets",
   "the unemployment rate",
   "the inflation rate",
   "the government deficit"], ans=1,
   why="Microeconomics works at the level of individual decision makers and single markets."),
 dict(q="Which of the following is a macroeconomic question?", choices=[
   "How many workers should a bakery hire?",
   "What determines the national unemployment rate?",
   "What price should a firm charge for its product?",
   "Should a household buy a car?",
   "How much wheat should a farmer plant?"], ans=1,
   why="It concerns an economy-wide aggregate."),
 dict(q="Which of the following is a microeconomic question?", choices=[
   "What causes inflation across the economy?",
   "How does a rise in the price of coffee affect the quantity of coffee sold?",
   "What determines a country's growth rate?",
   "How large should the national debt be?",
   "What is the effect of monetary policy on output?"], ans=1,
   why="It concerns one market's price and quantity."),
 dict(q="Opportunity cost is", choices=[
   "the money price of a good",
   "the value of the next-best alternative given up when a choice is made",
   "the total cost of all alternatives",
   "the cost of production",
   "always zero"], ans=1,
   why="Every choice forgoes something, and that forgone alternative is the true cost."),
 dict(q="A student who spends an evening studying instead of working a $60 shift has an opportunity cost of", choices=[
   "zero", "$60 of forgone earnings", "the cost of textbooks", "the tuition fee", "the value of the degree"], ans=1,
   why="The next-best use of that evening was the shift."),
 dict(q="The four factors of production are", choices=[
   "money, goods, services, and taxes",
   "land, labor, capital, and entrepreneurship",
   "supply, demand, price, and quantity",
   "consumption, investment, government, and net exports",
   "income, spending, saving, and borrowing"], ans=1,
   why="These are the categories of productive resources."),
 dict(q="In economics, capital refers to", choices=[
   "money in a bank account",
   "manufactured resources such as tools, machines, and buildings used to produce goods",
   "shares of stock",
   "natural resources",
   "workers' skills"], ans=1,
   why="Financial assets are not capital in the production sense."),
 dict(q="Land as a factor of production means", choices=[
   "only farmland",
   "all natural resources, including minerals, water, and timber",
   "real estate prices",
   "buildings",
   "government-owned property"], ans=1,
   why="It covers gifts of nature used in production."),
 dict(q="Entrepreneurship refers to", choices=[
   "working for wages",
   "organizing the other factors of production and bearing the risk of a venture",
   "owning land",
   "lending money",
   "government planning"], ans=1,
   why="The entrepreneur combines resources and accepts the risk of loss."),
 dict(q="Because resources are scarce, every economy must answer the questions of", choices=[
   "how to eliminate scarcity",
   "what to produce, how to produce it, and for whom to produce it",
   "how to raise taxes",
   "when to trade",
   "how to print money"], ans=1,
   why="These three questions arise in every economic system."),
 dict(q="A trade-off is", choices=[
   "the elimination of scarcity",
   "giving up some of one thing to obtain more of another",
   "an increase in all goods at once",
   "a tax",
   "a market price"], ans=1,
   why="Limited resources make trade-offs unavoidable."),
 dict(q="Scarcity applies to", choices=[
   "poor countries only",
   "every economy, no matter how wealthy",
   "developing economies only",
   "planned economies only",
   "no modern economy"], ans=1,
   why="Even a rich economy cannot produce everything everyone wants."),
 dict(q="A good is described as free in the economic sense only if", choices=[
   "the government provides it",
   "it is available in quantities greater than people want at a price of zero",
   "it has no price tag",
   "it is subsidized",
   "it is a public good"], ans=1,
   why="A free good has no opportunity cost, which is very rare."),
 dict(q="A positive economic statement is one that", choices=[
   "expresses an opinion about what should be",
   "describes what is and can in principle be tested against evidence",
   "recommends a policy",
   "concerns only good outcomes",
   "is always correct"], ans=1,
   why="Positive statements are descriptive and testable."),
 dict(q="A normative economic statement is one that", choices=[
   "describes what is",
   "makes a value judgement about what ought to be",
   "can be tested with data",
   "concerns only bad outcomes",
   "is always false"], ans=1,
   why="Normative statements involve values, not just facts."),
 dict(q="Which of the following is a normative statement?", choices=[
   "The unemployment rate rose to 6% last quarter.",
   "The government should reduce unemployment even if inflation rises.",
   "Inflation was 3% last year.",
   "GDP grew by 2%.",
   "The central bank cut interest rates."], ans=1,
   why="The word should marks a value judgement."),
 dict(q="Which of the following is a positive statement?", choices=[
   "Taxes on the wealthy ought to be higher.",
   "An increase in the minimum wage raised teenage unemployment by two percentage points.",
   "The government should spend more on schools.",
   "Inequality is too great.",
   "Free trade is unfair to workers."], ans=1,
   why="It is a factual claim that evidence could confirm or refute."),
 dict(q="Marginal analysis involves comparing", choices=[
   "total benefits with total costs",
   "the additional benefit of an action with its additional cost",
   "average costs across firms",
   "prices across markets",
   "past decisions with future ones"], ans=1,
   why="Rational decisions are made at the margin, not in totals."),
 dict(q="A rational decision maker takes an action when", choices=[
   "the total benefit is positive",
   "the marginal benefit is at least as large as the marginal cost",
   "the average cost falls",
   "others take the same action",
   "the action is free"], ans=1,
   why="The comparison is between the incremental gain and the incremental cost."),
 dict(q="An incentive is", choices=[
   "a legal requirement",
   "something that induces a person to act, such as a reward or a penalty",
   "a tax only",
   "a scarce resource",
   "an opportunity cost"], ans=1,
   why="Incentives shape behavior by changing the payoffs to choices."),
 dict(q="A tax on a good creates an incentive to", choices=[
   "buy more of it", "buy less of it", "ignore its price", "produce more of it", "raise its quality"], ans=1,
   why="A higher effective price discourages purchases."),
 dict(q="A subsidy for a good creates an incentive to", choices=[
   "buy less of it", "produce and consume more of it", "ignore it", "raise its price", "ban it"], ans=1,
   why="A subsidy lowers the effective cost of the activity."),
 dict(q="Economic models are useful because they", choices=[
   "describe reality perfectly",
   "simplify a complex world so that key relationships can be isolated and analyzed",
   "eliminate uncertainty",
   "predict every outcome",
   "avoid all assumptions"], ans=1,
   why="Simplification is the point of a model, not a defect."),
 dict(q="The assumption ceteris paribus means", choices=[
   "everything changes at once",
   "all other things are held constant",
   "the model is wrong",
   "no assumptions are made",
   "prices are fixed"], ans=1,
   why="It isolates the effect of one variable at a time."),
 dict(q="A society that decides to devote more resources to healthcare must, holding resources constant,", choices=[
   "produce more of everything",
   "produce less of something else",
   "eliminate scarcity",
   "reduce its population",
   "raise all prices"], ans=1,
   why="Scarcity means more of one thing requires less of another."),
 dict(q="Which of the following best illustrates opportunity cost at the national level?", choices=[
   "an increase in the money supply",
   "resources used to build military equipment cannot also build hospitals",
   "a rise in the price level",
   "an increase in exports",
   "a fall in unemployment"], ans=1,
   why="The forgone alternative use of the same resources is the cost."),
 dict(q="Economic goods differ from free goods in that economic goods", choices=[
   "have no price",
   "are scarce, so obtaining them involves an opportunity cost",
   "are provided by government",
   "cannot be traded",
   "have unlimited supply"], ans=1,
   why="Scarcity is what gives a good an opportunity cost."),
 dict(q="The statement that there is no such thing as a free lunch expresses the idea of", choices=[
   "inflation", "opportunity cost", "unemployment", "economic growth", "market equilibrium"], ans=1,
   why="Someone's resources were used, so something was given up."),
 dict(q="A country's standard of living depends primarily on", choices=[
   "the size of its money supply",
   "its ability to produce goods and services, that is, its productivity",
   "its trade deficit",
   "its tax rate",
   "its population size alone"], ans=1,
   why="Output per person is what people can consume."),
 dict(q="Productivity is best defined as", choices=[
   "total output",
   "output produced per unit of input, such as per hour worked",
   "the number of workers",
   "the growth rate of prices",
   "total employment"], ans=1,
   why="It is a ratio of output to input, not a level of output."),
 dict(q="An increase in a country's capital stock will, other things equal,", choices=[
   "reduce output",
   "raise productivity and the economy's capacity to produce",
   "raise unemployment",
   "reduce the labor force",
   "have no effect"], ans=1,
   why="More tools per worker raises output per worker."),
 dict(q="Investment in human capital refers to", choices=[
   "buying machinery",
   "spending on education, training, and health that raises workers' productivity",
   "purchasing shares",
   "government borrowing",
   "building factories"], ans=1,
   why="Human capital is productive capacity embodied in people."),
 dict(q="A command economy answers the basic economic questions primarily through", choices=[
   "market prices",
   "central government planning",
   "tradition",
   "individual firms competing",
   "international trade"], ans=1,
   why="Planners decide what is produced and how it is distributed."),
 dict(q="A market economy answers the basic economic questions primarily through", choices=[
   "government directives",
   "the decentralized decisions of buyers and sellers responding to prices",
   "custom",
   "central planning",
   "a single firm"], ans=1,
   why="Prices coordinate decisions without central direction."),
 dict(q="A mixed economy is one in which", choices=[
   "only markets operate",
   "markets allocate most resources but government also plays a significant role",
   "only government allocates resources",
   "no trade occurs",
   "prices do not exist"], ans=1,
   why="Almost every real economy is mixed."),
 dict(q="Prices in a market economy serve mainly to", choices=[
   "raise government revenue",
   "convey information and provide incentives that coordinate the decisions of buyers and sellers",
   "eliminate scarcity",
   "guarantee equality",
   "increase production costs"], ans=1,
   why="A price signals relative scarcity and rewards those who respond to it."),
 dict(q="The circular flow model shows that households", choices=[
   "only buy goods",
   "supply factors of production to firms and buy goods and services from them",
   "produce all goods",
   "pay no taxes",
   "have no income"], ans=1,
   why="Households are suppliers in factor markets and buyers in product markets."),
 dict(q="In the circular flow model, firms", choices=[
   "supply labor",
   "buy factors of production from households and sell goods and services to them",
   "pay no wages",
   "receive no revenue",
   "only save"], ans=1,
   why="Firms are buyers in factor markets and sellers in product markets."),
 dict(q="Which of the following would reduce the scarcity problem facing an economy?", choices=[
   "an increase in population with no change in resources",
   "a technological improvement that raises output from the same resources",
   "a fall in the capital stock",
   "a natural disaster",
   "a decrease in the labor force"], ans=1,
   why="Better technology stretches the same resources further."),
 dict(q="Which of the following would worsen the scarcity problem?", choices=[
   "discovery of a new oil field",
   "the destruction of a large part of the capital stock by an earthquake",
   "improved education",
   "new technology",
   "an increase in the labor force"], ans=1,
   why="Fewer resources means less can be produced."),
 dict(q="Economists assume individuals are rational, meaning they", choices=[
   "never make mistakes",
   "systematically do the best they can to achieve their objectives given the information available",
   "care only about money",
   "always agree with each other",
   "ignore incentives"], ans=1,
   why="Rationality here is purposeful behavior, not perfection."),
 dict(q="The economic way of thinking emphasizes that", choices=[
   "everything is free",
   "choices have costs and people respond to incentives",
   "government always knows best",
   "markets never work",
   "scarcity can be eliminated"], ans=1,
   why="These are the two organizing ideas of the discipline."),
 dict(q="A country that fully employs its resources is", choices=[
   "free of scarcity",
   "still constrained by scarcity, since it must choose among alternative uses",
   "producing infinite output",
   "necessarily wealthy",
   "unable to grow"], ans=1,
   why="Full employment removes waste but not the need to choose."),
 dict(q="Which of the following is the best example of a capital good?", choices=[
   "a loaf of bread bought by a household",
   "a delivery van bought by a bakery",
   "money in a savings account",
   "a share of stock",
   "a worker's wage"], ans=1,
   why="It is a produced good used to make other goods."),
 dict(q="Which of the following is the best example of a consumer good?", choices=[
   "an industrial oven in a factory",
   "a jacket bought by a household to wear",
   "a construction crane",
   "a delivery truck",
   "a factory building"], ans=1,
   why="It is bought for final use rather than to produce something else."),
 dict(q="The fundamental economic problem facing every society is", choices=[
   "inflation", "scarcity", "unemployment", "trade deficits", "government debt"], ans=1,
   why="Every other economic question follows from limited resources meeting unlimited wants."),
 dict(q="An economy that chooses to produce more capital goods and fewer consumer goods today is likely to", choices=[
   "have lower future output",
   "grow faster in the future at the cost of less consumption now",
   "eliminate scarcity",
   "reduce productivity",
   "experience no trade-off"], ans=1,
   why="Investment sacrifices present consumption for future capacity."),
]
