# MACRO 2.7 Business Cycles — 50 questions
# Arithmetic verified (output gaps; no data table required for this topic):
#   Output gap = actual real GDP - potential real GDP
#     actual 19.0 tn, potential 20.0 tn -> gap = -1.0 tn (recessionary),
#       as a percent of potential: -1.0/20.0 = -5.0%
#     actual 21.0 tn, potential 20.0 tn -> gap = +1.0 tn (inflationary), +5.0%
#     actual 950 bn, potential 1,000 bn -> gap = -50 bn = -5.0%
#   Okun's-rule illustration used in one item: cyclical unemployment =
#     actual rate - natural rate; 8% - 5% = 3 percentage points.
#   Peak-to-trough example: real GDP falls from 500 to 470
#     = (470 - 500)/500 = -6.0% decline over the contraction.
TOPIC = ("2.7", "Business Cycles", 2)

QUESTIONS = [
 dict(q="The business cycle refers to", choices=[
   "the seasonal pattern of retail sales",
   "the short-run fluctuations of real GDP around its long-run growth trend",
   "the steady long-run growth of potential output",
   "the annual budget process",
   "the life cycle of a firm"], ans=1,
   why="Business cycles are the irregular ups and downs of actual output relative to trend."),
 dict(q="The four phases of the business cycle, in order, are", choices=[
   "peak, expansion, trough, contraction",
   "expansion, peak, contraction, trough",
   "trough, contraction, peak, expansion",
   "contraction, trough, peak, expansion",
   "peak, trough, peak, trough"], ans=1,
   why="Output rises to a peak, falls through a contraction to a trough, and then expands again."),
 dict(q="During an expansion, real GDP", choices=[
   "falls and unemployment rises",
   "rises and unemployment falls",
   "is constant while prices fall",
   "falls while inflation accelerates",
   "rises while unemployment also rises"], ans=1,
   why="Growing output requires more labor, which pulls the unemployment rate down."),
 dict(q="During a contraction, one would expect", choices=[
   "rising real GDP and falling unemployment",
   "falling real GDP and rising unemployment",
   "constant output and constant unemployment",
   "rising output and rising inflation",
   "falling prices and falling unemployment"], ans=1,
   why="Less production means fewer workers are needed."),
 dict(q="The peak of the business cycle is the point at which", choices=[
   "real GDP reaches its lowest point",
   "real GDP reaches its highest point before beginning to decline",
   "unemployment is highest",
   "inflation is lowest",
   "potential output is reached exactly"], ans=1,
   why="A peak marks the turning point from expansion to contraction."),
 dict(q="The trough of the business cycle is the point at which", choices=[
   "real GDP reaches its highest point",
   "real GDP reaches its lowest point before beginning to recover",
   "unemployment is lowest",
   "inflation is highest",
   "potential output is highest"], ans=1,
   why="A trough marks the turning point from contraction to expansion."),
 dict(q="At a business cycle peak, one would expect unemployment to be", choices=[
   "at its highest for the cycle",
   "at or near its lowest for the cycle",
   "exactly equal to zero",
   "equal to the natural rate by definition",
   "rising rapidly"], ans=1,
   why="Output and employment are at their cyclical high point."),
 dict(q="At a business cycle trough, one would expect unemployment to be", choices=[
   "at its lowest for the cycle",
   "at or near its highest for the cycle",
   "zero",
   "below the natural rate",
   "falling rapidly"], ans=1,
   why="Output is at its cyclical low, so cyclical unemployment is at its greatest."),
 dict(q="Inflationary pressure is generally strongest", choices=[
   "at the trough",
   "near the peak of an expansion, when the economy is straining against its capacity",
   "during a deep contraction",
   "when unemployment is highest",
   "when real GDP is far below potential"], ans=1,
   why="Tight labor and product markets bid up wages and prices."),
 dict(q="A recession is commonly defined as", choices=[
   "any fall in nominal GDP",
   "a significant decline in economic activity spread across the economy, conventionally at least two consecutive quarters of falling real GDP",
   "an unemployment rate above 5%",
   "any quarter of below-average growth",
   "a fall in the price level"], ans=1,
   why="The rule of thumb is two consecutive quarters of declining real GDP, alongside broader measures of activity."),
 dict(q="A depression differs from a recession in that a depression is", choices=[
   "shorter and milder",
   "unusually deep and prolonged",
   "defined by falling prices only",
   "always accompanied by full employment",
   "a period of rising output"], ans=1,
   why="It is a difference of severity and duration, not of kind."),
 dict(q="Potential output (full-employment output) is", choices=[
   "the maximum output physically possible with unlimited overtime",
   "the level of real GDP an economy produces when unemployment is at its natural rate",
   "the level of nominal GDP at the peak",
   "always equal to actual output",
   "the level of output at the trough"], ans=1,
   why="Potential output corresponds to full employment, meaning zero cyclical unemployment."),
 dict(q="The output gap is defined as", choices=[
   "potential GDP minus nominal GDP",
   "actual real GDP minus potential real GDP",
   "real GDP minus nominal GDP",
   "the difference between the CPI and the deflator",
   "the change in real GDP from year to year"], ans=1,
   why="A negative gap means the economy is producing below its capacity."),
 dict(q="A recessionary gap exists when", choices=[
   "actual real GDP exceeds potential real GDP",
   "actual real GDP is below potential real GDP",
   "the price level is falling",
   "unemployment equals the natural rate",
   "inflation is above target"], ans=1,
   why="Output below potential leaves resources idle and unemployment above the natural rate."),
 dict(q="An inflationary gap exists when", choices=[
   "actual real GDP is below potential real GDP",
   "actual real GDP exceeds potential real GDP",
   "unemployment exceeds the natural rate",
   "the price level is constant",
   "the output gap is zero"], ans=1,
   why="Producing beyond the sustainable level puts upward pressure on wages and prices."),
 dict(q="If actual real GDP is $19 trillion and potential real GDP is $20 trillion, the output gap is", choices=[
   "-$2 trillion", "-$1 trillion", "$0", "+$1 trillion", "+$2 trillion"], ans=1,
   why="19 − 20 = −1 trillion, a recessionary gap."),
 dict(q="If actual real GDP is $21 trillion and potential real GDP is $20 trillion, the economy has", choices=[
   "a recessionary gap of $1 trillion",
   "an inflationary gap of $1 trillion",
   "no output gap",
   "a recessionary gap of $41 trillion",
   "an inflationary gap of $21 trillion"], ans=1,
   why="Actual output exceeds potential by $1 trillion."),
 dict(q="If actual real GDP is $950 billion and potential is $1,000 billion, the output gap as a percentage of potential output is", choices=[
   "-10.0%", "-5.3%", "-5.0%", "+5.0%", "+10.0%"], ans=2,
   why="−$50 billion ÷ $1,000 billion = −5.0%."),
 dict(q="During a recessionary gap, one would expect unemployment to be", choices=[
   "below the natural rate",
   "above the natural rate, with positive cyclical unemployment",
   "exactly at the natural rate",
   "zero",
   "unrelated to the gap"], ans=1,
   why="Idle capacity means workers who would be employed at potential output are not."),
 dict(q="During an inflationary gap, one would expect unemployment to be", choices=[
   "above the natural rate",
   "below the natural rate",
   "exactly at the natural rate",
   "rising steadily",
   "at its cyclical maximum"], ans=1,
   why="Firms producing beyond the sustainable level are hiring intensively."),
 dict(q="If the actual unemployment rate is 8% and the natural rate is 5%, the economy most likely has", choices=[
   "an inflationary gap",
   "a recessionary gap and 3 percentage points of cyclical unemployment",
   "no output gap",
   "zero structural unemployment",
   "output above potential"], ans=1,
   why="Unemployment above the natural rate corresponds to output below potential."),
 dict(q="Leading economic indicators are variables that", choices=[
   "change after the economy has already turned",
   "tend to change before the overall economy does, and so help forecast turning points",
   "change at the same time as GDP",
   "never change",
   "measure only the price level"], ans=1,
   why="Their value is that they move ahead of the cycle."),
 dict(q="Which of the following is a leading indicator?", choices=[
   "the unemployment rate",
   "new building permits issued",
   "real GDP",
   "the average duration of unemployment",
   "corporate profits for the past quarter"], ans=1,
   why="Permits are pulled today for construction that will occur months from now."),
 dict(q="Which of the following is a lagging indicator?", choices=[
   "stock prices",
   "the average duration of unemployment",
   "new orders for consumer goods",
   "consumer expectations",
   "initial claims for unemployment insurance"], ans=1,
   why="How long people have been unemployed keeps rising for a while after the recovery has begun."),
 dict(q="Which of the following is a coincident indicator?", choices=[
   "building permits",
   "industrial production",
   "the prime rate charged by banks",
   "consumer confidence about the future",
   "the average duration of unemployment"], ans=1,
   why="Industrial production moves essentially in step with the overall economy."),
 dict(q="A sharp rise in initial claims for unemployment insurance is best interpreted as", choices=[
   "a lagging sign that a recovery has ended",
   "a leading signal that the economy may be weakening",
   "evidence of an inflationary gap",
   "a sign of rising potential output",
   "unrelated to the business cycle"], ans=1,
   why="Layoffs show up in claims before they show up in quarterly GDP data."),
 dict(q="The unemployment rate is usually described as a lagging indicator because", choices=[
   "it is measured only annually",
   "firms tend to delay both layoffs and rehiring until they are confident a downturn or recovery is real",
   "it is unrelated to output",
   "it is measured with no error",
   "it always falls before GDP rises"], ans=1,
   why="Hiring and firing decisions respond to output changes with a lag."),
 dict(q="A jobless recovery describes a period in which", choices=[
   "unemployment falls faster than output rises",
   "real GDP grows but employment remains weak for a time",
   "output falls while employment rises",
   "both output and employment fall",
   "prices fall while output rises"], ans=1,
   why="Firms can raise output initially through longer hours and higher productivity before hiring."),
 dict(q="Business cycles are best described as", choices=[
   "perfectly regular in length and depth",
   "recurrent but irregular in both duration and severity",
   "occurring exactly every four years",
   "caused only by government policy",
   "identical in every country"], ans=1,
   why="The pattern of expansion and contraction repeats, but no two cycles are alike."),
 dict(q="Long-run economic growth is best represented by", choices=[
   "the amplitude of the business cycle",
   "an upward trend in potential output over time",
   "the movement from peak to trough",
   "an increase in the price level",
   "an increase in nominal GDP"], ans=1,
   why="Growth shifts the trend line up, while the cycle is movement around that trend."),
 dict(q="Which of the following would raise potential output rather than simply close a recessionary gap?", choices=[
   "an increase in consumer spending",
   "an increase in the capital stock and improvements in technology",
   "a temporary tax rebate",
   "an increase in government purchases during a recession",
   "a fall in the saving rate"], ans=1,
   why="Potential output depends on the quantity and productivity of resources, not on the level of demand."),
 dict(q="During a contraction, business inventories typically", choices=[
   "fall immediately as firms cut production instantly",
   "rise unintentionally at first as sales fall faster than firms adjust production",
   "remain exactly constant",
   "rise because firms deliberately expand production",
   "become negative"], ans=1,
   why="Unplanned inventory accumulation is one of the earliest signals that demand has weakened."),
 dict(q="An unplanned buildup of inventories usually signals that firms will soon", choices=[
   "raise prices sharply", "cut production and employment", "expand capacity", "increase exports", "raise wages"], ans=1,
   why="Goods piling up unsold tell firms they are producing more than the market wants."),
 dict(q="Which sector's spending is typically most volatile over the business cycle?", choices=[
   "government purchases",
   "investment and purchases of consumer durables",
   "spending on food and other nondurables",
   "spending on medical services",
   "transfer payments"], ans=1,
   why="Purchases that can be postponed swing far more than everyday necessities."),
 dict(q="Spending on nondurable goods and services is comparatively stable over the cycle because", choices=[
   "it is legally fixed",
   "these purchases are difficult to postpone",
   "they are all imported",
   "the government provides them",
   "their prices never change"], ans=1,
   why="People keep eating and heating their homes even in a downturn."),
 dict(q="Cyclical unemployment is zero when", choices=[
   "the unemployment rate is zero",
   "actual output equals potential output",
   "the economy is at a peak above potential",
   "inflation is zero",
   "the output gap is negative"], ans=1,
   why="At potential output, only frictional and structural unemployment remain."),
 dict(q="An economy at a business cycle peak with an inflationary gap would most likely call for", choices=[
   "expansionary policy",
   "contractionary policy to slow aggregate demand",
   "no policy response of any kind",
   "an increase in transfer payments",
   "a cut in interest rates"], ans=1,
   why="Demand is running ahead of capacity, so the appropriate response restrains it."),
 dict(q="An economy in a deep recessionary gap would most likely call for", choices=[
   "contractionary policy",
   "expansionary policy to raise aggregate demand",
   "a reduction in government spending",
   "an increase in the reserve requirement",
   "higher interest rates"], ans=1,
   why="Idle resources call for policy that raises spending."),
 dict(q="Automatic stabilizers such as progressive income taxes and unemployment benefits", choices=[
   "amplify the business cycle",
   "moderate the business cycle without any new legislation",
   "have no effect on output",
   "operate only during expansions",
   "raise potential output"], ans=1,
   why="Taxes fall and transfers rise in a downturn, cushioning the fall in spending automatically."),
 dict(q="Real GDP falls from $500 billion at a peak to $470 billion at the trough. The contraction amounted to", choices=[
   "-6.4%", "-6.0%", "-3.0%", "+6.0%", "+6.4%"], ans=1,
   why="($470 − $500)/$500 = −0.06."),
 dict(q="An economy grows at 3% a year for five years and then contracts for two quarters. Over the whole period, the economy has experienced", choices=[
   "no business cycle",
   "an expansion followed by a contraction, which is one phase sequence of a business cycle",
   "a depression",
   "a permanent fall in potential output",
   "stagflation"], ans=1,
   why="Expansion and contraction are the two main phases, with the peak between them."),
 dict(q="Which combination best characterizes an economy just past a business cycle trough?", choices=[
   "output falling, unemployment falling",
   "output beginning to rise while unemployment is still high",
   "output rising and unemployment already at its lowest",
   "output falling and inflation accelerating",
   "output at potential with zero cyclical unemployment"], ans=1,
   why="Employment recovers with a lag, so early recovery combines rising output with still-elevated joblessness."),
 dict(q="Stagflation describes the unusual combination of", choices=[
   "falling output with falling prices",
   "stagnant or falling output together with rising inflation",
   "rising output with falling prices",
   "rising output with rising employment",
   "zero inflation with zero unemployment"], ans=1,
   why="It is unusual because a normal contraction reduces inflationary pressure rather than raising it."),
 dict(q="A negative supply shock, such as a sharp rise in oil prices, tends to produce", choices=[
   "lower unemployment and lower inflation",
   "higher unemployment together with higher inflation",
   "higher output and lower prices",
   "no change in either variable",
   "a rise in potential output"], ans=1,
   why="Higher input costs reduce output while pushing the price level up."),
 dict(q="If the output gap is positive and unemployment is below the natural rate, the most likely near-term development is", choices=[
   "falling prices",
   "rising wages and prices as labor markets tighten",
   "a rise in cyclical unemployment",
   "a fall in potential output",
   "a stable price level"], ans=1,
   why="Competition for scarce workers bids up wages, which feed into prices."),
 dict(q="The National Bureau of Economic Research dates U.S. recessions using", choices=[
   "the two-consecutive-quarters rule alone",
   "a broad set of indicators including employment, income, production, and sales",
   "the unemployment rate alone",
   "the stock market",
   "the inflation rate"], ans=1,
   why="The official dating committee looks at the depth, diffusion, and duration of a decline across many series."),
 dict(q="Which of the following would tend to reduce the amplitude of business cycles?", choices=[
   "removing unemployment insurance",
   "well-designed automatic stabilizers and countercyclical monetary policy",
   "a flat tax with no transfers",
   "procyclical government spending",
   "eliminating the central bank"], ans=1,
   why="Policies that lean against the cycle damp its swings; procyclical policy would enlarge them."),
 dict(q="A country's real GDP is growing, but growth has slowed from 4% to 1% a year. This is best described as", choices=[
   "a recession", "a slowing expansion", "a depression", "a trough", "deflation"], ans=1,
   why="Output is still rising, so the economy is expanding, only more slowly than before."),
 dict(q="Which of the following is the strongest evidence that an economy has entered a contraction rather than merely slowing?", choices=[
   "a fall in the growth rate of real GDP from 3% to 2%",
   "declines in real GDP, employment, and industrial production sustained over several months",
   "a fall in stock prices for one week",
   "a rise in the price of oil",
   "an increase in the trade deficit"], ans=1,
   why="A contraction is a broad and sustained decline in the level of activity, not a slower rate of increase."),
 dict(q="A student says that because real GDP grew this quarter, there can be no recessionary gap. The best correction is that", choices=[
   "growth always eliminates gaps",
   "output can grow while still remaining well below potential, so a recessionary gap can persist through several quarters of growth",
   "recessionary gaps require negative nominal GDP",
   "potential output falls whenever GDP grows",
   "gaps are measured only at the peak"], ans=1,
   why="The gap compares the level of output with potential, while growth describes the change in that level."),
]
