# MACRO 3.1 Aggregate Demand — 50 questions
# No numeric table in this module. The only arithmetic appears in single-question
# stems and is worked out here:
#   AD components: C = 8000, I = 2000, G = 3000, X = 900, M = 1400
#     net exports = 900 - 1400 = -500; AD = 8000 + 2000 + 3000 - 500 = 12500  (used q40)
#   Second set: C = 6.0, I = 1.5, G = 2.0, NX = -0.5 (trillions) -> 9.0        (used q41)
#   Consumption share: C = 8000 of 12500 -> 8000/12500 = 0.64 = 64%           (used q42)
TOPIC = ('3.1', 'Aggregate Demand', 3)
QUESTIONS = [
 dict(q='The aggregate demand curve shows the relationship between', choices=[
   'the price of a single good and the quantity of that good demanded',
   'the aggregate price level and the quantity of real GDP demanded',
   'the interest rate and the quantity of money demanded',
   'the wage rate and the quantity of labor demanded',
   'national income and the level of saving'], ans=1,
   why="Aggregate demand plots total real output demanded against the overall price level, not a single good's price against its own quantity."),
 dict(q='The aggregate demand curve slopes downward because of', choices=[
   'the wealth effect, the interest rate effect, and the exchange rate effect',
   'the substitution effect between two goods',
   'diminishing marginal returns in production',
   "the income effect on a single household's budget",
   'diminishing marginal utility'], ans=0,
   why='Three economy-wide effects, not the microeconomic substitution and income effects, produce the downward slope of AD.'),
 dict(q='A microeconomic demand curve for one good slopes downward partly because buyers substitute toward other goods. This reasoning does not explain the slope of aggregate demand because', choices=[
   'aggregate demand has no substitutes at any price',
   'consumers behave irrationally in the aggregate',
   'the aggregate price level never changes',
   'aggregate demand is measured in nominal terms',
   'when the aggregate price level changes, the prices of all domestically produced goods move together, so there is no domestic substitute to switch to'], ans=4,
   why='Substitution between goods requires relative prices to change; a change in the overall price level moves domestic prices together, so the AD slope must come from other channels.'),
 dict(q='The wealth effect, also called the real balances effect, says that a higher price level', choices=[
   'leaves consumption unchanged',
   'reduces the interest rate',
   'raises the purchasing power of money held by households',
   "reduces the real value of households' money holdings, so they consume less",
   'increases household nominal wealth and so raises consumption'], ans=3,
   why='A higher price level erodes the real value of a fixed stock of money and other nominal assets, cutting real consumption spending.'),
 dict(q='The interest rate effect explains that a higher price level', choices=[
   'raises investment spending',
   'reduces the demand for money and lowers interest rates',
   'raises the demand for money, which pushes interest rates up and reduces investment and interest-sensitive consumption',
   'raises the money supply',
   'has no effect on borrowing'], ans=2,
   why='Higher prices raise the nominal amount of money people need for transactions; that raises interest rates and chokes off interest-sensitive spending.'),
 dict(q='The exchange rate effect, sometimes called the net exports effect, says that a higher domestic price level', choices=[
   'makes domestic goods cheaper relative to foreign goods',
   'makes domestic goods relatively more expensive, reducing exports and raising imports, so net exports fall',
   'raises net exports',
   'has no effect on trade',
   'raises the value of foreign currency'], ans=1,
   why='When domestic prices rise relative to foreign prices, foreigners buy fewer of our goods and domestic buyers buy more foreign goods.'),
 dict(q='Which effect explains the downward slope of aggregate demand through changes in the real value of money balances held by households?', choices=[
   'the wealth effect',
   'the exchange rate effect',
   'the multiplier effect',
   'the crowding-out effect',
   'the interest rate effect'], ans=0,
   why='The wealth or real balances effect works through the purchasing power of nominal assets.'),
 dict(q='Which effect explains the downward slope of aggregate demand through changes in the cost of borrowing?', choices=[
   'the exchange rate effect',
   'the substitution effect',
   'the income effect',
   'the wealth effect',
   'the interest rate effect'], ans=4,
   why='A higher price level raises money demand and therefore interest rates, reducing investment.'),
 dict(q='Which effect explains the downward slope of aggregate demand through changes in the relative price of domestic and foreign goods?', choices=[
   'the crowding-out effect',
   'the wage effect',
   'the wealth effect',
   'the exchange rate effect',
   'the interest rate effect'], ans=3,
   why='The exchange rate or net exports effect operates on the trade balance.'),
 dict(q='The components of aggregate demand are', choices=[
   'saving, taxes, imports, and transfers',
   'wages, rent, interest, and profit',
   'consumption, investment, government purchases, and net exports',
   'money, bonds, capital, and labor',
   'land, labor, capital, and entrepreneurship'], ans=2,
   why='AD is C + I + G + (X − M), the same expenditure categories used to compute GDP.'),
 dict(q='In the expression C + I + G + (X − M), the term I refers to', choices=[
   'household purchases of stocks and bonds',
   'business spending on capital goods, new residential construction, and changes in inventories',
   'government infrastructure spending',
   'interest paid on the national debt',
   'imports'], ans=1,
   why='Investment in the national accounts means real capital formation, not the purchase of financial assets.'),
 dict(q='A rise in the aggregate price level, holding everything else constant, causes', choices=[
   'a movement upward along the existing aggregate demand curve',
   'a rightward shift of aggregate demand',
   'a shift of short-run aggregate supply',
   'no change in the quantity of output demanded',
   'a leftward shift of aggregate demand'], ans=0,
   why='A change in the price level itself moves the economy along AD; only other variables shift the curve.'),
 dict(q='An increase in consumer confidence about future income will', choices=[
   'cause a movement along aggregate demand',
   'shift long-run aggregate supply left',
   'leave aggregate demand unchanged',
   'shift aggregate demand left',
   'shift aggregate demand right'], ans=4,
   why='Optimistic households consume more at every price level, which shifts the whole curve right.'),
 dict(q='A sharp fall in stock and housing prices would most likely', choices=[
   'shift long-run aggregate supply right',
   'raise net exports',
   'shift aggregate demand right because assets are cheaper',
   'shift aggregate demand left as households feel poorer and cut consumption',
   'cause a movement along aggregate demand'], ans=3,
   why='Lost wealth reduces consumption at every price level, which is a leftward shift rather than a movement along the curve.'),
 dict(q='An increase in personal income taxes will, other things equal,', choices=[
   'raise investment spending',
   'shift aggregate demand right',
   'shift aggregate demand left by reducing disposable income and consumption',
   'shift short-run aggregate supply right',
   'cause a movement along aggregate demand'], ans=2,
   why='Less disposable income means less consumption at every price level.'),
 dict(q='Which of the following would shift aggregate demand to the right?', choices=[
   'an increase in the personal income tax rate',
   'an increase in government spending on infrastructure',
   'a fall in consumer confidence',
   'an increase in the real interest rate',
   'an appreciation of the domestic currency'], ans=1,
   why='Government purchases are a direct component of aggregate demand.'),
 dict(q='Which of the following would shift aggregate demand to the left?', choices=[
   'a decrease in business confidence about future sales',
   'a cut in interest rates',
   'an increase in exports',
   'a depreciation of the domestic currency',
   'an increase in transfer payments'], ans=0,
   why='Pessimistic firms invest less at every price level, reducing aggregate demand.'),
 dict(q='A decrease in the real interest rate is most likely to', choices=[
   'cause a movement along aggregate demand',
   'shift long-run aggregate supply left',
   'have no effect on spending',
   'shift aggregate demand left',
   'shift aggregate demand right by encouraging investment and interest-sensitive consumption'], ans=4,
   why='Cheaper borrowing raises investment and durable-goods purchases at every price level.'),
 dict(q='An appreciation of the domestic currency, other things equal, will', choices=[
   'shift short-run aggregate supply left',
   'raise consumption',
   'shift aggregate demand right',
   'shift aggregate demand left by making exports more expensive abroad and imports cheaper at home',
   'leave net exports unchanged'], ans=3,
   why='A stronger currency reduces exports and raises imports, so net exports and aggregate demand fall.'),
 dict(q="A recession among a country's major trading partners would most likely", choices=[
   "raise the country's net exports",
   "raise the country's exports and shift AD right",
   "reduce the country's exports and shift AD left",
   "cause a movement along the country's AD curve",
   "shift the country's LRAS left"], ans=2,
   why='Foreign incomes drive foreign demand for our exports, so a foreign recession cuts our net exports.'),
 dict(q='An increase in the money supply that lowers interest rates will', choices=[
   'shift aggregate demand left',
   'shift aggregate demand right',
   'move the economy along aggregate demand',
   'shift long-run aggregate supply left',
   'reduce investment'], ans=1,
   why='Lower interest rates raise investment and interest-sensitive consumption at every price level.'),
 dict(q='Which of the following shifts aggregate demand right through the investment component?', choices=[
   'an investment tax credit for firms buying new equipment',
   'an increase in personal income taxes',
   'an appreciation of the currency',
   'a fall in household wealth',
   'an increase in unemployment benefits'], ans=0,
   why='A tax credit lowers the effective cost of capital goods and raises planned investment.'),
 dict(q='An increase in government transfer payments such as unemployment insurance affects aggregate demand', choices=[
   'not at all',
   'only through net exports',
   'only through investment',
   'directly, because transfers are part of government purchases',
   'indirectly, because transfers raise disposable income and therefore consumption'], ans=4,
   why='Transfers are not purchases of goods and services; they enter aggregate demand only when recipients spend them.'),
 dict(q='If households decide to save a larger fraction of their income, aggregate demand will', choices=[
   'become vertical',
   'become horizontal',
   'shift right',
   'shift left as consumption falls at every price level',
   'not shift'], ans=3,
   why='Saving more out of a given income means spending less, which reduces consumption.'),
 dict(q='Expectations of higher inflation in the near future are most likely to', choices=[
   'cause a movement along aggregate demand',
   'shift aggregate demand left as households postpone purchases',
   'shift aggregate demand right as households buy now to beat expected price increases',
   'have no effect on current spending',
   'shift long-run aggregate supply right'], ans=2,
   why='Expecting prices to rise gives households a reason to move purchases forward, raising current spending.'),
 dict(q='Which of the following causes a movement along the aggregate demand curve rather than a shift of it?', choices=[
   'an increase in government spending',
   'a change in the aggregate price level',
   'a tax cut',
   'an increase in consumer confidence',
   'a rise in exports'], ans=1,
   why='Only the price level, the variable on the vertical axis, produces a movement along the curve.'),
 dict(q='A large increase in immigration that raises the number of consumers in an economy would', choices=[
   'shift aggregate demand right and also shift long-run aggregate supply right',
   'shift aggregate demand right but leave aggregate supply unaffected',
   'have no effect on either curve',
   'shift short-run aggregate supply left',
   'shift aggregate demand left only'], ans=0,
   why='More people means both more spending and a larger labor force, so both curves shift right.'),
 dict(q='If the government raises spending and raises taxes by the same amount, aggregate demand will', choices=[
   'not change at all',
   'become vertical',
   'shift left by the amount of the tax',
   'fall, because taxes reduce disposable income',
   'rise, because government spending enters aggregate demand fully while the tax reduces spending only by the fraction households would have consumed'], ans=4,
   why='The spending injection is dollar for dollar while the tax withdrawal is only MPC times the tax, leaving a net increase.'),
 dict(q='Aggregate demand is measured on the horizontal axis in units of', choices=[
   'the money supply',
   'the unemployment rate',
   'nominal GDP',
   'real GDP',
   'the price level'], ans=3,
   why='The AD-AS diagram plots real output against the price level, so real GDP is the horizontal variable.'),
 dict(q='Which statement about the aggregate demand curve is correct?', choices=[
   'It slopes upward when the money supply increases.',
   'It slopes downward because of the substitution effect between domestic goods.',
   'It slopes downward because a higher price level reduces real wealth, raises interest rates, and worsens net exports.',
   'It slopes downward because production costs rise with output.',
   'It is vertical in the long run.'], ans=2,
   why='The three named channels are the standard AP explanation of the downward slope.'),
 dict(q='Suppose the price level falls. The interest rate effect predicts that', choices=[
   'money demand rises and interest rates rise',
   'money demand falls, interest rates fall, and investment spending increases',
   'money demand is unaffected',
   'investment falls',
   'net exports fall'], ans=1,
   why='With lower prices people need less money for transactions, so interest rates fall and interest-sensitive spending rises.'),
 dict(q='Consumers hold a fixed amount of currency and bank deposits. If the price level doubles, the real value of those holdings', choices=[
   'is cut in half, which reduces real consumption spending',
   'is unchanged',
   'rises by the inflation rate',
   'becomes zero',
   'doubles'], ans=0,
   why='Real balances equal nominal money divided by the price level, so doubling prices halves purchasing power.'),
 dict(q='An increase in the expected future profitability of new capital projects would', choices=[
   'affect only aggregate supply',
   'cause a movement along AD',
   'reduce consumption',
   'reduce investment and shift AD left',
   'raise investment and shift AD right'], ans=4,
   why='Firms invest when they expect the returns to justify the cost, so brighter expectations raise investment demand.'),
 dict(q='Which combination would unambiguously shift aggregate demand to the right?', choices=[
   'lower exports and lower consumer confidence',
   'currency appreciation and reduced investment',
   'higher taxes and lower government spending',
   'lower taxes and higher government spending',
   'higher taxes and higher interest rates'], ans=3,
   why='Both a tax cut and a spending increase raise total planned expenditure.'),
 dict(q='Which combination would leave the direction of the shift in aggregate demand indeterminate?', choices=[
   'a rise in transfers and a fall in interest rates',
   'an increase in government spending and a cut in taxes',
   'an increase in government spending and a currency appreciation',
   'a fall in consumer confidence and a rise in taxes',
   'a fall in exports and a fall in investment'], ans=2,
   why='More government purchases pushes AD right while a stronger currency pushes it left, so the net effect depends on the relative sizes.'),
 dict(q='A decrease in aggregate demand is best described as', choices=[
   'less real output demanded at every price level',
   'a higher price level with the same output',
   'a movement down along the AD curve',
   'a leftward shift of short-run aggregate supply',
   'a fall in the price of one good'], ans=0,
   why='A shift means the quantity of real GDP demanded changes at every possible price level.'),
 dict(q='Net exports are most likely to increase if', choices=[
   "incomes rise sharply among a country's trading partners",
   'domestic incomes rise sharply',
   'domestic inflation exceeds foreign inflation',
   'foreign economies enter a recession',
   'the domestic currency appreciates'], ans=0,
   why='Richer foreign customers buy more of our exports, raising net exports and aggregate demand.'),
 dict(q='Government purchases of goods and services differ from transfer payments in that government purchases', choices=[
   'are larger than transfers in every economy',
   'reduce disposable income',
   'are financed only by borrowing',
   'have no effect on aggregate demand',
   'directly buy output and so add to aggregate demand dollar for dollar'], ans=4,
   why='A purchase is itself spending on output, whereas a transfer only shifts income that recipients may or may not spend.'),
 dict(q='Which of the following would NOT shift the aggregate demand curve?', choices=[
   'a change in foreign income',
   'a change in government spending',
   'a change in consumer confidence',
   'a change in the aggregate price level',
   'a change in the real interest rate'], ans=3,
   why='The price level is the axis variable, so changing it moves the economy along AD rather than shifting it.'),
 dict(q='In an economy consumption is $8,000 billion, investment is $2,000 billion, government purchases are $3,000 billion, exports are $900 billion, and imports are $1,400 billion. Aggregate expenditure, in billions of dollars, equals', choices=[
   '$12,000',
   '$12,500',
   '$13,000',
   '$13,900',
   '$15,300'], ans=1,
   why='Net exports are 900 − 1,400 = −500, so total spending is 8,000 + 2,000 + 3,000 − 500 = 12,500.'),
 dict(q='An economy has consumption of $6.0 trillion, investment of $1.5 trillion, government purchases of $2.0 trillion, and net exports of −$0.5 trillion. Real GDP demanded, in trillions of dollars, equals', choices=[
   '$8.0',
   '$9.0',
   '$9.5',
   '$10.0',
   '$10.5'], ans=1,
   why='Adding the components gives 6.0 + 1.5 + 2.0 − 0.5 = 9.0 trillion.'),
 dict(q="If aggregate expenditure is $12,500 billion and consumption is $8,000 billion, consumption's share of total spending is", choices=[
   '36%',
   '56%',
   '64%',
   '72%',
   '80%'], ans=2,
   why='8,000 divided by 12,500 equals 0.64, or 64 percent, which is why consumption dominates aggregate demand.'),
 dict(q='Because consumption is the largest component of aggregate demand, a policy that changes disposable income will', choices=[
   'affect only aggregate supply',
   'have no effect on the price level',
   'shift the AD curve vertically only',
   'have a smaller effect on AD than a change in net exports of the same size',
   'generally have a large effect on aggregate demand'], ans=4,
   why='A change acting on the biggest component of spending moves aggregate demand substantially.'),
 dict(q='A cut in the corporate income tax rate is expected to shift aggregate demand right primarily through', choices=[
   'transfer payments',
   'imports',
   'government purchases',
   'investment spending',
   'net exports'], ans=3,
   why='Lower business taxes raise after-tax returns on capital projects and so raise planned investment.'),
 dict(q='A country experiences a simultaneous rise in household wealth and a fall in exports. Aggregate demand', choices=[
   'becomes vertical',
   'definitely shifts right',
   'shifts in a direction that depends on which effect is larger',
   'definitely shifts left',
   'does not shift'], ans=2,
   why='One force raises consumption and the other lowers net exports, so the net movement is indeterminate without magnitudes.'),
 dict(q='The statement that a lower price level raises the quantity of real GDP demanded because goods become cheaper relative to other goods is', choices=[
   'correct and is the main reason AD slopes down',
   'incorrect, because a change in the overall price level does not change the relative prices of domestic goods',
   'correct only in the long run',
   'correct only for imported goods',
   'the definition of the wealth effect'], ans=1,
   why='Relative-price substitution is a microeconomic argument that does not apply when all domestic prices move together.'),
 dict(q='Which of the following pairs correctly matches an effect with its channel?', choices=[
   'interest rate effect — money demand and the cost of borrowing',
   'exchange rate effect — the real value of money holdings',
   'wealth effect — the relative price of imports',
   'interest rate effect — the purchasing power of savings accounts',
   'wealth effect — the cost of borrowing'], ans=0,
   why='The interest rate effect runs from the price level to money demand to interest rates to investment.'),
 dict(q='A government announces a permanent increase in defense procurement financed by borrowing. In the short run this most directly', choices=[
   'shifts long-run aggregate supply left',
   'causes a movement along aggregate demand',
   'reduces the price level',
   'shifts short-run aggregate supply right',
   'shifts aggregate demand right'], ans=4,
   why='Procurement is a government purchase of output and so is a direct addition to aggregate demand.'),
 dict(q='Suppose the price level rises and, at the same time, foreign incomes rise sharply. The quantity of real GDP demanded', choices=[
   'is unaffected',
   'falls only if the currency appreciates',
   'must fall',
   'reflects a movement up along AD from the price level and a rightward shift from foreign income, so the net change is uncertain',
   'must rise by exactly the increase in exports'], ans=3,
   why='One change moves the economy along the curve while the other shifts it, so the two effects on real GDP demanded work in opposite directions.'),
 dict(q='A sustained increase in household debt payments that leaves less income available for spending will', choices=[
   'have no effect on consumption',
   'shift aggregate demand right',
   'shift aggregate demand left',
   'shift long-run aggregate supply right',
   'cause a movement along aggregate demand'], ans=2,
   why='Money committed to debt service is not available for consumption, so spending falls at every price level.'),
]
