# MACRO 3.3 Short-Run Aggregate Supply — 50 questions
# No table in this module. The only arithmetic in a stem is worked out here:
#   Nominal wage $20/hour, price level index rises from 100 to 125:
#     real wage = 20 x (100/125) = $16 per hour, a fall of $4       (used in the real-wage question)
#   Unit labor cost: wage $30/hour, output 10 units/hour -> $3 per unit;
#     if productivity rises to 15 units/hour -> 30/15 = $2 per unit  (used in the productivity question)
TOPIC = ('3.3', 'Short-Run Aggregate Supply', 3)
QUESTIONS = [
 dict(q='The short-run aggregate supply curve shows the relationship between', choices=[
   'the price of one good and the quantity supplied of that good',
   'the aggregate price level and the quantity of real GDP that firms are willing to produce',
   'the wage rate and employment',
   'the interest rate and investment',
   'real GDP and the unemployment rate'], ans=1,
   why='SRAS relates total real output supplied to the overall price level.'),
 dict(q='The short run in macroeconomics is defined as the period in which', choices=[
   'some input prices, especially nominal wages, are sticky and do not adjust fully to the price level',
   'all prices are perfectly flexible',
   'capital is fixed but labor is variable',
   'the government cannot act',
   'less than one year has passed'], ans=0,
   why='The macro short run is defined by the stickiness of input prices, not by a fixed number of months.'),
 dict(q='The short-run aggregate supply curve slopes upward primarily because', choices=[
   'the money supply grows with output',
   'resources are unlimited in the short run',
   'the government subsidizes production',
   'consumers buy less when prices rise',
   'nominal input costs, especially wages, are sticky, so a higher output price raises profit per unit and firms produce more'], ans=4,
   why='If output prices rise while wages are fixed by contract or convention, producing more becomes more profitable.'),
 dict(q='Sticky wages contribute to an upward-sloping SRAS because', choices=[
   'workers refuse to work at any wage',
   'wages have no effect on costs',
   'wages rise faster than prices',
   'when the price level rises and nominal wages are fixed, the real wage falls and firms expand hiring and output',
   'wages are set by the central bank'], ans=3,
   why='A falling real cost of labor makes additional production profitable, so output rises with the price level.'),
 dict(q='The misperceptions explanation for an upward-sloping SRAS holds that', choices=[
   'workers overestimate their wages',
   'firms always know the aggregate price level exactly',
   'producers may mistake a rise in the general price level for a rise in the relative price of their own product and expand output',
   'consumers misjudge their income',
   'the government misreports inflation'], ans=2,
   why='A producer who thinks the price of their own good has risen relative to others has an incentive to produce more.'),
 dict(q='A nominal wage of $20 per hour is fixed by contract. If the price index rises from 100 to 125, the real wage becomes', choices=[
   '$14',
   '$16',
   '$20',
   '$24',
   '$25'], ans=1,
   why='Dividing by the price level, 20 × (100/125) = $16, so the cost of labor in real terms falls.'),
 dict(q='When the real wage falls because the price level rose faster than nominal wages, firms will', choices=[
   'hire more workers and produce more, which is the movement along SRAS',
   'shut down',
   'raise wages immediately',
   'reduce prices',
   'hire fewer workers and produce less'], ans=0,
   why='Cheaper labor in real terms makes expanding output profitable in the short run.'),
 dict(q='A change in the aggregate price level, with all else constant, causes', choices=[
   'a shift of LRAS',
   'a shift of aggregate demand',
   'no change in output supplied',
   'a shift of SRAS',
   'a movement along the SRAS curve'], ans=4,
   why='The price level is the axis variable, so a change in it moves the economy along the SRAS curve.'),
 dict(q='An increase in nominal wages across the economy will', choices=[
   'shift LRAS right',
   'leave SRAS unchanged',
   'shift SRAS right',
   'shift SRAS left because production costs rise at every price level',
   'cause a movement along SRAS'], ans=3,
   why='Higher per-unit costs mean firms supply less real output at any given price level.'),
 dict(q='A fall in the world price of oil would most likely', choices=[
   'shift aggregate demand left',
   'shift SRAS left',
   'shift SRAS right because a key input cost has fallen',
   'cause a movement along SRAS',
   'shift LRAS left'], ans=2,
   why='Cheaper energy lowers costs at every level of output, which is a rightward shift of short-run supply.'),
 dict(q='Which of the following shifts the short-run aggregate supply curve?', choices=[
   'a change in the aggregate price level',
   'a change in nominal input prices',
   'a change in government spending',
   'a change in consumer confidence',
   'a change in the money supply'], ans=1,
   why='Input prices are a cost variable, so a change in them shifts the whole SRAS curve.'),
 dict(q='An improvement in productivity shifts SRAS', choices=[
   'right, because more output can be produced from the same inputs at lower unit cost',
   'not at all',
   'vertically only',
   'left, because wages rise',
   'left, because output rises'], ans=0,
   why='Higher output per unit of input lowers per-unit production cost and raises the quantity supplied at every price level.'),
 dict(q='A firm pays $30 per labor hour and gets 10 units of output per hour. Its unit labor cost is', choices=[
   '$0.33',
   '$2',
   '$3',
   '$10',
   '$30'], ans=2,
   why='Unit labor cost is the wage divided by output per hour, that is 30/10 = $3.'),
 dict(q='If productivity rises from 10 to 15 units per labor hour with the wage still $30 per hour, unit labor cost', choices=[
   'falls to $0.50',
   'cannot be calculated',
   'rises to $4.50',
   'falls to $2, which shifts SRAS right',
   'stays at $3'], ans=3,
   why='30/15 = $2, so each unit is cheaper to produce and firms supply more at every price level.'),
 dict(q='An increase in the expected rate of inflation, which leads workers to negotiate higher nominal wages, will', choices=[
   'have no effect',
   'shift SRAS right',
   'shift SRAS left',
   'shift LRAS right',
   'cause a movement along SRAS'], ans=2,
   why='Expectations of inflation raise nominal wage demands, and higher wage costs reduce short-run supply.'),
 dict(q='A negative supply shock is best described as', choices=[
   'a fall in aggregate demand',
   'a sudden increase in the cost of a widely used input, such as oil, which shifts SRAS left',
   'a rise in consumer confidence',
   'an increase in the money supply',
   'a fall in taxes'], ans=1,
   why='A supply shock works on production costs, not on spending, and a negative one shifts SRAS left.'),
 dict(q='A positive supply shock, such as a bumper harvest or a technological breakthrough, will', choices=[
   'shift SRAS right, raising output and lowering the price level',
   'shift aggregate demand left',
   'shift LRAS left',
   'leave output unchanged',
   'shift SRAS left and raise prices'], ans=0,
   why='Lower costs increase supply, which pushes output up and the price level down.'),
 dict(q='An increase in business taxes and regulatory compliance costs would', choices=[
   'shift aggregate demand right',
   'cause a movement along SRAS',
   'shift LRAS right',
   'shift SRAS right',
   'shift SRAS left'], ans=4,
   why='Anything that raises the cost of producing a unit of output reduces short-run aggregate supply.'),
 dict(q='A government subsidy to manufacturers that lowers their production costs would', choices=[
   'shift aggregate demand left',
   'make SRAS vertical',
   'shift SRAS left',
   'shift SRAS right',
   'leave SRAS unchanged'], ans=3,
   why='Lower per-unit costs allow more output at every price level.'),
 dict(q='Which of the following would NOT shift the SRAS curve?', choices=[
   'a change in expected inflation',
   'a change in nominal wages',
   'a change in the aggregate price level',
   'a change in the price of imported raw materials',
   'a change in productivity'], ans=2,
   why='A price-level change produces a movement along SRAS, while all the other items change costs.'),
 dict(q='Compared with the long-run aggregate supply curve, the short-run aggregate supply curve is', choices=[
   'vertical',
   'upward sloping, because input prices have not yet fully adjusted',
   'horizontal at all output levels',
   'downward sloping',
   'identical'], ans=1,
   why='Sticky input prices are what give SRAS a positive slope, while LRAS is vertical because all prices eventually adjust.'),
 dict(q='At very low levels of output with substantial unused capacity, the SRAS curve tends to be', choices=[
   'relatively flat, because output can expand with little upward pressure on costs',
   'vertical',
   'downward sloping',
   'undefined',
   'steep, because resources are scarce'], ans=0,
   why='Idle labor and capital can be put to work without bidding up input prices much.'),
 dict(q='As output approaches full employment, the SRAS curve becomes', choices=[
   'horizontal',
   'downward sloping',
   'unchanged in slope',
   'flatter',
   'steeper, because further increases in output require bidding up increasingly scarce resources'], ans=4,
   why='With few idle resources left, expanding output raises input prices sharply and so raises the price level.'),
 dict(q='Sticky wages are often explained by', choices=[
   'perfectly flexible labor markets',
   'the fact that workers change jobs frequently',
   'government price controls on all goods',
   "long-term labor contracts, minimum wage laws, and firms' reluctance to cut nominal pay",
   'the absence of unions'], ans=3,
   why='Institutional and behavioral features of labor markets keep nominal wages from falling quickly.'),
 dict(q='A rise in the price of imported intermediate goods, holding all else constant, will', choices=[
   'have no macroeconomic effect',
   'shift SRAS right and lower the price level',
   'shift SRAS left, reducing output and raising the price level',
   'shift aggregate demand right',
   'shift LRAS right'], ans=2,
   why='Imported inputs are a production cost, so a rise in their price is a negative supply shock.'),
 dict(q='Which of the following is a cost shock that shifts SRAS left?', choices=[
   'a fall in the price of natural gas',
   'a severe drought that destroys agricultural output and raises food and input prices',
   'an increase in worker productivity',
   'a reduction in payroll taxes',
   'a fall in nominal wages'], ans=1,
   why='A drought raises the cost of producing at every level of output.'),
 dict(q='A decrease in payroll taxes paid by employers would', choices=[
   'shift SRAS right by lowering the cost of employing labor',
   'shift aggregate demand left',
   'cause a movement along SRAS',
   'shift LRAS left',
   'shift SRAS left'], ans=0,
   why='Employer payroll taxes are part of the cost of labor, so cutting them reduces per-unit costs.'),
 dict(q='If the price level rises but firms correctly recognize that all prices, including their input prices, have risen proportionally, they will', choices=[
   'reduce output to zero',
   'shift the SRAS curve right',
   'raise employment permanently',
   'increase output substantially',
   'not increase output, which is why SRAS is vertical once perceptions and input prices adjust'], ans=4,
   why='Output responds only when the price level rises relative to input costs, which is a temporary condition.'),
 dict(q='A large increase in the legal minimum wage would most likely', choices=[
   'shift LRAS right',
   'cause a movement along SRAS',
   'shift SRAS right',
   'shift SRAS left by raising labor costs',
   'leave SRAS unchanged'], ans=3,
   why='A higher wage floor raises per-unit production costs for firms that employ low-wage labor.'),
 dict(q='Which of these best describes what happens along SRAS when aggregate demand increases?', choices=[
   'output falls and the price level rises',
   'output falls and the price level falls',
   'output rises and the price level rises',
   'output rises and the price level falls',
   'output is unchanged and the price level rises'], ans=2,
   why='Moving up an upward-sloping SRAS curve means more real output at a higher price level.'),
 dict(q='Which is the best example of an input price relevant to SRAS?', choices=[
   'the price of a finished automobile sold to a household',
   'the wage paid to assembly-line workers',
   'the price index of consumer goods',
   'the level of government debt',
   'the exchange rate of a currency not used in production'], ans=1,
   why='Wages are the largest single production cost in most economies.'),
 dict(q='If nominal wages rise by 5% and productivity also rises by 5%, unit labor costs', choices=[
   'are roughly unchanged, so SRAS does not shift much',
   'fall by 10%',
   'rise by 5%',
   'fall by 5%',
   'rise by 10%'], ans=0,
   why='Cost per unit depends on the wage relative to output per worker, and here both rose by the same proportion.'),
 dict(q='The SRAS curve would shift right if', choices=[
   'a hurricane destroyed a large share of the capital stock',
   'business taxes rose',
   'the minimum wage rose',
   'workers expected higher inflation and demanded higher wages',
   'energy prices fell sharply'], ans=4,
   why='Falling energy costs lower production costs across the economy.'),
 dict(q='Stagflation, a combination of falling output and rising prices, results from', choices=[
   'a decrease in aggregate demand',
   'an increase in long-run aggregate supply',
   'an increase in aggregate demand',
   'a leftward shift of short-run aggregate supply',
   'a rightward shift of short-run aggregate supply'], ans=3,
   why='Only a negative supply shock pushes output down and the price level up at the same time.'),
 dict(q='Which of the following distinguishes a supply shock from a demand shock?', choices=[
   'There is no difference between them.',
   'A supply shock changes spending; a demand shock changes costs.',
   'A supply shock moves output and the price level in opposite directions; a demand shock moves them in the same direction.',
   'A supply shock affects only the long run.',
   'A demand shock never changes the price level.'], ans=2,
   why='Tracing the shifts on the diagram shows the opposite-direction signature of a supply shock.'),
 dict(q="Firms' expectations of higher future input prices are likely to shift SRAS left today because", choices=[
   'firms immediately cut prices',
   'firms and workers build the expected cost increases into current contracts and prices',
   'consumers spend less',
   'productivity falls automatically',
   'the government forces prices up'], ans=1,
   why='Expected costs become actual contracted costs, which raises the cost of producing now.'),
 dict(q='The SRAS curve is drawn holding constant', choices=[
   'nominal wages, other input prices, productivity, and inflation expectations',
   'real GDP',
   'aggregate demand',
   'the unemployment rate',
   'the price level'], ans=0,
   why='Those are the cost determinants; letting the price level vary is what traces out the curve.'),
 dict(q='An increase in immigration that enlarges the labor force and moderates wage growth would', choices=[
   'cause a movement along SRAS',
   'shift aggregate demand left',
   'leave both curves unchanged',
   'shift SRAS left',
   'shift SRAS right'], ans=4,
   why='A larger supply of labor restrains wage costs and raises the output firms can supply at each price level.'),
 dict(q='Which of the following would shift SRAS left and LRAS left at the same time?', choices=[
   'an increase in expected inflation',
   'an increase in the money supply',
   'a temporary rise in oil prices',
   'a war that destroys a large share of the capital stock and kills or displaces many workers',
   'an increase in nominal wages under existing contracts'], ans=3,
   why='Permanently destroyed productive capacity reduces both short-run and long-run supply, whereas a temporary cost increase affects only SRAS.'),
 dict(q='A temporary increase in the price of a key imported input affects', choices=[
   'all three curves equally',
   'LRAS only',
   'SRAS only, since productive capacity is unchanged',
   'aggregate demand only',
   'neither curve'], ans=2,
   why="A temporary cost change does not alter the economy's underlying resources or technology."),
 dict(q="If the price level rises by 10% and nominal wages rise by 10% at the same time, firms' incentive to expand output", choices=[
   'increases sharply',
   'is essentially unchanged, because the real wage has not fallen',
   'becomes negative',
   'depends only on the interest rate',
   'doubles'], ans=1,
   why='The upward slope of SRAS depends on prices rising faster than input costs, which does not happen here.'),
 dict(q='Which of the following best explains why SRAS is not vertical?', choices=[
   'Some input prices are fixed for a time, so a higher price level temporarily raises profit margins.',
   'The economy has no full-employment level of output.',
   'Consumers always spend more when prices rise.',
   'Capital is perfectly mobile.',
   'Firms can always produce unlimited output.'], ans=0,
   why='The temporary gap between output prices and input costs is what makes output respond to the price level.'),
 dict(q='An economy experiences a sharp fall in shipping and freight costs. In the short run this will', choices=[
   'raise both the price level and output',
   'lower both the price level and output',
   'leave both unchanged',
   'raise the price level and lower output',
   'lower the price level and raise output'], ans=4,
   why='Cheaper logistics is a positive supply shock, shifting SRAS right along a fixed AD curve.'),
 dict(q='Between a change in the price of a final consumer good and a change in the price of steel used by manufacturers, the SRAS curve is shifted by', choices=[
   'neither',
   'only the consumer good price in the long run',
   'the consumer good price only',
   'the price of steel, because it is a production input',
   'both equally'], ans=3,
   why='Only input costs shift SRAS; output prices are already summarized by the price level on the vertical axis.'),
 dict(q='Suppose nominal wages fall while energy prices rise sharply. The effect on SRAS is', choices=[
   'a change in slope only',
   'definitely a rightward shift',
   'indeterminate, because one cost falls while another rises',
   'definitely a leftward shift',
   'no shift at all'], ans=2,
   why='The net movement depends on the relative size of the two cost changes.'),
 dict(q='Which of the following would most likely make SRAS shift right over several years?', choices=[
   'sustained increases in inflation expectations',
   'sustained gains in labor productivity from new technology',
   'a persistent rise in commodity prices',
   'an increase in employer payroll taxes',
   'a fall in the labor force'], ans=1,
   why='Productivity growth steadily lowers unit costs, allowing more output at every price level.'),
 dict(q='If unemployment is very high and many factories sit idle, an increase in aggregate demand will move the economy along SRAS with', choices=[
   'a large rise in output and only a small rise in the price level',
   'no change in output',
   'a fall in output',
   'a fall in the price level',
   'a large rise in the price level and little rise in output'], ans=0,
   why='Where SRAS is relatively flat, extra demand is met mostly by employing idle resources.'),
 dict(q='The distinction between the short run and the long run in the AD-AS model rests on', choices=[
   'the length of the business cycle',
   'whether the money supply changes',
   'whether the economy trades internationally',
   'whether the government acts',
   'whether input prices, especially nominal wages, have adjusted to the price level'], ans=4,
   why='Once nominal wages catch up with prices, the temporary profit incentive disappears and supply is vertical.'),
 dict(q="An economy's SRAS shifts left while aggregate demand is unchanged. The result is", choices=[
   'lower output and a lower price level',
   'no change in either',
   'higher output and a lower price level',
   'lower output, a higher price level, and higher unemployment',
   'higher output and a higher price level'], ans=3,
   why='Sliding back along a fixed AD curve to a smaller SRAS means less real GDP at a higher price level, which raises unemployment.'),
 dict(q='Which statement about the SRAS curve is FALSE?', choices=[
   'It becomes steeper as the economy nears full employment.',
   'It slopes upward.',
   'It shifts left when input prices rise.',
   'It shifts right when productivity improves.',
   'It shifts when the aggregate price level changes.'], ans=4,
   why='A change in the price level is a movement along SRAS, not a shift of it, which is the one false statement here.'),
]
