# MACRO 3.4 Long-Run Aggregate Supply — 50 questions
# No table in this module. Arithmetic used in stems, worked out here:
#   Full-employment output $18 trillion, current output $17.4 trillion
#     -> output gap = 17.4 - 18.0 = -0.6 trillion, a recessionary gap
#   Natural rate 5%, actual unemployment 5% -> economy is on LRAS
#   Labor force 160 million growing 1% per year -> 1.6 million more workers,
#     which shifts LRAS right
TOPIC = ('3.4', 'Long-Run Aggregate Supply', 3)
QUESTIONS = [
 dict(q='The long-run aggregate supply curve is', choices=[
   'upward sloping',
   'vertical at the full-employment level of real output',
   'downward sloping',
   'horizontal at the current price level',
   'vertical at zero output'], ans=1,
   why='In the long run output is determined by resources and technology, not by the price level, so LRAS is vertical at potential output.'),
 dict(q='The LRAS curve is vertical because in the long run', choices=[
   'all input prices, including nominal wages, adjust fully to the price level, so a higher price level gives no incentive to produce more',
   'firms cannot hire workers',
   'aggregate demand is fixed',
   'the government sets output',
   'prices never change'], ans=0,
   why='Once costs rise in the same proportion as output prices, the temporary profit incentive that makes SRAS slope upward disappears.'),
 dict(q='Potential output, or full-employment output, is the level of real GDP at which', choices=[
   'inflation is zero',
   'the budget is balanced',
   'net exports are zero',
   'unemployment is zero',
   'the economy is producing at its sustainable capacity and unemployment equals the natural rate'], ans=4,
   why='Full employment means no cyclical unemployment, not the complete absence of unemployment.'),
 dict(q='At the level of output corresponding to LRAS, the unemployment rate', choices=[
   'is undefined',
   'equals the inflation rate',
   'is zero',
   'equals the natural rate of unemployment, consisting of frictional and structural unemployment',
   'is at its maximum'], ans=3,
   why='Frictional and structural unemployment persist even when the economy is at potential output.'),
 dict(q='Which of the following shifts the LRAS curve to the right?', choices=[
   'an increase in consumer confidence',
   'an increase in the money supply',
   'an increase in the quantity or quality of productive resources',
   'an increase in government spending',
   'a fall in the price level'], ans=2,
   why="Only changes in the economy's productive capacity shift long-run supply; demand-side changes do not."),
 dict(q='The factors that shift LRAS right are essentially the same factors that', choices=[
   'shift aggregate demand right',
   'shift a production possibilities curve outward',
   'raise the price level',
   'lower interest rates',
   'reduce the money supply'], ans=1,
   why='Both curves represent productive capacity, so more resources, better technology, or better institutions move both outward.'),
 dict(q='A technological breakthrough that raises productivity throughout the economy will', choices=[
   'shift LRAS right',
   'leave LRAS unchanged and shift only AD',
   'make LRAS upward sloping',
   'cause a movement along LRAS',
   'shift LRAS left'], ans=0,
   why='Better technology allows more output from the same resources, raising potential GDP.'),
 dict(q='A permanent increase in the size of the labor force will', choices=[
   'have no effect on LRAS',
   'shift only SRAS',
   'cause a movement along LRAS',
   'shift LRAS left',
   'shift LRAS right'], ans=4,
   why="More available labor raises the economy's sustainable output."),
 dict(q='Which of the following would shift LRAS left?', choices=[
   'an increase in immigration',
   'a rise in productivity',
   'an increase in investment in physical capital',
   "a devastating war that destroys much of a country's capital stock and labor force",
   'an improvement in education'], ans=3,
   why="Permanent destruction of productive resources lowers the economy's capacity to produce."),
 dict(q='A rise in the aggregate price level, with resources and technology unchanged, causes', choices=[
   'potential output to rise',
   'a rightward shift of LRAS',
   'no change in long-run aggregate supply',
   'a leftward shift of LRAS',
   'LRAS to slope upward'], ans=2,
   why='LRAS is vertical, so the quantity of output supplied in the long run does not depend on the price level.'),
 dict(q="Improvements in a country's legal system, property rights, and financial institutions are likely to", choices=[
   'shift LRAS left',
   'shift LRAS right by making productive investment and exchange more efficient',
   'affect only aggregate demand',
   'raise the natural rate of unemployment',
   'have no long-run effect'], ans=1,
   why='Institutions determine how effectively an economy converts its resources into output.'),
 dict(q='Which of the following does NOT shift the LRAS curve?', choices=[
   'a change in the money supply',
   'a change in technology',
   'a change in the size of the labor force',
   'a change in the availability of natural resources',
   'a change in the capital stock'], ans=0,
   why='Money is a nominal variable; in the long run it affects the price level rather than real output.'),
 dict(q='The natural rate of unemployment is', choices=[
   'the highest possible unemployment rate',
   'the same as the actual rate in every year',
   'the rate at which inflation is zero',
   'zero',
   'the sum of frictional and structural unemployment when cyclical unemployment is zero'], ans=4,
   why='It is the unemployment that remains when the economy is producing at potential.'),
 dict(q='If the natural rate of unemployment rises because of a permanent skills mismatch, LRAS will', choices=[
   'become upward sloping',
   'become horizontal',
   'shift right',
   'shift left, since fewer workers can be productively employed at potential output',
   'not shift'], ans=3,
   why='A higher natural rate means a smaller sustainable level of employment and therefore lower potential output.'),
 dict(q='An economy is producing at a level of real GDP equal to potential output. This means', choices=[
   'inflation is zero',
   'there is no unemployment',
   'actual output equals full-employment output and the economy is on its LRAS curve',
   'the price level is fixed',
   'the budget is balanced'], ans=2,
   why='Being on LRAS is exactly the condition that actual output equals potential output.'),
 dict(q='Full-employment output is $18 trillion and current real GDP is $17.4 trillion. The economy has', choices=[
   'an inflationary gap of $0.6 trillion',
   'a recessionary gap of $0.6 trillion',
   'no output gap',
   'a recessionary gap of $17.4 trillion',
   'an inflationary gap of $18 trillion'], ans=1,
   why='Output below potential by 17.4 − 18.0 = −0.6 trillion is a recessionary gap of that size.'),
 dict(q='If actual unemployment equals the natural rate of unemployment, the economy is', choices=[
   'at long-run equilibrium on the LRAS curve',
   'in an inflationary gap',
   'experiencing deflation',
   'growing rapidly',
   'in a recessionary gap'], ans=0,
   why='No cyclical unemployment means output is at potential.'),
 dict(q='An increase in the LRAS curve represents', choices=[
   'inflation',
   'a business cycle expansion only',
   'a fall in the price level',
   'a temporary boom',
   'long-run economic growth'], ans=4,
   why='Growth in potential output is precisely what a rightward shift of LRAS means.'),
 dict(q='Which of the following would most likely shift LRAS right over a decade?', choices=[
   'an increase in the money supply',
   'a fall in interest rates',
   'an increase in government transfer payments',
   'sustained investment in education and physical capital',
   'a series of tax rebates to households'], ans=3,
   why="Human and physical capital accumulation raises the economy's productive capacity."),
 dict(q='In the long run, an increase in aggregate demand with LRAS unchanged results in', choices=[
   'a rightward shift of LRAS',
   'higher real output permanently',
   'a higher price level with real output back at potential',
   'lower output and lower prices',
   'no change in the price level'], ans=2,
   why='Because LRAS is vertical, extra demand ultimately raises prices rather than sustainable output.'),
 dict(q="The vertical LRAS curve implies that in the long run the economy's output is determined by", choices=[
   'the level of aggregate demand',
   'the supply of resources, technology, and institutions',
   'the money supply',
   'the price level',
   'government spending'], ans=1,
   why='Real supply-side variables, not nominal demand, set potential output.'),
 dict(q='A country discovers a large, exploitable deposit of natural resources. This would', choices=[
   'shift LRAS right',
   'shift only aggregate demand',
   'make LRAS horizontal',
   'raise the natural rate of unemployment',
   'shift LRAS left'], ans=0,
   why="More usable natural resources expands the economy's capacity to produce."),
 dict(q='Which pair of curves intersects at potential output when the economy is in long-run equilibrium?', choices=[
   'SRAS and LRAS only',
   'AD and LRAS at different points from SRAS',
   'none of the curves intersect',
   'AD and SRAS only',
   'AD, SRAS, and LRAS all intersect at the same point'], ans=4,
   why='Long-run equilibrium requires that the short-run equilibrium output also equals potential output.'),
 dict(q='An economy operating beyond its LRAS level of output in the short run is', choices=[
   'at long-run equilibrium',
   'experiencing deflation',
   'sustainable indefinitely',
   'in an inflationary gap, with unemployment temporarily below the natural rate',
   'in a recession'], ans=3,
   why='Output above potential means resources are being used at an unsustainably intense rate.'),
 dict(q='Which statement about LRAS and the price level is correct?', choices=[
   'LRAS slopes upward at high price levels.',
   'A higher price level raises long-run output.',
   'The long-run quantity of output supplied is independent of the price level.',
   'A lower price level raises long-run output.',
   'LRAS shifts whenever the price level changes.'], ans=2,
   why='Vertical means the same real output is supplied whatever the price level.'),
 dict(q="If a country's population ages and a large share of workers retire without replacement, LRAS will most likely", choices=[
   'shift right',
   'shift left',
   'stay in place',
   'become vertical at a higher output',
   'become upward sloping'], ans=1,
   why="A shrinking labor force reduces the economy's sustainable level of output."),
 dict(q='A labor force of 160 million grows by 1% in a year. Other things equal, this adds', choices=[
   '1.6 million workers and shifts LRAS right',
   '16 million workers and shifts LRAS right',
   '1.6 million workers with no effect on LRAS',
   'no workers',
   '0.16 million workers and shifts LRAS left'], ans=0,
   why='One percent of 160 million is 1.6 million additional workers, which raises potential output.'),
 dict(q='Which of the following affects SRAS but not LRAS?', choices=[
   'an increase in the capital stock',
   'an increase in the labor force',
   'an improvement in worker training',
   'a permanent improvement in technology',
   'a temporary spike in oil prices'], ans=4,
   why="A temporary cost shock changes production costs now but not the economy's underlying capacity."),
 dict(q='Which of the following affects both SRAS and LRAS?', choices=[
   'an increase in expected inflation',
   'a temporary rise in nominal wages',
   'a one-year increase in the price of imported steel',
   'a permanent increase in labor productivity from new technology',
   'a temporary strike in one industry'], ans=3,
   why='A permanent productivity gain lowers current costs and raises long-run capacity at the same time.'),
 dict(q='Economists sometimes say that money is neutral in the long run. In the AD-AS model this corresponds to', choices=[
   'output being determined by aggregate demand',
   'the SRAS curve being upward sloping',
   'the LRAS curve being vertical, so a change in the money supply changes only the price level',
   'the AD curve being vertical',
   'the LRAS curve shifting with the money supply'], ans=2,
   why='With a vertical LRAS, nominal changes end up in the price level rather than in real output.'),
 dict(q='The relationship between LRAS and the production possibilities curve is that', choices=[
   'they are unrelated concepts',
   'both represent maximum sustainable production, so the same forces expand both',
   'LRAS shows spending while the PPC shows production',
   'the PPC is vertical and LRAS is bowed outward',
   'only the PPC can shift'], ans=1,
   why='Both are capacity concepts describing what the economy can produce with its resources and technology.'),
 dict(q='A government policy that reduces long-term unemployment by improving job matching and retraining would', choices=[
   'lower the natural rate of unemployment and shift LRAS right',
   'raise the natural rate of unemployment',
   'affect only aggregate demand',
   'make LRAS horizontal',
   'shift LRAS left'], ans=0,
   why='Reducing structural unemployment raises the employment level consistent with potential output.'),
 dict(q='In the long run, an increase in the price level accompanied by proportional increases in all nominal wages leaves', choices=[
   'real output lower',
   'the natural rate of unemployment lower',
   'the capital stock larger',
   'real output higher',
   'real output unchanged at potential'], ans=4,
   why='If everything nominal rises together, no real variable changes, which is the meaning of a vertical LRAS.'),
 dict(q='Which of the following is NOT a determinant of long-run aggregate supply?', choices=[
   'the state of technology',
   'the quality of economic institutions',
   'the quantity of labor',
   'the current level of consumer spending',
   'the stock of physical capital'], ans=3,
   why='Consumer spending is a component of aggregate demand rather than a determinant of capacity.'),
 dict(q='A permanent increase in the average education level of the workforce would', choices=[
   'raise the natural rate of unemployment',
   'shift LRAS left',
   'shift LRAS right by raising human capital and productivity',
   'shift only aggregate demand right',
   'cause a movement along LRAS'], ans=2,
   why='Better-trained workers produce more from the same physical resources.'),
 dict(q='If actual real GDP exceeds potential real GDP, the actual unemployment rate is', choices=[
   'above the natural rate',
   'below the natural rate',
   'equal to the natural rate',
   'zero',
   'unrelated to the natural rate'], ans=1,
   why='Producing beyond potential requires drawing labor in beyond the sustainable level, so unemployment falls below the natural rate.'),
 dict(q='If actual real GDP is below potential real GDP, the actual unemployment rate is', choices=[
   'above the natural rate because cyclical unemployment is positive',
   'equal to the natural rate',
   'zero',
   'unaffected',
   'below the natural rate'], ans=0,
   why='The shortfall of output shows up as cyclical unemployment on top of the natural rate.'),
 dict(q='Which of the following combinations describes long-run macroeconomic equilibrium?', choices=[
   'output below potential and unemployment above the natural rate',
   'output equal to potential and unemployment equal to zero',
   'output above potential and inflation equal to zero',
   'output above potential and unemployment below the natural rate',
   'output equal to potential and unemployment equal to the natural rate'], ans=4,
   why='Long-run equilibrium is defined by output at potential, which corresponds to the natural rate of unemployment.'),
 dict(q='A country that invests a large share of its output in capital goods rather than consumption goods will most likely', choices=[
   'experience deflation permanently',
   'raise its natural rate of unemployment',
   'see LRAS shift left',
   'see LRAS shift further right over time than a country that invests little',
   'see no change in LRAS'], ans=3,
   why='Capital accumulation is one of the main sources of growth in potential output.'),
 dict(q='Which of the following would shift LRAS right but leave aggregate demand roughly unchanged in the short run?', choices=[
   'an increase in the money supply',
   'an increase in government purchases',
   'a reform that raises total factor productivity in existing firms',
   'a cut in personal income taxes',
   'an increase in transfer payments'], ans=2,
   why='A pure productivity improvement raises capacity without directly adding to spending.'),
 dict(q='If the LRAS curve shifts right while aggregate demand is unchanged, the long-run result is', choices=[
   'a higher price level and higher output',
   'a lower price level and higher output',
   'a higher price level and lower output',
   'no change in either',
   'a lower price level and lower output'], ans=1,
   why='More capacity meeting the same demand yields more real output at a lower price level.'),
 dict(q='The claim that a country can permanently raise its real GDP simply by increasing government spending is inconsistent with', choices=[
   'a vertical LRAS',
   'a downward-sloping AD',
   'the multiplier',
   'sticky wages',
   'an upward-sloping SRAS'], ans=0,
   why='With potential output fixed by supply-side factors, demand stimulus cannot permanently raise real output.'),
 dict(q='Two economies have identical resources but one has more secure property rights and less corruption. That economy will most likely have', choices=[
   'an identical LRAS curve',
   'a horizontal LRAS curve',
   'no LRAS curve',
   'an LRAS curve to the left of the other',
   'an LRAS curve to the right of the other'], ans=4,
   why='Institutions determine how productively the same resources are used, so better institutions mean higher potential output.'),
 dict(q="A hurricane destroys 10% of a country's factories. In the AD-AS model this is shown as", choices=[
   'a movement along SRAS',
   'a leftward shift of AD only',
   'a rightward shift of AD',
   'a leftward shift of both SRAS and LRAS',
   'a rightward shift of LRAS only'], ans=3,
   why="Lost capital reduces both current production and the economy's sustainable capacity."),
 dict(q='The LRAS curve is best interpreted as showing', choices=[
   'the level of spending in the economy',
   'what the economy does produce this quarter',
   'what the economy can sustainably produce when all its resources are employed at their natural rates',
   'the maximum output ever recorded',
   'the level of output that eliminates all unemployment'], ans=2,
   why='Potential output is a sustainable capacity concept, not a record high or a zero-unemployment level.'),
 dict(q='Which of the following statements about LRAS is FALSE?', choices=[
   'It is vertical at potential output.',
   'It shifts right when technology improves.',
   'It shifts left when the capital stock is destroyed.',
   'It shifts right when the money supply increases.',
   'It corresponds to the natural rate of unemployment.'], ans=3,
   why="Money supply changes affect nominal variables in the long run, not the economy's productive capacity."),
 dict(q='Economic growth is best represented in the AD-AS model by', choices=[
   'a rightward shift of LRAS',
   'a movement along SRAS',
   'a rise in the price level',
   'a leftward shift of SRAS',
   'a rightward shift of AD'], ans=0,
   why="Growth means an increase in the economy's sustainable output, which is exactly what the LRAS position measures."),
 dict(q='Suppose immigration raises the labor force while a natural disaster destroys part of the capital stock. The effect on LRAS is', choices=[
   'definitely leftward',
   'zero',
   'a change in slope only',
   'definitely rightward',
   'indeterminate, because one force raises capacity and the other reduces it'], ans=4,
   why='Opposing changes in two productive resources leave the net direction of the shift ambiguous.'),
 dict(q='Which policy is most likely to shift LRAS right in the long run?', choices=[
   'an expansion of the money supply',
   'an increase in tariffs on imported consumer goods',
   'a temporary increase in unemployment benefits',
   'a permanent research and development tax credit that raises innovation',
   'a one-time stimulus check to households'], ans=3,
   why='Encouraging innovation raises productivity and therefore potential output.'),
 dict(q='A student argues that because LRAS is vertical, aggregate demand does not matter. The best correction is that', choices=[
   'the short run does not exist',
   'aggregate demand determines long-run output',
   'aggregate demand determines the price level in the long run and both output and prices in the short run',
   'aggregate demand has no effect on anything',
   'LRAS is actually upward sloping'], ans=2,
   why='Vertical LRAS pins down long-run real output, but demand still drives short-run output and the long-run price level.'),
]
