# MACRO 3.5 Equilibrium in the AD-AS Model — 50 questions
# GAP table below, worked out line by line (all figures in trillions of real dollars):
#   Alba:   actual 19.0, potential 20.0 -> gap = -1.0  recessionary
#   Borvia: actual 12.5, potential 12.5 -> gap =  0.0  long-run equilibrium
#   Cresca: actual  8.4, potential  8.0 -> gap = +0.4  inflationary
#   Doran:  actual 15.2, potential 16.0 -> gap = -0.8  recessionary
#   Elmar:  actual 22.5, potential 21.0 -> gap = +1.5  inflationary
# The only gap of exactly zero is Borvia; the largest recessionary gap is Alba's
# 1.0; the largest inflationary gap is Elmar's 1.5.
TOPIC = ("3.5", "Equilibrium in the AD-AS Model", 3)
GAPS = dict(
  headers=["Economy", "Actual real GDP", "Potential real GDP"],
  rows=[["Alba", "19.0", "20.0"],
        ["Borvia", "12.5", "12.5"],
        ["Cresca", "8.4", "8.0"],
        ["Doran", "15.2", "16.0"],
        ["Elmar", "22.5", "21.0"]])
QUESTIONS = [
 dict(q='Short-run macroeconomic equilibrium occurs where', choices=[
   'aggregate demand crosses long-run aggregate supply',
   'aggregate demand crosses short-run aggregate supply',
   'SRAS crosses LRAS',
   'output equals zero',
   'the price level equals 100'], ans=1,
   why='The short-run equilibrium price level and output are set by the intersection of AD and SRAS.'),
 dict(q='Long-run macroeconomic equilibrium occurs where', choices=[
   'AD, SRAS, and LRAS all intersect at the same point',
   'SRAS is horizontal',
   'the budget is balanced',
   'net exports are zero',
   'AD crosses SRAS at any output level'], ans=0,
   why='Only when the short-run equilibrium also sits on LRAS is the economy producing at potential with no pressure to adjust.'),
 dict(q='A recessionary gap exists when', choices=[
   'actual real GDP equals potential real GDP',
   'the price level is falling',
   'the budget deficit is large',
   'actual real GDP exceeds potential real GDP',
   'actual real GDP is below potential real GDP'], ans=4,
   why='A shortfall of output relative to potential is the definition of a recessionary, or negative, output gap.'),
 dict(q='An inflationary gap exists when', choices=[
   'unemployment equals the natural rate',
   'the price level is constant',
   'actual real GDP is below potential real GDP',
   'actual real GDP exceeds potential real GDP',
   'actual and potential output are equal'], ans=3,
   why='Producing beyond potential puts upward pressure on wages and prices, which is what the term describes.'),
 dict(q='In a recessionary gap, the unemployment rate is', choices=[
   'equal to the inflation rate',
   'below the natural rate',
   'above the natural rate',
   'equal to the natural rate',
   'zero'], ans=2,
   why='Output below potential means positive cyclical unemployment on top of the natural rate.'),
 dict(q='In an inflationary gap, the unemployment rate is', choices=[
   'above the natural rate',
   'below the natural rate',
   'equal to the natural rate',
   'always zero',
   'unrelated to output'], ans=1,
   why='Producing above potential requires employing labor more intensively than is sustainable.'),
 dict(q='An economy is in long-run equilibrium when', choices=[
   'actual output equals potential output and unemployment equals the natural rate',
   'the price level is zero',
   'aggregate demand is vertical',
   'the government budget is balanced',
   'actual output exceeds potential output'], ans=0,
   why='Long-run equilibrium and full-employment output are the same condition.'),
 dict(q="Alba's actual real GDP is 19.0 trillion and its potential real GDP is 20.0 trillion. Alba has", choices=[
   'no output gap',
   'an inflationary gap of 19.0 trillion',
   'a recessionary gap of 39.0 trillion',
   'an inflationary gap of 1.0 trillion',
   'a recessionary gap of 1.0 trillion'], ans=4, table=GAPS,
   why='19.0 − 20.0 = −1.0, so output is one trillion short of potential.'),
 dict(q='Which economy in the table is in long-run equilibrium?', choices=[
   'Doran',
   'Elmar',
   'Alba',
   'Borvia',
   'Cresca'], ans=3, table=GAPS,
   why='Borvia is the only economy whose actual output exactly equals its potential output.'),
 dict(q='Which economy in the table has the largest inflationary gap?', choices=[
   'Elmar',
   'Alba',
   'Borvia',
   'Cresca',
   'Doran'], ans=0, table=GAPS,
   why="Elmar's output exceeds potential by 1.5 trillion, larger than Cresca's excess of 0.4."),
 dict(q='Which economy in the table has the largest recessionary gap?', choices=[
   'Alba',
   'Borvia',
   'Cresca',
   'Doran',
   'Elmar'], ans=0, table=GAPS,
   why="Alba is short of potential by 1.0 trillion, compared with Doran's shortfall of 0.8."),
 dict(q='Which economies in the table have unemployment above the natural rate?', choices=[
   'Cresca and Elmar',
   'Borvia only',
   'all five',
   'none of them',
   'Alba and Doran'], ans=4, table=GAPS,
   why='Alba and Doran are the two economies producing below potential, which is where cyclical unemployment appears.'),
 dict(q="Doran's output gap equals", choices=[
   '-1.5',
   '-1.0',
   '-0.8',
   '0.4',
   '1.5'], ans=2, table=GAPS,
   why='15.2 − 16.0 = −0.8 trillion.'),
 dict(q="Cresca's output gap equals", choices=[
   '-0.8',
   '-0.4',
   '0',
   '0.4',
   '1.5'], ans=3, table=GAPS,
   why='8.4 − 8.0 = +0.4 trillion, an inflationary gap.'),
 dict(q='An increase in aggregate demand starting from long-run equilibrium creates, in the short run,', choices=[
   'a leftward shift of LRAS',
   'a recessionary gap',
   'an inflationary gap with output above potential and a higher price level',
   'no gap at all',
   'a fall in the price level'], ans=2,
   why='Moving up along SRAS carries output past potential while raising the price level.'),
 dict(q='A decrease in aggregate demand starting from long-run equilibrium creates, in the short run,', choices=[
   'an inflationary gap',
   'a recessionary gap with output below potential and a lower price level',
   'no change in output',
   'a rightward shift of LRAS',
   'an immediate rise in the price level'], ans=1,
   why='Sliding down SRAS reduces both output and the price level, leaving output short of potential.'),
 dict(q='At the short-run equilibrium the quantity of real GDP demanded', choices=[
   'equals the quantity of real GDP supplied at the prevailing price level',
   'is always at potential',
   'is zero',
   'is less than the quantity supplied',
   'exceeds the quantity supplied'], ans=0,
   why='Equilibrium is exactly the price level at which planned spending matches the output firms supply.'),
 dict(q='If the price level is above the short-run equilibrium level, then', choices=[
   'the economy is in long-run equilibrium',
   'output must equal potential',
   'aggregate demand shifts left',
   'a shortage of goods develops and prices rise further',
   'a surplus of goods develops and prices are pushed down toward equilibrium'], ans=4,
   why='Above equilibrium, the quantity supplied exceeds the quantity demanded, and unsold output pushes prices back down.'),
 dict(q='If the price level is below the short-run equilibrium level, then', choices=[
   'output falls to zero',
   'SRAS shifts left',
   'a surplus develops',
   'a shortage develops and the price level is bid up',
   'the economy is at potential output'], ans=3,
   why='Below equilibrium, more output is demanded than supplied, so prices rise.'),
 dict(q='An economy at short-run equilibrium with output above potential will experience pressure for', choices=[
   'no adjustment',
   'nominal wages to fall',
   'nominal wages to rise, shifting SRAS left over time',
   'LRAS to shift right',
   'aggregate demand to shift right'], ans=2,
   why='Tight labor markets bid wages up, raising costs and pulling short-run supply back.'),
 dict(q='An economy at short-run equilibrium with output below potential will experience pressure for', choices=[
   'nominal wages to rise',
   'nominal wages to fall or grow more slowly, shifting SRAS right over time',
   'LRAS to shift left',
   'aggregate demand to fall further',
   'the price level to rise immediately'], ans=1,
   why='High unemployment eventually restrains wage growth, lowering costs and increasing short-run supply.'),
 dict(q='The output gap is calculated as', choices=[
   'actual GDP minus potential GDP',
   'nominal GDP minus real GDP',
   'real GDP divided by the price level',
   'the change in real GDP',
   'potential GDP minus actual GDP'], ans=0,
   why='Written this way a negative number is a recessionary gap and a positive number an inflationary gap.'),
 dict(q='Which of the following describes a short-run equilibrium that is NOT a long-run equilibrium?', choices=[
   'the price level equals 100',
   'unemployment equals the natural rate',
   'the budget is balanced',
   'AD crosses SRAS exactly on LRAS',
   'AD crosses SRAS at an output level to the left of LRAS'], ans=4,
   why='If the AD-SRAS intersection is off the LRAS curve, the economy is in a gap and adjustment is still to come.'),
 dict(q='A negative output gap is another name for', choices=[
   'stagflation',
   'economic growth',
   'an inflationary gap',
   'a recessionary gap',
   'long-run equilibrium'], ans=3,
   why='Actual output below potential gives a negative value for actual minus potential.'),
 dict(q='A country reports actual real GDP of $9.6 trillion and potential real GDP of $9.6 trillion. This country', choices=[
   'must be experiencing deflation',
   'has an inflationary gap',
   'is at full-employment output with no cyclical unemployment',
   'has a recessionary gap',
   'has zero unemployment'], ans=2,
   why='Equality of actual and potential output means no output gap, though frictional and structural unemployment remain.'),
 dict(q='Which of the following is the clearest sign of an inflationary gap?', choices=[
   'rising unemployment and falling prices',
   'unemployment below the natural rate together with accelerating wage and price increases',
   'unemployment equal to the natural rate',
   'a stable price level',
   'falling real GDP'], ans=1,
   why='Overheating shows up as unusually low unemployment and upward pressure on wages and prices.'),
 dict(q='Which of the following is the clearest sign of a recessionary gap?', choices=[
   'unemployment above the natural rate together with idle capacity and weak price pressure',
   'output above potential',
   'accelerating inflation',
   'labor shortages',
   'unemployment below the natural rate'], ans=0,
   why='Slack in labor and product markets is the signature of output below potential.'),
 dict(q='In the AD-AS diagram, potential output is shown by', choices=[
   'the height of the AD curve',
   'the slope of SRAS',
   'the vertical intercept of AD',
   'the intersection of AD and SRAS',
   'the position of the vertical LRAS curve'], ans=4,
   why="LRAS is drawn vertically at the economy's full-employment level of real output."),
 dict(q='If AD shifts right and the economy was already at potential, the short-run result is', choices=[
   'no change in output',
   'a leftward shift of LRAS',
   'higher output, a higher price level, and an inflationary gap',
   'lower output and a lower price level',
   'higher output and a lower price level'], ans=2,
   why='Extra demand meeting an upward-sloping SRAS pushes output past potential and raises prices.'),
 dict(q='Two economies have identical potential output, but one is in a deep recessionary gap. Compared with the other, that economy will have', choices=[
   'a vertical SRAS',
   'higher output and a higher price level',
   'lower output, higher unemployment, and a lower price level',
   'lower output but higher inflation',
   'identical unemployment'], ans=2,
   why='Weak demand relative to capacity depresses output and prices and raises cyclical unemployment.'),
 dict(q='Which of the following can produce a recessionary gap?', choices=[
   'an increase in exports',
   'a sharp fall in business investment',
   'an increase in government spending',
   'a cut in taxes',
   'an increase in consumer confidence'], ans=1,
   why='A drop in a component of aggregate demand shifts AD left and leaves output below potential.'),
 dict(q='Which of the following can produce an inflationary gap?', choices=[
   'a large increase in government spending when the economy is already at potential',
   'an increase in taxes',
   'a recession abroad',
   'a currency appreciation',
   'a fall in household wealth'], ans=0,
   why='Adding demand to an economy already at capacity pushes output temporarily above potential.'),
 dict(q='An adverse supply shock at an economy previously in long-run equilibrium produces a short-run equilibrium with', choices=[
   'higher output and a higher price level',
   'no gap',
   'lower output and a lower price level',
   'higher output and a lower price level',
   'lower output, a higher price level, and a recessionary gap'], ans=4,
   why='A leftward SRAS shift moves the economy up and to the left along AD, which is stagflation.'),
 dict(q='At long-run equilibrium, which of the following is true?', choices=[
   'structural unemployment is zero',
   'total unemployment is zero',
   'cyclical unemployment is positive',
   'cyclical unemployment is zero',
   'frictional unemployment is zero'], ans=3,
   why='Only the cyclical component disappears at potential output; the natural components remain.'),
 dict(q='Suppose AD and SRAS intersect to the right of LRAS. Over time, without policy, the economy will', choices=[
   'experience deflation',
   'stay there permanently',
   'see nominal wages rise, SRAS shift left, and output return to potential at a higher price level',
   'see LRAS shift right to meet the intersection',
   'see AD shift right further'], ans=2,
   why='An inflationary gap eventually closes through rising input costs rather than through a change in capacity.'),
 dict(q='Suppose AD and SRAS intersect to the left of LRAS. Over time, without policy, the economy should', choices=[
   'remain permanently below potential',
   'see wage growth slow, SRAS shift right, and output return to potential at a lower price level',
   'see LRAS shift left',
   'see AD shift left further',
   'experience accelerating inflation'], ans=1,
   why='A recessionary gap closes through falling costs, though many economists argue this happens slowly.'),
 dict(q='Which statement about short-run equilibrium output is correct?', choices=[
   'It can be above, below, or equal to potential output.',
   'It can never exceed potential output.',
   'It is determined only by LRAS.',
   'It is determined only by the money supply.',
   'It always equals potential output.'], ans=0,
   why='The AD-SRAS intersection is unconstrained by LRAS in the short run.'),
 dict(q='An economy has actual GDP of $22.5 trillion and potential GDP of $21.0 trillion. Real GDP is above potential, in trillions of dollars, by', choices=[
   '0.4',
   '0.8',
   '1.0',
   '1.5',
   '2.0'], ans=3, table=GAPS,
   why="22.5 − 21.0 = 1.5 trillion, which is Elmar's inflationary gap."),
 dict(q='A rightward shift of LRAS with AD and SRAS unchanged converts a long-run equilibrium into', choices=[
   'another long-run equilibrium immediately',
   'a fall in potential output',
   'an inflationary gap',
   'a recessionary gap, because potential output now exceeds actual output',
   'a stagflation'], ans=3,
   why='If capacity grows and spending does not, actual output falls short of the new potential.'),
 dict(q='Which of the following pairs of observations is internally inconsistent?', choices=[
   'output below potential and idle factory capacity',
   'output below potential and unemployment above the natural rate',
   'output above potential and unemployment above the natural rate',
   'output equal to potential and unemployment equal to the natural rate',
   'output above potential and rising wage pressure'], ans=2,
   why='Producing more than potential requires unusually intense use of labor, so unemployment must be below the natural rate.'),
 dict(q='Full employment in the AD-AS model corresponds to', choices=[
   'zero unemployment',
   'the output level at which the economy sits on its LRAS curve',
   'the maximum output ever produced',
   'zero inflation',
   'a balanced budget'], ans=1,
   why='Full employment is a potential-output concept, not the absence of all unemployment.'),
 dict(q='In the short run, an increase in aggregate demand raises both output and the price level. This is because', choices=[
   'SRAS slopes upward, so more output is supplied only at a higher price level',
   'LRAS is horizontal',
   'AD is vertical',
   'wages adjust instantly',
   'SRAS is vertical'], ans=0,
   why='The upward slope of SRAS is what splits a demand increase between output and prices.'),
 dict(q='If both AD and SRAS shift right by similar amounts, the short-run effect on real output is', choices=[
   'no change',
   'an increase in the price level with certainty',
   'indeterminate for output',
   'an increase, while the effect on the price level is ambiguous',
   'a decrease'], ans=3,
   why='Both shifts raise output, but one pushes the price level up and the other pushes it down.'),
 dict(q='If AD shifts right while SRAS shifts left, the effect on the price level is', choices=[
   'zero',
   'a decrease in output with certainty',
   'ambiguous',
   'an increase, while the effect on real output is ambiguous',
   'a decrease'], ans=3,
   why='Both shifts push the price level up, but they push output in opposite directions.'),
 dict(q='A country in a severe recessionary gap will typically show', choices=[
   'accelerating inflation',
   'labor shortages and rapid wage growth',
   'high cyclical unemployment, unused capacity, and weak inflation',
   'output above potential',
   'unemployment below the natural rate'], ans=2,
   why='A large negative output gap means substantial slack throughout the economy.'),
 dict(q='Which change would move an economy from a recessionary gap to long-run equilibrium?', choices=[
   'a leftward shift of AD',
   'a rightward shift of AD sufficient to raise output to potential',
   'a leftward shift of SRAS',
   'a leftward shift of LRAS to meet output',
   'no change at all'], ans=1,
   why='Raising spending enough to reach the LRAS output level closes a negative gap.'),
 dict(q='Which change would move an economy from an inflationary gap to long-run equilibrium?', choices=[
   'a leftward shift of AD sufficient to lower output to potential',
   'a rightward shift of SRAS beyond potential',
   'an increase in the money supply',
   'an increase in government spending',
   'a rightward shift of AD'], ans=0,
   why='Reducing spending to the level consistent with potential output closes a positive gap.'),
 dict(q="Actual real GDP of $15.2 trillion against potential of $16.0 trillion implies that this economy's cyclical unemployment is", choices=[
   'negative',
   'equal to the natural rate',
   'impossible to sign',
   'zero',
   'positive, because output falls short of potential'], ans=4,
   why='A negative output gap of 0.8 trillion corresponds to workers who would be employed at potential but are not.'),
 dict(q='Which statement best distinguishes short-run from long-run equilibrium?', choices=[
   'Short-run equilibrium requires output above potential.',
   'There is no difference.',
   'Short-run equilibrium requires a balanced budget.',
   'Short-run equilibrium is where AD meets SRAS, while long-run equilibrium additionally requires that point to lie on LRAS.',
   'Long-run equilibrium requires zero unemployment.'], ans=3,
   why='The extra condition in the long run is that output equals potential.'),
 dict(q='A persistent output gap is a problem for policymakers mainly because', choices=[
   'it has no economic consequences',
   'it means the price level is fixed',
   'a recessionary gap wastes resources through unemployment while an inflationary gap builds inflationary pressure',
   'it eliminates the natural rate of unemployment',
   'it makes LRAS shift'], ans=2,
   why='Both types of gap carry real costs, which is why closing them is a stabilization objective.'),
]
