# MACRO 3.6 Changes in the AD-AS Model in the Short Run — 50 questions
# The four short-run cases, worked out so every answer below is derivable:
#   AD increases  -> real GDP up,   price level up,   unemployment down
#   AD decreases  -> real GDP down, price level down, unemployment up
#   SRAS increases-> real GDP up,   price level down, unemployment down
#   SRAS decreases-> real GDP down, price level up,   unemployment up  (stagflation)
# Ambiguous combinations:
#   AD up + SRAS up   -> output up,          price level ambiguous
#   AD down + SRAS down-> output down,       price level ambiguous
#   AD up + SRAS down -> price level up,     output ambiguous
#   AD down + SRAS up -> price level down,   output ambiguous
TOPIC = ("3.6", "Changes in the AD-AS Model in the Short Run", 3)
QUESTIONS = [
 dict(q='An increase in aggregate demand in the short run causes real GDP to', choices=[
   'fall and the price level to fall',
   'rise and the price level to rise',
   'rise and the price level to fall',
   'stay the same while the price level rises',
   'fall while the price level rises'], ans=1,
   why='More spending moves the economy up along an upward-sloping SRAS, raising both output and prices.'),
 dict(q='An increase in aggregate demand in the short run causes unemployment to', choices=[
   'fall, because firms hire more workers to produce the extra output',
   'stay exactly at the natural rate',
   'become zero',
   'rise then fall immediately',
   'rise'], ans=0,
   why='Higher output requires more labor, so cyclical unemployment falls.'),
 dict(q='A decrease in aggregate demand in the short run causes', choices=[
   'lower output and a higher price level',
   'higher output and a lower price level',
   'no change in output',
   'higher output and a higher price level',
   'lower output, a lower price level, and higher unemployment'], ans=4,
   why='Sliding down SRAS reduces real GDP and the price level together, which raises unemployment.'),
 dict(q='An increase in short-run aggregate supply causes', choices=[
   'lower output and a lower price level',
   'no change in the price level',
   'lower output and a higher price level',
   'higher output, a lower price level, and lower unemployment',
   'higher output and a higher price level'], ans=3,
   why='A rightward SRAS shift moves the economy down along AD, so more is produced and sold at lower prices.'),
 dict(q='A decrease in short-run aggregate supply causes', choices=[
   'no change in unemployment',
   'higher output and a lower price level',
   'lower output, a higher price level, and higher unemployment',
   'higher output and a higher price level',
   'lower output and a lower price level'], ans=2,
   why='A leftward SRAS shift moves the economy up along AD, producing stagflation.'),
 dict(q='Stagflation is the combination of', choices=[
   'falling output and falling prices',
   'falling output and rising prices',
   'rising output and rising prices',
   'rising output and falling prices',
   'stable output and stable prices'], ans=1,
   why='The term joins stagnation of output with inflation of prices.'),
 dict(q='Stagflation is caused in the AD-AS model by', choices=[
   'a leftward shift of short-run aggregate supply, such as a sharp rise in oil prices',
   'a rightward shift of short-run aggregate supply',
   'a decrease in aggregate demand',
   'a rightward shift of LRAS',
   'an increase in aggregate demand'], ans=0,
   why='Only a negative supply shock raises the price level while reducing output.'),
 dict(q='Stagflation is a difficult problem for policymakers because', choices=[
   'output and prices always move together',
   'the price level cannot be measured',
   'supply shocks are always permanent',
   'no policy affects the economy',
   'demand-side policy that raises output raises inflation further, while policy that fights inflation deepens the output loss'], ans=4,
   why='A single demand-side tool cannot push output up and prices down at the same time.'),
 dict(q='A sharp increase in world oil prices affects an oil-importing economy in the short run by', choices=[
   'shifting LRAS right',
   'leaving the price level unchanged',
   'shifting AD right',
   'shifting SRAS left, raising the price level and lowering real GDP',
   'shifting SRAS right'], ans=3,
   why='Energy is an input to nearly all production, so its price is a cost shock rather than a spending shock.'),
 dict(q='A large increase in government spending on infrastructure, with the economy below full employment, will in the short run', choices=[
   'leave output unchanged',
   'lower output and the price level',
   'raise output, raise the price level, and lower unemployment',
   'raise output and lower the price level',
   'shift SRAS right'], ans=2,
   why='Government purchases shift AD right, moving the economy up along SRAS.'),
 dict(q='A collapse in consumer confidence would in the short run', choices=[
   'shift AD right and raise output',
   'shift AD left, lowering output and the price level and raising unemployment',
   'shift SRAS left',
   'shift SRAS right',
   'leave the economy unchanged'], ans=1,
   why='Pessimistic households spend less, which is a leftward AD shift.'),
 dict(q='A technological advance that sharply raises productivity will in the short run', choices=[
   'shift SRAS right, raising real GDP and lowering the price level',
   'shift AD left',
   'raise the price level',
   'raise unemployment',
   'shift SRAS left'], ans=0,
   why='Lower unit costs increase supply, so output rises while prices fall.'),
 dict(q='A severe drought that destroys crops and raises food and input prices will in the short run', choices=[
   'raise both real GDP and the price level',
   'lower both real GDP and the price level',
   'shift AD right',
   'raise real GDP and lower prices',
   'lower real GDP and raise the price level'], ans=4,
   why='It is a negative supply shock, so output falls while the price level rises.'),
 dict(q='An increase in exports to a booming trading partner will in the short run', choices=[
   'shift SRAS right',
   'lower the price level',
   'shift AD left',
   'shift AD right, raising output and the price level',
   'shift SRAS left'], ans=3,
   why='Net exports are a component of aggregate demand.'),
 dict(q='Which shift produces a fall in the price level together with a rise in real GDP?', choices=[
   'a decrease in long-run aggregate supply',
   'an increase in aggregate demand',
   'an increase in short-run aggregate supply',
   'a decrease in aggregate demand',
   'a decrease in short-run aggregate supply'], ans=2,
   why='Only a rightward SRAS shift moves output and the price level in opposite directions in this way.'),
 dict(q='Which shift produces a rise in the price level together with a fall in real GDP?', choices=[
   'an increase in aggregate demand',
   'a decrease in short-run aggregate supply',
   'an increase in short-run aggregate supply',
   'a decrease in aggregate demand',
   'an increase in long-run aggregate supply'], ans=1,
   why='This is the stagflation case produced by a negative supply shock.'),
 dict(q='Which shift produces a fall in both real GDP and the price level?', choices=[
   'a decrease in aggregate demand',
   'an increase in short-run aggregate supply',
   'a decrease in short-run aggregate supply',
   'an increase in long-run aggregate supply',
   'an increase in aggregate demand'], ans=0,
   why='A demand contraction moves the economy down along SRAS, reducing both variables.'),
 dict(q='Which shift produces a rise in both real GDP and the price level?', choices=[
   'an increase in short-run aggregate supply',
   'a decrease in short-run aggregate supply',
   'a decrease in long-run aggregate supply',
   'a decrease in aggregate demand',
   'an increase in aggregate demand'], ans=4,
   why='A demand expansion moves the economy up along the SRAS curve.'),
 dict(q='If both AD and SRAS increase, real GDP', choices=[
   'rises only if the price level falls',
   'cannot be determined',
   'definitely falls',
   'definitely rises, while the effect on the price level is ambiguous',
   'is unchanged'], ans=3,
   why='Both shifts raise output, but one pushes prices up and the other pushes them down.'),
 dict(q='If AD increases and SRAS decreases, the price level', choices=[
   'cannot be signed',
   'definitely falls',
   'definitely rises, while the effect on real GDP is ambiguous',
   'is unchanged',
   'and output both rise'], ans=2,
   why='Both shifts push the price level up, but they pull output in opposite directions.'),
 dict(q='If AD decreases and SRAS increases, real GDP', choices=[
   'definitely rises',
   'is ambiguous, while the price level definitely falls',
   'definitely falls',
   'is unchanged',
   'and the price level both rise'], ans=1,
   why='Both shifts lower the price level, but their effects on output offset.'),
 dict(q='If both AD and SRAS decrease, real GDP', choices=[
   'definitely falls, while the effect on the price level is ambiguous',
   'is unchanged',
   'falls only if prices rise',
   'cannot be signed',
   'definitely rises'], ans=0,
   why='Both contractions reduce output, while one lowers prices and the other raises them.'),
 dict(q='An economy experiences rising unemployment and rising inflation at the same time. The most likely cause is', choices=[
   'a decrease in aggregate demand',
   'a positive supply shock',
   'an increase in potential output',
   'an increase in aggregate demand',
   'a negative supply shock'], ans=4,
   why='A demand change moves inflation and unemployment in opposite directions; only a supply shock moves both up.'),
 dict(q='An economy experiences falling unemployment and falling inflation at the same time. The most likely cause is', choices=[
   'an increase in aggregate demand',
   'a leftward shift of LRAS',
   'a decrease in aggregate demand',
   'a positive supply shock that shifts SRAS right',
   'a negative supply shock'], ans=3,
   why='Only a rightward SRAS shift raises output, which lowers unemployment, while lowering the price level.'),
 dict(q='A sharp cut in personal income taxes when the economy has substantial slack will most likely', choices=[
   'have no effect on either variable',
   'raise the price level a great deal and output very little',
   'raise output substantially with only a modest rise in the price level',
   'lower output',
   'shift SRAS left'], ans=2,
   why='Where SRAS is relatively flat, extra demand is absorbed mainly by putting idle resources to work.'),
 dict(q='The same increase in aggregate demand applied to an economy already producing beyond potential will mostly', choices=[
   'raise real output',
   'raise the price level, because SRAS is steep near capacity',
   'lower the price level',
   'lower output',
   'shift LRAS right'], ans=1,
   why='With few idle resources, added demand bids up input prices rather than generating much more output.'),
 dict(q='A fall in nominal wages negotiated across the economy will in the short run', choices=[
   'shift SRAS right, raising output and lowering the price level',
   'shift AD right',
   'shift AD left',
   'leave both curves unchanged',
   'shift SRAS left, raising prices'], ans=0,
   why='Lower labor costs let firms supply more output at every price level.'),
 dict(q='An increase in the money supply that lowers interest rates will in the short run', choices=[
   'shift AD left',
   'shift SRAS left',
   'lower the price level',
   'shift SRAS right',
   'shift AD right, raising output and the price level'], ans=4,
   why='Cheaper credit raises investment and interest-sensitive consumption, which are components of AD.'),
 dict(q='A currency depreciation that makes exports cheaper abroad will in the short run', choices=[
   'lower output',
   'leave AD unchanged',
   'shift AD left',
   'shift AD right through higher net exports, raising output and the price level',
   'shift SRAS right'], ans=3,
   why='Net exports rise, and net exports are part of aggregate demand.'),
 dict(q='Which of the following would shift AD left and raise unemployment in the short run?', choices=[
   'an increase in consumer wealth',
   'an increase in government purchases',
   'a sharp increase in personal income taxes',
   'a fall in interest rates',
   'an increase in exports'], ans=2,
   why='Higher taxes reduce disposable income and consumption, shrinking aggregate demand.'),
 dict(q='An economy experiences a rightward shift of AD while output was already at potential. In the short run this creates', choices=[
   'a recessionary gap',
   'an inflationary gap with unemployment below the natural rate',
   'stagflation',
   'no gap',
   'a fall in the price level'], ans=1,
   why='Output pushed beyond potential means unusually tight labor markets and rising prices.'),
 dict(q='Suppose oil prices fall sharply while consumer confidence collapses. In the short run the price level', choices=[
   'definitely falls, while the effect on real GDP is ambiguous',
   'is unchanged',
   'and output both rise',
   'cannot be determined',
   'definitely rises'], ans=0,
   why='A rightward SRAS shift and a leftward AD shift both push the price level down but pull output in opposite directions.'),
 dict(q='Suppose the government raises spending sharply at the same time that a hurricane damages refineries and raises energy costs. Real GDP', choices=[
   'definitely falls',
   'is unchanged',
   'falls and the price level falls',
   'definitely rises',
   'may rise or fall, while the price level definitely rises'], ans=4,
   why='An AD increase and an SRAS decrease both raise prices while working against each other on output.'),
 dict(q='In the short run, which variable moves in the same direction as real GDP for a demand shock but in the opposite direction for a supply shock?', choices=[
   'the money supply',
   'potential output',
   'employment',
   'the price level',
   'the unemployment rate'], ans=3,
   why='A demand shock moves output and prices together; a supply shock moves them apart.'),
 dict(q='A leftward shift of SRAS raises the unemployment rate because', choices=[
   'potential output falls',
   'the price level falls',
   'firms produce less output and therefore employ fewer workers',
   'the labor force grows',
   'wages fall'], ans=2,
   why='Lower real output requires less labor, which shows up as cyclical unemployment.'),
 dict(q='Which policy response would most directly offset the output loss from a leftward shift of AD?', choices=[
   'raising taxes',
   'increasing government spending',
   'cutting government spending',
   'raising interest rates',
   'reducing transfer payments'], ans=1,
   why='Adding to a component of aggregate demand can shift AD back toward its original position.'),
 dict(q='A negative supply shock that policymakers offset by increasing aggregate demand will result in', choices=[
   'both output and the price level restored to their original values',
   'a lower price level than before the shock',
   'no change in the price level',
   'output permanently below potential',
   'output restored but a still higher price level'], ans=4,
   why='Pushing AD right restores output but adds further upward pressure to an already elevated price level.'),
 dict(q='A positive supply shock in the short run affects the price level and real GDP', choices=[
   'not at all',
   'with output down and prices down',
   'with output up and prices up',
   'in the same direction',
   'in opposite directions, with output up and prices down'], ans=4,
   why='Moving down along a fixed AD curve means more output sold at a lower price level.'),
 dict(q='If aggregate demand increases while long-run aggregate supply is unchanged, the short-run gain in output is', choices=[
   'accompanied by falling prices',
   'matched by a leftward AD shift',
   'permanent',
   'temporary, because output above potential is not sustainable',
   'always zero'], ans=3,
   why='Output beyond potential eventually triggers rising wages that pull SRAS back.'),
 dict(q='Which of the following best describes the short-run effect of a large tariff increase that raises the cost of imported components?', choices=[
   'unemployment falls',
   'SRAS shifts right and prices fall',
   'SRAS shifts left, raising the price level and lowering real GDP',
   'AD shifts right',
   'LRAS shifts right'], ans=2,
   why='More expensive imported inputs raise domestic production costs, which is a negative supply shock.'),
 dict(q='An economy in a recessionary gap experiences a further leftward shift of AD. The gap will', choices=[
   'close',
   'widen, with output falling further below potential',
   'become an inflationary gap',
   'disappear',
   'reverse'], ans=1,
   why='Additional demand weakness moves output still further from potential.'),
 dict(q='Which pair of short-run outcomes cannot result from a single shift of one curve?', choices=[
   'output up and unemployment up',
   'output down and prices up',
   'output up and prices down',
   'output down and prices down',
   'output up and prices up'], ans=0,
   why='More output always requires more employment in the short run, so output and unemployment cannot both rise.'),
 dict(q='Which short-run outcome follows a fall in the price of a widely used imported raw material?', choices=[
   'output falls and the price level falls',
   'nothing changes',
   'output falls and the price level rises',
   'output rises and the price level falls',
   'output rises and the price level rises'], ans=3,
   why='Lower input costs shift SRAS right, moving the economy down along aggregate demand.'),
 dict(q="A country's central bank sharply raises interest rates. In the short run this will most likely", choices=[
   'raise the price level',
   'shift SRAS right',
   'shift AD left, lowering output and the price level and raising unemployment',
   'shift AD right',
   'shift LRAS left'], ans=2,
   why='Dearer credit reduces investment and interest-sensitive consumption, contracting aggregate demand.'),
 dict(q='Comparing a demand shock with a supply shock of equal size, the demand shock', choices=[
   'moves inflation and unemployment in the same direction',
   'moves inflation and unemployment in opposite directions, while the supply shock moves them together',
   'affects only the price level',
   'affects only output',
   'has no effect on unemployment'], ans=1,
   why='This contrast is the reason a negative supply shock is uniquely awkward for stabilization policy.'),
 dict(q='An increase in aggregate demand raises the price level more, the', choices=[
   'steeper the SRAS curve',
   'further the economy is below potential',
   'larger the amount of idle capacity',
   'lower the current price level',
   'flatter the SRAS curve'], ans=0,
   why='A steep SRAS means each additional unit of output comes with a large increase in costs and prices.'),
 dict(q='An economy sees real GDP rise while the price level is roughly unchanged. The most consistent explanation is', choices=[
   'a large SRAS decrease alone',
   'an AD decrease alone',
   'an SRAS decrease alone',
   'a large AD increase alone',
   'AD and SRAS both increasing, with the price effects offsetting'], ans=4,
   why='Two rightward shifts both raise output while their opposite price effects cancel.'),
 dict(q='Which of the following would move an economy from a recessionary gap toward potential output without raising the price level?', choices=[
   'a decrease in short-run aggregate supply',
   'an increase in taxes',
   'an increase in aggregate demand',
   'an increase in short-run aggregate supply from lower input costs',
   'a decrease in aggregate demand'], ans=3,
   why='A rightward SRAS shift raises output while lowering rather than raising prices.'),
 dict(q='After a negative supply shock, the short-run equilibrium lies', choices=[
   'below the horizontal axis',
   'to the right of LRAS with a lower price level',
   'to the left of LRAS with a higher price level',
   'exactly on LRAS',
   'to the right of LRAS with a higher price level'], ans=2,
   why='Output falls below potential while the price level rises, which is the stagflation position on the diagram.'),
 dict(q='Which of the following statements about short-run shifts is FALSE?', choices=[
   'An AD increase raises output and the price level.',
   'An SRAS decrease raises the price level and lowers output.',
   'An SRAS increase lowers the price level and raises output.',
   'An AD decrease lowers output and raises the price level.',
   'An AD decrease raises unemployment.'], ans=3,
   why='A fall in aggregate demand lowers the price level rather than raising it; only a supply contraction raises prices while cutting output.'),
]
