# MACRO 3.7 Long-Run Self-Adjustment — 50 questions
# The two adjustment paths, worked out so every answer below follows from them:
#   Recessionary gap (output below potential):
#     unemployment above natural rate -> nominal wages and other input prices
#     fall or grow slowly -> SRAS shifts RIGHT -> output rises back to potential
#     and the price level FALLS. Ends at a lower price level than during the gap.
#   Inflationary gap (output above potential):
#     unemployment below natural rate -> nominal wages bid UP -> SRAS shifts LEFT
#     -> output falls back to potential and the price level RISES.
#   In both cases the endpoint is output = potential (on LRAS) with the price
#   level having moved; real output is unchanged in the long run.
TOPIC = ("3.7", "Long-Run Self-Adjustment", 3)
QUESTIONS = [
 dict(q='Long-run self-adjustment refers to the idea that', choices=[
   'the government always closes output gaps',
   'an economy in a recessionary or inflationary gap returns to potential output on its own through changes in nominal wages and other input prices',
   'potential output changes to match actual output',
   'aggregate demand automatically returns to its original position',
   'output gaps never close'], ans=1,
   why='Self-correction works through the input-price side, shifting SRAS rather than requiring a policy change.'),
 dict(q='In a recessionary gap, the mechanism that closes the gap without policy is', choices=[
   'falling or slower-growing nominal wages and input prices, which shift SRAS right',
   'a rightward shift of AD',
   'a leftward shift of LRAS',
   'an increase in taxes',
   'rising nominal wages'], ans=0,
   why="Persistent unemployment weakens workers' bargaining position, lowering costs and increasing short-run supply."),
 dict(q='In an inflationary gap, the mechanism that closes the gap without policy is', choices=[
   'a rightward shift of SRAS',
   'a rightward shift of LRAS',
   'a fall in the price level',
   'falling nominal wages',
   'rising nominal wages and input prices, which shift SRAS left'], ans=4,
   why='Tight labor markets bid wages up, raising production costs and reducing short-run supply.'),
 dict(q='When a recessionary gap closes through self-adjustment, the final long-run outcome is', choices=[
   'output permanently lower',
   'no change in the price level',
   'output above potential and a higher price level',
   'output back at potential and a lower price level',
   'output back at potential and a higher price level'], ans=3,
   why='The rightward SRAS shift restores potential output while pushing the price level down.'),
 dict(q='When an inflationary gap closes through self-adjustment, the final long-run outcome is', choices=[
   'no change in the price level',
   'output back at potential and a higher price level',
   'output back at potential and a lower price level',
   'output permanently higher',
   'output permanently lower'], ans=1,
   why='The leftward SRAS shift returns output to potential but leaves prices higher than at the peak of the boom.'),
 dict(q='Self-adjustment implies that in the long run, real GDP', choices=[
   'is determined by aggregate demand',
   'returns to the level given by the LRAS curve',
   'grows without limit',
   'falls to zero',
   'equals nominal GDP'], ans=1,
   why="Vertical LRAS means the economy's sustainable output is a supply-side quantity that demand cannot permanently change."),
 dict(q='Starting from long-run equilibrium, an increase in aggregate demand has which long-run effect after full self-adjustment?', choices=[
   'a higher price level with real GDP back at potential',
   'a lower price level',
   'permanently lower unemployment',
   'a rightward shift of LRAS',
   'permanently higher real GDP'], ans=0,
   why='The short-run output gain is erased as wages catch up, leaving only a higher price level.'),
 dict(q='Starting from long-run equilibrium, a decrease in aggregate demand has which long-run effect after full self-adjustment?', choices=[
   'a higher price level',
   'permanently higher unemployment',
   'a leftward shift of LRAS',
   'permanently lower real GDP',
   'a lower price level with real GDP back at potential'], ans=4,
   why='Falling wages eventually restore output to potential at a lower price level.'),
 dict(q='During self-adjustment out of a recessionary gap, unemployment', choices=[
   'is unaffected',
   'rises above the natural rate permanently',
   'rises further and stays high',
   'falls back toward the natural rate as output returns to potential',
   'falls to zero'], ans=3,
   why='Restoring output to potential eliminates cyclical unemployment.'),
 dict(q='During self-adjustment out of an inflationary gap, unemployment', choices=[
   'is unaffected',
   'falls further below the natural rate',
   'rises back toward the natural rate as output returns to potential',
   'stays below the natural rate permanently',
   'falls to zero'], ans=2,
   why='Output falling back to potential means employment returns to its sustainable level.'),
 dict(q='The self-adjustment process is often described as slow mainly because', choices=[
   'the government blocks it',
   'nominal wages are sticky downward, so they fall only reluctantly and gradually',
   'prices never change',
   'potential output is unknown',
   'firms cannot change output'], ans=1,
   why='Workers and firms resist nominal pay cuts, so the cost adjustment that closes a recessionary gap takes a long time.'),
 dict(q='Downward wage stickiness implies that self-adjustment is', choices=[
   'slower out of a recessionary gap than an inflationary gap',
   'equally fast in both directions',
   'instantaneous',
   'impossible in either direction',
   'faster out of a recessionary gap than an inflationary gap'], ans=0,
   why='Wages rise readily in a boom but fall only with difficulty in a slump, making downward adjustment the slower case.'),
 dict(q='Which of the following best explains why nominal wages fall only slowly in a recession?', choices=[
   'the government sets all wages',
   'firms cannot observe the price level',
   'unemployment does not affect wages',
   'workers have no preferences about pay',
   'long-term contracts, minimum wage laws, and the damage pay cuts do to morale and retention'], ans=4,
   why='Institutional and behavioral factors keep nominal pay from adjusting downward quickly.'),
 dict(q="Keynes's argument against relying on self-adjustment was essentially that", choices=[
   'prices are perfectly flexible',
   'aggregate demand cannot be influenced',
   'self-adjustment does not exist in theory',
   'the adjustment may take so long that the human cost of prolonged unemployment is unacceptable',
   'potential output falls automatically'], ans=3,
   why='The famous point is that in the long run we are all dead, so waiting is not a neutral choice.'),
 dict(q='An economist who favors active fiscal policy over waiting for self-adjustment would emphasize', choices=[
   'the balanced budget multiplier',
   'the speed of wage adjustment',
   'the length and cost of the adjustment period, including lost output and long-term unemployment',
   'the neutrality of money',
   'the vertical LRAS curve'], ans=2,
   why='The case for policy rests on the claim that the self-correcting mechanism is too slow to be relied upon.'),
 dict(q='An economist skeptical of active stabilization policy would emphasize', choices=[
   'the impossibility of self-adjustment',
   'policy lags and the risk that stimulus arrives after the economy has already self-corrected, adding only inflation',
   'the stickiness of wages',
   'the size of the multiplier',
   'the depth of the output gap'], ans=1,
   why='If recognition, decision, and implementation lags are long, a policy can arrive too late and destabilize instead.'),
 dict(q='Long-term unemployment during a slow adjustment can raise the natural rate of unemployment because', choices=[
   "workers' skills and attachment to the labor force erode, a process called hysteresis",
   'the labor force grows',
   'wages rise',
   'potential output is unaffected by unemployment',
   'workers gain skills while unemployed'], ans=0,
   why="If a long slump permanently damages workers' employability, LRAS itself can shift left, which is an argument against waiting."),
 dict(q='Self-adjustment out of a recessionary gap is shown on the AD-AS diagram as', choices=[
   'SRAS shifting left',
   'LRAS shifting left',
   'AD shifting left',
   'AD shifting right',
   'SRAS shifting right until it intersects AD on the LRAS curve'], ans=4,
   why='Falling input costs move the short-run supply curve right until output equals potential.'),
 dict(q='Self-adjustment out of an inflationary gap is shown on the AD-AS diagram as', choices=[
   'LRAS shifting right',
   'AD shifting right',
   'AD shifting left',
   'SRAS shifting left until it intersects AD on the LRAS curve',
   'SRAS shifting right'], ans=3,
   why='Rising input costs move short-run supply left until output falls back to potential.'),
 dict(q='After a negative supply shock, if policymakers do nothing, the economy will eventually', choices=[
   'experience permanent deflation',
   'stay permanently below potential',
   'return to potential output as the shock passes and input prices fall back, restoring SRAS',
   'move further from potential',
   'see LRAS shift left permanently'], ans=2,
   why='A temporary cost shock unwinds, and the resulting rightward SRAS shift restores potential output.'),
 dict(q='In the long run, the only lasting effect of a demand shock in the basic AD-AS model is on', choices=[
   'real GDP',
   'the price level',
   'potential output',
   'the natural rate of unemployment',
   'the capital stock'], ans=1,
   why='Because LRAS is vertical, the price level absorbs the whole of a permanent demand change.'),
 dict(q='An economy is in a recessionary gap. Which of the following describes the self-correction path?', choices=[
   'wages and input prices fall, SRAS shifts right, output rises and the price level falls',
   'wages rise, SRAS shifts left, output falls',
   'AD shifts right on its own',
   'LRAS shifts left to meet output',
   'prices rise, then output falls'], ans=0,
   why='The gap closes through cheaper inputs raising short-run supply, not through a change in demand or capacity.'),
 dict(q='An economy is in an inflationary gap. Which of the following describes the self-correction path?', choices=[
   'AD shifts left on its own',
   'LRAS shifts right',
   'nothing happens',
   'wages fall, SRAS shifts right',
   'wages rise, SRAS shifts left, output falls back to potential and the price level rises further'], ans=4,
   why='Workers demand higher pay when labor is scarce, raising costs and pulling output back to potential.'),
 dict(q='During the adjustment out of an inflationary gap, the price level', choices=[
   'falls then rises',
   'becomes zero',
   'falls',
   'rises further before the economy settles at potential',
   'stays constant'], ans=3,
   why='A leftward SRAS shift along a fixed AD curve raises the price level as output declines.'),
 dict(q='During the adjustment out of a recessionary gap, the price level', choices=[
   'becomes negative',
   'rises',
   'falls as SRAS shifts right',
   'stays constant',
   'rises then falls'], ans=2,
   why='Cheaper inputs lower prices while output expands along the AD curve.'),
 dict(q='The self-adjustment mechanism relies on the assumption that', choices=[
   'input prices are permanently fixed',
   'input prices eventually respond to conditions in labor and resource markets',
   'aggregate demand is vertical',
   'the government intervenes',
   'potential output changes with demand'], ans=1,
   why='Without flexible input prices in the long run, SRAS would never shift and the gap would persist.'),
 dict(q='Suppose a recessionary gap has persisted for several years with little wage adjustment. This observation is evidence for', choices=[
   'the view that wages are sticky and self-correction can be slow',
   'a vertical SRAS curve',
   'the neutrality of money',
   'an inflationary gap',
   'very rapid self-correction'], ans=0,
   why='A persistent gap is exactly what the sticky-wage critique of self-adjustment predicts.'),
 dict(q='Which statement about the long-run outcome of an increase in aggregate demand is correct?', choices=[
   'Both output and the price level end where they started.',
   'Output ends higher and the price level ends where it started.',
   'Output ends lower and prices end lower.',
   'Both output and the price level end up permanently higher.',
   'Output ends where it started while the price level ends higher.'], ans=4,
   why='Self-adjustment erases the real gain and leaves only the nominal one.'),
 dict(q='If a country repeatedly uses demand stimulus to keep output above potential, the long-run result is likely to be', choices=[
   'a rightward shift of LRAS',
   'a lower natural rate of unemployment',
   'permanently higher real GDP',
   'persistent inflation with real GDP near potential',
   'permanent deflation'], ans=3,
   why='Each round of stimulus is eventually absorbed by higher wages and prices rather than sustained output.'),
 dict(q='The speed of self-adjustment depends most on', choices=[
   'the number of firms',
   'the size of the government budget',
   'how quickly nominal wages and other input prices respond to labor market conditions',
   'the level of potential output',
   'the exchange rate'], ans=2,
   why='The whole mechanism runs through input-price flexibility.'),
 dict(q='A critic of the self-adjustment argument would most likely point out that', choices=[
   'LRAS is vertical',
   'wages rarely fall in nominal terms, so a recessionary gap can persist for years',
   'SRAS slopes upward',
   'aggregate demand slopes downward',
   'the multiplier exists'], ans=1,
   why='Downward nominal wage rigidity is the central empirical objection to relying on self-correction.'),
 dict(q='Which of the following is NOT part of the self-adjustment mechanism?', choices=[
   'changes in the position of the LRAS curve',
   'shifts of the SRAS curve',
   'changes in input prices',
   'movement of output back toward potential',
   'changes in nominal wages'], ans=0,
   why="Self-adjustment moves short-run supply; the economy's capacity itself is taken as given."),
 dict(q='After full self-adjustment from an inflationary gap, the unemployment rate is', choices=[
   'zero',
   'above the natural rate permanently',
   'unrelated to the natural rate',
   'below the natural rate',
   'equal to the natural rate'], ans=4,
   why='Output back at potential corresponds precisely to the natural rate of unemployment.'),
 dict(q='An economy has an inflationary gap and the central bank does nothing. Compared with a policy that closes the gap immediately by reducing AD, the self-adjustment path ends with', choices=[
   'the same output and the same price level',
   'higher output and a higher price level',
   'the same output but a higher price level',
   'lower output and a lower price level',
   'higher output and the same price level'], ans=2,
   why='Both paths return output to potential, but demand restraint lowers prices while wage-driven adjustment raises them.'),
 dict(q='An economy has a recessionary gap and the government does nothing. Compared with a fiscal stimulus that closes the gap, the self-adjustment path ends with', choices=[
   'lower output and a higher price level',
   'the same output but a lower price level',
   'higher output and a higher price level',
   'lower output permanently',
   'the same output and the same price level'], ans=1,
   why='Both restore potential output, but stimulus raises the price level while falling wages lower it.'),
 dict(q='One reason firms avoid cutting nominal wages even in a downturn is that', choices=[
   'wage cuts are illegal everywhere',
   'pay cuts damage morale and cause the best workers to leave',
   'wages have no effect on costs',
   'unemployment does not exist',
   'labor is not a factor of production'], ans=1,
   why='Efficiency wage considerations make firms prefer layoffs to across-the-board pay cuts.'),
 dict(q='Which of the following would speed up the self-adjustment out of a recessionary gap?', choices=[
   'highly flexible labor markets in which wages respond quickly to unemployment',
   'a legally binding wage floor above the market wage',
   'indexation of wages to past inflation',
   'strong downward wage rigidity',
   'longer, more rigid labor contracts'], ans=0,
   why='The faster input prices respond, the faster SRAS shifts and the gap closes.'),
 dict(q='Wage indexation, which automatically raises wages with inflation, tends to', choices=[
   'eliminate output gaps',
   'make LRAS shift right',
   'have no effect on SRAS',
   'speed up adjustment out of an inflationary gap',
   'slow the closing of an inflationary gap by embedding higher costs and further shifting SRAS left'], ans=4,
   why='Automatic wage increases feed cost pressure back into the system, prolonging adjustment.'),
 dict(q='The long-run neutrality of money is an application of self-adjustment because', choices=[
   'SRAS is vertical',
   'AD is vertical',
   'money changes potential output',
   'a monetary expansion raises output only until wages and prices adjust, after which only the price level is higher',
   'money has no effect at all'], ans=3,
   why='The temporary real effect disappears once input prices catch up with the higher price level.'),
 dict(q='Which of the following observations would most challenge the view that economies self-correct quickly?', choices=[
   'output returning to potential within a quarter',
   'wages rising rapidly during a boom',
   'unemployment remaining well above the natural rate for a decade with little wage decline',
   'the price level rising after a demand increase',
   'SRAS shifting right after oil prices fall'], ans=2,
   why='A decade-long gap with no wage response is the opposite of what fast self-correction predicts.'),
 dict(q='If potential output itself falls because a long slump destroys skills and capital, then', choices=[
   'the recessionary gap closes faster',
   'LRAS shifts left, so the economy returns to a lower potential output rather than the original one',
   'the price level must rise',
   'self-adjustment is instant',
   'the natural rate falls'], ans=1,
   why='Hysteresis means the long slump changes capacity, so the destination of adjustment is worse than the starting point.'),
 dict(q='Consider an economy that receives a permanent increase in aggregate demand. In the short run output rises; in the long run', choices=[
   'wages rise, SRAS shifts left, and output returns to potential at a higher price level',
   'LRAS shifts right to accommodate the new demand',
   'the price level returns to its original level',
   'unemployment stays below the natural rate',
   'output stays above potential'], ans=0,
   why='This is the standard demand-shock adjustment path in the AD-AS model.'),
 dict(q='Which combination correctly describes the SRAS movement during self-adjustment?', choices=[
   'both gaps — SRAS shifts right',
   'both gaps — SRAS shifts left',
   'neither gap moves SRAS',
   'recessionary gap — SRAS shifts left; inflationary gap — SRAS shifts right',
   'recessionary gap — SRAS shifts right; inflationary gap — SRAS shifts left'], ans=4,
   why='Costs fall in a slump and rise in a boom, moving short-run supply in opposite directions.'),
 dict(q='During self-adjustment, the LRAS curve', choices=[
   'disappears',
   'shifts left in every case',
   'shifts to meet the short-run equilibrium',
   'stays where it is, since the process changes costs rather than capacity',
   'becomes upward sloping'], ans=3,
   why='Potential output is determined by resources and technology, which the wage adjustment process does not change.'),
 dict(q='Self-adjustment implies that the long-run Phillips curve relationship is', choices=[
   'undefined',
   'a stable trade-off between inflation and unemployment',
   'vertical at the natural rate of unemployment, since output returns to potential whatever the inflation rate',
   'downward sloping forever',
   'upward sloping'], ans=2,
   why='If output always returns to potential, no permanent inflation-unemployment trade-off can exist.'),
 dict(q='An economy experiences a temporary boom driven by a surge in exports. Without policy, in the long run the boom', choices=[
   'becomes permanent',
   'ends as rising wages shift SRAS left and output falls back to potential',
   'causes LRAS to shift right',
   'leads to deflation',
   'lowers the natural rate of unemployment'], ans=1,
   why='A demand-driven expansion beyond potential is unwound by the input-price response.'),
 dict(q='The main practical disagreement about self-adjustment is over', choices=[
   'how long the adjustment takes and how costly the waiting is',
   'whether SRAS slopes upward',
   'whether AD slopes downward',
   'whether output gaps exist',
   'whether LRAS is vertical'], ans=0,
   why='Most economists accept the mechanism in principle; the argument is about speed and the cost of the transition.'),
 dict(q='If nominal wages were perfectly flexible in both directions, the economy would', choices=[
   'experience permanent recessions',
   'have a horizontal SRAS',
   'have no LRAS curve',
   'never reach potential output',
   'return to potential almost immediately, making SRAS effectively vertical'], ans=4,
   why='The upward slope of SRAS exists only because input prices lag the price level.'),
 dict(q='Following a positive supply shock that later reverses, the economy', choices=[
   'experiences permanent inflation',
   'sees AD shift left',
   'remains permanently above potential',
   'returns to potential as SRAS shifts back to its original position',
   'sees LRAS shift right permanently'], ans=3,
   why='A temporary cost change has no lasting effect on capacity, so the short-run curve returns.'),
 dict(q='Which statement about self-adjustment is FALSE?', choices=[
   'It leaves the price level different from its level during the gap.',
   'It works through changes in nominal wages and input prices.',
   'It returns output to potential in the long run.',
   'It shifts the LRAS curve to close the gap.',
   'It can be slow when wages are sticky downward.'], ans=3,
   why='Self-adjustment moves SRAS, not LRAS; potential output is unchanged by the process.'),
]
