# MACRO 3.8 Fiscal Policy — 50 questions
# Every numeric answer below, worked out:
#   Multipliers used: MPC 0.5 -> k 2, tax mult -1 ; MPC 0.6 -> k 2.5, tax mult -1.5
#     MPC 0.75 -> k 4, tax mult -3 ; MPC 0.8 -> k 5, tax mult -4 ; MPC 0.9 -> k 10, tax mult -9
#   Gap 300, MPC 0.75 -> spending 300/4 = 75 ; tax cut 300/3 = 100
#   Gap 500, MPC 0.8  -> spending 500/5 = 100 ; tax cut 500/4 = 125
#   Gap 800, MPC 0.9  -> spending 800/10 = 80
#   Gap 200, MPC 0.5  -> spending 200/2 = 100 ; tax cut 200/1 = 200
#   Gap 250, MPC 0.6  -> spending 250/2.5 = 100
#   Inflationary gap 400, MPC 0.8 -> cut spending 400/5 = 80, or raise taxes 400/4 = 100
#   Inflationary gap 600, MPC 0.75 -> cut spending 600/4 = 150
#   Spending 40 with MPC 0.8 -> 5 x 40 = 200 change in GDP
TOPIC = ("3.8", "Fiscal Policy", 3)
QUESTIONS = [
 dict(q='Fiscal policy refers to', choices=[
   'central bank changes in the money supply and interest rates',
   'government decisions about spending and taxation used to influence the economy',
   'regulation of banks',
   'management of the exchange rate',
   'control of wages and prices'], ans=1,
   why='Fiscal policy is the spending and taxing side of government, which is separate from monetary policy.'),
 dict(q='Expansionary fiscal policy consists of', choices=[
   'increasing government spending or cutting taxes',
   'raising interest rates',
   'reducing the money supply',
   'increasing tariffs',
   'increasing taxes or cutting government spending'], ans=0,
   why='Both tools raise aggregate demand by adding to spending or to disposable income.'),
 dict(q='Contractionary fiscal policy consists of', choices=[
   'lowering interest rates',
   'expanding the money supply',
   'depreciating the currency',
   'cutting taxes or raising government spending',
   'cutting government spending or raising taxes'], ans=4,
   why='Both tools reduce aggregate demand, which is appropriate when output is above potential.'),
 dict(q='Expansionary fiscal policy is the appropriate response to', choices=[
   'a positive supply shock',
   'a balanced budget',
   'an inflationary gap',
   'a recessionary gap',
   'long-run equilibrium'], ans=3,
   why='When output is below potential, boosting aggregate demand moves the economy toward full employment.'),
 dict(q='Contractionary fiscal policy is the appropriate response to', choices=[
   'long-run equilibrium',
   'a recessionary gap',
   'an inflationary gap',
   'high unemployment',
   'a negative demand shock'], ans=2,
   why='When output exceeds potential, reducing aggregate demand relieves inflationary pressure.'),
 dict(q='An increase in government spending shifts', choices=[
   'SRAS right',
   'AD right, raising output and the price level in the short run',
   'AD left',
   'LRAS left',
   'SRAS left'], ans=1,
   why='Government purchases are a component of aggregate demand.'),
 dict(q='A cut in personal income taxes shifts AD right because', choices=[
   'it raises disposable income, and households spend the MPC fraction of it',
   'it lowers production costs',
   'it raises the money supply',
   'it reduces imports',
   'it directly buys output'], ans=0,
   why='Taxes act on aggregate demand indirectly, through consumption.'),
 dict(q='An economy has a recessionary gap of $300 billion and an MPC of 0.75. Government spending must rise by, in billions of dollars,', choices=[
   '60',
   '75',
   '100',
   '225',
   '300'], ans=1,
   why='The spending multiplier is 4, so 300/4 = 75 closes the gap.'),
 dict(q='The same economy, with a recessionary gap of $300 billion and an MPC of 0.75, could instead cut taxes by, in billions of dollars,', choices=[
   '75',
   '100',
   '150',
   '225',
   '300'], ans=1,
   why='The tax multiplier has magnitude 3, so a cut of 300/3 = 100 is required.'),
 dict(q='An economy has a recessionary gap of $500 billion and an MPC of 0.8. The required increase in government spending, in billions of dollars, is', choices=[
   '80',
   '100',
   '125',
   '400',
   '500'], ans=1,
   why='With a multiplier of 5, spending must rise by 500/5 = 100.'),
 dict(q='An economy has a recessionary gap of $500 billion and an MPC of 0.8. The required tax cut, in billions of dollars, is', choices=[
   '100',
   '125',
   '200',
   '400',
   '500'], ans=1,
   why='The tax multiplier magnitude is 4, so the cut must be 500/4 = 125.'),
 dict(q='An economy has a recessionary gap of $800 billion and an MPC of 0.9. The required increase in government spending, in billions of dollars, is', choices=[
   '80',
   '89',
   '160',
   '720',
   '800'], ans=0,
   why='The multiplier is 10, so 800/10 = 80 is enough.'),
 dict(q='An economy has a recessionary gap of $200 billion and an MPC of 0.5. The required increase in government spending, in billions of dollars, is', choices=[
   '50',
   '100',
   '150',
   '200',
   '400'], ans=1,
   why='With a multiplier of 2, spending must rise by 200/2 = 100.'),
 dict(q='An economy has a recessionary gap of $200 billion and an MPC of 0.5. The required tax cut, in billions of dollars, is', choices=[
   '50',
   '100',
   '150',
   '200',
   '400'], ans=3,
   why='The tax multiplier is −1 when MPC is 0.5, so the tax cut must equal the whole gap.'),
 dict(q='An economy has a recessionary gap of $250 billion and an MPC of 0.6. The required increase in government spending, in billions of dollars, is', choices=[
   '60',
   '100',
   '125',
   '150',
   '250'], ans=1,
   why='The multiplier is 2.5, so 250/2.5 = 100.'),
 dict(q='An economy has an inflationary gap of $400 billion and an MPC of 0.8. Government spending should be cut by, in billions of dollars,', choices=[
   '80',
   '100',
   '160',
   '320',
   '400'], ans=0,
   why='With a multiplier of 5, a cut of 400/5 = 80 removes the gap.'),
 dict(q='An economy has an inflationary gap of $400 billion and an MPC of 0.8. Taxes should instead be raised by, in billions of dollars,', choices=[
   '80',
   '100',
   '160',
   '320',
   '400'], ans=1,
   why='The tax multiplier magnitude is 4, so a tax increase of 400/4 = 100 is needed.'),
 dict(q='An economy has an inflationary gap of $600 billion and an MPC of 0.75. Government spending should be cut by, in billions of dollars,', choices=[
   '100',
   '150',
   '200',
   '450',
   '600'], ans=1,
   why='The multiplier is 4, so 600/4 = 150.'),
 dict(q='Government spending rises by $40 billion in an economy with an MPC of 0.8. Real GDP rises by, in billions of dollars,', choices=[
   '32',
   '40',
   '80',
   '160',
   '200'], ans=4,
   why='The multiplier is 5, so the change in output is 5 × 40 = 200.'),
 dict(q='To close a given gap, a policymaker using tax changes rather than spending changes must use', choices=[
   'an amount that does not depend on the MPC',
   'a smaller dollar amount',
   'a larger dollar amount, because the tax multiplier is smaller in magnitude',
   'exactly the same dollar amount',
   'no policy at all'], ans=2,
   why='Part of any tax cut is saved, so the first-round injection is smaller than under direct spending.'),
 dict(q='The two main tools of fiscal policy are', choices=[
   'the discount rate and reserve requirements',
   'government spending and taxation',
   'open market operations and the money supply',
   'tariffs and quotas',
   'wage and price controls'], ans=1,
   why='Interest rate and money supply tools belong to monetary policy, not fiscal policy.'),
 dict(q='Discretionary fiscal policy means', choices=[
   'deliberate changes in spending or tax law enacted to stabilize the economy',
   'central bank action',
   'changes in the exchange rate',
   'regulation of industry',
   'changes in spending and taxes that occur automatically with the business cycle'], ans=0,
   why='Discretionary action requires new legislation, unlike automatic stabilizers.'),
 dict(q='The recognition lag in fiscal policy refers to the time it takes to', choices=[
   'spend appropriated funds',
   'for the multiplier to work',
   'change interest rates',
   'pass legislation',
   'collect and analyze data showing that the economy has entered a downturn'], ans=4,
   why='Macroeconomic data arrive with a delay and are revised, so a recession is often identified only months after it begins.'),
 dict(q='The legislative or decision lag in fiscal policy refers to', choices=[
   'the time for prices to adjust',
   'the time for wages to fall',
   'the delay in collecting data',
   'the time required for a legislature to debate, amend, and pass a fiscal package',
   'the time for spending to reach the economy'], ans=3,
   why='Fiscal action requires political agreement, which can take many months.'),
 dict(q='The implementation lag in fiscal policy refers to', choices=[
   'the stickiness of wages',
   'the delay before data are available',
   'the time between enacting a policy and the money actually being spent in the economy',
   'the delay in setting interest rates',
   'the speed of the multiplier'], ans=2,
   why='Even after a bill passes, projects must be planned and contracted before spending occurs.'),
 dict(q='Long policy lags create the risk that', choices=[
   'fiscal policy has no effect at all',
   'stimulus arrives after the economy has already recovered, adding to inflation rather than output',
   'the multiplier becomes negative',
   'taxes cannot be changed',
   'potential output falls'], ans=1,
   why='Badly timed policy can amplify rather than dampen the business cycle.'),
 dict(q='Compared with tax changes, government spending on goods and services affects aggregate demand', choices=[
   'more strongly per dollar, because the whole amount enters the spending stream immediately',
   'identically per dollar',
   'not at all',
   'only after wages adjust',
   'less strongly per dollar'], ans=0,
   why='A purchase is spending by definition, while a tax cut is spent only in the MPC proportion.'),
 dict(q='A budget deficit occurs when', choices=[
   'the national debt is zero',
   'taxes are progressive',
   'the economy is at potential',
   'government spending is less than tax revenue',
   'government spending exceeds tax revenue in a given year'], ans=4,
   why='A deficit is the annual flow of spending in excess of revenue.'),
 dict(q='The national debt is best described as', choices=[
   'total tax revenue',
   'the trade deficit',
   'the deficit in a single year',
   'the accumulated total of past deficits less past surpluses',
   'government spending in a year'], ans=3,
   why='Debt is a stock accumulated from the annual flows of deficits and surpluses.'),
 dict(q='Expansionary fiscal policy financed by borrowing tends to', choices=[
   'eliminate the debt',
   'reduce the budget deficit',
   'increase the budget deficit',
   'leave the deficit unchanged',
   'reduce the national debt'], ans=2,
   why='Spending more or taxing less while output is weak widens the gap between outlays and revenue.'),
 dict(q='Crowding out refers to the possibility that', choices=[
   'government spending raises consumption',
   'government borrowing raises interest rates and reduces private investment',
   'taxes rise automatically',
   'imports fall',
   'the money supply expands'], ans=1,
   why='Competition for loanable funds can raise the cost of borrowing and displace private spending.'),
 dict(q='Crowding out makes expansionary fiscal policy', choices=[
   'less effective than the simple multiplier suggests',
   'exactly as effective',
   'contractionary',
   'irrelevant to interest rates',
   'more effective than the simple multiplier suggests'], ans=0,
   why='Some of the demand added by government is offset by private investment that does not happen.'),
 dict(q='An increase in transfer payments is an example of', choices=[
   'monetary policy',
   'a supply-side policy only',
   'a change in potential output',
   'contractionary fiscal policy',
   'expansionary fiscal policy that works through disposable income and consumption'], ans=4,
   why='Transfers raise household incomes and therefore consumption, shifting AD right.'),
 dict(q='Which of the following is an example of contractionary fiscal policy?', choices=[
   "a cut in the central bank's policy rate",
   'an increase in defense procurement',
   'a payroll tax cut',
   'a reduction in federal infrastructure spending',
   'an increase in unemployment benefits'], ans=3,
   why='Reducing government purchases lowers aggregate demand.'),
 dict(q='Which of the following is an example of expansionary fiscal policy?', choices=[
   'reducing transfer payments',
   'raising the income tax rate',
   'a large temporary tax rebate to households',
   'cutting government payrolls',
   'raising interest rates'], ans=2,
   why='A rebate raises disposable income and consumption, shifting AD right.'),
 dict(q='If the government wants to close a recessionary gap while also limiting the increase in the deficit, it could', choices=[
   'cut taxes by the full amount of the gap',
   'raise spending and taxes together, relying on the balanced budget multiplier of 1',
   'do nothing',
   'reduce spending',
   'raise taxes only'], ans=1,
   why='Equal increases in spending and taxes raise GDP by the amount of the change without widening the deficit.'),
 dict(q='Fiscal policy affects the economy in the AD-AS model primarily by', choices=[
   'shifting the AD curve',
   'shifting the SRAS curve',
   'moving along the LRAS curve',
   'changing potential output immediately',
   'shifting the LRAS curve'], ans=0,
   why='Spending and tax changes act on total planned expenditure, which is the AD curve.'),
 dict(q='Which fiscal action could shift LRAS right over time as well as AD in the short run?', choices=[
   'an increase in unemployment benefits',
   'a one-time tax refund',
   'an increase in defense salaries',
   'a temporary consumption rebate',
   'sustained public investment in infrastructure, research, and education'], ans=4,
   why="Public capital and human capital raise the economy's productive capacity in addition to adding demand now."),
 dict(q='Using expansionary fiscal policy when the economy is already at full employment will most likely', choices=[
   'shift LRAS right',
   'reduce the natural rate of unemployment',
   'raise real output permanently',
   'create an inflationary gap and raise the price level',
   'lower the price level'], ans=3,
   why='With no slack, added demand shows up mainly as higher prices rather than more real output.'),
 dict(q='A government cuts spending during a recession in order to balance its budget. The most likely short-run effect is', choices=[
   'no effect on output',
   'a faster recovery',
   'a deeper recession as AD shifts further left',
   'a rise in the price level',
   'a rightward shift of SRAS'], ans=2,
   why='Cutting spending in a slump is contractionary and widens the recessionary gap.'),
 dict(q='Which of the following would make fiscal stimulus less effective?', choices=[
   'a high MPC',
   'significant crowding out and a large share of the stimulus saved rather than spent',
   'substantial unused capacity',
   'a low marginal propensity to import',
   'rapid implementation'], ans=1,
   why='Both leakages and higher interest rates reduce the net addition to aggregate demand.'),
 dict(q='Which of the following would make fiscal stimulus more effective?', choices=[
   'an economy with substantial slack and interest rates that do not rise much',
   'extensive crowding out',
   'a very open economy with high imports',
   'long implementation lags',
   'a low MPC'], ans=0,
   why='Idle resources and stable borrowing costs allow more of the spending to become real output.'),
 dict(q='Supply-side fiscal policies aim to', choices=[
   'reduce the money supply',
   'raise the price level',
   'increase transfer payments',
   'shift AD right in the short run',
   'shift LRAS right by raising incentives to work, save, and invest'], ans=4,
   why='Supply-side measures target productive capacity rather than the level of spending.'),
 dict(q='A tax cut on business investment is expected to raise aggregate demand and, if it raises the capital stock, also', choices=[
   'lower potential output',
   'raise the natural rate of unemployment',
   'shift AD left later',
   'shift LRAS right over time',
   'shift LRAS left'], ans=3,
   why="More capital raises the economy's productive capacity in addition to adding demand now."),
 dict(q='If policymakers overestimate the size of a recessionary gap and overshoot with stimulus, the likely result is', choices=[
   'deflation',
   'a deeper recession',
   'an inflationary gap and rising prices',
   'no change in output',
   'a leftward shift of LRAS'], ans=2,
   why='Too much demand pushes output past potential, which is the overheating case.'),
 dict(q='A politically important obstacle to contractionary fiscal policy is that', choices=[
   'it requires no legislation',
   'raising taxes and cutting spending are unpopular, so the policy is often delayed',
   'it has no effect on the economy',
   'it lowers the deficit',
   'it works instantly'], ans=1,
   why='The political economy of fiscal restraint is a real constraint on timely stabilization.'),
 dict(q='An economy with an MPC of 0.9 requires a smaller spending increase to close a given gap than one with an MPC of 0.6 because', choices=[
   'the spending multiplier is larger, so each dollar of spending generates more induced consumption',
   'prices are more flexible',
   'it has more capacity',
   'it saves more',
   'the tax multiplier is larger'], ans=0,
   why='With a multiplier of 10 rather than 2.5, far less initial spending is needed.'),
 dict(q='Which combination would most reliably close a recessionary gap while keeping the deficit unchanged?', choices=[
   'a spending cut alone',
   'a tax increase alone',
   'no action',
   'a tax cut alone',
   'an equal increase in spending and taxes several times the size of the gap'], ans=4,
   why='With a balanced budget multiplier of 1, the equal change must be as large as the gap itself, which is why it is a costly way to stimulate.'),
 dict(q='If a fiscal stimulus raises interest rates enough to reduce private investment by an amount equal to the increase in government spending, the net effect on aggregate demand is', choices=[
   'an increase in potential output',
   'a fall in the price level',
   'a large increase',
   'approximately zero, a case of complete crowding out',
   'a large decrease'], ans=3,
   why='Full crowding out means the private spending displaced exactly offsets the public spending added.'),
 dict(q='Which statement about fiscal policy is FALSE?', choices=[
   'Fiscal policy is subject to recognition, decision, and implementation lags.',
   'Expansionary policy shifts AD right.',
   'Contractionary policy can be used to fight an inflationary gap.',
   'The tax multiplier is smaller in magnitude than the spending multiplier.',
   'Fiscal policy is conducted by the central bank.'], ans=4,
   why='Central banks conduct monetary policy; fiscal policy is set by the legislature and the executive.'),
]
