# MACRO 3.9 Automatic Stabilizers — 50 questions
# Arithmetic used in stems, worked out here:
#   Progressive tax illustration: income falls from $60,000 to $40,000 and the
#     marginal bracket falls from 30% to 20%. Tax paid falls from 0.30 x 60,000
#     = $18,000 to 0.20 x 40,000 = $8,000, a fall of $10,000 on an income fall of
#     $20,000, so disposable income falls only $10,000 -- half the drop.
#   Cyclical vs structural balance: actual deficit $500b, of which $200b is
#     attributed to the recession -> structural (cyclically adjusted) deficit
#     = 500 - 200 = $300b.
#   Tax revenue at potential $2,000b, actual revenue $1,850b -> cyclical revenue
#     shortfall = $150b.
TOPIC = ("3.9", "Automatic Stabilizers", 3)
QUESTIONS = [
 dict(q='Automatic stabilizers are', choices=[
   'deliberate changes in tax law passed during a recession',
   'features of the budget that automatically dampen the business cycle without new legislation',
   'central bank interest rate decisions',
   'changes in the money supply',
   'wage and price controls'], ans=1,
   why='They work through existing law, so no new act of the legislature is required.'),
 dict(q='The two most important automatic stabilizers are', choices=[
   'income taxes that vary with income and transfer payments such as unemployment benefits',
   'the discount rate and reserve requirements',
   'defense spending and infrastructure',
   'exchange rates and interest rates',
   'tariffs and quotas'], ans=0,
   why='Tax collections fall and transfers rise automatically when incomes fall, cushioning spending.'),
 dict(q='During a recession, income tax revenue automatically', choices=[
   'stays constant',
   'becomes zero',
   'must be raised by legislation',
   'rises, worsening the downturn',
   "falls, which softens the decline in households' disposable income"], ans=4,
   why='Lower incomes mean smaller tax bills, so disposable income falls less than pre-tax income.'),
 dict(q='During a recession, spending on unemployment insurance automatically', choices=[
   'must be legislated each time',
   'becomes zero',
   'falls',
   'rises, supporting the incomes of those who lose jobs',
   'stays constant'], ans=3,
   why='More people qualify for benefits when unemployment rises, which props up consumption.'),
 dict(q='During an economic boom, automatic stabilizers', choices=[
   'lower tax revenue',
   'add to aggregate demand',
   'restrain aggregate demand as tax revenue rises and transfer payments fall',
   'have no effect',
   'require new legislation'], ans=2,
   why='Stabilizers work in both directions, cooling a boom just as they cushion a slump.'),
 dict(q='A progressive income tax acts as an automatic stabilizer because', choices=[
   'everyone pays the same rate',
   'as income falls households move into lower brackets, so taxes fall more than proportionally',
   'it is fixed in dollar terms',
   'it applies only to the wealthy',
   'it does not change with income'], ans=1,
   why='A more-than-proportional fall in taxes cushions disposable income by more than a flat tax would.'),
 dict(q="A household's income falls from $60,000 to $40,000 while its effective tax rate falls from 30% to 20%. Disposable income falls from", choices=[
   '$60,000 to $40,000, a fall of $20,000',
   '$42,000 to $20,000, a fall of $22,000',
   '$18,000 to $8,000, a fall of $10,000',
   '$30,000 to $30,000, no fall at all',
   '$42,000 to $32,000, a fall of $10,000'], ans=4,
   why='Taxes fall from 18,000 to 8,000, so after-tax income falls from 42,000 to 32,000, only half as much as pre-tax income.'),
 dict(q='Automatic stabilizers differ from discretionary fiscal policy in that automatic stabilizers', choices=[
   'affect only the long run',
   'are conducted by the central bank',
   'always balance the budget',
   'are larger in size',
   'operate without any new action by policymakers, so they take effect immediately'], ans=4,
   why='Because they are built into existing law, they avoid recognition, decision, and implementation lags.'),
 dict(q='Which of the following is an automatic stabilizer?', choices=[
   "a change in the central bank's policy rate",
   'a temporary tax holiday passed during a downturn',
   'a newly enacted infrastructure spending bill',
   'unemployment compensation paid under existing law',
   'a one-time stimulus check approved by the legislature'], ans=3,
   why='Benefits paid under standing law expand automatically as unemployment rises.'),
 dict(q='Which of the following is discretionary fiscal policy rather than an automatic stabilizer?', choices=[
   'unemployment benefit outlays rising',
   'income tax revenue falling as incomes fall',
   'a newly passed law cutting income tax rates during a recession',
   'food assistance caseloads rising in a downturn',
   'corporate tax collections falling with profits'], ans=2,
   why='A change in tax law requires legislation, which is the defining feature of discretionary policy.'),
 dict(q='The main advantage of automatic stabilizers over discretionary policy is that they', choices=[
   'are always larger',
   'avoid the recognition, legislative, and implementation lags',
   'eliminate output gaps entirely',
   'reduce the national debt',
   'raise potential output'], ans=1,
   why='Timeliness is the central advantage, since the response begins as soon as incomes change.'),
 dict(q='A limitation of automatic stabilizers is that they', choices=[
   'dampen fluctuations but are generally too small to close a large output gap on their own',
   'require new legislation',
   'work only in booms',
   'raise the natural rate of unemployment',
   'cause recessions'], ans=0,
   why='They soften the cycle rather than eliminating it, which is why discretionary policy is still discussed.'),
 dict(q='Automatic stabilizers reduce the size of the spending multiplier because', choices=[
   'they raise government purchases',
   'they lower interest rates',
   'they shift SRAS',
   'they raise the MPC',
   'taxes and reduced transfers leak out of each round of induced spending'], ans=4,
   why='Any withdrawal from the income stream at each round shortens the chain of induced spending.'),
 dict(q='A budget deficit that grows during a recession without any change in policy is', choices=[
   'always a policy failure',
   'unrelated to the business cycle',
   'evidence of discretionary stimulus',
   'largely the result of automatic stabilizers',
   'impossible'], ans=3,
   why='Falling revenue and rising transfers widen the deficit automatically when output falls.'),
 dict(q='The cyclical component of the budget balance refers to', choices=[
   'spending on defense',
   "the part of the deficit or surplus caused by the economy's position in the business cycle",
   'the part caused by deliberate policy choices',
   'the total national debt',
   'interest payments only'], ans=1,
   why='It is the portion attributable to output being above or below potential.'),
 dict(q='The structural, or cyclically adjusted, budget balance is', choices=[
   'the actual balance in any year',
   'the balance that would exist if the economy were producing at potential output',
   'the balance in a boom',
   'the same as the national debt',
   'always zero'], ans=1,
   why='It removes the effect of the cycle to reveal the underlying stance of fiscal policy.'),
 dict(q='A country runs an actual deficit of $500 billion, of which $200 billion is attributable to the recession. Its structural deficit, in billions of dollars, is', choices=[
   '200',
   '300',
   '500',
   '700',
   '1,000'], ans=1,
   why='500 − 200 = 300, the part that would remain even at potential output.'),
 dict(q='Tax revenue at potential output would be $2,000 billion but actual revenue is $1,850 billion. The cyclical revenue shortfall, in billions of dollars, is', choices=[
   '50',
   '150',
   '300',
   '1,850',
   '2,000'], ans=1,
   why='2,000 − 1,850 = 150, the revenue lost because output is below potential.'),
 dict(q='If an economy is producing above potential, the actual budget balance will look', choices=[
   'unrelated to the structural balance',
   'always in deficit',
   'worse than the structural balance',
   'better than the structural balance, because revenues are temporarily high and transfers temporarily low',
   'identical to the structural balance'], ans=3,
   why='A boom flatters the budget, which is why the cyclically adjusted measure is the better guide to policy.'),
 dict(q='If an economy is producing below potential, the actual budget balance will look', choices=[
   'unaffected by output',
   'better than the structural balance',
   'worse than the structural balance',
   'identical to the structural balance',
   'always in surplus'], ans=2,
   why='Weak revenue and high transfers widen the measured deficit beyond the underlying policy stance.'),
 dict(q='A rise in the structural deficit indicates', choices=[
   'the economy has entered a recession',
   'a deliberate loosening of fiscal policy, since the change is not explained by the cycle',
   'automatic stabilizers at work',
   'faster growth of potential output',
   'a fall in the national debt'], ans=1,
   why='The cyclically adjusted balance changes only when policy itself changes.'),
 dict(q="Which of the following would strengthen an economy's automatic stabilizers?", choices=[
   'making unemployment benefits more generous and longer lasting',
   'eliminating food assistance programs',
   'making the income tax less progressive',
   'abolishing corporate income taxes',
   'replacing the progressive income tax with a fixed lump-sum tax'], ans=0,
   why='More generous income support means a bigger automatic cushion when employment falls.'),
 dict(q="Which of the following would weaken an economy's automatic stabilizers?", choices=[
   'adding means-tested transfer programs',
   'raising the top marginal tax rate',
   'indexing benefits to unemployment',
   'expanding unemployment insurance coverage',
   'replacing a progressive income tax with a flat lump-sum tax unrelated to income'], ans=4,
   why='A tax that does not vary with income cannot cushion a fall in income.'),
 dict(q='Corporate income tax revenue is a strong automatic stabilizer because corporate profits', choices=[
   'are unrelated to output',
   'are taxed at a flat rate',
   'never change',
   'are highly cyclical, falling sharply in recessions and rising sharply in booms',
   'are fixed by law'], ans=3,
   why='Highly volatile profits mean tax collections swing strongly with the cycle.'),
 dict(q='In the AD-AS model, automatic stabilizers make the AD curve shift', choices=[
   'not at all',
   'further in response to shocks',
   'less far in response to shocks, because taxes and transfers offset part of the income change',
   'only to the right',
   'only to the left'], ans=2,
   why='By damping the multiplier, stabilizers reduce the size of demand fluctuations.'),
 dict(q='Automatic stabilizers can be said to work through', choices=[
   'changes in the money supply',
   'changes in disposable income that are smaller than changes in pre-tax income',
   'changes in potential output',
   'changes in the exchange rate',
   'changes in production costs'], ans=1,
   why='Smoothing disposable income is exactly how the stabilizers smooth consumption.'),
 dict(q='Which statement about automatic stabilizers is correct?', choices=[
   'They operate in both recessions and expansions, working against the cycle in each case.',
   'They require an act of the legislature.',
   'They eliminate the business cycle.',
   'They are a form of monetary policy.',
   'They only operate in recessions.'], ans=0,
   why='Rising revenue and falling transfers in a boom are as automatic as the reverse in a slump.'),
 dict(q='Means-tested transfer programs act as automatic stabilizers because', choices=[
   'they require new legislation each year',
   'they are funded by borrowing only',
   'they are unrelated to income',
   'benefits are fixed regardless of circumstances',
   'the number of people qualifying rises automatically when incomes fall'], ans=4,
   why='Eligibility depends on income, so caseloads move counter to the cycle.'),
 dict(q='An economy with very generous automatic stabilizers will typically experience', choices=[
   'smaller swings in the budget balance',
   'a permanently balanced budget',
   'larger swings in output over the business cycle',
   'smaller swings in output but larger swings in the budget balance',
   'no business cycle at all'], ans=3,
   why="Shifting the volatility from household incomes to the government's books is the point of the mechanism."),
 dict(q='Because of automatic stabilizers, a balanced budget requirement that applies every year would', choices=[
   'eliminate the national debt burden',
   'strengthen stabilization',
   'force spending cuts or tax increases during recessions, making downturns worse',
   'have no effect on the cycle',
   'raise potential output'], ans=2,
   why='Forcing the budget to balance in a slump means acting pro-cyclically at exactly the wrong time.'),
 dict(q='Which of the following best illustrates an automatic stabilizer at work?', choices=[
   'the legislature passes a new jobs program',
   'unemployment insurance payments rise by $50 billion as layoffs increase, with no change in the law',
   'the central bank cuts interest rates',
   'the government builds a new highway',
   'the tax code is rewritten'], ans=1,
   why='The increase happens under existing law simply because more people qualify.'),
 dict(q='Automatic stabilizers reduce the volatility of consumption because', choices=[
   'they smooth disposable income, which is what consumption depends on',
   'they change potential output',
   'they lower interest rates',
   'they reduce imports',
   'they change the MPC'], ans=0,
   why='If disposable income falls by less, consumption falls by less.'),
 dict(q='A recession that increases the budget deficit through automatic stabilizers should be interpreted as', choices=[
   'evidence that policy has tightened',
   'an increase in the structural deficit',
   'proof that stabilizers do not work',
   'a failure of fiscal discipline',
   'the budget doing its stabilizing job, with the deficit reflecting the cycle rather than a policy change'], ans=4,
   why='A cyclical deficit is the mechanical result of the stabilizers cushioning the downturn.'),
 dict(q='If the structural balance is in surplus but the actual balance is in deficit, the economy is most likely', choices=[
   'growing rapidly',
   'in an inflationary gap',
   'producing above potential',
   'producing below potential',
   'at potential'], ans=3,
   why='Only a negative output gap can turn an underlying surplus into a measured deficit.'),
 dict(q='If the actual balance is in surplus but the structural balance is in deficit, the economy is most likely', choices=[
   'experiencing deflation',
   'producing below potential',
   'producing above potential, with the boom temporarily flattering revenue',
   'at potential',
   'in a recession'], ans=2,
   why='A boom raises revenue and cuts transfers, masking an underlying deficit.'),
 dict(q='Which combination correctly describes automatic stabilizers in a recession?', choices=[
   'tax revenue up, transfers down, deficit down',
   'tax revenue down, transfers up, deficit up',
   'tax revenue up, transfers up, deficit down',
   'tax revenue down, transfers down, deficit down',
   'no change in any of them'], ans=1,
   why='Falling incomes cut revenue while rising unemployment raises transfers, which widens the deficit.'),
 dict(q='Which combination correctly describes automatic stabilizers in an expansion?', choices=[
   'tax revenue up, transfers down, deficit down',
   'tax revenue down, transfers down, deficit up',
   'tax revenue up, transfers up, deficit up',
   'no change in any of them',
   'tax revenue down, transfers up, deficit up'], ans=0,
   why='Rising incomes raise revenue and shrink transfer caseloads, which improves the balance.'),
 dict(q='Automatic stabilizers are described as counter-cyclical because they', choices=[
   'operate only when the legislature acts',
   'have no effect on aggregate demand',
   'raise potential output',
   'amplify the business cycle',
   'push against the direction of the cycle in both booms and slumps'], ans=4,
   why='Counter-cyclical means acting in the opposite direction to the current swing in output.'),
 dict(q='A tax system in which everyone pays a fixed dollar amount regardless of income would', choices=[
   'raise the multiplier to infinity',
   'act only in booms',
   'be a strong automatic stabilizer',
   'provide essentially no automatic stabilization',
   'eliminate the business cycle'], ans=3,
   why='If tax payments do not respond to income, they cannot cushion changes in income.'),
 dict(q='The presence of automatic stabilizers means the actual multiplier in an economy is', choices=[
   'equal to the tax multiplier',
   'larger than 1/MPS',
   'smaller than 1/MPS',
   'exactly 1/MPS',
   'negative'], ans=2,
   why='Taxes and reduced transfers are leakages that shorten the chain of induced spending.'),
 dict(q='During a severe recession, which government outlay category typically rises fastest without new legislation?', choices=[
   'defense procurement',
   'unemployment insurance and income support programs',
   'highway construction',
   'space exploration',
   'public university construction'], ans=1,
   why='Income support caseloads respond immediately and mechanically to rising unemployment.'),
 dict(q='Automatic stabilizers primarily affect the economy through', choices=[
   'aggregate demand',
   'long-run aggregate supply',
   'potential output',
   'the exchange rate',
   'short-run aggregate supply'], ans=0,
   why='They work by smoothing disposable income and therefore consumption spending.'),
 dict(q='Which of the following would be classified as a cyclical, rather than structural, change in the budget?', choices=[
   'a newly legislated expansion of a benefit program',
   'a permanent cut in defense spending',
   'a new infrastructure program',
   'a permanent increase in the corporate tax rate',
   'a fall in income tax collections caused by a recession'], ans=4,
   why="It results from the economy's position in the cycle, not from a change in law."),
 dict(q='Which of the following would be classified as a structural change in the budget?', choices=[
   'an increase in food assistance caseloads',
   'a fall in payroll tax revenue as employment declines',
   'a rise in unemployment benefit outlays during a recession',
   'a permanent reduction in income tax rates enacted by law',
   'a fall in corporate tax revenue as profits decline'], ans=3,
   why='A change in tax law alters the balance even at potential output.'),
 dict(q='Economists prefer the cyclically adjusted balance for judging fiscal policy because it', choices=[
   'measures the national debt',
   'is always in surplus',
   'separates the effect of policy choices from the effect of the business cycle',
   'is easier to compute',
   'ignores taxes'], ans=2,
   why='Only the cyclically adjusted figure tells you whether policy itself has loosened or tightened.'),
 dict(q='Suppose an economy in a deep recession sees its deficit widen sharply while no new laws are passed. The best conclusion is that', choices=[
   'fiscal policy has become expansionary by choice',
   'automatic stabilizers are cushioning the downturn and the deficit is cyclical',
   'the structural deficit has risen',
   'policy has tightened',
   'the stabilizers have failed'], ans=1,
   why='With no legislative change, the entire widening must come from the cycle.'),
 dict(q='Automatic stabilizers make discretionary fiscal policy', choices=[
   'less urgent for small fluctuations, though a large gap may still call for discretionary action',
   'impossible',
   'more subject to lags',
   'contractionary',
   'unnecessary in every situation'], ans=0,
   why='They handle ordinary fluctuations, but their size limits what they can do about a deep slump.'),
 dict(q='Which feature of unemployment insurance makes it an effective stabilizer?', choices=[
   'it is financed only by borrowing',
   'it requires annual legislation',
   'it is unrelated to employment',
   'it pays the same amount to everyone every year',
   'payments go to households whose income has just fallen and who are likely to spend the money'], ans=4,
   why='Targeting money at households with a high propensity to consume maximizes the support to spending.'),
 dict(q='Which statement about automatic stabilizers is FALSE?', choices=[
   'They shift the LRAS curve right during recessions.',
   'They moderate but do not eliminate business cycle fluctuations.',
   'They reduce the size of the multiplier.',
   'They operate without new legislation.',
   'They cause the deficit to widen in recessions.'], ans=0,
   why="Stabilizers act on aggregate demand; they do not change the economy's productive capacity."),
 dict(q='A country strengthens its progressive income tax and expands unemployment benefits. Compared with before, its business cycle fluctuations in output should be', choices=[
   'replaced by permanent inflation',
   'larger',
   'smaller, though its budget balance will swing more over the cycle',
   'unchanged',
   'eliminated entirely'], ans=2,
   why='Stronger stabilizers move volatility from household income onto the government budget.'),
]
