# MACRO 5.1 Fiscal and Monetary Policy Actions in the Short Run — 50 questions
# Numbers used, worked out:
#   Spending multiplier with MPC = 0.8: 1/(1-0.8) = 5; a $20b increase shifts AD by $100b.
#   Tax multiplier with MPC = 0.8: -0.8/0.2 = -4; a $20b tax cut shifts AD by $80b.
#   MPC = 0.75: spending multiplier 4, tax multiplier -3; $10b spending -> $40b AD shift.
#   MPC = 0.9: spending multiplier 10; a $5b cut in spending shifts AD by -$50b.
#   Recessionary gap of $200b with multiplier 5 needs $40b of new spending (200/5),
#     or a tax cut of 200/4 = $50b.
#   Inflationary gap of $120b with MPC = 0.75 (multiplier 4) needs $30b less spending.
TOPIC = ("5.1", "Fiscal and Monetary Policy Actions in the Short Run", 5)
QUESTIONS = [
 dict(q="Expansionary fiscal policy consists of", choices=[
   "raising taxes or cutting government spending",
   "increasing government spending or cutting taxes",
   "increasing the money supply",
   "raising the discount rate",
   "selling government bonds to the public"], ans=1,
   why="Fiscal policy works through the government budget, and expansion means adding to aggregate demand through spending or lower taxes."),
 dict(q="Contractionary monetary policy is best described as", choices=[
   "an increase in government spending",
   "central bank actions that reduce the money supply and raise the nominal interest rate",
   "an increase in transfer payments",
   "a cut in the reserve requirement",
   "a reduction in income tax rates"], ans=1,
   why="Monetary contraction shrinks the money supply, which pushes the nominal interest rate up."),
 dict(q="In the short run, expansionary monetary policy is expected to", choices=[
   "lower real GDP and the price level",
   "raise real GDP and the price level and lower unemployment",
   "raise unemployment and lower the price level",
   "leave real GDP unchanged",
   "raise the nominal interest rate immediately"], ans=1,
   why="A larger money supply lowers the interest rate, raises investment and AD, and moves the economy up along SRAS."),
 dict(q="An open market purchase of bonds by the central bank will", choices=[
   "reduce bank reserves and raise interest rates",
   "increase bank reserves, increase the money supply, and lower the nominal interest rate",
   "have no effect on the money supply",
   "raise the required reserve ratio",
   "reduce aggregate demand"], ans=1,
   why="Buying bonds pays reserves into the banking system, expanding the money supply and pushing the interest rate down."),
 dict(q="If the central bank sells government bonds while the government simultaneously raises spending, the effect on real GDP is", choices=[
   "certainly an increase",
   "indeterminate, because fiscal expansion and monetary contraction push output in opposite directions",
   "certainly a decrease",
   "certainly zero",
   "certainly a fall in the price level"], ans=1,
   why="The two policies shift aggregate demand in opposite directions, so the net change depends on their relative sizes."),
 dict(q="Expansionary fiscal policy financed by borrowing tends to raise the real interest rate because", choices=[
   "the central bank always tightens in response",
   "government borrowing increases the demand for loanable funds",
   "the money supply falls automatically",
   "saving rises sharply",
   "investment demand disappears"], ans=1,
   why="Additional government borrowing adds to the demand for loanable funds, bidding the real interest rate up."),
 dict(q="Both expansionary fiscal policy and expansionary monetary policy raise real GDP in the short run, but they differ in that", choices=[
   "fiscal policy lowers the price level",
   "fiscal expansion tends to raise the real interest rate while monetary expansion lowers it",
   "monetary policy has no effect on interest rates",
   "fiscal policy affects only exports",
   "monetary policy raises taxes"], ans=1,
   why="Fiscal expansion adds to borrowing demand, while monetary expansion adds to the supply of money and credit."),
 dict(q="A combination of expansionary fiscal policy and expansionary monetary policy will, in the short run, certainly", choices=[
   "lower the price level",
   "increase real GDP and the price level",
   "lower real GDP",
   "raise unemployment",
   "lower the price level and raise output"], ans=1,
   why="Both policies shift aggregate demand right, so output and the price level both rise."),
 dict(q="A combination of expansionary fiscal policy and expansionary monetary policy has an effect on the real interest rate that is", choices=[
   "certainly positive",
   "indeterminate, since fiscal expansion pushes it up and monetary expansion pushes it down",
   "certainly negative",
   "certainly zero",
   "the same as the effect on output"], ans=1,
   why="The two forces act on the interest rate in opposite directions, so the net movement depends on their magnitudes."),
 dict(q="If the economy is in a recessionary gap, an appropriate policy mix would be", choices=[
   "raising taxes and selling bonds",
   "cutting taxes and buying bonds on the open market",
   "cutting government spending and raising the discount rate",
   "raising the reserve requirement and cutting spending",
   "raising taxes and cutting the money supply"], ans=1,
   why="Both actions expand aggregate demand and close a gap below potential output."),
 dict(q="If the economy is in an inflationary gap, an appropriate policy mix would be", choices=[
   "cutting taxes and buying bonds",
   "raising taxes and selling bonds",
   "increasing transfer payments and lowering the discount rate",
   "increasing spending and lowering reserve requirements",
   "cutting taxes and lowering the federal funds rate target"], ans=1,
   why="Both actions reduce aggregate demand and pull output back toward potential."),
 dict(q="With a marginal propensity to consume of 0.8, the spending multiplier is", choices=[
   "0.8", "1.25", "4", "5", "8"], ans=3,
   why="The spending multiplier is 1/(1 - MPC) = 1/0.2 = 5."),
 dict(q="With a marginal propensity to consume of 0.8, a $20 billion increase in government purchases shifts aggregate demand by", choices=[
   "$16 billion", "$20 billion", "$80 billion", "$100 billion", "$400 billion"], ans=3,
   why="The multiplier is 5, so $20 billion times 5 equals a $100 billion shift."),
 dict(q="With a marginal propensity to consume of 0.8, a $20 billion tax cut shifts aggregate demand by", choices=[
   "$16 billion", "$20 billion", "$80 billion", "$100 billion", "$160 billion"], ans=2,
   why="The tax multiplier is -MPC/(1 - MPC) = -4 in size, so a $20 billion cut raises AD by $80 billion."),
 dict(q="A tax cut has a smaller effect on aggregate demand than an equal increase in government purchases because", choices=[
   "taxes are collected later",
   "part of the tax cut is saved rather than spent",
   "government purchases are not counted in GDP",
   "the tax multiplier is always zero",
   "consumers ignore tax changes"], ans=1,
   why="Only the fraction of the tax cut that households consume enters the first round of spending."),
 dict(q="An economy has a recessionary gap of $200 billion and an MPC of 0.8. The increase in government purchases needed to close it is", choices=[
   "$20 billion", "$40 billion", "$50 billion", "$160 billion", "$200 billion"], ans=1,
   why="With a multiplier of 5, $200 billion divided by 5 is $40 billion."),
 dict(q="An economy has a recessionary gap of $200 billion and an MPC of 0.8. The tax cut needed to close it is", choices=[
   "$25 billion", "$40 billion", "$50 billion", "$100 billion", "$200 billion"], ans=2,
   why="The tax multiplier has size 4, so $200 billion divided by 4 is $50 billion."),
 dict(q="An economy has an inflationary gap of $120 billion and an MPC of 0.75. The reduction in government purchases needed to close it is", choices=[
   "$20 billion", "$30 billion", "$40 billion", "$90 billion", "$120 billion"], ans=1,
   why="With MPC 0.75 the multiplier is 4, so $120 billion divided by 4 is $30 billion."),
 dict(q="With an MPC of 0.9, a $5 billion cut in government purchases shifts aggregate demand by", choices=[
   "$4.5 billion", "$5 billion", "$10 billion", "$45 billion", "$50 billion"], ans=4,
   why="The multiplier is 1/0.1 = 10, so the shift is $50 billion to the left."),
 dict(q="The short-run effect of contractionary fiscal policy on the price level is", choices=[
   "an increase",
   "a decrease, as aggregate demand shifts left along an upward-sloping SRAS",
   "no change",
   "an increase only if the money supply falls",
   "indeterminate"], ans=1,
   why="Less aggregate demand moves the economy down along the short-run aggregate supply curve."),
 dict(q="Contractionary monetary policy in the short run is expected to", choices=[
   "raise real GDP and lower unemployment",
   "raise the nominal interest rate, reduce investment, and lower real GDP and the price level",
   "raise the price level",
   "lower the nominal interest rate",
   "leave the price level unchanged"], ans=1,
   why="A smaller money supply raises interest rates, cutting interest-sensitive spending and aggregate demand."),
 dict(q="Which of the following combinations would most reliably reduce inflation while limiting the rise in interest rates?", choices=[
   "expansionary fiscal and expansionary monetary policy",
   "contractionary fiscal policy combined with a smaller monetary contraction",
   "contractionary monetary policy alone with fiscal expansion",
   "tax cuts and open market purchases",
   "increased spending and a lower discount rate"], ans=1,
   why="Fiscal contraction reduces borrowing demand, which offsets some of the upward pressure on rates."),
 dict(q="An increase in the money supply lowers the nominal interest rate because", choices=[
   "the demand for money falls",
   "at the old interest rate people hold more money than they wish to and buy bonds, bidding bond prices up",
   "the government spends more",
   "prices adjust instantly",
   "banks stop lending"], ans=1,
   why="Excess money balances are used to buy bonds, raising bond prices and lowering yields."),
 dict(q="A cut in the required reserve ratio is", choices=[
   "contractionary fiscal policy",
   "expansionary monetary policy",
   "expansionary fiscal policy",
   "contractionary monetary policy",
   "neutral"], ans=1,
   why="Lower reserve requirements let banks lend more, expanding the money supply."),
 dict(q="An increase in the discount rate is intended to", choices=[
   "expand bank lending",
   "discourage bank borrowing from the central bank and tighten the money supply",
   "raise government spending",
   "lower taxes",
   "raise potential output"], ans=1,
   why="A higher cost of borrowing reserves discourages banks from expanding loans."),
 dict(q="The transmission mechanism of monetary policy runs from the money supply to real GDP through", choices=[
   "the tax rate",
   "the interest rate and interest-sensitive spending such as investment",
   "the price of imports only",
   "government purchases",
   "the labor force participation rate"], ans=1,
   why="Monetary policy changes the interest rate, which changes investment and consumption of durables."),
 dict(q="If the central bank lowers its policy interest rate target while the government raises income tax rates, real GDP will", choices=[
   "certainly rise",
   "change in a direction that depends on the relative strength of the two policies",
   "certainly fall",
   "remain exactly at potential",
   "fall only if prices are fixed"], ans=1,
   why="Monetary expansion and fiscal contraction shift aggregate demand in opposite directions."),
 dict(q="If the central bank lowers its policy rate while the government raises income tax rates, the real interest rate will", choices=[
   "rise", "fall", "stay constant", "become negative", "be indeterminate"], ans=1,
   why="Both policies reduce upward pressure on rates: monetary easing lowers them and lower government borrowing needs reduce loan demand."),
 dict(q="Automatic stabilizers refer to", choices=[
   "discretionary spending bills",
   "features of the budget such as progressive taxes and unemployment benefits that dampen fluctuations without new legislation",
   "central bank interest rate targets",
   "the reserve requirement",
   "the natural rate of unemployment"], ans=1,
   why="These features change tax collections and transfers automatically as income changes."),
 dict(q="During a recession, automatic stabilizers", choices=[
   "increase tax collections",
   "reduce tax collections and raise transfer payments, cushioning the fall in disposable income",
   "reduce government spending",
   "raise the money supply",
   "have no budget effect"], ans=1,
   why="Falling incomes mean less tax paid and more benefits received, which supports spending."),
 dict(q="A lag that affects fiscal policy more than monetary policy is the", choices=[
   "recognition lag",
   "legislative lag required to pass a budget change",
   "impact lag on investment",
   "data collection lag",
   "expectations lag"], ans=1,
   why="Fiscal changes must move through the legislative process, while a central bank can act quickly."),
 dict(q="Monetary policy is often said to have a long impact lag because", choices=[
   "the central bank meets rarely",
   "investment plans and construction projects respond to interest rates only over many months",
   "money supply changes are illegal",
   "banks do not respond to reserves",
   "prices are perfectly flexible"], ans=1,
   why="The spending decisions monetary policy works through take time to be made and carried out."),
 dict(q="If policymakers apply expansionary policy to an economy already at full employment, the most likely short-run result is", choices=[
   "higher real GDP with no inflation",
   "an inflationary gap with a rising price level and unemployment below the natural rate",
   "a recession",
   "a fall in the price level",
   "no change in any variable"], ans=1,
   why="Adding demand at full employment pushes output temporarily above potential and raises prices."),
 dict(q="In the short run, an increase in aggregate demand lowers the unemployment rate because", choices=[
   "the labor force shrinks",
   "firms expand output and hire more workers as prices rise faster than nominal wages",
   "the natural rate falls",
   "productivity falls",
   "wages are perfectly flexible"], ans=1,
   why="Sticky nominal wages mean higher prices raise profitability, so firms hire and produce more."),
 dict(q="A government that cuts spending while the central bank buys bonds is pursuing a mix that", choices=[
   "definitely raises the price level",
   "leaves the effect on real GDP indeterminate but clearly pushes interest rates down",
   "definitely raises interest rates",
   "definitely reduces the money supply",
   "definitely raises real GDP"], ans=1,
   why="The two shift AD in opposite directions, while both reduce pressure on interest rates."),
 dict(q="Expansionary fiscal policy conducted through transfer payments rather than government purchases will", choices=[
   "have a larger effect on AD than purchases of the same size",
   "have a smaller effect on AD than purchases of the same size, since some of the transfer is saved",
   "have no effect on AD",
   "reduce AD",
   "affect only the price level"], ans=1,
   why="Transfers enter spending only through the recipient's marginal propensity to consume."),
 dict(q="An open market sale of bonds by the central bank will, in the short run,", choices=[
   "raise real GDP",
   "reduce the money supply, raise the interest rate, and reduce aggregate demand",
   "lower the interest rate",
   "raise the price level",
   "increase bank reserves"], ans=1,
   why="Selling bonds drains reserves, contracting money and credit."),
 dict(q="Suppose real GDP is $900 billion and potential output is $960 billion, with an MPC of 0.75. Closing the gap with government purchases requires an increase of", choices=[
   "$12 billion", "$15 billion", "$20 billion", "$45 billion", "$60 billion"], ans=1,
   why="The gap is $60 billion and the multiplier is 4, so $60/4 = $15 billion."),
 dict(q="With an MPC of 0.75, an economy producing $900 billion against potential output of $960 billion could instead close the gap with a tax cut of", choices=[
   "$15 billion", "$20 billion", "$45 billion", "$60 billion", "$80 billion"], ans=1,
   why="The tax multiplier has size 3, so $60 billion divided by 3 is $20 billion."),
 dict(q="Which action would the central bank take to combat rising inflation?", choices=[
   "buy government bonds",
   "sell government bonds",
   "lower the reserve requirement",
   "lower the discount rate",
   "raise government transfer payments"], ans=1,
   why="Selling bonds withdraws reserves, tightening money and reducing aggregate demand."),
 dict(q="Expansionary monetary policy affects net exports because a lower domestic interest rate", choices=[
   "attracts foreign financial capital and appreciates the currency",
   "causes financial capital to flow out, depreciating the currency and raising net exports",
   "has no effect on the exchange rate",
   "raises the price of exports abroad",
   "eliminates the trade balance"], ans=1,
   why="Lower returns push capital abroad, the currency depreciates, and exports become cheaper for foreigners."),
 dict(q="Expansionary fiscal policy that raises the real interest rate tends to", choices=[
   "raise net exports",
   "appreciate the currency and reduce net exports",
   "depreciate the currency",
   "leave the exchange rate unchanged",
   "raise the money supply"], ans=1,
   why="Higher domestic returns attract capital inflows, which appreciate the currency and make exports dearer."),
 dict(q="If aggregate demand rises while short-run aggregate supply falls, the effect on the price level is", choices=[
   "certainly a fall",
   "certainly a rise",
   "indeterminate",
   "zero",
   "the same as the effect on output"], ans=1,
   why="Both a rightward AD shift and a leftward SRAS shift push the price level up."),
 dict(q="If aggregate demand rises while short-run aggregate supply falls, the effect on real GDP is", choices=[
   "certainly a rise",
   "indeterminate, since the two shifts move output in opposite directions",
   "certainly a fall",
   "certainly zero",
   "certainly equal to potential output"], ans=1,
   why="Higher demand raises output while lower supply reduces it, so the net effect depends on relative sizes."),
 dict(q="A central bank that wants to hold the interest rate constant while the government undertakes a large deficit-financed spending program must", choices=[
   "sell bonds",
   "buy bonds to accommodate the increased demand for money and credit",
   "raise the discount rate",
   "raise reserve requirements",
   "do nothing"], ans=1,
   why="Accommodating the fiscal expansion with money growth prevents the interest rate from rising."),
 dict(q="Fiscal and monetary policy both work in the short run by shifting", choices=[
   "long-run aggregate supply",
   "aggregate demand",
   "the production possibilities curve",
   "the natural rate of unemployment",
   "the labor force"], ans=1,
   why="Stabilization policy is demand-side policy in the short run."),
 dict(q="An economy suffering stagflation presents policymakers with a dilemma because", choices=[
   "no policy affects the price level",
   "demand-side policy that fights unemployment worsens inflation and policy that fights inflation worsens unemployment",
   "fiscal policy is illegal",
   "the money supply cannot change",
   "output is at potential"], ans=1,
   why="A single aggregate demand instrument cannot move output and prices in opposite directions at once."),
 dict(q="The most likely short-run effect of a large tax increase combined with an open market purchase of bonds on the price level is", choices=[
   "a definite rise",
   "indeterminate, because the two policies shift aggregate demand in opposite directions",
   "a definite fall",
   "no change under any circumstances",
   "a rise in output but not prices"], ans=1,
   why="The net movement of aggregate demand, and so of the price level, depends on which policy dominates."),
 dict(q="Which statement about the short-run effects of expansionary policy is correct?", choices=[
   "It raises output without changing the price level.",
   "It raises output and the price level, with the size of each depending on the slope of SRAS.",
   "It raises the price level but never output.",
   "It always leaves unemployment unchanged.",
   "It shifts long-run aggregate supply outward."], ans=1,
   why="How a demand increase splits between output and prices depends on how steep short-run aggregate supply is."),
 dict(q="If short-run aggregate supply is nearly horizontal because the economy is deep in recession, expansionary fiscal policy will mainly", choices=[
   "raise the price level with little effect on output",
   "raise real GDP with little effect on the price level",
   "reduce the money supply",
   "raise the natural rate of unemployment",
   "shift LRAS left"], ans=1,
   why="With ample idle capacity, firms meet extra demand by producing more rather than by raising prices."),
]
