# MACRO 5.2 The Phillips Curve — 50 questions
# Numbers used, worked out:
#   Natural rate 5%. Actual unemployment 3% => output above potential, inflationary gap.
#   Actual unemployment 7% => 2 points above natural, recessionary gap.
#   PHILLIPS table (a single short-run Phillips curve): inflation falls as unemployment rises.
#     (u=3, pi=6), (u=4, pi=5), (u=5, pi=4), (u=6, pi=3), (u=7, pi=2).
#     Natural rate is 5%, so the LRPC is vertical at u = 5 and the SRPC crosses the LRPC
#     at (5, 4): expected inflation embedded in this curve is 4%.
#     If expected inflation rises from 4% to 6%, every point shifts up by 2 points:
#     (5, 6) is the new crossing, so at u = 5 inflation is 6%.
#   Rule check: at u = 3 (2 points below natural) inflation is 6%, which is 2 points above
#     the 4% expected rate, so this table is consistent with a one-for-one trade-off.
TOPIC = ("5.2", "The Phillips Curve", 5)
PHILLIPS = dict(
    headers=["Unemployment rate (%)", "Inflation rate (%)"],
    rows=[["3", "6"], ["4", "5"], ["5", "4"], ["6", "3"], ["7", "2"]],
)
QUESTIONS = [
 dict(q="The short-run Phillips curve shows", choices=[
   "a positive relationship between inflation and unemployment",
   "an inverse relationship between the inflation rate and the unemployment rate",
   "the relationship between money and prices",
   "the relationship between saving and investment",
   "the relationship between output and the capital stock"], ans=1,
   why="In the short run, lower unemployment comes with higher inflation and vice versa."),
 dict(q="The short-run Phillips curve is the mirror image of", choices=[
   "the long-run aggregate supply curve",
   "the short-run aggregate supply curve",
   "the aggregate demand curve",
   "the money demand curve",
   "the production possibilities curve"], ans=1,
   why="Movement up along SRAS raises prices and output, which is the same event as lower unemployment with higher inflation."),
 dict(q="A movement along a given short-run Phillips curve is caused by", choices=[
   "a change in expected inflation",
   "a shift in aggregate demand",
   "a supply shock",
   "a change in the natural rate of unemployment",
   "a change in productivity"], ans=1,
   why="Demand shocks trade off inflation against unemployment along the existing curve."),
 dict(q="The long-run Phillips curve is", choices=[
   "downward sloping",
   "vertical at the natural rate of unemployment",
   "horizontal",
   "upward sloping",
   "the same as the short-run curve"], ans=1,
   why="In the long run any inflation rate is compatible with unemployment at its natural rate."),
 dict(q="The long-run Phillips curve is vertical because", choices=[
   "prices never change",
   "once expectations adjust, nominal wages catch up and unemployment returns to its natural rate at any inflation rate",
   "the money supply is fixed",
   "unemployment is always zero",
   "the government sets wages"], ans=1,
   why="Only unexpected inflation moves unemployment away from the natural rate, and surprises do not last."),
 dict(q="The long-run Phillips curve corresponds to", choices=[
   "the short-run aggregate supply curve",
   "the long-run aggregate supply curve at potential output",
   "the aggregate demand curve",
   "the loanable funds market",
   "the money supply curve"], ans=1,
   why="Both express the idea that output and employment settle at their natural levels regardless of the price level."),
 dict(q="An increase in expected inflation causes the short-run Phillips curve to", choices=[
   "shift down and to the left",
   "shift up and to the right, so any unemployment rate is paired with higher inflation",
   "become vertical",
   "become horizontal",
   "remain unchanged"], ans=1,
   why="Workers and firms build the higher expected inflation into wages and prices."),
 dict(q="A decrease in expected inflation causes the short-run Phillips curve to", choices=[
   "shift up",
   "shift down, improving the short-run trade-off",
   "become vertical",
   "shift right",
   "stay in place"], ans=1,
   why="Lower expected inflation means lower actual inflation at every unemployment rate."),
 dict(q="An adverse supply shock, such as a sharp rise in oil prices, causes", choices=[
   "inflation and unemployment to move in opposite directions",
   "both inflation and unemployment to rise, shifting the short-run Phillips curve right",
   "both inflation and unemployment to fall",
   "the long-run Phillips curve to shift left",
   "no change in either variable"], ans=1,
   why="A leftward SRAS shift raises the price level while reducing output and employment."),
 dict(q="A favorable supply shock, such as a fall in energy prices, will", choices=[
   "shift the short-run Phillips curve outward",
   "shift the short-run Phillips curve inward, allowing lower inflation and lower unemployment together",
   "make the long-run Phillips curve downward sloping",
   "raise the natural rate of unemployment",
   "raise inflation"], ans=1,
   why="Cheaper inputs let firms produce more at lower prices, improving both variables at once."),
 dict(q="The natural rate of unemployment consists of", choices=[
   "cyclical unemployment only",
   "frictional plus structural unemployment",
   "all unemployment during a recession",
   "unemployment caused by inflation",
   "zero unemployment"], ans=1,
   why="The natural rate is the unemployment that remains when cyclical unemployment is zero."),
 dict(q="When actual unemployment equals the natural rate, the economy is", choices=[
   "in a recessionary gap",
   "producing at potential output, on the long-run Phillips curve",
   "in an inflationary gap",
   "experiencing deflation necessarily",
   "growing at zero"], ans=1,
   why="Zero cyclical unemployment means real GDP equals potential GDP."),
 dict(q="If actual unemployment is below the natural rate, the economy is", choices=[
   "in a recessionary gap",
   "in an inflationary gap with output above potential",
   "at long-run equilibrium",
   "experiencing deflation",
   "outside its production possibilities curve permanently"], ans=1,
   why="Unemployment below the natural rate corresponds to output above potential."),
 dict(q="If actual unemployment is above the natural rate, the economy is experiencing", choices=[
   "an inflationary gap",
   "a recessionary gap with positive cyclical unemployment",
   "long-run equilibrium",
   "hyperinflation",
   "output above potential"], ans=1,
   why="The excess of actual over natural unemployment is cyclical unemployment."),
 dict(q="An increase in aggregate demand moves the economy", choices=[
   "down and to the right along the short-run Phillips curve",
   "up and to the left along the short-run Phillips curve",
   "onto a new long-run Phillips curve",
   "along the long-run Phillips curve",
   "nowhere"], ans=1,
   why="Higher demand raises inflation and lowers unemployment along the existing short-run curve."),
 dict(q="A decrease in aggregate demand moves the economy", choices=[
   "up along the short-run Phillips curve",
   "down and to the right along the short-run Phillips curve, with lower inflation and higher unemployment",
   "to a lower long-run Phillips curve",
   "to the left along the long-run Phillips curve",
   "to a higher natural rate"], ans=1,
   why="Weaker demand reduces price pressure and raises unemployment."),
 dict(q="An increase in the natural rate of unemployment shifts", choices=[
   "only the short-run Phillips curve",
   "both the long-run Phillips curve and the short-run Phillips curve to the right",
   "the long-run Phillips curve left",
   "neither curve",
   "only the aggregate demand curve"], ans=1,
   why="The vertical long-run curve sits at the natural rate, and the short-run curve moves with it."),
 dict(q="According to the Phillips curve framework, there is no long-run trade-off between inflation and unemployment because", choices=[
   "inflation never changes",
   "in the long run expectations fully adjust to actual inflation, so only the natural rate is sustainable",
   "the government controls unemployment directly",
   "wages are permanently fixed",
   "aggregate demand cannot shift"], ans=1,
   why="Sustained inflation gets built into expectations and stops fooling anyone into extra hiring."),
 dict(q="Refer to the table. The natural rate of unemployment implied by an expected inflation rate of 4 percent is", table=PHILLIPS, choices=[
   "3%", "4%", "5%", "6%", "7%"], ans=2,
   why="The short-run curve crosses the long-run curve where actual equals expected inflation, which is at 4% inflation and 5% unemployment."),
 dict(q="Refer to the table. If aggregate demand rises and unemployment falls from 5 percent to 3 percent, inflation becomes", table=PHILLIPS, choices=[
   "2%", "3%", "4%", "5%", "6%"], ans=4,
   why="Reading the schedule at 3% unemployment gives 6% inflation."),
 dict(q="Refer to the table. If expected inflation rises from 4 percent to 6 percent, inflation at the natural rate of unemployment becomes", table=PHILLIPS, choices=[
   "2%", "4%", "5%", "6%", "8%"], ans=3,
   why="At the natural rate actual inflation equals expected inflation, so it is 6%."),
 dict(q="Refer to the table. Moving from 6 percent unemployment to 4 percent unemployment along this curve raises inflation by", table=PHILLIPS, choices=[
   "1 percentage point", "2 percentage points", "3 percentage points", "4 percentage points", "5 percentage points"], ans=1,
   why="Inflation goes from 3% to 5%, a rise of 2 percentage points."),
 dict(q="Refer to the table. Cyclical unemployment when the unemployment rate is 7 percent equals", table=PHILLIPS, choices=[
   "0 percentage points", "1 percentage point", "2 percentage points", "5 percentage points", "7 percentage points"], ans=2,
   why="Actual unemployment of 7% minus the 5% natural rate leaves 2 points of cyclical unemployment."),
 dict(q="A central bank that permanently raises the money growth rate will, in the long run, produce", choices=[
   "permanently lower unemployment",
   "higher inflation with unemployment back at the natural rate",
   "lower inflation",
   "a permanently lower natural rate",
   "no change in inflation"], ans=1,
   why="Money growth determines inflation in the long run but leaves real variables at their natural levels."),
 dict(q="Disinflation refers to", choices=[
   "a falling price level",
   "a decline in the rate of inflation, with prices still rising but more slowly",
   "a rise in inflation",
   "zero inflation forever",
   "an increase in unemployment only"], ans=1,
   why="Disinflation slows inflation; deflation is an actual fall in the price level."),
 dict(q="The short-run cost of a disinflation policy is usually", choices=[
   "higher inflation",
   "a temporary rise in unemployment above the natural rate",
   "a permanent fall in potential output",
   "a lower natural rate",
   "an immediate boom"], ans=1,
   why="Until expectations adjust downward, tighter policy shows up as a recessionary gap."),
 dict(q="A disinflation is less costly in lost output when", choices=[
   "expectations are slow to adjust",
   "the central bank is credible, so expected inflation falls quickly and the short-run Phillips curve shifts down",
   "wages are rigid for many years",
   "the natural rate is high",
   "the policy is a surprise reversal of previous promises"], ans=1,
   why="A credible announcement moves expectations directly instead of forcing a long recession to do it."),
 dict(q="Stagflation appears on the Phillips curve diagram as", choices=[
   "a movement down the short-run curve",
   "an outward shift of the short-run Phillips curve, with higher inflation and higher unemployment",
   "a movement along the long-run curve",
   "an inward shift of the short-run curve",
   "a vertical short-run curve"], ans=1,
   why="Only a shift, not a movement along the curve, can raise both variables together."),
 dict(q="The 1970s experience of simultaneous high inflation and high unemployment showed that", choices=[
   "the Phillips curve trade-off is permanent",
   "the short-run trade-off can break down when supply shocks and rising expected inflation shift the curve",
   "unemployment cannot exist with inflation",
   "monetary policy has no effect",
   "the natural rate is zero"], ans=1,
   why="Supply shocks and rising inflation expectations moved the whole short-run curve outward."),
 dict(q="Which of the following would shift the short-run Phillips curve but not the long-run Phillips curve?", choices=[
   "a change in the natural rate of unemployment",
   "a rise in expected inflation",
   "an increase in the labor force's skill level",
   "a permanent improvement in job-matching technology",
   "a change in the minimum wage that alters structural unemployment"], ans=1,
   why="Expected inflation moves the short-run trade-off without changing the sustainable unemployment rate."),
 dict(q="Which of the following would shift both the short-run and the long-run Phillips curve to the left?", choices=[
   "a fall in expected inflation",
   "an improvement in job-search technology that reduces frictional unemployment",
   "an increase in aggregate demand",
   "an adverse supply shock",
   "an increase in the money supply"], ans=1,
   why="Reducing frictional unemployment lowers the natural rate itself, moving the vertical curve left."),
 dict(q="If actual inflation exceeds expected inflation, unemployment will temporarily be", choices=[
   "above the natural rate",
   "below the natural rate",
   "equal to the natural rate",
   "zero",
   "unaffected"], ans=1,
   why="Unexpected inflation raises prices relative to sticky wages, so firms expand hiring beyond the natural level."),
 dict(q="If actual inflation is less than expected inflation, unemployment will temporarily be", choices=[
   "below the natural rate",
   "above the natural rate",
   "equal to the natural rate",
   "zero",
   "at potential output"], ans=1,
   why="Wages set for higher inflation turn out too high in real terms, so firms hire less."),
 dict(q="In long-run equilibrium, actual inflation", choices=[
   "exceeds expected inflation",
   "equals expected inflation and unemployment equals the natural rate",
   "is below expected inflation",
   "is always zero",
   "is unrelated to expectations"], ans=1,
   why="Long-run equilibrium is the point where the short-run curve crosses the vertical long-run curve."),
 dict(q="The economy is at the intersection of its short-run and long-run Phillips curves. An unexpected increase in aggregate demand will in the short run", choices=[
   "lower inflation and raise unemployment",
   "raise inflation and lower unemployment",
   "raise both inflation and unemployment",
   "lower both",
   "leave both unchanged"], ans=1,
   why="A demand increase is a movement up and to the left along the existing short-run curve."),
 dict(q="Following an unexpected increase in aggregate demand, the economy returns to the natural rate of unemployment because", choices=[
   "aggregate demand falls back automatically",
   "nominal wages eventually rise as expected inflation catches up, shifting the short-run Phillips curve up",
   "the natural rate rises",
   "the long-run curve shifts right",
   "prices fall"], ans=1,
   why="Once expectations adjust, the short-run curve shifts up until unemployment is back at the natural rate at higher inflation."),
 dict(q="Contractionary monetary policy moves the economy in the short run", choices=[
   "up along the short-run Phillips curve",
   "down and to the right along the short-run Phillips curve",
   "left along the long-run Phillips curve",
   "onto a lower long-run curve",
   "to a lower natural rate"], ans=1,
   why="Tighter money reduces inflation while raising unemployment temporarily."),
 dict(q="Which pair of outcomes is impossible along a single short-run Phillips curve?", choices=[
   "lower unemployment with higher inflation",
   "lower unemployment with lower inflation",
   "higher unemployment with lower inflation",
   "unemployment at the natural rate with positive inflation",
   "unemployment below the natural rate"], ans=1,
   why="Along one curve the two variables must move in opposite directions; moving together requires a shift."),
 dict(q="An economy observes falling inflation together with falling unemployment. The most likely cause is", choices=[
   "an increase in aggregate demand",
   "a favorable supply shock that shifted the short-run Phillips curve inward",
   "a rise in expected inflation",
   "contractionary fiscal policy",
   "an oil price spike"], ans=1,
   why="Only an inward shift of the short-run curve improves both variables at once."),
 dict(q="Suppose the natural rate is 5 percent and actual unemployment is 3 percent. Over time, if policy does not change,", choices=[
   "unemployment will stay at 3 percent forever",
   "expected inflation will rise and unemployment will return toward 5 percent at a higher inflation rate",
   "the natural rate will fall to 3 percent",
   "inflation will fall",
   "output will fall below potential immediately"], ans=1,
   why="Unemployment below the natural rate is not sustainable once wage demands catch up with inflation."),
 dict(q="The Phillips curve relationship is derived from", choices=[
   "the loanable funds market",
   "the aggregate demand and short-run aggregate supply model",
   "the money multiplier",
   "the production possibilities curve",
   "the balance of payments"], ans=1,
   why="Shifts in AD along SRAS trace out the inflation-unemployment trade-off."),
 dict(q="A rise in the price of imported raw materials will, on the Phillips curve diagram,", choices=[
   "move the economy down the existing curve",
   "shift the short-run curve outward while leaving the long-run curve unchanged",
   "shift the long-run curve left",
   "shift the short-run curve inward",
   "have no effect"], ans=1,
   why="A cost shock worsens the short-run trade-off without changing the natural rate."),
 dict(q="Rational expectations theory suggests that a fully anticipated monetary expansion will", choices=[
   "reduce unemployment substantially",
   "raise inflation with little or no change in unemployment, even in the short run",
   "reduce inflation",
   "lower the natural rate",
   "have no effect on prices"], ans=1,
   why="If the policy is anticipated, expectations adjust immediately and the short-run curve shifts at once."),
 dict(q="Along the long-run Phillips curve, a higher inflation rate is associated with", choices=[
   "lower unemployment",
   "the same natural rate of unemployment",
   "higher unemployment",
   "zero unemployment",
   "higher potential output"], ans=1,
   why="The curve is vertical, so unemployment is unchanged at every inflation rate."),
 dict(q="An economy with an expected inflation rate of 3 percent experiences actual inflation of 3 percent. Unemployment is therefore", choices=[
   "below the natural rate",
   "at the natural rate",
   "above the natural rate",
   "zero",
   "impossible to relate to the natural rate"], ans=1,
   why="No inflation surprise means no deviation from the natural rate."),
 dict(q="The short-run Phillips curve becomes steeper as", choices=[
   "expectations become slower to adjust",
   "the economy moves further below the natural rate of unemployment and closer to capacity",
   "unemployment rises",
   "the natural rate rises",
   "aggregate demand falls"], ans=1,
   why="Near capacity, extra demand shows up mainly as inflation rather than as employment gains."),
 dict(q="A policy that lowers the natural rate of unemployment, such as improved worker retraining, will", choices=[
   "shift only the short-run curve right",
   "shift the long-run Phillips curve left and permit lower unemployment at any inflation rate",
   "shift the long-run curve right",
   "raise inflation permanently",
   "make the long-run curve downward sloping"], ans=1,
   why="Reducing structural unemployment lowers the sustainable unemployment rate."),
 dict(q="If the central bank tries to hold unemployment permanently below the natural rate, the likely result is", choices=[
   "permanently lower unemployment with stable inflation",
   "accelerating inflation as expectations chase actual inflation upward",
   "deflation",
   "a lower natural rate",
   "no change in inflation"], ans=1,
   why="Each time expectations catch up, more inflation is needed to keep unemployment below its natural level."),
 dict(q="Two economies are identical except that one has a credible inflation-targeting central bank. That economy will most likely have", choices=[
   "a higher natural rate",
   "a more stable expected inflation rate and therefore a more stable short-run Phillips curve",
   "no short-run trade-off at all",
   "permanently lower unemployment",
   "higher inflation"], ans=1,
   why="Anchored expectations keep the short-run curve from drifting upward."),
 dict(q="Which of the following is the best evidence that the long-run Phillips curve is vertical?", choices=[
   "inflation and unemployment always move together",
   "sustained high inflation has not been accompanied by permanently low unemployment",
   "unemployment is always zero",
   "inflation is always zero",
   "supply shocks do not exist"], ans=1,
   why="Economies with persistently high inflation have not enjoyed permanently low unemployment."),
]
