# MACRO 5.7 Public Policy and Economic Growth — 50 questions
# Every number worked out:
#   POLICY table: two budget allocations of the same $500 billion.
#     Plan A: current transfers 400, infrastructure and R&D 100.
#     Plan B: current transfers 250, infrastructure and R&D 250.
#     Plan B devotes 250 - 100 = $150 billion more to capacity-building outlays,
#     so Plan B raises future potential output by more while Plan A supports more
#     consumption today. Shares: Plan A 100/500 = 20% growth-oriented;
#     Plan B 250/500 = 50% growth-oriented.
#   Rule of 70 reused: a policy that lifts growth from 2% to 2.8% cuts doubling time
#     from 70/2 = 35 years to 70/2.8 = 25 years, a saving of 10 years.
#   Saving-incentive example: national saving rises from $600b to $700b, a 16.7% rise
#     (100/600 = 0.1667).
TOPIC = ("5.7", "Public Policy and Economic Growth", 5)
POLICY = dict(
    headers=["Budget item", "Plan A ($b)", "Plan B ($b)"],
    rows=[["Current transfer payments", "400", "250"],
          ["Infrastructure and research", "100", "250"],
          ["Total", "500", "500"]],
)
QUESTIONS = [
 dict(q="Public policies aimed at long-run growth work primarily by", choices=[
   "shifting aggregate demand to the right",
   "shifting long-run aggregate supply to the right through more or better resources and technology",
   "lowering the price level",
   "raising the money supply",
   "reducing the unemployment rate below the natural rate"], ans=1,
   why="Growth policy targets the economy's capacity, not its current level of spending."),
 dict(q="Government spending on public education contributes to growth mainly by", choices=[
   "increasing aggregate demand permanently",
   "raising human capital and therefore labor productivity",
   "lowering the price level",
   "raising the money supply",
   "reducing the natural rate of interest"], ans=1,
   why="Better-educated workers produce more per hour."),
 dict(q="Government investment in transportation infrastructure raises growth because it", choices=[
   "raises transfer payments",
   "lowers the cost of moving goods and raises the productivity of private capital and labor",
   "reduces the capital stock",
   "raises the inflation rate permanently",
   "increases the labor force participation rate directly"], ans=1,
   why="Public capital complements private inputs and raises what they can produce."),
 dict(q="A research and development tax credit is intended to", choices=[
   "reduce aggregate demand",
   "increase private spending on innovation, which raises technological progress",
   "reduce the capital stock",
   "raise the natural rate of unemployment",
   "increase current consumption"], ans=1,
   why="It lowers the cost of R&D, so firms do more of it than they otherwise would."),
 dict(q="Governments often subsidize basic research because", choices=[
   "research is unproductive",
   "the knowledge it produces spills over to other firms, so private firms would otherwise underinvest",
   "research reduces the money supply",
   "firms are forbidden to do research",
   "research raises the price level"], ans=1,
   why="Positive externalities mean the private return falls short of the social return."),
 dict(q="Patent protection promotes growth by", choices=[
   "eliminating competition permanently",
   "giving inventors a temporary exclusive right so that innovation is profitable enough to undertake",
   "lowering prices immediately",
   "reducing research spending",
   "raising the money supply"], ans=1,
   why="Without some protection of returns, ideas would be copied and innovation underprovided."),
 dict(q="A cost of patent protection is that", choices=[
   "it raises innovation too much",
   "it temporarily restricts use of the new knowledge and allows above-competitive prices",
   "it lowers technological progress",
   "it reduces human capital",
   "it raises the price level permanently"], ans=1,
   why="The incentive to invent is bought at the price of restricted access for a period."),
 dict(q="Secure and enforceable property rights promote growth because", choices=[
   "they raise the money supply",
   "people invest and innovate only when they expect to keep the returns from doing so",
   "they lower consumption",
   "they eliminate scarcity",
   "they raise the price level"], ans=1,
   why="The expectation of expropriation destroys the incentive to accumulate capital."),
 dict(q="Political instability discourages growth mainly because it", choices=[
   "raises the labor force",
   "raises the risk of investing, deterring both domestic and foreign capital formation",
   "lowers the natural rate of unemployment",
   "raises productivity",
   "reduces the inflation rate"], ans=1,
   why="Investors require a much higher expected return where property and contracts are insecure."),
 dict(q="Policies that increase the saving rate promote growth because", choices=[
   "saving reduces the capital stock",
   "greater saving increases the supply of loanable funds, lowering the real interest rate and financing more investment",
   "saving raises current consumption",
   "saving lowers productivity",
   "saving raises the price level"], ans=1,
   why="Investment must be funded out of saving, and investment builds the capital stock."),
 dict(q="A tax-preferred retirement savings account is intended to", choices=[
   "raise current consumption",
   "raise the after-tax return to saving and therefore increase national saving and investment",
   "lower the money supply",
   "reduce human capital",
   "raise the deficit deliberately"], ans=1,
   why="A higher after-tax return makes saving more attractive relative to consuming now."),
 dict(q="A shift from an income tax toward a consumption tax is often argued to promote growth because it", choices=[
   "taxes saving more heavily",
   "reduces the tax penalty on saving and investment",
   "eliminates all taxes",
   "raises aggregate demand permanently",
   "raises the price level"], ans=1,
   why="A consumption tax falls on what is spent rather than on the return to deferring spending."),
 dict(q="A cut in the corporate income tax is argued to promote growth because it", choices=[
   "lowers wages",
   "raises the after-tax return on business investment, encouraging capital formation",
   "reduces technology",
   "reduces human capital",
   "raises the deficit and therefore raises investment"], ans=1,
   why="Higher after-tax returns raise the quantity of investment projects worth undertaking."),
 dict(q="A concern about financing growth policies with borrowing is that", choices=[
   "borrowing has no cost",
   "the resulting rise in the real interest rate may crowd out private investment, partly offsetting the benefit",
   "borrowing raises private saving one for one",
   "borrowing lowers the deficit",
   "borrowing reduces the money supply"], ans=1,
   why="Public investment funded by deficits competes with private investment for the same pool of saving."),
 dict(q="Refer to the table. Compared with Plan A, Plan B devotes more to infrastructure and research by", table=POLICY, choices=[
   "$50 billion", "$100 billion", "$150 billion", "$250 billion", "$400 billion"], ans=2,
   why="$250 billion less $100 billion is $150 billion."),
 dict(q="Refer to the table. Under Plan B, the share of the budget devoted to infrastructure and research is", table=POLICY, choices=[
   "10%", "20%", "25%", "50%", "80%"], ans=3,
   why="250 out of 500 is 50 percent."),
 dict(q="Refer to the table. Compared with Plan A, Plan B is most likely to", table=POLICY, choices=[
   "raise current consumption and future output",
   "reduce current consumption but raise future potential output",
   "reduce both current consumption and future output",
   "have identical effects since totals are equal",
   "reduce the capital stock"], ans=1,
   why="Shifting spending from current transfers to capacity-building outlays trades consumption now for capacity later."),
 dict(q="Refer to the table. A politician who favors Plan A over Plan B is most plausibly prioritizing", table=POLICY, choices=[
   "long-run productivity growth",
   "the living standards of current recipients over future output",
   "the capital stock",
   "technological progress",
   "the export sector"], ans=1,
   why="Transfers support consumption today rather than building future capacity."),
 dict(q="The central trade-off in growth-oriented public policy is between", choices=[
   "inflation and unemployment",
   "consumption today and greater output in the future",
   "exports and imports",
   "money and bonds",
   "taxes and tariffs"], ans=1,
   why="Resources used to build capital and knowledge cannot be consumed now."),
 dict(q="Openness to international trade is generally thought to promote growth because it", choices=[
   "protects domestic firms from competition",
   "allows specialization according to comparative advantage and speeds the diffusion of technology",
   "raises the price level",
   "reduces the capital stock",
   "eliminates opportunity cost"], ans=1,
   why="Trade raises productivity through specialization and brings in ideas and capital goods."),
 dict(q="A tariff imposed to protect a domestic industry is likely to", choices=[
   "raise long-run growth",
   "reduce efficiency by shifting resources toward less productive uses",
   "raise productivity",
   "lower domestic prices",
   "increase technological diffusion"], ans=1,
   why="Protection keeps resources in industries where the country is comparatively inefficient."),
 dict(q="Policies that attract foreign direct investment can raise growth because", choices=[
   "foreign firms never bring technology",
   "they add to the domestic capital stock and often transfer technology and management practices",
   "they lower the labor force",
   "they raise the natural rate of unemployment",
   "they reduce national saving"], ans=1,
   why="FDI supplements domestic saving and imports know-how along with the capital."),
 dict(q="Public health spending in a low-income country can raise growth because", choices=[
   "healthier workers are less productive",
   "better health raises human capital, working life, and labor productivity",
   "it lowers the price level",
   "it raises the money supply",
   "it lowers the saving rate"], ans=1,
   why="Health is a component of human capital."),
 dict(q="A policy that raises the growth rate of real GDP per capita from 2 percent to 2.8 percent shortens the doubling time from about", choices=[
   "70 years to 35 years", "35 years to 25 years", "25 years to 20 years", "35 years to 14 years", "20 years to 10 years"], ans=1,
   why="70/2 = 35 years and 70/2.8 = 25 years."),
 dict(q="If a saving-incentive policy raises national saving from $600 billion to $700 billion, national saving has risen by about", choices=[
   "10%", "14%", "17%", "20%", "100%"], ans=2,
   why="100/600 is about 16.7 percent."),
 dict(q="Which of the following is the best example of a supply-side growth policy?", choices=[
   "an increase in unemployment benefits during a recession",
   "a permanent investment tax credit for new equipment",
   "an open market purchase of bonds",
   "an increase in transfer payments",
   "a temporary consumer rebate"], ans=1,
   why="It works by raising capital formation rather than by adding to current spending."),
 dict(q="Which of the following is primarily a demand-side stabilization policy rather than a growth policy?", choices=[
   "a program to expand vocational training",
   "a temporary tax rebate designed to boost consumer spending during a downturn",
   "a research subsidy",
   "construction of a new port",
   "reform of property registration"], ans=1,
   why="It aims to raise current spending rather than the economy's productive capacity."),
 dict(q="An improvement in the rule of law and contract enforcement is expected to", choices=[
   "shift aggregate demand right only",
   "shift long-run aggregate supply right by raising the return to investment and lowering transaction costs",
   "shift LRAS left",
   "raise the natural rate of unemployment",
   "have no effect on output"], ans=1,
   why="Institutions determine whether the incentives to invest and innovate exist at all."),
 dict(q="Which of the following policies would most directly raise the quantity of physical capital per worker?", choices=[
   "an increase in retirement transfer payments",
   "an investment tax credit that reduces the cost of new plant and equipment",
   "an increase in import tariffs",
   "an increase in the money supply",
   "a reduction in the discount rate for one quarter"], ans=1,
   why="It lowers the effective price of capital goods, so firms buy more of them."),
 dict(q="Which of the following would most directly raise human capital?", choices=[
   "an infrastructure bond issue",
   "a program expanding access to secondary and technical education",
   "a patent extension",
   "a corporate tax cut",
   "an open market operation"], ans=1,
   why="Human capital is built through education, training, and experience."),
 dict(q="The main reason growth policies are politically difficult is that", choices=[
   "they have no benefits",
   "their costs are borne now while their benefits arrive years later",
   "they are illegal",
   "they always cause inflation",
   "they raise unemployment permanently"], ans=1,
   why="Present sacrifice for future gain is a hard case to make within an electoral cycle."),
 dict(q="A government that reduces its budget deficit contributes to growth by", choices=[
   "reducing national saving",
   "raising public saving, which lowers the real interest rate and encourages private investment",
   "raising the money supply",
   "raising interest rates",
   "reducing the capital stock"], ans=1,
   why="Less government borrowing leaves more of the pool of saving available for private investment."),
 dict(q="Immigration policy can affect long-run growth by", choices=[
   "changing the price level",
   "changing the size and skill composition of the labor force",
   "changing velocity",
   "changing the money multiplier",
   "changing the inflation rate"], ans=1,
   why="Labor is a factor of production, and its quantity and quality determine potential output."),
 dict(q="Which statement about growth policy and the price level is most accurate?", choices=[
   "Growth policy raises the price level permanently.",
   "By shifting LRAS right, successful growth policy tends to put downward pressure on the price level for a given level of aggregate demand.",
   "Growth policy has no effect on output.",
   "Growth policy raises inflation one for one.",
   "Growth policy works only through the money supply."], ans=1,
   why="More capacity relative to demand means output can rise without prices rising."),
 dict(q="A concern about subsidizing particular industries to promote growth is that", choices=[
   "subsidies never change behavior",
   "governments may choose poorly and direct resources toward politically favored rather than productive uses",
   "subsidies reduce the deficit",
   "subsidies raise the money supply",
   "subsidies always lower prices"], ans=1,
   why="The information and incentive problems of industrial policy are the standard objection to it."),
 dict(q="Which of the following would be expected to lower an economy's long-run growth rate?", choices=[
   "expanded technical training",
   "a policy of expropriating successful private firms",
   "improved transport links",
   "increased spending on basic research",
   "greater openness to trade"], ans=1,
   why="Expropriation destroys the incentive to invest and accumulate capital."),
 dict(q="An economy that improves its financial system so that savings are channeled more efficiently to investors will", choices=[
   "reduce investment",
   "raise growth by improving the allocation of saving toward the most productive projects",
   "raise the price level permanently",
   "reduce human capital",
   "have no effect on capital formation"], ans=1,
   why="Financial development raises the productivity of a given quantity of saving."),
 dict(q="A country that spends heavily on current consumption transfers and little on investment is likely to have", choices=[
   "rapid growth in potential output",
   "high current living standards relative to its future growth prospects",
   "a rapidly growing capital stock",
   "rising productivity",
   "an outward-shifting LRAS"], ans=1,
   why="The trade-off between present consumption and future capacity is unavoidable."),
 dict(q="Public policies that reduce structural unemployment, such as retraining and job-matching services,", choices=[
   "raise the natural rate of unemployment",
   "lower the natural rate of unemployment and raise potential output",
   "shift aggregate demand left",
   "raise the price level",
   "have no supply-side effect"], ans=1,
   why="Better matching means more of the labor force is productively employed at any time."),
 dict(q="Deregulation that removes unnecessary barriers to starting a business is expected to", choices=[
   "reduce entrepreneurship",
   "raise entry, competition, and innovation, contributing to productivity growth",
   "raise the price level permanently",
   "lower the labor force",
   "reduce the capital stock"], ans=1,
   why="Lower entry barriers let new and more productive firms displace less productive ones."),
 dict(q="A criticism of relying on deficit-financed public investment for growth is that", choices=[
   "public investment never raises productivity",
   "the growth benefit must be weighed against the crowding out of private investment and higher future debt service",
   "public investment lowers the price level",
   "public investment raises the money supply",
   "public investment reduces human capital"], ans=1,
   why="Both sides of the ledger matter: the asset created and the private capital displaced."),
 dict(q="Two economies invest the same share of GDP, but one has stronger institutions. That economy is likely to have", choices=[
   "identical growth",
   "faster growth, because the same investment is allocated more productively",
   "slower growth",
   "higher inflation necessarily",
   "a smaller labor force"], ans=1,
   why="Institutions determine how efficiently investment is used, not just how much occurs."),
 dict(q="Which of the following is the best example of a policy that raises technology rather than capital or labor?", choices=[
   "a subsidy for new factory construction",
   "public funding of university scientific research",
   "an increase in the retirement age",
   "an immigration expansion",
   "an infrastructure bond"], ans=1,
   why="It expands the stock of knowledge rather than the stock of machines or workers."),
 dict(q="An economy that raises its investment share of GDP will, in the short run, most likely experience", choices=[
   "higher current consumption",
   "lower current consumption but a faster-growing capital stock",
   "no change in the capital stock",
   "an immediate doubling of output",
   "a permanent recession"], ans=1,
   why="Output devoted to capital goods is output not consumed today."),
 dict(q="Policies to promote growth are often described as supply-side because they", choices=[
   "shift the aggregate demand curve",
   "operate on the economy's productive capacity rather than on the level of spending",
   "operate through the money market",
   "reduce the unemployment rate below the natural rate",
   "raise the price level"], ans=1,
   why="They target LRAS, the supply side of the AD-AS model."),
 dict(q="If a growth policy succeeds, the long-run Phillips curve will", choices=[
   "become downward sloping",
   "remain vertical, though it may shift if the natural rate of unemployment changes",
   "become horizontal",
   "shift up",
   "disappear"], ans=1,
   why="Growth raises potential output; the long-run curve moves only if the natural rate itself changes."),
 dict(q="A government that improves the efficiency of its tax collection while lowering marginal rates may raise growth by", choices=[
   "reducing the capital stock",
   "reducing the distortion of decisions to work, save, and invest",
   "raising the price level",
   "raising velocity",
   "increasing transfer payments"], ans=1,
   why="Lower marginal distortions raise the incentive to supply labor and capital."),
 dict(q="Investment in early childhood education is often defended on growth grounds because", choices=[
   "it raises current consumption",
   "the returns to human capital investment compound over an entire working life",
   "it lowers the price level",
   "it reduces the labor force",
   "it raises the money supply"], ans=1,
   why="Skills acquired early raise productivity for decades."),
 dict(q="Which combination would most reliably raise an economy's long-run growth rate?", choices=[
   "higher transfer payments and monetary expansion",
   "higher national saving, stronger property rights, and increased spending on education and research",
   "higher tariffs and a larger deficit",
   "lower interest rates alone",
   "an increase in aggregate demand alone"], ans=1,
   why="Growth comes from more capital, better human capital, better technology, and institutions that reward investment."),
 dict(q="The most important limitation of demand-side stabilization policy as a growth strategy is that", choices=[
   "it cannot affect output at all",
   "it can move output toward potential but cannot by itself raise potential output",
   "it always causes deflation",
   "it lowers the natural rate of unemployment permanently",
   "it raises the capital stock automatically"], ans=1,
   why="Stabilization closes gaps; growth requires expanding the capacity itself."),
]
