# MACRO 6.1 Balance of Payments Accounts — 50 questions
# Arithmetic verified line by line:
#   BOP1 table: exports of goods 500, imports of goods 620 => goods balance -120.
#     exports of services 180, imports of services 130 => services balance +50.
#     net investment income -20, net transfers -10.
#     Current account = -120 + 50 - 20 - 10 = -100.
#     With official reserves unchanged and no statistical discrepancy, the
#     financial account must be +100.
#   BOP2 table: current account -250, capital account +5, so the financial
#     account balance = +245 (so that -250 + 5 + 245 = 0).
#   Trade balance in BOP1 counting goods only = 500 - 620 = -120 (deficit of 120).
#   Trade balance counting goods and services = -120 + 50 = -70.
TOPIC = ("6.1", "Balance of Payments Accounts", 6)

BOP1 = dict(headers=["Item", "Billions of dollars"],
            rows=[["Exports of goods", "500"],
                  ["Imports of goods", "620"],
                  ["Exports of services", "180"],
                  ["Imports of services", "130"],
                  ["Net investment income", "-20"],
                  ["Net transfers", "-10"]])

BOP2 = dict(headers=["Account", "Billions of dollars"],
            rows=[["Current account", "-250"],
                  ["Capital account", "+5"],
                  ["Financial account", "?"]])

QUESTIONS = [
 dict(q="The balance of payments is best described as", choices=[
   "a record of a country's government budget",
   "a record of all transactions between residents of a country and the rest of the world during a period",
   "a list of a country's exports only",
   "the total value of a country's money supply held abroad",
   "the difference between a country's tax revenue and its spending"], ans=1,
   why="The balance of payments records every cross-border transaction, not just trade."),
 dict(q="The current account records", choices=[
   "purchases of foreign factories and financial assets",
   "trade in goods and services, income payments, and transfers",
   "changes in official reserve holdings only",
   "domestic transactions between households and firms",
   "the government's borrowing from its own citizens"], ans=1,
   why="Goods, services, income, and transfers are the four components of the current account."),
 dict(q="The financial account records", choices=[
   "exports and imports of goods",
   "purchases and sales of financial and real assets across borders",
   "wages paid to domestic workers",
   "gifts sent abroad by households",
   "tourism spending by foreign visitors"], ans=1,
   why="The financial account tracks cross-border ownership of assets."),
 dict(q="A country's balance of trade in goods is calculated as", choices=[
   "exports of goods plus imports of goods",
   "exports of goods minus imports of goods",
   "imports of goods minus exports of goods",
   "exports of goods divided by imports of goods",
   "exports of goods plus net transfers"], ans=1,
   why="A trade balance is always exports minus imports."),
 dict(q="A country runs a current account deficit when", choices=[
   "it exports more than it imports",
   "the value of what it buys from and pays to the rest of the world in the current account exceeds what it sells and receives",
   "its government spends more than it taxes",
   "its currency appreciates",
   "its central bank raises interest rates"], ans=1,
   why="A deficit means current-account outflows exceed current-account inflows."),
 dict(q="Ignoring the small capital account and statistical discrepancy, the balance of payments identity says that", choices=[
   "the current account balance equals the financial account balance",
   "the current account balance plus the financial account balance equals zero",
   "both accounts must be in surplus",
   "both accounts must be in deficit",
   "the current account always equals net exports of goods only"], ans=1,
   why="The two accounts are mirror images, so their sum is zero."),
 dict(q="If a country has a current account deficit of $200 billion, then (ignoring the capital account and any discrepancy) its financial account has", choices=[
   "a deficit of $200 billion",
   "a surplus of $200 billion",
   "a balance of zero",
   "a surplus of $400 billion",
   "an indeterminate balance"], ans=1,
   why="A current account deficit is financed by a matching net inflow of financial capital."),
 dict(q="A U.S. household buys a Japanese-made television. In the U.S. balance of payments this is recorded as", choices=[
   "a credit in the current account",
   "a debit in the current account",
   "a credit in the financial account",
   "a debit in the financial account",
   "it is not recorded"], ans=1,
   why="Importing a good is a purchase from abroad and so a current account debit."),
 dict(q="A German firm buys software from a U.S. company. In the U.S. balance of payments this is", choices=[
   "a debit in the current account",
   "a credit in the current account",
   "a debit in the financial account",
   "a credit in the financial account",
   "a capital account entry"], ans=1,
   why="Exporting a service brings money in, so it is a current account credit for the United States."),
 dict(q="A U.S. investor buys shares in a British corporation. In the U.S. balance of payments this is", choices=[
   "a credit in the current account",
   "a debit in the financial account",
   "a credit in the financial account",
   "a debit in the current account",
   "a transfer"], ans=1,
   why="Buying a foreign asset is an outflow of financial capital, a financial account debit."),
 dict(q="A Canadian pension fund buys U.S. Treasury bonds. For the United States this is", choices=[
   "a debit in the financial account",
   "a credit in the financial account",
   "a debit in the current account",
   "a credit in the current account",
   "not recorded anywhere"], ans=1,
   why="A foreigner buying a U.S. asset is an inflow of financial capital into the United States."),
 dict(q="A Mexican worker in the United States sends money home to her family. For the United States this remittance is", choices=[
   "a credit in the financial account",
   "a debit in the current account, as a transfer",
   "a credit in the current account",
   "a debit in the financial account",
   "excluded from the balance of payments"], ans=1,
   why="Remittances are unilateral transfers and money leaving counts as a current account debit."),
 dict(q="Japanese tourists spend money at hotels in Hawaii. For the United States this is", choices=[
   "a debit in the current account",
   "a credit in the current account, because a service is exported",
   "a credit in the financial account",
   "a debit in the financial account",
   "a transfer payment"], ans=1,
   why="Selling lodging to a foreign visitor is a service export."),
 dict(q="A U.S. multinational builds a new factory in Vietnam. For the United States this is", choices=[
   "a credit in the current account",
   "a debit in the financial account, as foreign direct investment abroad",
   "a credit in the financial account",
   "a debit in the current account",
   "a capital account transfer"], ans=1,
   why="Acquiring real assets abroad sends financial capital out of the country."),
 dict(q="A South Korean automaker opens an assembly plant in Alabama. For the United States this is", choices=[
   "a debit in the financial account",
   "a credit in the financial account, as foreign direct investment inflow",
   "a credit in the current account",
   "a debit in the current account",
   "not part of the balance of payments"], ans=1,
   why="Foreign money entering to buy real assets in the U.S. is a financial account credit."),
 dict(q="A U.S. bondholder receives an interest payment from a French government bond she owns. For the United States this appears as", choices=[
   "a debit in the financial account",
   "a credit in the current account, as investment income received",
   "a debit in the current account",
   "a credit in the financial account",
   "an official reserve transaction"], ans=1,
   why="Income earned on assets held abroad is a current account credit."),
 dict(q="U.S. foreign aid granted to a developing country is recorded as", choices=[
   "a current account credit",
   "a current account debit, as a unilateral transfer",
   "a financial account credit",
   "a financial account debit",
   "an export of goods"], ans=1,
   why="Aid is a transfer with nothing received in return, and it flows out."),
 dict(q="Which of the following belongs in the financial account rather than the current account?", choices=[
   "a shipment of wheat sold to Egypt",
   "a Chinese investor's purchase of an apartment building in Chicago",
   "royalties paid to a U.S. musician by a foreign broadcaster",
   "dividends received by a U.S. investor from a Brazilian stock",
   "an American family's vacation spending in Rome"], ans=1,
   why="Buying property abroad is an asset purchase, so it is a financial account entry."),
 dict(q="Which of the following belongs in the current account?", choices=[
   "a U.S. bank's loan to a Turkish firm",
   "the sale of U.S.-grown soybeans to China",
   "a Japanese purchase of U.S. corporate stock",
   "a U.S. purchase of a British factory",
   "a foreign central bank's purchase of dollars"], ans=1,
   why="An export of goods is a current account transaction."),
 dict(q="Net exports as reported in GDP correspond most closely to which balance of payments component?", choices=[
   "the financial account balance",
   "the balance on goods and services within the current account",
   "the capital account balance",
   "official reserve transactions",
   "net unilateral transfers"], ans=1,
   why="Net exports is exports minus imports of goods and services, the largest part of the current account."),
 dict(q="Using the table, the balance on goods is", table=BOP1, choices=[
   "a deficit of $120 billion",
   "a surplus of $120 billion",
   "a deficit of $70 billion",
   "a surplus of $50 billion",
   "zero"], ans=0,
   why="Goods exports of 500 minus goods imports of 620 is -120."),
 dict(q="Using the table, the balance on services is", table=BOP1, choices=[
   "a deficit of $50 billion",
   "a surplus of $50 billion",
   "a surplus of $180 billion",
   "a deficit of $130 billion",
   "zero"], ans=1,
   why="Service exports of 180 minus service imports of 130 is +50."),
 dict(q="Using the table, the combined balance on goods and services is", table=BOP1, choices=[
   "a deficit of $70 billion",
   "a surplus of $70 billion",
   "a deficit of $120 billion",
   "a deficit of $100 billion",
   "a surplus of $50 billion"], ans=0,
   why="Adding the goods deficit of 120 to the services surplus of 50 gives -70."),
 dict(q="Using the table, the current account balance is", table=BOP1, choices=[
   "a deficit of $100 billion",
   "a surplus of $100 billion",
   "a deficit of $70 billion",
   "a deficit of $120 billion",
   "a surplus of $30 billion"], ans=0,
   why="-120 goods, +50 services, -20 income, and -10 transfers sum to -100."),
 dict(q="Using the table, and assuming official reserves do not change and there is no statistical discrepancy, the financial account balance is", table=BOP1, choices=[
   "a deficit of $100 billion",
   "a surplus of $100 billion",
   "zero",
   "a surplus of $70 billion",
   "a deficit of $70 billion"], ans=1,
   why="The financial account must offset the current account deficit of 100."),
 dict(q="Using the table, the financial account balance must be", table=BOP2, choices=[
   "a deficit of $245 billion",
   "a surplus of $245 billion",
   "a surplus of $255 billion",
   "a deficit of $250 billion",
   "zero"], ans=1,
   why="The three accounts sum to zero, so -250 + 5 + 245 = 0."),
 dict(q="A country exports $340 billion of goods, imports $410 billion of goods, exports $90 billion of services, and imports $60 billion of services. Its balance on goods and services is", choices=[
   "a deficit of $40 billion",
   "a deficit of $70 billion",
   "a surplus of $30 billion",
   "a surplus of $40 billion",
   "a deficit of $100 billion"], ans=0,
   why="Goods give -70 and services give +30, for a net of -40."),
 dict(q="A country has a current account surplus of $150 billion and a capital account balance of zero. Its financial account balance is", choices=[
   "a surplus of $150 billion",
   "a deficit of $150 billion",
   "zero",
   "a deficit of $300 billion",
   "indeterminate"], ans=1,
   why="A current account surplus means the country is on net lending abroad, a financial account deficit."),
 dict(q="A country with a current account surplus is, on net,", choices=[
   "borrowing from the rest of the world",
   "acquiring claims on the rest of the world",
   "reducing its exports",
   "running a government budget surplus",
   "experiencing a currency depreciation"], ans=1,
   why="Selling more than it buys leaves the country holding foreign assets."),
 dict(q="A country with a persistent current account deficit is, on net,", choices=[
   "accumulating foreign assets",
   "selling assets to or borrowing from foreigners",
   "exporting financial capital",
   "necessarily in a recession",
   "necessarily running a budget surplus"], ans=1,
   why="The deficit is financed by net financial capital inflows, which are claims foreigners gain on the country."),
 dict(q="Which entry would appear in the capital account as it is defined in the balance of payments?", choices=[
   "a purchase of foreign stocks",
   "debt forgiveness granted to a foreign government",
   "an import of automobiles",
   "interest received on a foreign bond",
   "a foreign firm's purchase of a U.S. factory"], ans=1,
   why="The capital account covers a narrow set of items such as debt forgiveness and transfers of nonproduced assets."),
 dict(q="Official reserve transactions refer to", choices=[
   "private purchases of foreign stocks",
   "a central bank's purchases and sales of foreign currency assets",
   "commercial bank lending to firms",
   "government spending on goods and services",
   "household saving in foreign banks"], ans=1,
   why="Reserves are the foreign-currency assets a central bank buys and sells."),
 dict(q="A statistical discrepancy appears in the balance of payments because", choices=[
   "the identity is only an approximation in theory",
   "not every cross-border transaction is measured perfectly",
   "governments deliberately misreport trade",
   "exchange rates change during the year",
   "the current account is measured in a different currency"], ans=1,
   why="The accounts must balance in principle, so the discrepancy is a measurement residual."),
 dict(q="An increase in U.S. imports of goods, other things equal, will", choices=[
   "increase the U.S. current account balance",
   "decrease the U.S. current account balance",
   "leave the current account unchanged",
   "increase the financial account deficit",
   "decrease the U.S. money supply"], ans=1,
   why="Imports are a debit, so more of them push the current account toward deficit."),
 dict(q="A large increase in foreign purchases of U.S. government bonds would", choices=[
   "move the U.S. financial account toward deficit",
   "move the U.S. financial account toward surplus",
   "have no effect on the balance of payments",
   "reduce U.S. exports directly",
   "reduce the current account deficit dollar for dollar with no other change"], ans=1,
   why="Foreign purchases of U.S. assets are financial account credits."),
 dict(q="Which of the following would move the U.S. current account toward surplus?", choices=[
   "an increase in U.S. tourism spending abroad",
   "an increase in foreign demand for U.S. agricultural exports",
   "an increase in remittances sent from the U.S. to other countries",
   "an increase in U.S. imports of consumer electronics",
   "an increase in interest the U.S. pays to foreign bondholders"], ans=1,
   why="More exports are current account credits."),
 dict(q="Which of the following would move the U.S. current account toward deficit?", choices=[
   "an increase in foreign tourists visiting the United States",
   "an increase in the value of oil the United States imports",
   "an increase in dividends U.S. investors receive from abroad",
   "an increase in U.S. software exports",
   "an increase in foreign purchases of U.S. aircraft"], ans=1,
   why="A larger import bill is a larger current account debit."),
 dict(q="If a nation's exports and imports of goods and services are equal but it pays large net interest to foreign lenders, the current account", choices=[
   "must be in surplus",
   "is in deficit because of the negative net investment income",
   "must be zero",
   "cannot be determined without the financial account",
   "is unaffected by interest payments"], ans=1,
   why="Investment income is a current account component, so net payments abroad create a deficit."),
 dict(q="An American company's profits earned by its subsidiary in Ireland and sent back to the United States are recorded as", choices=[
   "a financial account debit",
   "a current account credit, as investment income",
   "a current account debit",
   "a capital account entry",
   "an export of goods"], ans=1,
   why="Repatriated earnings are income received from assets held abroad."),
 dict(q="Which statement about the relationship between the current and financial accounts is correct?", choices=[
   "a current account deficit is always harmful and always shrinks the financial account",
   "a current account deficit means a country receives more financial capital from abroad than it sends out",
   "both accounts can be in surplus at the same time in the long run",
   "the financial account balance is unrelated to the current account balance",
   "a current account surplus requires a financial account surplus"], ans=1,
   why="The offsetting net inflow of financial capital is exactly what finances the deficit."),
 dict(q="If foreigners suddenly find a country's assets far more attractive, that country's currency will tend to appreciate and its current account will tend to", choices=[
   "move toward surplus",
   "move toward deficit",
   "remain exactly unchanged",
   "become identical to its financial account",
   "disappear from the balance of payments"], ans=1,
   why="A financial account surplus and a stronger currency go together with a weaker current account."),
 dict(q="Which of the following is NOT part of the current account?", choices=[
   "merchandise exports",
   "a Japanese investor's purchase of U.S. corporate bonds",
   "tourism receipts",
   "net investment income",
   "remittances sent abroad"], ans=1,
   why="A bond purchase is a financial asset transaction and belongs in the financial account."),
 dict(q="Which of the following is NOT part of the financial account?", choices=[
   "foreign direct investment abroad",
   "payment for imported crude oil",
   "purchases of foreign stocks by domestic residents",
   "foreign purchases of domestic real estate",
   "cross-border bank lending"], ans=1,
   why="Paying for imported goods is a current account debit."),
 dict(q="Suppose a country's exports of goods and services are $700 billion, imports are $700 billion, net investment income is +$40 billion, and net transfers are -$15 billion. The current account balance is", choices=[
   "-$55 billion",
   "-$15 billion",
   "+$25 billion",
   "+$40 billion",
   "+$55 billion"], ans=2,
   why="Zero on goods and services plus 40 minus 15 equals +25."),
 dict(q="A student claims that a current account deficit proves a country is 'losing' in trade. The best correction is that", choices=[
   "the claim is right because imports always destroy jobs",
   "the deficit is matched by an inflow of financial capital that can fund domestic investment",
   "current account deficits are impossible in a floating exchange rate system",
   "the deficit means the country's exports are zero",
   "deficits only occur when a government overspends"], ans=1,
   why="The deficit is financed by foreigners investing in the country, which is not automatically a loss."),
 dict(q="A country's current account deficit widens while its currency is fixed and the central bank sells foreign reserves. The reserve sale is recorded as", choices=[
   "a current account credit",
   "a credit in the balance of payments that offsets part of the deficit",
   "a current account debit",
   "an increase in the statistical discrepancy",
   "an export of goods"], ans=1,
   why="Selling reserves brings foreign currency in, financing the shortfall."),
 dict(q="Two countries trade only with each other. If Country A has a current account surplus of $80 billion, Country B must have", choices=[
   "a current account surplus of $80 billion",
   "a current account deficit of $80 billion",
   "a balanced current account",
   "a financial account deficit of $80 billion",
   "no recorded balance of payments"], ans=1,
   why="One country's surplus is its trading partner's deficit when only two countries trade."),
 dict(q="Which combination is internally consistent for a single country in one year?", choices=[
   "a current account surplus of $100 billion and a financial account surplus of $100 billion",
   "a current account deficit of $100 billion and a financial account surplus of $100 billion",
   "a current account deficit of $100 billion and a financial account deficit of $100 billion",
   "a current account surplus of $50 billion and a financial account deficit of $150 billion",
   "a current account balance of zero and a financial account surplus of $200 billion"], ans=1,
   why="Ignoring the capital account and discrepancy, the two balances must be equal and opposite."),
 dict(q="A rise in domestic real interest rates attracts foreign financial capital. The immediate balance of payments effect is", choices=[
   "a larger current account surplus",
   "a larger financial account surplus",
   "a larger financial account deficit",
   "a fall in official reserves",
   "no change in either account"], ans=1,
   why="Inflows of foreign financial capital are credits in the financial account."),
 dict(q="Over many years, a country that consistently runs current account deficits will most likely", choices=[
   "accumulate a growing net creditor position",
   "accumulate a growing net debtor position with the rest of the world",
   "see its financial account move into a matching deficit",
   "eliminate its need to export entirely",
   "experience a permanently fixed exchange rate"], ans=1,
   why="Each year's deficit adds to foreign claims on the country's assets."),
]
