# MACRO 6.3 The Foreign Exchange Market — 50 questions
# Convention used throughout, stated in every stem that needs it: "the market for
# dollars" has the price of the dollar in foreign currency on the vertical axis
# and the quantity of dollars on the horizontal axis. Demand for dollars comes
# from foreigners who want U.S. goods, services, or assets; supply of dollars
# comes from Americans who want foreign goods, services, or assets (they offer
# dollars to obtain foreign currency).
# Numeric checks:
#   Equilibrium example: at 0.90 euros per dollar, quantity demanded of dollars
#     = 400 billion and quantity supplied = 400 billion, so that is equilibrium.
#     At 1.00 euros per dollar Qd = 300 and Qs = 500, a surplus of 200 billion
#     dollars, which pushes the dollar's price down.
#     At 0.80 euros per dollar Qd = 500 and Qs = 300, a shortage of 200 billion,
#     which pushes the dollar's price up.
TOPIC = ("6.3", "The Foreign Exchange Market", 6)

FX = dict(headers=["Price of a dollar (euros)", "Quantity of dollars demanded (billions)",
                   "Quantity of dollars supplied (billions)"],
          rows=[["1.00", "300", "500"],
                ["0.90", "400", "400"],
                ["0.80", "500", "300"]])

QUESTIONS = [
 dict(q="In the foreign exchange market for dollars, the price on the vertical axis is", choices=[
   "the U.S. price level",
   "the value of a dollar expressed in foreign currency",
   "the U.S. nominal interest rate",
   "the quantity of dollars in circulation",
   "the U.S. trade balance"], ans=1,
   why="The foreign exchange market prices a currency in units of another currency."),
 dict(q="In the market for dollars, the quantity on the horizontal axis is", choices=[
   "real GDP",
   "the quantity of dollars exchanged",
   "the quantity of U.S. exports",
   "the money supply",
   "the number of foreign tourists"], ans=1,
   why="It is a market for the currency itself, so quantity of that currency is on the horizontal axis."),
 dict(q="Demand for U.S. dollars in the foreign exchange market comes from", choices=[
   "Americans buying foreign goods",
   "foreigners who want U.S. goods, services, or financial assets",
   "the Federal Reserve setting interest rates",
   "U.S. firms building factories abroad",
   "American tourists visiting Europe"], ans=1,
   why="Anyone abroad who wants something priced in dollars must first buy dollars."),
 dict(q="Supply of U.S. dollars in the foreign exchange market comes from", choices=[
   "foreigners buying U.S. exports",
   "Americans who want foreign currency to buy foreign goods or assets",
   "the U.S. Treasury issuing bonds domestically",
   "foreign purchases of U.S. Treasury bonds",
   "foreign students paying U.S. tuition"], ans=1,
   why="Americans offer dollars in exchange for the foreign currency they need."),
 dict(q="The demand curve for dollars slopes downward because as the dollar becomes more expensive in foreign currency", choices=[
   "U.S. goods and assets become cheaper to foreigners",
   "U.S. goods and assets become more expensive to foreigners, so fewer dollars are wanted",
   "the U.S. money supply falls",
   "American incomes fall",
   "foreign inflation rises"], ans=1,
   why="A dearer dollar raises the foreign-currency price of everything priced in dollars."),
 dict(q="The supply curve of dollars slopes upward because as the dollar becomes more valuable", choices=[
   "foreign goods become more expensive to Americans",
   "foreign goods and assets become cheaper to Americans, so more dollars are offered for foreign currency",
   "U.S. exports rise",
   "the Federal Reserve buys dollars",
   "foreign incomes rise"], ans=1,
   why="A stronger dollar buys more foreign currency, so Americans supply more dollars."),
 dict(q="The equilibrium exchange rate occurs where", choices=[
   "the current account balance is zero",
   "the quantity of the currency demanded equals the quantity supplied",
   "the central bank sets it",
   "exports equal imports of goods only",
   "interest rates are equal across countries"], ans=1,
   why="Like any market, the foreign exchange market clears where the two quantities are equal."),
 dict(q="Using the table for the market for dollars, the equilibrium price of a dollar is", table=FX, choices=[
   "0.70 euros", "0.80 euros", "0.90 euros", "1.00 euros", "1.10 euros"], ans=2,
   why="At 0.90 euros per dollar both quantity demanded and quantity supplied are 400 billion."),
 dict(q="Using the table, at a price of 1.00 euros per dollar there is", table=FX, choices=[
   "a shortage of 200 billion dollars",
   "a surplus of 200 billion dollars",
   "equilibrium",
   "a surplus of 100 billion dollars",
   "a shortage of 500 billion dollars"], ans=1,
   why="Quantity supplied of 500 exceeds quantity demanded of 300 by 200 billion."),
 dict(q="Using the table, at a price of 0.80 euros per dollar the market pressure is for the dollar to", table=FX, choices=[
   "depreciate", "appreciate", "stay put", "be devalued", "leave the market"], ans=1,
   why="Quantity demanded of 500 exceeds quantity supplied of 300, a shortage that bids the dollar's price up."),
 dict(q="An increase in foreign demand for U.S. exports will, in the market for dollars,", choices=[
   "shift the supply of dollars right and depreciate the dollar",
   "shift the demand for dollars right and appreciate the dollar",
   "shift the demand for dollars left and depreciate the dollar",
   "shift the supply of dollars left and depreciate the dollar",
   "leave both curves unchanged"], ans=1,
   why="Foreign buyers need dollars to pay for U.S. goods, so demand for dollars rises."),
 dict(q="An increase in American demand for imported goods will, in the market for dollars,", choices=[
   "shift the demand for dollars right and appreciate the dollar",
   "shift the supply of dollars right and depreciate the dollar",
   "shift the supply of dollars left and appreciate the dollar",
   "shift the demand for dollars left and appreciate the dollar",
   "have no effect"], ans=1,
   why="Americans must supply more dollars to obtain the foreign currency to pay for imports."),
 dict(q="A surge of foreign investment into U.S. stocks and bonds will, in the market for dollars,", choices=[
   "increase the supply of dollars and depreciate the dollar",
   "increase the demand for dollars and appreciate the dollar",
   "decrease the demand for dollars and depreciate the dollar",
   "decrease the supply of dollars and depreciate the dollar",
   "leave the exchange rate unchanged"], ans=1,
   why="Foreigners buy dollars in order to buy dollar-denominated assets."),
 dict(q="A wave of American purchases of European government bonds will, in the market for dollars,", choices=[
   "increase demand for dollars and appreciate the dollar",
   "increase the supply of dollars and depreciate the dollar",
   "decrease the supply of dollars and appreciate the dollar",
   "decrease demand for dollars and appreciate the dollar",
   "have no effect on the exchange rate"], ans=1,
   why="Americans offer dollars for euros, adding to the supply of dollars."),
 dict(q="A recession in Europe that reduces European incomes will, in the market for dollars,", choices=[
   "increase demand for dollars and appreciate the dollar",
   "decrease demand for dollars and depreciate the dollar",
   "increase supply of dollars and appreciate the dollar",
   "decrease supply of dollars and depreciate the dollar",
   "have no effect"], ans=1,
   why="Poorer Europeans buy fewer U.S. exports, so they demand fewer dollars."),
 dict(q="A boom in the United States that raises American incomes will, in the market for dollars,", choices=[
   "decrease the supply of dollars and appreciate the dollar",
   "increase the supply of dollars and depreciate the dollar",
   "increase the demand for dollars and appreciate the dollar",
   "decrease the demand for dollars and depreciate the dollar",
   "leave the exchange rate unchanged"], ans=1,
   why="Higher American income raises import purchases, and Americans supply dollars to pay for them."),
 dict(q="In the market for euros, an increase in American demand for European wine will", choices=[
   "shift the demand for euros right and appreciate the euro",
   "shift the supply of euros right and depreciate the euro",
   "shift the demand for euros left and depreciate the euro",
   "shift the supply of euros left and appreciate the euro",
   "leave the euro's value unchanged"], ans=0,
   why="Americans must buy euros to pay for the wine, which raises demand for euros."),
 dict(q="In the market for euros, an increase in European purchases of U.S. Treasury bonds will", choices=[
   "increase demand for euros and appreciate the euro",
   "increase the supply of euros and depreciate the euro",
   "decrease the supply of euros and appreciate the euro",
   "decrease demand for euros and appreciate the euro",
   "leave the euro unaffected"], ans=1,
   why="Europeans offer euros in order to obtain the dollars they need, adding to euro supply."),
 dict(q="In the market for Mexican pesos, a rise in American tourism to Mexico will", choices=[
   "increase demand for pesos and appreciate the peso",
   "increase supply of pesos and depreciate the peso",
   "decrease demand for pesos and depreciate the peso",
   "decrease supply of pesos and appreciate the peso",
   "have no effect on the peso"], ans=0,
   why="American tourists need pesos to spend in Mexico."),
 dict(q="If demand for a currency increases while its supply is unchanged, the currency will", choices=[
   "depreciate and the quantity exchanged will fall",
   "appreciate and the quantity exchanged will rise",
   "appreciate and the quantity exchanged will fall",
   "depreciate and the quantity exchanged will rise",
   "stay at the same value"], ans=1,
   why="A rightward demand shift raises both price and quantity in any market."),
 dict(q="If the supply of a currency increases while demand is unchanged, the currency will", choices=[
   "appreciate and the quantity exchanged will rise",
   "depreciate and the quantity exchanged will rise",
   "depreciate and the quantity exchanged will fall",
   "appreciate and the quantity exchanged will fall",
   "remain at the same price"], ans=1,
   why="A rightward supply shift lowers price and raises quantity."),
 dict(q="If demand for dollars decreases and supply of dollars increases at the same time, the dollar will", choices=[
   "appreciate, with an indeterminate change in quantity",
   "depreciate, with an indeterminate change in quantity",
   "depreciate, with quantity certainly falling",
   "appreciate, with quantity certainly rising",
   "be unchanged in value"], ans=1,
   why="Both shifts push the price down, but they push quantity in opposite directions."),
 dict(q="If demand for dollars increases and supply of dollars also increases, the effect on the exchange rate is", choices=[
   "certainly an appreciation",
   "indeterminate without knowing which shift is larger",
   "certainly a depreciation",
   "certainly zero",
   "an increase in the dollar's value only if quantity falls"], ans=1,
   why="The two shifts push the price in opposite directions, so the net effect depends on relative magnitudes."),
 dict(q="Every transaction in the foreign exchange market involves", choices=[
   "only one currency",
   "the demand for one currency and the simultaneous supply of another",
   "a central bank as one of the two parties",
   "a government-set price",
   "an equal change in both countries' money supplies"], ans=1,
   why="Buying euros with dollars is the same trade as supplying dollars for euros."),
 dict(q="If the dollar appreciates against the euro, then in the market for euros the euro has", choices=[
   "also appreciated",
   "depreciated",
   "kept the same value",
   "been revalued upward",
   "left equilibrium permanently"], ans=1,
   why="The two markets are mirror images of one another."),
 dict(q="An expectation that the dollar will appreciate in the future will, today,", choices=[
   "decrease demand for dollars and depreciate the dollar",
   "increase demand for dollars and appreciate the dollar now",
   "increase supply of dollars and depreciate the dollar",
   "have no effect until the future arrives",
   "shift both curves right by identical amounts"], ans=1,
   why="Speculators buy the currency now to profit from the expected rise, which raises its price immediately."),
 dict(q="A rise in U.S. real interest rates relative to those abroad will, in the market for dollars,", choices=[
   "increase supply and depreciate the dollar",
   "increase demand and appreciate the dollar",
   "decrease demand and depreciate the dollar",
   "decrease supply and depreciate the dollar",
   "have no effect on the dollar"], ans=1,
   why="Higher U.S. returns attract foreign financial capital, and foreigners must buy dollars to invest."),
 dict(q="A rise in European real interest rates while U.S. rates are flat will, in the market for dollars,", choices=[
   "increase demand for dollars and appreciate the dollar",
   "increase the supply of dollars and depreciate the dollar",
   "decrease supply of dollars and appreciate the dollar",
   "leave the dollar unchanged",
   "increase both curves equally"], ans=1,
   why="Americans send financial capital to Europe, supplying dollars to obtain euros."),
 dict(q="If U.S. inflation is expected to be much higher than Japan's, the market for dollars will most likely see", choices=[
   "demand rise and the dollar appreciate",
   "demand fall and supply rise, depreciating the dollar",
   "supply fall and the dollar appreciate",
   "no change, since inflation is a domestic matter",
   "the dollar's price rise and quantity fall"], ans=1,
   why="Expected loss of purchasing power makes people want fewer dollars and want to unload the ones they hold."),
 dict(q="A U.S. tariff that sharply reduces imports would, in the market for dollars,", choices=[
   "increase the supply of dollars and depreciate the dollar",
   "decrease the supply of dollars and appreciate the dollar",
   "increase demand for dollars and depreciate the dollar",
   "decrease demand for dollars and appreciate the dollar",
   "leave the dollar unchanged"], ans=1,
   why="Fewer imports means Americans need less foreign currency, so fewer dollars are supplied."),
 dict(q="A foreign country's decision to stop buying U.S. agricultural products would, in the market for dollars,", choices=[
   "shift demand for dollars left and depreciate the dollar",
   "shift demand for dollars right and appreciate the dollar",
   "shift supply of dollars left and appreciate the dollar",
   "shift supply of dollars right and depreciate the dollar",
   "have no effect on the exchange rate"], ans=0,
   why="Fewer U.S. exports means foreigners need fewer dollars."),
 dict(q="Which of the following shifts the demand curve for dollars rather than causing a movement along it?", choices=[
   "a change in the euro price of a dollar",
   "an increase in European tastes for American films",
   "a change in the quantity of dollars exchanged",
   "a movement to a new point on the existing curve",
   "the market reaching equilibrium"], ans=1,
   why="A change in foreign tastes for U.S. products shifts the whole curve; a price change moves along it."),
 dict(q="A change in the exchange rate itself causes", choices=[
   "a shift in both curves",
   "a movement along the demand and supply curves for the currency",
   "a shift in demand only",
   "a shift in supply only",
   "no change in quantities at all"], ans=1,
   why="Price is on the axis, so a price change is a movement along, not a shift."),
 dict(q="Central bank intervention to weaken its own currency involves", choices=[
   "buying its own currency with foreign reserves",
   "selling its own currency and buying foreign currency",
   "raising the domestic interest rate",
   "reducing the money supply",
   "imposing a tariff on imports"], ans=1,
   why="Selling its own currency increases that currency's supply and lowers its price."),
 dict(q="Central bank intervention to strengthen its own currency involves", choices=[
   "selling its own currency for foreign currency",
   "buying its own currency using foreign reserves",
   "cutting the policy interest rate",
   "printing more of its currency",
   "subsidizing imports"], ans=1,
   why="Buying its own currency raises demand for it and pushes its price up."),
 dict(q="Speculators who believe the Brazilian real will fall in value will", choices=[
   "increase demand for reais",
   "increase the supply of reais on the market, pushing the real down further",
   "decrease the supply of reais",
   "have no influence because they trade no goods",
   "cause the real to appreciate"], ans=1,
   why="Selling the currency they expect to fall adds to its supply, which is self-fulfilling in the short run."),
 dict(q="In the market for the Japanese yen, an increase in Japanese purchases of American semiconductors will", choices=[
   "increase demand for yen and appreciate the yen",
   "increase supply of yen and depreciate the yen",
   "decrease supply of yen and appreciate the yen",
   "decrease demand for yen and appreciate the yen",
   "leave the yen unchanged"], ans=1,
   why="Japanese buyers must offer yen to obtain the dollars they need, raising yen supply."),
 dict(q="In the market for the British pound, a large increase in foreign tourism to London will", choices=[
   "increase demand for pounds and appreciate the pound",
   "increase supply of pounds and depreciate the pound",
   "decrease demand for pounds and depreciate the pound",
   "decrease supply of pounds and appreciate the pound",
   "leave the pound unaffected"], ans=0,
   why="Tourists must buy pounds to spend in Britain."),
 dict(q="Which of the following increases the demand for a country's currency?", choices=[
   "domestic residents buying more foreign assets",
   "foreign residents buying more of the country's exports",
   "a fall in foreign incomes",
   "a rise in the country's expected inflation",
   "a fall in the country's interest rate relative to abroad"], ans=1,
   why="Foreign buyers of the country's exports must obtain its currency first."),
 dict(q="Which of the following increases the supply of a country's currency in the foreign exchange market?", choices=[
   "an increase in the country's exports",
   "an increase in the country's residents' purchases of foreign goods and assets",
   "a rise in foreign demand for the country's bonds",
   "a rise in the country's real interest rate",
   "an expectation the currency will appreciate"], ans=1,
   why="Residents offer their own currency to acquire the foreign currency they need."),
 dict(q="Under a floating regime, if a currency is above its equilibrium value there will be", choices=[
   "a shortage of the currency and upward pressure on its price",
   "a surplus of the currency and downward pressure on its price",
   "no market pressure at all",
   "central bank purchases by law",
   "a permanent trade surplus"], ans=1,
   why="Above equilibrium the quantity supplied exceeds the quantity demanded, which pushes the price down."),
 dict(q="A country pegs its currency above the market equilibrium value. To defend the peg its central bank must", choices=[
   "sell its own currency and accumulate reserves",
   "buy its own currency using foreign exchange reserves, which it can run out of",
   "let the currency float immediately",
   "raise tariffs on all imports",
   "cut interest rates to zero"], ans=1,
   why="An overvalued peg creates a surplus of the currency, which the central bank must absorb by buying it."),
 dict(q="A country pegs its currency below the market equilibrium value. Over time its central bank will",
   choices=[
   "lose foreign reserves rapidly",
   "accumulate foreign exchange reserves as it sells its own currency",
   "be unable to intervene at all",
   "have to raise interest rates sharply",
   "face a currency shortage it cannot address"], ans=1,
   why="An undervalued peg means excess demand for the currency, which the central bank meets by selling its own currency for foreign assets."),
 dict(q="The main reason exchange rates are called market-determined under a floating regime is that", choices=[
   "central banks are forbidden from acting",
   "the rate settles where private demand for and supply of the currency are equal",
   "governments negotiate them annually",
   "they are fixed to gold",
   "they always equal purchasing power parity"], ans=1,
   why="A floating rate is simply the market-clearing price of the currency."),
 dict(q="Foreign direct investment into a country raises the demand for that country's currency because investors", choices=[
   "want to sell their holdings of it",
   "must acquire the local currency to pay for the plants and firms they buy",
   "are required to hold reserves at the local central bank",
   "expect its currency to fall",
   "are avoiding local taxes"], ans=1,
   why="Payment for local real assets must be made in the local currency."),
 dict(q="Which event would cause both a rightward shift of the demand for dollars and a leftward shift of the supply of dollars?", choices=[
   "a fall in U.S. interest rates",
   "a rise in U.S. interest rates that both attracts foreign capital and keeps American capital at home",
   "a rise in American incomes",
   "an increase in U.S. imports",
   "an expected depreciation of the dollar"], ans=1,
   why="Higher U.S. returns draw foreigners in and give Americans less reason to send funds abroad."),
 dict(q="A student says an increase in U.S. exports 'increases the supply of dollars.' The correct statement is that it", choices=[
   "increases the supply of dollars, because dollars flow in",
   "increases the demand for dollars, because foreign buyers must purchase dollars",
   "decreases the demand for dollars",
   "leaves the market for dollars unchanged",
   "increases both curves equally"], ans=1,
   why="Exports are paid for in dollars that foreigners must first buy, which is demand, not supply."),
 dict(q="After the dollar appreciates because of a demand increase, the quantity of dollars exchanged in the market", choices=[
   "falls", "rises", "is unchanged", "becomes zero", "cannot be determined"], ans=1,
   why="A rightward demand shift along an upward-sloping supply curve raises equilibrium quantity."),
 dict(q="Two events occur at once: foreigners buy more U.S. bonds and Americans buy more foreign cars. The effect on the dollar's value is", choices=[
   "certainly an appreciation",
   "indeterminate, because demand for dollars rises while supply of dollars also rises",
   "certainly a depreciation",
   "zero by definition",
   "an appreciation only if quantity falls"], ans=1,
   why="One event raises demand and the other raises supply, so the net price effect depends on relative sizes."),
 dict(q="Which of the following would NOT shift the demand curve for dollars?", choices=[
   "a change in foreign incomes",
   "a change in the euro price of the dollar",
   "a change in foreign tastes for U.S. goods",
   "a change in U.S. interest rates relative to abroad",
   "a change in expectations about the dollar's future value"], ans=1,
   why="The exchange rate is the price on the axis, so changing it moves along the curve instead of shifting it."),
]
