# 1.1 Basic Economic Concepts: Scarcity — 50 questions
# Each: q, choices (5, A-E), ans (0-4), why (one line, for the answer key)
TOPIC = ("1.1", "Scarcity", 1)
QUESTIONS = [
 dict(q="Scarcity exists because", choices=[
   "governments print too little money",
   "human wants are unlimited while resources are limited",
   "some countries produce more than others",
   "prices are set too high for most consumers",
   "firms deliberately restrict output to raise profits"], ans=1,
   why="Scarcity is the mismatch between unlimited wants and limited resources."),
 dict(q="Which of the following best defines economics as a field of study?", choices=[
   "The study of how to make the most money in financial markets",
   "The study of how governments should regulate businesses",
   "The study of how societies allocate limited resources to satisfy unlimited wants",
   "The study of how firms maximize their production capacity",
   "The study of stock prices and interest rates"], ans=2,
   why="Economics studies the allocation of scarce resources among unlimited wants."),
 dict(q="Scarcity is faced by", choices=[
   "only developing countries",
   "only households with low incomes",
   "only economies without central planning",
   "every society, regardless of its wealth or economic system",
   "only economies that rely on markets"], ans=3,
   why="Scarcity is universal and inevitable — no society has infinite resources."),
 dict(q="The opportunity cost of a decision is best defined as", choices=[
   "the total money spent on the decision",
   "the value of the next best alternative forgone",
   "the value of all alternatives given up",
   "the difference between total benefit and total cost",
   "the time spent making the decision"], ans=1,
   why="Opportunity cost is the value of the single next best alternative given up."),
 dict(q="Maria has one free evening and can either study, watch a film, or work a shift paying $40. She most prefers studying, and would choose the film over the shift. If she studies, her opportunity cost is", choices=[
   "the film and the $40 shift together",
   "the $40 shift",
   "the film",
   "zero, because studying is what she prefers",
   "the value of studying itself"], ans=2,
   why="Only the next best alternative — the film — counts, not all forgone options."),
 dict(q="Which of the following is NOT one of the four factors of production?", choices=[
   "Land", "Labor", "Money", "Capital", "Entrepreneurship"], ans=2,
   why="Money is not a productive resource itself; it buys the real factors."),
 dict(q="A fishing boat used by a commercial fishing company is an example of which factor of production?", choices=[
   "Land", "Labor", "Physical capital", "Human capital", "Entrepreneurship"], ans=2,
   why="A produced tool used to make other goods is physical capital."),
 dict(q="The knowledge and skills a surgeon gains through years of training are an example of", choices=[
   "land", "entrepreneurship", "physical capital", "human capital", "a natural resource"], ans=3,
   why="Human capital is the acquired skill and knowledge embodied in workers."),
 dict(q="Crude oil deposits beneath the ocean floor are classified as", choices=[
   "capital", "land", "labor", "entrepreneurship", "technology"], ans=1,
   why="Natural resources and raw materials fall under the factor 'land.'"),
 dict(q="An individual who combines land, labor, and capital to launch a new product, bearing the risk of failure, is providing", choices=[
   "human capital", "physical capital", "entrepreneurship", "labor", "land"], ans=2,
   why="Coordinating the other factors and bearing risk is entrepreneurship."),
 dict(q="Which of the following is the fundamental economic question that arises from scarcity?", choices=[
   "How can inflation be kept low?",
   "How should scarce resources be allocated to maximize benefit?",
   "How can firms eliminate their competition?",
   "How can every want of every person be satisfied?",
   "How should money be distributed equally?"], ans=1,
   why="Scarcity forces the question of how to allocate limited resources for maximum benefit."),
 dict(q="Microeconomics differs from macroeconomics in that microeconomics", choices=[
   "studies the overall level of economic activity",
   "focuses on the behavior of individual agents such as households and firms",
   "is concerned mainly with inflation and unemployment",
   "studies only government policy",
   "examines the economy of small countries"], ans=1,
   why="Micro studies individual decision-makers; macro studies the economy as a whole."),
 dict(q="Which of the following questions would a MACROeconomist most likely study?", choices=[
   "How a rise in the price of coffee affects a cafe's sales",
   "How a firm chooses between producing T-shirts and sweaters",
   "How an increase in the money supply affects the national inflation rate",
   "How a household allocates its weekly grocery budget",
   "How two competing firms set their prices"], ans=2,
   why="The money supply and inflation concern the economy as a whole."),
 dict(q="Which of the following questions would a MICROeconomist most likely study?", choices=[
   "The causes of a nationwide recession",
   "The effect of fiscal policy on national income",
   "The national unemployment rate over a decade",
   "How the price of a product affects the quantity consumers are willing to buy",
   "The growth rate of an economy's total output"], ans=3,
   why="Individual product prices and consumer responses are microeconomic questions."),
 dict(q="A trade-off is best described as", choices=[
   "a situation in which nothing must be given up",
   "the alternatives sacrificed when a choice is made",
   "an exchange of goods between two countries",
   "the money cost of a purchase",
   "a government tax on consumption"], ans=1,
   why="Trade-offs are the alternative choices given up when deciding."),
 dict(q="Because resources are scarce, every choice made by an individual or society necessarily involves", choices=[
   "monetary payment", "government approval", "an opportunity cost", "a market transaction", "a loss of efficiency"], ans=2,
   why="Choosing one use of scarce resources always sacrifices the next best use."),
 dict(q="A student spends an hour playing video games instead of studying or sleeping, and considers studying the better of the two alternatives given up. The opportunity cost of gaming is", choices=[
   "the hour of sleep",
   "the enjoyment of the video games",
   "the hour of studying",
   "both the studying and the sleep",
   "nothing, because no money was spent"], ans=2,
   why="Time is scarce; the next best forgone use — studying — is the opportunity cost."),
 dict(q="Which statement about opportunity cost is correct?", choices=[
   "It applies only to decisions involving money",
   "It applies only to firms, not individuals",
   "It can include non-monetary sacrifices such as time",
   "It equals the sum of all forgone alternatives",
   "It is zero whenever a good is provided free of charge"], ans=2,
   why="Opportunity costs need not be material — forgone time counts."),
 dict(q="Economics and business are distinct subjects primarily because economics", choices=[
   "ignores the behavior of firms entirely",
   "is a social science focused on how choices are made under scarcity",
   "deals only with government activity",
   "studies profit maximization exclusively",
   "does not use quantitative methods"], ans=1,
   why="Economics is the social science of allocation under scarcity, not just business practice."),
 dict(q="A clothing manufacturer deciding how much of its fabric and labor to devote to T-shirts versus sweaters is an example of", choices=[
   "scarcity forcing choices at the firm level",
   "a macroeconomic policy decision",
   "the elimination of opportunity cost",
   "a decision without trade-offs",
   "consumption rather than production"], ans=0,
   why="Firms, like individuals, must allocate limited resources among competing uses."),
 dict(q="Full employment, as economists use the term, describes a situation in which", choices=[
   "every citizen holds a job",
   "all available resources are being used efficiently to produce maximum output",
   "the government employs most workers",
   "wages are at their highest possible level",
   "no worker ever changes jobs"], ans=1,
   why="Full employment means all available resources are used efficiently."),
 dict(q="Which of the following is an example of physical capital?", choices=[
   "A barista's espresso-making skills",
   "The espresso machine in a coffee shop",
   "The coffee beans grown on a farm",
   "The manager's decision to open a second location",
   "The shop's monthly revenue"], ans=1,
   why="Machines and tools used in production are physical capital; beans are land, skills are human capital."),
 dict(q="Untrained workers stocking shelves at a warehouse are supplying which factor of production?", choices=[
   "Entrepreneurship", "Land", "Capital", "Labor", "Technology"], ans=3,
   why="Effort and time devoted to production for pay is labor."),
 dict(q="Which of the following best illustrates scarcity at the level of an entire society?", choices=[
   "A consumer choosing between two brands of cereal",
   "A nation deciding whether limited land should be conserved or opened for development",
   "A firm advertising a new product",
   "A bank raising its interest rate",
   "A worker asking for a raise"], ans=1,
   why="Societies must choose among alternative uses of limited resources like land."),
 dict(q="If resources were unlimited, which of the following would be TRUE?", choices=[
   "Opportunity costs would rise",
   "Choices would still be necessary for all goods",
   "The basic economic problem of scarcity would disappear",
   "Prices would rise without limit",
   "Trade-offs would become more severe"], ans=2,
   why="Scarcity — and the need to choose — exists only because resources are limited."),
 dict(q="The opportunity cost of attending a two-year college includes", choices=[
   "only tuition and fees",
   "only the income the student gives up by not working",
   "both tuition paid and the forgone income from working",
   "food and clothing expenses the student would incur anyway",
   "nothing, if the student receives a scholarship"], ans=2,
   why="Opportunity cost combines explicit outlays with the forgone next best alternative."),
 dict(q="All of the following are included in the opportunity cost of attending college EXCEPT", choices=[
   "wages given up to attend classes",
   "money spent on tuition",
   "money spent on required textbooks",
   "interest paid on student loans",
   "money spent on clothing the student would buy regardless"], ans=4,
   why="Expenses incurred in every alternative, like everyday clothing, are not part of opportunity cost."),
 dict(q="Ravi earns $15 per hour. He takes 3 unpaid hours off work to attend a concert with a $30 ticket. His opportunity cost of attending is", choices=[
   "$30", "$45", "$60", "$75", "$105"], ans=3,
   why="Forgone wages 3 × $15 = $45 (implicit) plus the $30 ticket (explicit) = $75."),
 dict(q="Which of the following statements about wants and resources underlies the definition of scarcity?", choices=[
   "Wants are limited; resources are unlimited",
   "Wants are unlimited; resources are limited",
   "Both wants and resources are unlimited",
   "Both wants and resources are limited equally",
   "Wants and resources always grow at the same rate"], ans=1,
   why="Infinite wants meeting finite resources is the definition of scarcity."),
 dict(q="A society choosing to build more roads must repair fewer schools. This illustrates", choices=[
   "a free good",
   "the invisible hand",
   "a trade-off imposed by scarcity",
   "macroeconomic instability",
   "market failure"], ans=2,
   why="Using scarce resources for one public project sacrifices another."),
 dict(q="Which of the following would an economist classify as land?", choices=[
   "A tractor", "A farmer's knowledge of crop rotation", "A river used to irrigate crops", "A loan used to buy seed", "A farm manager's planning"], ans=2,
   why="Naturally occurring resources such as water are land."),
 dict(q="Which pair correctly matches a resource with its factor category?", choices=[
   "Iron ore — capital",
   "A delivery van — land",
   "A software engineer's coding ability — human capital",
   "A founder's risk-taking — labor",
   "A factory building — entrepreneurship"], ans=2,
   why="Acquired skills are human capital; ore is land, the van and factory are capital, risk-taking is entrepreneurship."),
 dict(q="The main reason individuals cannot have everything they want is that", choices=[
   "governments restrict consumption",
   "prices are always rising",
   "productive resources are limited",
   "people do not work hard enough",
   "firms produce the wrong goods"], ans=2,
   why="Limited resources, not policy or effort, create scarcity."),
 dict(q="When economists say a rational decision-maker weighs costs and benefits, the relevant cost is", choices=[
   "the sunk cost already paid",
   "the average cost of all options",
   "the opportunity cost of the choice",
   "only costs paid in cash",
   "the cost of the least attractive alternative"], ans=2,
   why="Rational choice compares benefits against the value of the next best alternative."),
 dict(q="A farmer can hire many workers or buy a new tractor, but not both. This constraint most directly reflects", choices=[
   "diminishing returns",
   "the scarcity of the farmer's resources",
   "government regulation",
   "a lack of technology",
   "market inefficiency"], ans=1,
   why="Limited funds force a choice between competing uses — scarcity in action."),
 dict(q="Which of the following is a capital resource for an airline?", choices=[
   "The pilots' flying experience",
   "Its fleet of aircraft",
   "The air routes over the ocean",
   "The CEO's decision to enter new markets",
   "Ticket revenue"], ans=1,
   why="Aircraft are produced goods used to provide services — physical capital."),
 dict(q="Time is considered a scarce resource because", choices=[
   "it can be stored for later use",
   "everyone has the same amount each day and cannot obtain more",
   "it has no opportunity cost",
   "it is not valued by consumers",
   "only workers experience limits on it"], ans=1,
   why="Time is fixed for everyone, so using it one way sacrifices another use."),
 dict(q="Choosing to read this study guide instead of playing video games means the video games are", choices=[
   "an explicit cost",
   "a sunk cost",
   "the opportunity cost of studying",
   "a fixed cost",
   "a free good"], ans=2,
   why="The forgone fun of the next best use of time is the opportunity cost."),
 dict(q="Which of the following decisions is a firm-level response to scarcity?", choices=[
   "Setting the national minimum wage",
   "Choosing how to allocate limited machinery between two product lines",
   "Regulating imports of foreign steel",
   "Printing additional currency",
   "Setting the central bank's interest rate"], ans=1,
   why="Firms allocate their own scarce resources among production alternatives."),
 dict(q="Which of the following is TRUE of every economic system, whether market, command, or traditional?", choices=[
   "It eliminates scarcity through planning",
   "It faces scarcity and must make allocation choices",
   "It relies on prices to allocate goods",
   "It guarantees full employment",
   "It produces every good its citizens want"], ans=1,
   why="Scarcity is unavoidable in all systems; only the coordination method differs."),
 dict(q="An economy produces at maximum efficiency when", choices=[
   "some resources are held in reserve",
   "all available resources are used efficiently to produce maximum output",
   "only capital goods are produced",
   "every industry is government-owned",
   "consumption exceeds production"], ans=1,
   why="Full, efficient use of all available resources yields maximum output."),
 dict(q="A student says, 'The concert ticket was free, so attending costs me nothing.' An economist would object because", choices=[
   "free tickets are illegal",
   "the student's time at the concert has an opportunity cost",
   "the ticket must have a hidden monetary price",
   "concerts are not economic goods",
   "opportunity cost applies only to firms"], ans=1,
   why="The forgone alternative use of the evening is still a cost."),
 dict(q="Which of the following lists contains ONLY factors of production?", choices=[
   "Wages, rent, interest",
   "Land, labor, capital, entrepreneurship",
   "Money, stocks, bonds",
   "Prices, profits, taxes",
   "Goods, services, wants"], ans=1,
   why="The four factors are land, labor, capital, and entrepreneurship; wages and rent are payments to them."),
 dict(q="Bill Gates coordinating programmers, computers, and office space to found a software company is a classic example of", choices=[
   "labor", "land", "human capital only", "entrepreneurship", "physical capital"], ans=3,
   why="Combining the other factors to create a product, at personal risk, is entrepreneurship."),
 dict(q="The phrase 'there is no such thing as a free lunch' expresses the idea that", choices=[
   "restaurants never give away food",
   "every choice involves an opportunity cost",
   "prices always exceed costs",
   "only money measures value",
   "government programs are always wasteful"], ans=1,
   why="Someone's scarce resources are always sacrificed, even when no price is charged."),
 dict(q="Which of the following changes would directly reduce the scarcity of productive resources available to an economy?", choices=[
   "A decrease in consumer wants",
   "A discovery of new mineral deposits",
   "A rise in the price level",
   "A shift from market to command organization",
   "An increase in the money supply"], ans=1,
   why="New resources expand what can be produced; more money or fewer wants do not add resources."),
 dict(q="A hospital must decide whether its one available operating room will be used for scheduled surgeries or kept open for emergencies. This decision problem exists because", choices=[
   "hospital administrators dislike planning",
   "the operating room is a scarce resource with competing uses",
   "surgeries have no opportunity cost",
   "emergencies are unpredictable only in poor countries",
   "medical care is not an economic good"], ans=1,
   why="A single scarce facility with rival uses forces an allocation choice."),
 dict(q="In economics, the term 'capital' refers to", choices=[
   "money held in bank accounts",
   "shares of corporate stock",
   "produced goods, such as tools and machines, used to make other goods and services",
   "natural resources found in the ground",
   "government bonds"], ans=2,
   why="Economic capital means physical (and human) productive assets, not financial holdings."),
 dict(q="Which situation best illustrates the concept of increasing wants outpacing resources?", choices=[
   "As incomes rise, households desire newer phones, bigger homes, and more travel than the economy can produce at once",
   "A factory shuts down for repairs",
   "A government balances its budget",
   "A store runs a temporary sale",
   "A worker retires at age 65"], ans=0,
   why="Wants expand without limit while productive capacity remains finite."),
 dict(q="Scarcity differs from a temporary shortage in that scarcity", choices=[
   "can be eliminated by raising prices",
   "is a permanent condition faced by all societies",
   "occurs only when governments set price ceilings",
   "affects only luxury goods",
   "disappears during economic booms"], ans=1,
   why="Shortages can be resolved by price changes; scarcity is the permanent limit of resources."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
