# 1.2 Resource Allocation and Economic Systems — 50 questions
TOPIC = ("1.2", "Resource Allocation and Economic Systems", 1)
QUESTIONS = [
 dict(q="The three fundamental questions every economy must answer are", choices=[
   "when, where, and why to produce",
   "what to produce, how to produce it, and for whom to produce it",
   "how to tax, how to spend, and how to borrow",
   "what to import, what to export, and what to ban",
   "who works, who saves, and who invests"], ans=1,
   why="Every economic system must answer what, how, and for whom to produce."),
 dict(q="An economic system is best defined as", choices=[
   "the set of banks operating within a country",
   "a set of institutional arrangements and coordinating mechanisms a society uses to allocate scarce resources",
   "the government agencies that collect taxes",
   "the technology available to firms",
   "the stock exchanges of a nation"], ans=1,
   why="An economic system is the framework of rules and mechanisms for allocation."),
 dict(q="The question 'For whom will goods and services be produced?' is answered", choices=[
   "before any production occurs",
   "by determining who is allowed to consume what has been produced",
   "only in command economies",
   "by engineers choosing production methods",
   "only when goods are exported"], ans=1,
   why="'For whom' concerns how output is distributed among consumers."),
 dict(q="Deciding whether pipes should be made of copper or plastic answers which fundamental economic question?", choices=[
   "What to produce", "How to produce", "For whom to produce", "When to produce", "Where to produce"], ans=1,
   why="Choice of production method answers 'how' goods are produced."),
 dict(q="In a traditional economic system, production and distribution decisions are guided primarily by", choices=[
   "supply and demand",
   "central government planners",
   "custom and long-standing cultural practice",
   "corporate boards",
   "international treaties"], ans=2,
   why="Traditional economies rely on custom and inherited practice."),
 dict(q="Which of the following is most characteristic of a traditional economy?", choices=[
   "Sophisticated financial markets",
   "Central planning committees",
   "Simple production methods and roles passed down through generations",
   "Frequent technological disruption",
   "Extensive foreign investment"], ans=2,
   why="Traditional economies use simple methods with roles set by custom."),
 dict(q="In a command economy, the primary decision-maker regarding what and how much to produce is", choices=[
   "the individual consumer",
   "the central government or planning authority",
   "the largest private firm",
   "the price mechanism",
   "foreign investors"], ans=1,
   why="A central authority makes production decisions in a command system."),
 dict(q="A command economy is also commonly called a", choices=[
   "laissez-faire economy",
   "planned economy",
   "barter economy",
   "market economy",
   "subsistence economy"], ans=1,
   why="Command systems are known as planned (or socialist) economies."),
 dict(q="Which of the following is an advantage often claimed for command economies?", choices=[
   "Prices adjust quickly to consumer preferences",
   "Resources can be directed toward social goals such as public health",
   "Innovation is strongly rewarded",
   "Consumers fully express preferences through markets",
   "Information problems are eliminated"], ans=1,
   why="Central control can steer resources toward chosen social goals."),
 dict(q="A common weakness of command economies is that", choices=[
   "income inequality is always extreme",
   "planners may lack the information and incentives that markets provide",
   "prices change too frequently",
   "firms compete too aggressively",
   "consumers have too much influence over production"], ans=1,
   why="Central planners lack the information and incentives of private actors."),
 dict(q="In a market economy, the production, distribution, and consumption of goods are guided primarily by", choices=[
   "tradition",
   "the laws of supply and demand operating through prices",
   "five-year government plans",
   "religious institutions",
   "labor unions"], ans=1,
   why="Market systems coordinate through prices set by supply and demand."),
 dict(q="The term 'invisible hand,' associated with Adam Smith, refers to", choices=[
   "hidden government intervention in markets",
   "the self-interested actions of buyers and sellers unintentionally coordinating an efficient allocation of resources",
   "secret agreements among large firms",
   "central bank operations",
   "charity that goes unnoticed"], ans=1,
   why="Smith's invisible hand: self-interest in markets yields coordination without a planner."),
 dict(q="In a pure market economy, prices act as", choices=[
   "arbitrary numbers set by law",
   "signals of overproduction and underproduction that guide resource allocation",
   "instruments of central planning",
   "guarantees of fairness",
   "fixed values that never change"], ans=1,
   why="Price movements signal surpluses and shortages, redirecting resources."),
 dict(q="One frequently cited disadvantage of a market economy is", choices=[
   "slow response to consumer preferences",
   "absence of innovation",
   "the possibility of significant income inequality",
   "excessive central planning",
   "guaranteed unemployment"], ans=2,
   why="Market rewards can concentrate income among resource owners."),
 dict(q="Without any regulation, a market economy may experience all of the following EXCEPT", choices=[
   "market failure",
   "negative externalities such as pollution",
   "exploitation",
   "instability in prices and demand",
   "the elimination of scarcity"], ans=4,
   why="Markets cannot abolish scarcity; the other problems can arise without regulation."),
 dict(q="A mixed economy combines", choices=[
   "traditional and barter systems only",
   "elements of market decision-making with government involvement",
   "two different national currencies",
   "agriculture and industry",
   "imports and exports"], ans=1,
   why="Mixed systems blend private markets with government participation."),
 dict(q="The United States is best classified as a", choices=[
   "pure market economy",
   "pure command economy",
   "traditional economy",
   "mixed economy",
   "barter economy"], ans=3,
   why="The U.S. combines private markets with regulation and public programs."),
 dict(q="In a mixed economy, the government may do all of the following EXCEPT", choices=[
   "regulate industries to protect consumers",
   "provide public goods such as infrastructure",
   "redistribute income through progressive taxation",
   "prohibit all private ownership of businesses",
   "provide services such as public education"], ans=3,
   why="Banning all private enterprise describes a command, not mixed, system."),
 dict(q="Efficiency, as a criterion for evaluating economic systems, refers to", choices=[
   "the fairness of the income distribution",
   "producing the greatest possible output from given resources",
   "the stability of prices over time",
   "the speed of government decision-making",
   "equal pay for all workers"], ans=1,
   why="Efficiency means maximum output with minimum wasted resources."),
 dict(q="Equity, as a criterion for evaluating economic systems, refers to", choices=[
   "producing at lowest cost",
   "the fairness of how resources and opportunities are distributed",
   "the total value of the stock market",
   "how quickly an economy grows",
   "the balance of trade"], ans=1,
   why="Equity concerns fairness in distribution."),
 dict(q="Stability, as a criterion for evaluating economic systems, refers to an economy's ability to", choices=[
   "keep the same leaders in power",
   "withstand external shocks and maintain a steady state",
   "avoid all technological change",
   "prevent any firm from failing",
   "hold prices constant forever"], ans=1,
   why="Stability is resilience to shocks and steadiness of performance."),
 dict(q="A government that chooses to forgo some economic surplus in exchange for greater social control is describing a trade-off typical of", choices=[
   "market economies",
   "command economies",
   "traditional economies",
   "barter systems",
   "free trade zones"], ans=1,
   why="Command systems trade market efficiency for centralized control."),
 dict(q="In which system are the answers to all three economic questions left most fully to individual buyers and sellers?", choices=[
   "Command economy",
   "Traditional economy",
   "Pure market economy",
   "Mixed economy",
   "Feudal economy"], ans=2,
   why="A pure market economy leaves what, how, and for whom to the market."),
 dict(q="In a market economy, firms are motivated to produce goods that consumers want because", choices=[
   "the government orders them to do so",
   "tradition requires it",
   "producing what consumers will buy is how firms earn profit",
   "they are penalized for innovation",
   "prices are fixed by regulators"], ans=2,
   why="The profit motive aligns production with consumer demand."),
 dict(q="Which economic system tends to be found in societies with long histories and relatively little contact with the outside world?", choices=[
   "Market", "Mixed", "Command", "Traditional", "Corporate"], ans=3,
   why="Isolated, custom-bound societies typify traditional economies."),
 dict(q="In command economies, the central authority typically does all of the following EXCEPT", choices=[
   "set production targets",
   "control prices and wages",
   "provide certain goods free or at subsidized prices",
   "allow supply and demand to determine most prices",
   "decide how resources are allocated"], ans=3,
   why="Letting supply and demand set prices is a market feature, not command."),
 dict(q="The 'coordinating mechanism' of an economic system refers to", choices=[
   "its transportation network",
   "the method by which decisions about resource allocation, production, and distribution are made",
   "its telephone and internet infrastructure",
   "the central bank's payment system",
   "the way firms schedule work shifts"], ans=1,
   why="The coordinating mechanism is how allocation decisions get made (prices, plans, or custom)."),
 dict(q="Deciding whether scarce hospital beds go to those who pay the most or to those who arrive first is an example of answering the question", choices=[
   "what to produce",
   "how to produce",
   "for whom to produce",
   "when to produce",
   "why to produce"], ans=2,
   why="Allocating output among people is the 'for whom' question."),
 dict(q="In a market economy, consumers influence what gets produced primarily through", choices=[
   "voting in elections",
   "their purchases, which signal preferences to producers",
   "petitions to planning boards",
   "labor strikes",
   "letters to newspapers"], ans=1,
   why="'Dollar votes' — consumer spending — direct production in markets."),
 dict(q="Which of the following best describes how a traditional economy distributes goods?", choices=[
   "By auction to the highest bidder",
   "According to central plan quotas",
   "Based on social and familial relationships and custom",
   "Through stock markets",
   "Randomly by lottery"], ans=2,
   why="Distribution follows custom and social ties in traditional systems."),
 dict(q="A key advantage of a market economy is that it", choices=[
   "guarantees perfectly equal incomes",
   "allocates resources according to consumer preferences and rewards innovation",
   "eliminates unemployment",
   "removes the need for money",
   "prevents all business failures"], ans=1,
   why="Markets align production with preferences and reward new ideas."),
 dict(q="Compared with a market economy, a command economy is MORE likely to", choices=[
   "respond quickly to changes in consumer tastes",
   "suffer from inefficiency because planners lack market information",
   "generate rapid product innovation",
   "let prices allocate goods",
   "experience competitive advertising"], ans=1,
   why="Without price signals, planners misallocate more easily."),
 dict(q="Government provision of public education, healthcare subsidies, and infrastructure within an otherwise private economy illustrates", choices=[
   "a pure market system",
   "a traditional system",
   "the public role in a mixed economy",
   "a barter system",
   "central planning of all production"], ans=2,
   why="Public goods and services alongside private markets define a mixed economy."),
 dict(q="Progressive taxation and social welfare programs in a mixed economy are primarily intended to", choices=[
   "increase economic efficiency",
   "reduce income inequality",
   "raise the rate of inflation",
   "eliminate private property",
   "expand exports"], ans=1,
   why="Redistribution addresses inequality generated by markets."),
 dict(q="Which of the following is a potential drawback of a mixed economy?", choices=[
   "Absence of any consumer choice",
   "Total lack of public goods",
   "Conflicts of interest and inefficiencies from government interference",
   "No mechanism for dealing with market failure",
   "Complete reliance on tradition"], ans=2,
   why="Mixing sectors can create interference, inefficiency, and conflicts of interest."),
 dict(q="'Should the government conserve wilderness areas or open them for development?' is fundamentally a question of", choices=[
   "how to produce",
   "what to produce",
   "for whom to produce",
   "monetary policy",
   "international trade"], ans=1,
   why="Choosing among alternative uses of resources is the 'what to produce' question."),
 dict(q="In a market system, a sustained rise in the price of a good generally signals producers to", choices=[
   "produce less of it",
   "produce more of it",
   "ignore the change",
   "wait for government instructions",
   "lower quality"], ans=1,
   why="Higher prices signal underproduction relative to demand, drawing in resources."),
 dict(q="Which of the following would NOT occur in a pure command economy?", choices=[
   "Government-set production targets",
   "State-controlled wages",
   "Private entrepreneurs freely starting firms to seek profit",
   "Subsidized provision of basic goods",
   "Central allocation of raw materials"], ans=2,
   why="Free private enterprise is absent under pure central planning."),
 dict(q="The question of whether one firm should serve an entire market or many smaller firms should compete concerns", choices=[
   "for whom to produce",
   "how goods are produced and industries are organized",
   "when to consume",
   "how to tax production",
   "what wages to pay"], ans=1,
   why="Industry structure is part of the 'how to produce' question."),
 dict(q="Custom dictating that farming roles pass from parent to child, with little specialization, is typical of", choices=[
   "market economies",
   "mixed economies",
   "traditional economies",
   "command economies",
   "industrial economies"], ans=2,
   why="Inherited roles and little specialization mark traditional systems."),
 dict(q="A society debating between building roads and buying textbooks for schools illustrates that", choices=[
   "public goods are free",
   "scarcity forces even governments to choose among competing uses of resources",
   "education is not an economic good",
   "roads have no opportunity cost",
   "government spending is unlimited"], ans=1,
   why="Even governments face trade-offs among alternative outputs."),
 dict(q="In which system are consumers LEAST able to express their preferences through their purchases?", choices=[
   "Pure market economy",
   "Mixed economy",
   "Pure command economy",
   "Market economy with light regulation",
   "Any economy using money"], ans=2,
   why="Central planning overrides consumer price signals."),
 dict(q="Which of the following best explains why most real-world economies are mixed?", choices=[
   "Pure systems are illegal under international law",
   "Societies want both the efficiency and innovation of markets and the ability to address social goals and market failures",
   "Tradition prevents any change",
   "Central planning is impossible with modern technology",
   "Markets cannot exist alongside taxation"], ans=1,
   why="Mixing captures market efficiency while addressing market failures and equity."),
 dict(q="When a market economy experiences pollution that harms third parties, economists call this", choices=[
   "a positive externality",
   "an example of market failure through a negative externality",
   "allocative efficiency",
   "the invisible hand at work",
   "a stabilization policy"], ans=1,
   why="Costs imposed on bystanders are negative externalities — a market failure."),
 dict(q="A perfect market economy differs from a command economy in that it has", choices=[
   "no central planning body whatsoever",
   "no private property",
   "no use of prices",
   "no self-interested behavior",
   "no consumer choice"], ans=0,
   why="Pure markets leave all answers to supply and demand, with no planner."),
 dict(q="Which observation about economic systems is most accurate?", choices=[
   "Efficiency, equity, and stability can all be maximized simultaneously with no trade-offs",
   "Systems differ in how they answer the three economic questions and involve trade-offs among efficiency, equity, and stability",
   "Only command economies face trade-offs",
   "Traditional economies are the most common systems today",
   "Mixed economies avoid all disadvantages of markets and planning"], ans=1,
   why="Systems are different answers to what/how/for whom, each with trade-offs."),
 dict(q="A government subsidizing bread so every household can afford it, within an economy that is otherwise market-driven, is an example of", choices=[
   "pure central planning",
   "government intervention typical of a mixed economy",
   "a traditional economy",
   "the invisible hand",
   "laissez-faire policy"], ans=1,
   why="Targeted intervention inside a market framework is mixed-economy behavior."),
 dict(q="Which statement about incentives in a command economy is most accurate?", choices=[
   "State-set targets may give producers weaker incentives to cut costs and innovate than profit does",
   "Profit provides the main production incentive",
   "Consumers set incentives through prices",
   "Incentives do not exist outside markets",
   "Planners always replicate market incentives exactly"], ans=0,
   why="Without profit and price signals, cost-cutting and innovation incentives weaken."),
 dict(q="If a society values rapid response to changing consumer tastes above all else, it should rely most heavily on", choices=[
   "tradition",
   "central planning",
   "market coordination through prices",
   "rationing by queue",
   "inheritance rules"], ans=2,
   why="Prices transmit changing preferences to producers fastest."),
 dict(q="Laissez-faire describes a policy stance in which the government", choices=[
   "owns all major industries",
   "intervenes minimally in markets",
   "sets all prices",
   "bans imports",
   "plans production five years ahead"], ans=1,
   why="Laissez-faire means leaving markets largely free of intervention."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
