# 1.3 Production Possibilities Curve (PPC) — 50 questions
# Optional "table": dict(headers=[...], rows=[[...], ...]) rendered above the stem.
TOPIC = ("1.3", "Production Possibilities Curve", 1)
QUESTIONS = [
 dict(q="The production possibilities curve (PPC) shows", choices=[
   "the combinations of two goods consumers wish to buy",
   "the maximum combinations of two goods an economy can produce with its available resources and technology",
   "the prices at which two goods will sell",
   "the minimum output an economy must produce",
   "how income is distributed between two groups"], ans=1,
   why="The PPC maps maximum feasible output combinations for two goods."),
 dict(q="Which of the following is one of the standard assumptions of the PPC model?", choices=[
   "Resources can grow without limit",
   "Technology improves continuously",
   "Only two goods are produced",
   "Prices are constant",
   "Trade with other economies is unrestricted"], ans=2,
   why="The PPC assumes two goods, fixed resources, and fixed technology."),
 dict(q="A point lying INSIDE an economy's PPC represents", choices=[
   "an unattainable combination",
   "productive efficiency",
   "underutilization of resources, such as unemployment",
   "allocative efficiency",
   "economic growth"], ans=2,
   why="Interior points mean some resources are idle or used inefficiently."),
 dict(q="A point lying OUTSIDE (beyond) the PPC represents", choices=[
   "efficient production",
   "an attainable but wasteful combination",
   "a combination unattainable with current resources and technology",
   "full employment",
   "underutilization"], ans=2,
   why="Points beyond the curve exceed current productive capacity."),
 dict(q="Every point ON the PPC represents", choices=[
   "allocative efficiency only",
   "productive efficiency — all resources fully and efficiently employed",
   "unattainable output",
   "unemployment of labor",
   "the single best combination for society"], ans=1,
   why="On-curve points use all resources efficiently (productive efficiency)."),
 dict(q="Allocative efficiency differs from productive efficiency in that allocative efficiency requires", choices=[
   "producing anywhere on the PPC",
   "producing inside the PPC",
   "producing the particular on-curve combination that society most desires",
   "minimizing the use of labor",
   "producing equal amounts of both goods"], ans=2,
   why="Allocative efficiency is the on-curve point matching society's preferences."),
 dict(q="If an economy is producing on its PPC, producing more of one good necessarily requires", choices=[
   "new technology",
   "producing less of the other good",
   "importing resources",
   "unemployment",
   "higher prices"], ans=1,
   why="On the curve, resources are fully used, so more of one good costs some of the other."),
 dict(q="Opportunity cost on a PPC is represented graphically by", choices=[
   "the area under the curve",
   "the slope of the curve — the amount of one good given up per unit of the other gained",
   "the distance from the origin",
   "the vertical intercept only",
   "the horizontal intercept only"], ans=1,
   why="The slope measures how much of one good must be sacrificed per unit of the other."),
 dict(q="A PPC that is bowed out (concave to the origin) reflects", choices=[
   "constant opportunity costs",
   "decreasing opportunity costs",
   "increasing opportunity costs as more of a good is produced",
   "unemployment of resources",
   "technological change"], ans=2,
   why="A bowed-out curve means opportunity cost rises as production of a good expands."),
 dict(q="A straight-line (linear) PPC reflects", choices=[
   "increasing opportunity costs",
   "constant opportunity costs — resources are equally suited to both goods",
   "decreasing opportunity costs",
   "an unattainable frontier",
   "economic contraction"], ans=1,
   why="Constant slope = constant opportunity cost; resources are perfectly adaptable."),
 dict(q="Increasing opportunity costs along a PPC occur mainly because", choices=[
   "prices rise with production",
   "resources are not equally well suited to producing both goods",
   "technology deteriorates with use",
   "consumers change their preferences",
   "the government taxes production"], ans=1,
   why="Shifting increasingly ill-suited resources into a good raises its opportunity cost."),
 dict(q="Economic growth is shown on a PPC diagram as", choices=[
   "a movement along the curve",
   "a movement from the curve to an interior point",
   "an outward (rightward) shift of the entire curve",
   "a steeper slope",
   "a movement to the origin"], ans=2,
   why="Growth expands capacity, shifting the whole frontier outward."),
 dict(q="Economic contraction is shown on a PPC diagram as", choices=[
   "an outward shift of the curve",
   "an inward (leftward) shift of the curve",
   "a movement along the curve",
   "a flatter slope only",
   "a point moving beyond the curve"], ans=1,
   why="Losing productive capacity shifts the frontier inward."),
 dict(q="Which of the following would shift an economy's entire PPC outward?", choices=[
   "A decrease in unemployment",
   "An improvement in technology affecting both goods",
   "Moving from one point on the curve to another",
   "A decrease in consumer demand",
   "Higher prices for both goods"], ans=1,
   why="Better technology raises capacity; less unemployment only moves toward the existing curve."),
 dict(q="A decline in a country's working-age population would most likely", choices=[
   "shift the PPC outward",
   "shift the PPC inward",
   "move production along the curve",
   "make the PPC linear",
   "leave the PPC unchanged"], ans=1,
   why="Fewer labor resources reduce productive capacity."),
 dict(q="A reduction in unemployment moves an economy", choices=[
   "along its PPC",
   "from a point inside the PPC toward the curve",
   "beyond its PPC",
   "to a new, outwardly shifted PPC",
   "to the vertical intercept"], ans=1,
   why="Employing idle resources moves production from inside toward the frontier — no shift."),
 dict(q="An improvement in technology used ONLY in producing good X (on the horizontal axis) causes the PPC to", choices=[
   "shift out along both axes equally",
   "rotate outward along the X-axis while the maximum of good Y is unchanged",
   "shift inward along the X-axis",
   "become vertical",
   "remain entirely unchanged"], ans=1,
   why="One-good technology gains expand the frontier only in that good's direction."),
 dict(q="Which of the following events would shift a nation's PPC inward?", choices=[
   "Discovery of new oil reserves",
   "An increase in the labor force",
   "Destruction of factories in a natural disaster",
   "Improved worker training",
   "Faster computer technology"], ans=2,
   why="Losing capital resources reduces maximum producible output."),
 dict(q="An improvement in the quality of human capital (better-trained workers) causes", choices=[
   "a movement along the PPC",
   "an outward shift of the PPC",
   "an inward shift of the PPC",
   "a move to a point inside the PPC",
   "no change in the PPC"], ans=1,
   why="Higher-quality resources raise productive capacity — growth."),
 dict(q="On a PPC between capital goods and consumer goods, choosing a point with MORE capital goods today tends to", choices=[
   "shrink future production possibilities",
   "generate faster future economic growth and a larger outward shift of the future PPC",
   "leave the future PPC unchanged",
   "cause immediate unemployment",
   "make the current PPC bow inward"], ans=1,
   why="Investing in capital today builds future productive capacity."),
 dict(q="High unemployment in an economy is best represented by", choices=[
   "a point on the PPC",
   "a point outside the PPC",
   "a point inside the PPC",
   "an outward shift of the PPC",
   "a steeper PPC"], ans=2,
   why="Idle labor means the economy produces below its frontier."),
 dict(table=dict(headers=["Point", "Sugar (tons)", "Wheat (tons)"],
   rows=[["A","100","0"],["B","90","40"],["C","60","70"],["D","30","90"],["E","0","100"]]),
   q="The table shows points on an economy's PPC. The opportunity cost of moving from point B to point C is", choices=[
   "30 tons of sugar",
   "30 tons of wheat",
   "70 tons of wheat",
   "10 tons of sugar",
   "60 tons of sugar"], ans=0,
   why="Sugar falls from 90 to 60: 30 tons of sugar are given up for 30 more wheat."),
 dict(table=dict(headers=["Point", "Sugar (tons)", "Wheat (tons)"],
   rows=[["A","100","0"],["B","90","40"],["C","60","70"],["D","30","90"],["E","0","100"]]),
   q="Using the same table, the opportunity cost of ONE additional ton of wheat when moving from A to B is", choices=[
   "4 tons of sugar",
   "1 ton of sugar",
   "0.25 tons of sugar",
   "10 tons of sugar",
   "40 tons of sugar"], ans=2,
   why="10 sugar given up for 40 wheat gained = 10/40 = 0.25 tons of sugar per wheat."),
 dict(table=dict(headers=["Point", "Sugar (tons)", "Wheat (tons)"],
   rows=[["A","100","0"],["B","90","40"],["C","60","70"],["D","30","90"],["E","0","100"]]),
   q="Comparing the move A-to-B with the move D-to-E in the table, the data illustrate", choices=[
   "constant opportunity costs",
   "decreasing opportunity costs",
   "increasing opportunity costs of wheat production",
   "unattainable production",
   "allocative efficiency"], ans=2,
   why="A→B costs 0.25 sugar per wheat; D→E costs 30/10 = 3 sugar per wheat — rising cost."),
 dict(q="An economy can produce either 20 tractors or 10 houses, or any linear combination between. The opportunity cost of ONE house is", choices=[
   "0.5 tractors", "1 tractor", "2 tractors", "10 tractors", "20 tractors"], ans=2,
   why="20 tractors / 10 houses = 2 tractors given up per house."),
 dict(q="Suppose a linear PPC runs from 60 computers (vertical) to 30 bicycles (horizontal). Moving from producing only computers to producing 10 bicycles costs", choices=[
   "10 computers", "20 computers", "30 computers", "40 computers", "60 computers"], ans=1,
   why="Each bicycle costs 60/30 = 2 computers; 10 bicycles cost 20 computers."),
 dict(q="If two points, one inside the PPC and one on it, are compared, moving from the interior point to the frontier", choices=[
   "requires giving up some of the other good",
   "allows more of one or both goods without sacrificing either",
   "is impossible without new technology",
   "causes economic contraction",
   "raises opportunity cost to infinity"], ans=1,
   why="From an inefficient interior point, output of both goods can rise at no opportunity cost."),
 dict(q="The assumption of 'fixed resources' in the PPC model means", choices=[
   "resources cannot move between industries",
   "the quantity and quality of available resources do not change along a given curve",
   "resource prices are fixed by law",
   "only capital is used in production",
   "resources are never scarce"], ans=1,
   why="A given PPC holds the resource base constant; changes shift the curve."),
 dict(q="Which change is illustrated by a MOVEMENT ALONG a fixed PPC?", choices=[
   "Technological progress",
   "Reallocating fully employed resources from one good to the other",
   "A natural disaster destroying capital",
   "Immigration expanding the labor force",
   "A rise in unemployment"], ans=1,
   why="Along the curve, society trades one good for the other at full employment."),
 dict(q="Trade with another country can allow an economy to", choices=[
   "shift its PPC outward instantly",
   "consume combinations beyond its own PPC",
   "produce beyond its PPC",
   "eliminate opportunity costs",
   "escape scarcity permanently"], ans=1,
   why="Trade expands consumption possibilities beyond domestic production limits."),
 dict(q="A bowed-IN (convex) PPC would represent", choices=[
   "increasing opportunity costs",
   "constant opportunity costs",
   "decreasing opportunity costs",
   "unemployment",
   "negative growth"], ans=2,
   why="A curve bowed toward the origin depicts falling opportunity costs."),
 dict(q="An economy produces at a point where 5 more units of good Y could be made without reducing good X. This economy is", choices=[
   "productively efficient",
   "allocatively efficient",
   "producing inside its PPC",
   "producing outside its PPC",
   "on its PPC"], ans=2,
   why="Getting more of one good for free is possible only from an interior (inefficient) point."),
 dict(q="Which of the following is a source of economic growth in the PPC model?", choices=[
   "Moving to a point with more consumer goods",
   "An increase in the quantity or quality of resources",
   "Reducing prices",
   "Rationing output",
   "Shifting demand between goods"], ans=1,
   why="More or better resources (or technology) shift the frontier outward."),
 dict(q="Two economies have identical PPCs today. Economy A produces mostly capital goods; Economy B produces mostly consumer goods. Over time we expect", choices=[
   "identical future PPCs",
   "A's PPC to shift outward by more than B's",
   "B's PPC to shift outward by more than A's",
   "both PPCs to shift inward",
   "A's PPC to become linear"], ans=1,
   why="Heavier investment in capital goods produces faster growth in capacity."),
 dict(q="The vertical intercept of a PPC for guns (vertical) and butter (horizontal) shows", choices=[
   "maximum butter output when no guns are produced",
   "maximum gun output when no butter is produced",
   "the efficient combination society prefers",
   "the level of unemployment",
   "the price of guns"], ans=1,
   why="An intercept is the maximum of that axis's good when all resources go to it."),
 dict(q="Suppose war destroys half of a nation's factories but leaves its labor force intact. In the PPC model this is shown as", choices=[
   "a movement along the curve",
   "an inward shift of the PPC",
   "an outward shift of the PPC",
   "no change, since labor is unchanged",
   "a movement from inside the curve to the curve"], ans=1,
   why="Losing capital shrinks capacity for both goods."),
 dict(q="Which point can an economy reach ONLY after growth, trade, or better technology?", choices=[
   "A point inside its PPC",
   "A point on its PPC",
   "A point beyond its current PPC",
   "The origin",
   "The midpoint of the curve"], ans=2,
   why="Beyond-frontier combinations are unattainable with current capacity."),
 dict(q="If the opportunity cost of each additional unit of butter is always exactly 2 guns, the PPC between guns and butter is", choices=[
   "bowed out", "bowed in", "a straight line", "vertical", "horizontal"], ans=2,
   why="A constant trade-off produces a linear frontier."),
 dict(q="Moving down along a bowed-out PPC (gaining the horizontal good), the curve becomes steeper because", choices=[
   "the price of the horizontal good falls",
   "each extra unit of the horizontal good costs more of the vertical good",
   "technology worsens",
   "resources become unemployed",
   "consumers want less of the vertical good"], ans=1,
   why="Steepening slope = rising opportunity cost of the horizontal good."),
 dict(q="Which of the following best explains why society cannot simply produce at a point beyond its PPC by working harder?", choices=[
   "Laws forbid overproduction",
   "The frontier already assumes full, efficient use of all available resources and technology",
   "Prices would rise too fast",
   "Consumers would not buy the extra output",
   "Working harder shifts the curve inward"], ans=1,
   why="The PPC is defined at full efficient employment; more effort is already counted."),
 dict(q="A country's PPC for robots and rice shifts outward only along the robot axis. The most likely cause is", choices=[
   "a general increase in the labor force",
   "an improvement in robot-making technology only",
   "new farmland",
   "a fall in rice demand",
   "increased unemployment"], ans=1,
   why="A one-good technology gain rotates the frontier out along that good's axis."),
 dict(q="If society values sugar and wheat about equally and its PPC offers point C with a balanced mix, choosing C over other efficient points achieves", choices=[
   "productive efficiency only",
   "allocative efficiency — the efficient mix society most desires",
   "an unattainable outcome",
   "economic contraction",
   "increasing returns"], ans=1,
   why="Allocative efficiency picks the on-curve mix matching society's preferences."),
 dict(q="Underutilized resources are best described as", choices=[
   "resources that do not exist",
   "resources not used to their full productive capacity, shown by interior PPC points",
   "resources used in both industries at once",
   "imported resources",
   "resources with zero opportunity cost"], ans=1,
   why="Interior points reflect resources working below capacity."),
 dict(q="An economy at full employment moves from producing 40 guns and 50 butter to 30 guns and 60 butter along its PPC. The opportunity cost of the 10 extra butter is", choices=[
   "60 butter", "50 butter", "40 guns", "10 guns", "30 guns"], ans=3,
   why="Guns fall from 40 to 30 — 10 guns are sacrificed for the extra butter."),
 dict(q="Which statement correctly pairs a change with its PPC effect?", choices=[
   "Lower unemployment — outward shift",
   "New resource discovery — movement along the curve",
   "Improved technology — outward shift",
   "Natural disaster — outward shift",
   "Reallocation between goods — inward shift"], ans=2,
   why="Technology shifts the frontier out; unemployment changes move points relative to a fixed curve."),
 dict(q="The opportunity cost of moving between two points on a PPC is measured by", choices=[
   "the money spent on inputs",
   "the amount of the other good given up",
   "the increase in total output",
   "the change in the price level",
   "the distance to the origin"], ans=1,
   why="On a PPC, cost is paid in units of the forgone good."),
 dict(q="A PPC diagram can illustrate all of the following concepts EXCEPT", choices=[
   "scarcity", "opportunity cost", "efficiency", "economic growth", "the distribution of income among households"], ans=4,
   why="The PPC shows production limits and trade-offs, not who receives the output."),
 dict(q="If an economy experiences growth that benefits both industries equally, the new PPC will be", choices=[
   "steeper everywhere",
   "flatter everywhere",
   "shifted outward roughly parallel to the old curve",
   "rotated inward on one axis",
   "unchanged"], ans=2,
   why="Balanced growth expands maximum output of both goods together."),
 dict(q="Point F lies inside a PPC and point G lies outside it. Which statement is correct?", choices=[
   "F is unattainable and G is inefficient",
   "F is inefficient (or reflects unemployment) and G is currently unattainable",
   "Both points are productively efficient",
   "F requires more resources than the economy has",
   "G can be reached by reducing unemployment alone"], ans=1,
   why="Interior = inefficiency/unemployment; exterior = beyond current capacity."),
 dict(q="Which scenario is best represented by a movement from a point ON the PPC to another point ON the same PPC?", choices=[
   "A recession raising unemployment",
   "A society shifting fully employed resources from military goods to consumer goods",
   "A technological breakthrough",
   "Post-war reconstruction of destroyed capital",
   "Discovery of new resources"], ans=1,
   why="Reallocating fully employed resources moves along the fixed frontier."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
