# 1.5 Cost-Benefit Analysis — 50 questions
# Math checks: 15000+5000=20000; 12*5+75=135; MU from TU 10,18,24,28,30 -> 10,8,6,4,2;
# Pepsi-style: MB 1.25,1.20,1.00,0.65 at price 1.00 -> 3 units;
# accounting profit 100k-60k=40k; economic profit 40k-50k=-10k.
MBTAB = dict(headers=["Glass of lemonade", "Marginal benefit"],
             rows=[["1st", "$1.25"], ["2nd", "$1.20"], ["3rd", "$1.00"], ["4th", "$0.65"]])
TUTAB = dict(headers=["Slices of pizza", "Total utility (utils)"],
             rows=[["1", "10"], ["2", "18"], ["3", "24"], ["4", "28"], ["5", "30"]])

QUESTIONS = [
 dict(q="Cost-benefit analysis is a technique used to", choices=[
   "measure only the monetary costs of a project",
   "evaluate a decision by comparing its expected costs with its expected benefits",
   "guarantee that projects earn profits",
   "calculate tax obligations",
   "set market prices"], ans=1,
   why="Cost-benefit analysis weighs expected costs against expected benefits."),
 dict(q="Explicit costs are", choices=[
   "the value of forgone alternatives",
   "direct, out-of-pocket monetary payments for resources",
   "costs that never appear in accounting records",
   "always larger than implicit costs",
   "costs paid only by governments"], ans=1,
   why="Explicit costs are direct monetary outlays recorded in the books."),
 dict(q="Implicit costs are", choices=[
   "payments to outside suppliers",
   "opportunity costs of using resources the decision-maker already owns, involving no direct payment",
   "wages paid to employees",
   "rent paid for office space",
   "identical to accounting costs"], ans=1,
   why="Implicit costs are forgone returns on self-owned resources — no cash changes hands."),
 dict(q="Which of the following is an EXPLICIT cost of running a bakery?", choices=[
   "The owner's forgone salary from a previous job",
   "The flour and sugar purchased each week",
   "The interest the owner's savings could have earned elsewhere",
   "The owner's forgone leisure time",
   "The rent the owner could have charged for the building she owns"], ans=1,
   why="Purchased ingredients are direct monetary payments."),
 dict(q="Which of the following is an IMPLICIT cost for an entrepreneur who quit a salaried job and uses her own building to run a shop?", choices=[
   "Employee wages",
   "Utility bills",
   "The salary she gave up and the rent her building could have earned",
   "The cost of inventory",
   "Business insurance premiums"], ans=2,
   why="Forgone salary and forgone rent are opportunity costs of owned resources."),
 dict(q="After high school, Billy enrolls in a two-year program instead of taking an internship paying $15,000 per year. Tuition and fees are $5,000 per year. His annual opportunity cost of attending is", choices=[
   "$5,000", "$10,000", "$15,000", "$20,000", "$25,000"], ans=3,
   why="Forgone salary $15,000 (implicit) + tuition $5,000 (explicit) = $20,000."),
 dict(q="Sylvia earns $12 per hour and takes 5 unpaid hours off work to attend an event with a discounted $75 ticket. Her opportunity cost of attending is", choices=[
   "$75", "$60", "$135", "$100", "$160"], ans=2,
   why="Forgone wages $60 plus the $75 ticket = $135."),
 dict(q="Total benefit is", choices=[
   "the benefit of the last unit consumed",
   "the overall satisfaction gained from consuming a given quantity of a good",
   "always equal to total cost",
   "the benefit net of all costs",
   "marginal benefit divided by quantity"], ans=1,
   why="Total benefit is cumulative satisfaction from all units consumed."),
 dict(q="Marginal benefit is", choices=[
   "total benefit divided by price",
   "the additional benefit from consuming one more unit",
   "the average benefit per unit",
   "the benefit of the first unit only",
   "always constant"], ans=1,
   why="Marginal benefit is the extra benefit of one additional unit."),
 dict(q="Marginal cost is", choices=[
   "the total cost of production",
   "the additional cost of producing or consuming one more unit",
   "the fixed cost per unit",
   "always zero for consumers",
   "total cost divided by total benefit"], ans=1,
   why="Marginal cost is the extra cost of one more unit."),
 dict(q="The Law of Diminishing Marginal Utility states that as a person consumes more of a good,", choices=[
   "total utility must fall",
   "the additional utility from each extra unit eventually declines",
   "the price of the good rises",
   "marginal utility rises without limit",
   "the good becomes inferior"], ans=1,
   why="Extra units eventually add less and less satisfaction."),
 dict(q="Diminishing marginal utility explains why", choices=[
   "people want to consume infinite quantities of every good",
   "consumers do not endlessly consume a single good even when they enjoy it",
   "prices never change",
   "total utility is always negative",
   "firms maximize revenue"], ans=1,
   why="Falling extra satisfaction eventually makes more consumption not worth it."),
 dict(q="Negative marginal utility means that consuming an additional unit", choices=[
   "adds nothing to total utility",
   "actually reduces total utility",
   "is free of charge",
   "doubles total utility",
   "is impossible"], ans=1,
   why="Past some point (e.g., getting sick from pizza), an extra unit lowers total utility."),
 dict(q="According to the cost-benefit maximizing principle, total net benefit is maximized at the quantity where", choices=[
   "marginal benefit is greatest",
   "marginal cost is lowest",
   "marginal benefit equals marginal cost",
   "total benefit equals total cost",
   "average benefit equals average cost"], ans=2,
   why="Consume until MB = MC — before that each unit adds surplus; after, it subtracts."),
 dict(q="If marginal benefit currently exceeds marginal cost, a rational decision-maker should", choices=[
   "consume or produce more",
   "consume or produce less",
   "stop immediately",
   "raise the price",
   "ignore marginal values"], ans=0,
   why="MB > MC means each additional unit still adds net benefit."),
 dict(q="If marginal cost currently exceeds marginal benefit, a rational decision-maker should", choices=[
   "expand the activity",
   "reduce the activity",
   "keep quantity unchanged",
   "double the activity",
   "switch to average analysis"], ans=1,
   why="MB < MC means the last units subtract from net benefit."),
 dict(q="Marginal surplus on a unit is calculated as", choices=[
   "MB + MC", "MB − MC", "MC − MB", "MB × MC", "total benefit − total cost"], ans=1,
   why="A unit's surplus is its marginal benefit minus its marginal cost."),
 dict(table=MBTAB, q="The table shows Jane's marginal benefit from glasses of lemonade. If each glass costs $1.00, how many should she buy to maximize net benefit?", choices=[
   "1", "2", "3", "4", "As many as possible"], ans=2,
   why="Buy while MB ≥ price: glasses 1-3 (MB 1.25, 1.20, 1.00); the 4th's MB (0.65) < $1."),
 dict(table=MBTAB, q="Using the same table with a $1.00 price, Jane's surplus on the FIRST glass is", choices=[
   "$0.00", "$0.20", "$0.25", "$1.00", "$1.25"], ans=2,
   why="$1.25 benefit − $1.00 price = $0.25."),
 dict(table=MBTAB, q="If the price of lemonade fell to $0.60 per glass, Jane should buy", choices=[
   "1 glass", "2 glasses", "3 glasses", "4 glasses", "0 glasses"], ans=3,
   why="Now even the 4th glass (MB $0.65) exceeds the $0.60 price."),
 dict(table=TUTAB, q="The table shows total utility from pizza slices. The marginal utility of the THIRD slice is", choices=[
   "24 utils", "18 utils", "8 utils", "6 utils", "4 utils"], ans=3,
   why="MU3 = TU3 − TU2 = 24 − 18 = 6 utils."),
 dict(table=TUTAB, q="The total utility figures in the table illustrate", choices=[
   "increasing marginal utility",
   "diminishing marginal utility (MU falls: 10, 8, 6, 4, 2)",
   "negative total utility",
   "constant marginal utility",
   "irrational behavior"], ans=1,
   why="Each successive slice adds less utility: 10, 8, 6, 4, 2."),
 dict(q="A firm's accounting profit equals total revenue minus", choices=[
   "implicit costs only",
   "explicit costs only",
   "both explicit and implicit costs",
   "opportunity costs of the owner's time",
   "taxes only"], ans=1,
   why="Accountants subtract only explicit, recorded costs."),
 dict(q="Economic profit equals total revenue minus", choices=[
   "explicit costs only",
   "implicit costs only",
   "the sum of explicit and implicit costs",
   "fixed costs only",
   "marginal cost"], ans=2,
   why="Economists subtract total economic cost — explicit plus implicit."),
 dict(q="A shop earns $100,000 in revenue with $60,000 of explicit costs. The owner gave up a $50,000 salary to run it. Accounting and economic profit are, respectively,", choices=[
   "$40,000 and $40,000",
   "$40,000 and −$10,000",
   "−$10,000 and $40,000",
   "$100,000 and $50,000",
   "$40,000 and $90,000"], ans=1,
   why="Accounting: 100k−60k = $40k. Economic: 40k−50k implicit = −$10k."),
 dict(q="A negative economic profit alongside a positive accounting profit tells the owner that", choices=[
   "the business is illegal",
   "her resources would earn more in their next best alternative use",
   "revenues are falsified",
   "implicit costs are zero",
   "the firm should raise prices immediately"], ans=1,
   why="Economic loss means the forgone alternative beats the current venture."),
 dict(q="Total economic cost is defined as", choices=[
   "explicit costs minus implicit costs",
   "the sum of all explicit and implicit costs of a decision",
   "only production costs",
   "costs recorded by accountants",
   "marginal cost times price"], ans=1,
   why="Economic cost includes both out-of-pocket and opportunity costs."),
 dict(q="Rational agents are decision-makers who", choices=[
   "always avoid risk",
   "compare benefits and costs to maximize their satisfaction or profit",
   "ignore opportunity costs",
   "make choices at random",
   "consider only monetary factors"], ans=1,
   why="Rational agents weigh costs against benefits to maximize net gain."),
 dict(q="Optimal choice is the decision that", choices=[
   "minimizes total cost regardless of benefit",
   "maximizes total benefit regardless of cost",
   "maximizes total net benefit — the gap between total benefit and total cost",
   "equalizes total benefit and total cost",
   "eliminates marginal cost"], ans=2,
   why="Optimality maximizes total benefits minus total costs."),
 dict(q="Why should a decision-maker stop at MB = MC rather than continuing until total benefit equals total cost?", choices=[
   "Total benefit never equals total cost",
   "Beyond MB = MC each extra unit reduces net benefit, even while total benefit still exceeds total cost",
   "MB = MC guarantees zero total benefit",
   "Marginal analysis is only for firms",
   "Total values cannot be measured"], ans=1,
   why="After MB = MC, additional units have MB < MC and shrink accumulated net benefit."),
 dict(q="Eating a first slice of pizza when very hungry gives great satisfaction; the sixth slice makes you feel ill. The sixth slice most likely has", choices=[
   "high positive marginal utility",
   "zero total utility",
   "negative marginal utility",
   "infinite marginal utility",
   "no effect on total utility"], ans=2,
   why="Feeling ill means the extra slice lowered total satisfaction."),
 dict(q="If there is no quantity at which MB exactly equals MC, a rational consumer should", choices=[
   "consume nothing",
   "consume every unit available",
   "consume all units for which MB exceeds MC and stop before MB falls below MC",
   "flip a coin",
   "consume until total cost is exhausted"], ans=2,
   why="Take every surplus-adding unit; stop before the first net-loss unit."),
 dict(q="Which cost should be IGNORED when deciding whether to continue a project?", choices=[
   "Marginal cost of continuing",
   "Opportunity cost of resources used going forward",
   "Costs already paid that cannot be recovered",
   "Implicit costs of the owner's time going forward",
   "Future explicit costs"], ans=2,
   why="Unrecoverable past (sunk) costs are irrelevant to marginal decisions."),
 dict(q="The terms 'benefit' and 'utility' in economics are", choices=[
   "opposites",
   "used interchangeably to mean satisfaction",
   "measured only in dollars",
   "applicable only to firms",
   "always negative"], ans=1,
   why="Utility is the economist's word for benefit or satisfaction."),
 dict(q="An example of constant marginal cost for a consumer is", choices=[
   "each additional slice of pizza costing the same $4",
   "each slice costing more than the last",
   "the first slice being free",
   "utility falling with each slice",
   "prices doubling with each purchase"], ans=0,
   why="A fixed per-unit price means the marginal cost of each unit is identical."),
 dict(q="Marta values a first movie this month at $18, a second at $10, and a third at $6. Tickets cost $8. To maximize net benefit she should see", choices=[
   "0 movies", "1 movie", "2 movies", "3 movies", "as many as the theater shows"], ans=2,
   why="Movies 1 and 2 have MB ($18, $10) above the $8 price; the third ($6) does not."),
 dict(q="In Marta's case above, her total net benefit (consumer surplus) from the two movies she attends is", choices=[
   "$28", "$16", "$12", "$10", "$2"], ans=2,
   why="(18−8) + (10−8) = 10 + 2 = $12."),
 dict(q="When MB > MC for the current unit, consuming it causes total net benefit to", choices=[
   "fall", "rise", "stay constant", "become negative", "equal zero"], ans=1,
   why="A positive marginal surplus adds to accumulated net benefit."),
 dict(q="Which of the following illustrates an implicit cost of attending a review session?", choices=[
   "The bus fare to campus",
   "The printed notes purchased",
   "The two hours of paid tutoring work the student gives up",
   "The coffee bought on the way",
   "The session's entry fee"], ans=2,
   why="Forgone earnings from the student's own time are implicit."),
 dict(q="Total revenue is calculated as", choices=[
   "price plus quantity",
   "price multiplied by quantity sold",
   "quantity minus costs",
   "profit plus implicit costs",
   "price divided by quantity"], ans=1,
   why="TR = P × Q."),
 dict(q="A rational firm deciding whether to produce one more unit compares", choices=[
   "total revenue with total cost",
   "the marginal revenue (benefit) of that unit with its marginal cost",
   "average cost with fixed cost",
   "last year's profit with this year's",
   "its output with rivals' output"], ans=1,
   why="Marginal decisions weigh the extra unit's benefit against its extra cost."),
 dict(q="Why do economists insist that time spent is a real cost even when no money changes hands?", choices=[
   "Because time can be banked for later",
   "Because time is scarce and has valuable alternative uses",
   "Because wages are always paid in cash",
   "Because leisure has no value",
   "Because accountants record time"], ans=1,
   why="Scarce time given to one activity is taken from its next best use."),
 dict(q="Ahmed pays a $40 nonrefundable deposit for a class, then learns he values attending at only $10 while attending costs him $15 in bus fare. Rationally, he should", choices=[
   "attend, to avoid wasting the deposit",
   "not attend, because the $15 marginal cost exceeds the $10 marginal benefit; the deposit is sunk",
   "attend, because total spending is already high",
   "not attend, because the deposit was too small",
   "attend only if the deposit is refunded"], ans=1,
   why="Compare only forward-looking MB and MC; the sunk deposit is unrecoverable either way."),
 dict(q="Consumer surplus on a purchased unit equals", choices=[
   "price minus marginal cost",
   "marginal benefit minus price paid",
   "total benefit plus total cost",
   "price times quantity",
   "marginal utility divided by price"], ans=1,
   why="Surplus is what the unit is worth to you minus what you paid."),
 dict(q="The statement 'I've eaten three slices; a fourth would give me less satisfaction than the third did' reflects", choices=[
   "negative total utility",
   "the law of diminishing marginal utility",
   "increasing marginal returns",
   "irrational preferences",
   "constant marginal utility"], ans=1,
   why="Falling additional satisfaction across units is diminishing marginal utility."),
 dict(q="Which decision rule summarizes marginal analysis for any activity?", choices=[
   "Do it if total cost is low",
   "Continue while marginal benefit is at least as large as marginal cost; stop at MB = MC",
   "Continue until total benefit is zero",
   "Stop when marginal benefit is at its maximum",
   "Always consume the average quantity"], ans=1,
   why="Marginal analysis: proceed while MB ≥ MC, settle where they are equal."),
 dict(q="If total benefit is still rising but marginal benefit has fallen below marginal cost, net benefit is", choices=[
   "rising", "falling", "constant", "maximized", "zero"], ans=1,
   why="Units with MB < MC subtract surplus even while total benefit grows."),
 dict(q="Paying $1.00 for a fourth item that gives only $0.65 of benefit is irrational because", choices=[
   "the item's total benefit is negative",
   "it is like paying a dollar to receive sixty-five cents of value",
   "prices should always fall",
   "the first three items were free",
   "benefits cannot be measured in dollars"], ans=1,
   why="The marginal loss of $0.35 reduces overall net benefit."),
 dict(q="Opportunity cost in cost-benefit analysis includes", choices=[
   "only cash payments",
   "both explicit outlays and implicit (forgone) values",
   "only implicit values",
   "only losses reported to tax authorities",
   "no time-related elements"], ans=1,
   why="Full opportunity cost sums explicit and implicit components."),
 dict(q="A city weighs building a park: construction will cost $2 million, and the land could otherwise be leased for $300,000. The park's full economic cost includes", choices=[
   "only the $2 million construction cost",
   "only the $300,000 lease value",
   "the $2 million construction cost plus the $300,000 forgone lease income",
   "neither amount, since parks are public",
   "the construction cost minus the lease value"], ans=2,
   why="Economic cost adds the implicit forgone lease to the explicit outlay."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
