# 1.6 Marginal Analysis and Consumer Choice — 50 questions
# Math checks:
#  Bundle A: budget $7, burger $2, pretzel $1; MU burgers 12,8,4 (MU/P 6,4,2);
#    MU pretzels 6,5,4,3 (MU/P 6,5,4,3) -> buy B1,P1 (6), P2 (5), B2,P3 (4);
#    spend 2+1+1+2+1 = $7 -> 2 burgers, 3 pretzels; last MU/P both 4; TU=35.
#  Bundle B: budget $12, book $3, pen $1; MU books 24,18,12,6 (8,6,4,2);
#    MU pens 8,7,4,2 (8,7,4,2) -> B1,Pen1 (8), Pen2 (7), B2 (6), B3,Pen3 (4);
#    spend 3+1+1+3+3+1 = $12 -> 3 books, 3 pens; last MU/P both 4.
BURG = dict(headers=["Unit", "MU of hamburgers (utils)", "MU of pretzels (utils)"],
            rows=[["1st", "12", "6"], ["2nd", "8", "5"], ["3rd", "4", "4"], ["4th", "—", "3"]])
BOOK = dict(headers=["Unit", "MU of books (utils)", "MU of pens (utils)"],
            rows=[["1st", "24", "8"], ["2nd", "18", "7"], ["3rd", "12", "4"], ["4th", "6", "2"]])

QUESTIONS = [
 dict(q="In consumer choice theory, utility means", choices=[
   "the price of a good",
   "the usefulness of money",
   "the satisfaction a consumer receives from consuming goods and services",
   "the number of goods purchased",
   "a public service such as electricity"], ans=2,
   why="Utility is the economist's measure of satisfaction."),
 dict(q="Utility maximization refers to a consumer's goal of", choices=[
   "buying the cheapest goods available",
   "obtaining the greatest total satisfaction possible from a limited budget",
   "saving all income",
   "consuming equal amounts of every good",
   "maximizing the number of items purchased"], ans=1,
   why="Consumers allocate limited income to maximize total satisfaction."),
 dict(q="In the two-good utility-maximization model, one standard assumption is that the consumer", choices=[
   "saves half of all income",
   "spends all of their income on the two goods",
   "buys only one unit of each good",
   "faces prices that change with each purchase",
   "has unlimited income"], ans=1,
   why="The model assumes the entire budget is spent on the two goods."),
 dict(q="MU/P measures", choices=[
   "total utility per good",
   "the marginal utility received per dollar spent on a good — 'bang for the buck'",
   "the price of a marginal unit",
   "average utility over all units",
   "profit per unit"], ans=1,
   why="Dividing marginal utility by price expresses extra satisfaction per dollar."),
 dict(q="Economists compare MU/P rather than raw MU across goods because", choices=[
   "utility cannot be measured",
   "goods have different prices, so satisfaction must be compared per dollar spent",
   "prices are irrelevant to choices",
   "MU is always equal across goods",
   "the government requires it"], ans=1,
   why="Different prices make per-dollar comparison the fair standard."),
 dict(q="A consumer maximizes utility across two goods when", choices=[
   "MU of good 1 equals MU of good 2",
   "MU1/P1 = MU2/P2 and all income is spent",
   "the prices of both goods are equal",
   "total utility of each good is equal",
   "spending on both goods is equal"], ans=1,
   why="The utility-maximizing rule equalizes marginal utility per dollar with the budget exhausted."),
 dict(q="If MU1/P1 exceeds MU2/P2, a utility-maximizing consumer should", choices=[
   "buy more of good 2",
   "buy more of good 1, since it currently yields more satisfaction per dollar",
   "buy less of good 1",
   "stop buying both goods",
   "borrow money"], ans=1,
   why="Buy the good with the higher bang per buck; its MU then falls toward balance."),
 dict(q="The equalization of MU/P across goods eventually occurs because of", choices=[
   "rising prices",
   "diminishing marginal utility — buying more of a good lowers its MU",
   "government intervention",
   "increasing returns to scale",
   "fixed preferences"], ans=1,
   why="As purchases of the favored good rise, its MU (and MU/P) falls until equality."),
 dict(q="When choosing which good to buy next, a rational consumer picks the good with", choices=[
   "the lowest price",
   "the highest marginal utility per dollar",
   "the highest total utility",
   "the largest package size",
   "the most advertising"], ans=1,
   why="Each dollar goes where it buys the most extra satisfaction."),
 dict(q="Ana gets 30 utils from another movie ($10 per ticket) and 8 utils from another coffee ($2 per cup). To maximize utility she should next buy", choices=[
   "the movie, because 30 utils exceeds 8 utils",
   "the coffee, because 4 utils per dollar exceeds the movie's 3 utils per dollar",
   "the movie, because it costs more",
   "neither good",
   "both in equal numbers"], ans=1,
   why="Compare MU/P: coffee 8/2 = 4 beats movie 30/10 = 3."),
 dict(q="If given total utility data, the FIRST step in solving a utility-maximization problem is to", choices=[
   "divide total utility by price",
   "compute marginal utility as the change in total utility between units",
   "add the prices together",
   "graph the budget line",
   "compare total utilities across goods"], ans=1,
   why="MU must be derived from TU before computing MU per dollar."),
 dict(q="After computing marginal utility, the next step is to", choices=[
   "multiply MU by price",
   "divide each MU by the good's price to get MU per dollar",
   "sum the MUs",
   "convert utils to dollars",
   "rank goods by total utility"], ans=1,
   why="MU/P is what gets compared across goods."),
 dict(table=BURG, q="Hamburgers cost $2 and pretzels cost $1, and Sam has $7 to spend. Using the marginal utilities shown, which combination maximizes his utility?", choices=[
   "1 hamburger and 5 pretzels",
   "2 hamburgers and 3 pretzels",
   "3 hamburgers and 1 pretzel",
   "2 hamburgers and 2 pretzels",
   "1 hamburger and 3 pretzels"], ans=1,
   why="Buying by highest MU/P uses exactly $7 and ends with MU/P equal at 4 (burger 8/2, pretzel 4/1)."),
 dict(table=BURG, q="In Sam's optimal bundle (2 hamburgers, 3 pretzels at $2 and $1 with $7), the MU per dollar of the LAST unit of each good is", choices=[
   "6 for each good", "5 for each good", "4 for each good", "3 for each good", "unequal across the goods"], ans=2,
   why="Last burger: 8/2 = 4; last pretzel: 4/1 = 4."),
 dict(table=BURG, q="Sam's total utility from his optimal bundle (2 hamburgers, 3 pretzels) is", choices=[
   "27 utils", "31 utils", "35 utils", "39 utils", "20 utils"], ans=2,
   why="(12+8) + (6+5+4) = 35 utils."),
 dict(table=BOOK, q="Books cost $3, pens cost $1, and Heather has $12. Using the marginal utilities shown, her utility-maximizing combination is", choices=[
   "2 books and 6 pens",
   "3 books and 3 pens",
   "4 books and 0 pens",
   "1 book and 9 pens",
   "3 books and 2 pens"], ans=1,
   why="Highest-MU/P order spends exactly $12 and equalizes final MU/P at 4 (12/3 and 4/1)."),
 dict(table=BOOK, q="In Heather's problem, the MU per dollar of the FIRST book is", choices=[
   "24", "12", "8", "6", "3"], ans=2,
   why="24 utils / $3 = 8 utils per dollar."),
 dict(q="At her chosen bundle, Rosa's MU/P is 5 for tea and 5 for toast, and her budget is fully spent. Rosa", choices=[
   "should buy more tea",
   "should buy more toast",
   "is maximizing her utility",
   "is violating the budget constraint",
   "should save instead"], ans=2,
   why="Equal MU per dollar with income exhausted is the maximizing condition."),
 dict(q="At his current bundle, Ed's MU/P for juice is 7 and for fruit is 3. Ed should", choices=[
   "buy more fruit and less juice",
   "buy more juice and less fruit",
   "keep the bundle unchanged",
   "buy less of both",
   "compare total utilities instead"], ans=1,
   why="Reallocate dollars toward the higher MU/P good, juice."),
 dict(q="The logic behind MU1/P1 = MU2/P2 parallels the MB = MC rule because both state that", choices=[
   "totals must be equal at the optimum",
   "at the margin, the last dollar (or unit) should yield equal value in every use",
   "prices equal costs in equilibrium",
   "consumers ignore prices",
   "supply equals demand"], ans=1,
   why="Optimality equalizes returns at the margin across alternatives."),
 dict(q="If two goods have equal prices, the utility-maximizing consumer will buy quantities such that", choices=[
   "total utilities are equal",
   "the marginal utilities of the last units are equal",
   "one good is not consumed at all",
   "spending on the goods differs",
   "marginal utility of one good is zero"], ans=1,
   why="With P1 = P2, MU/P equality reduces to MU equality."),
 dict(q="Suppose MU of the next slice of cake is 12 utils at $4 (MU/P = 3) and MU of the next cookie is 4 utils at $1 (MU/P = 4). With $5 left and wanting maximum utility, the consumer buys", choices=[
   "the cake first, then a cookie",
   "the cookie first, because its MU per dollar is higher",
   "neither item",
   "half of each",
   "whichever has higher MU"], ans=1,
   why="4 utils per dollar beats 3; the cookie comes first."),
 dict(q="A consumer who buys goods in order of highest MU/P and stops when income is exhausted is applying", choices=[
   "the law of supply",
   "utility-maximization through marginal analysis",
   "the invisible hand",
   "cost-push reasoning",
   "average-cost pricing"], ans=1,
   why="Sequential highest-bang-per-buck purchasing is the marginal method."),
 dict(q="Why won't a rational consumer typically spend all income on the single good with the highest initial marginal utility?", choices=[
   "Prices always rise",
   "Diminishing marginal utility lowers that good's MU/P below other goods' as more is bought",
   "It is prohibited by the budget constraint",
   "Total utility cannot rise",
   "Other goods have no utility"], ans=1,
   why="Falling MU eventually makes another good the better use of the next dollar."),
 dict(q="In utility-maximization problems, the consumer's constraint is", choices=[
   "time", "technology", "their fixed income or budget", "government quotas", "storage space"], ans=2,
   why="The budget is the binding limit on purchases."),
 dict(q="Kim has $6; smoothies cost $3 and yield MU of 18 then 9; muffins cost $1 and yield MU of 5, 4, 3, 2. Her optimal bundle is", choices=[
   "2 smoothies and 0 muffins",
   "1 smoothie and 3 muffins",
   "0 smoothies and 6 muffins",
   "1 smoothie and 1 muffin",
   "2 smoothies and 3 muffins"], ans=1,
   why="Order by MU/P: smoothie1 (6), muffin1 (5), muffin2 (4), muffin3 (3) = $6; smoothie2 (3) ties muffin3 but exceeds remaining budget. Bundle: 1 smoothie, 3 muffins."),
 dict(q="In Kim's problem, her total utility at the optimum (1 smoothie, 3 muffins) is", choices=[
   "18 utils", "27 utils", "30 utils", "12 utils", "24 utils"], ans=2,
   why="18 + (5+4+3) = 30 utils."),
 dict(q="The condition MU1/P1 = MU2/P2 with all income spent guarantees that", choices=[
   "total spending is minimized",
   "no reallocation of a dollar between the goods can raise total utility",
   "both goods are consumed in equal amounts",
   "prices will fall",
   "marginal utility is maximized"], ans=1,
   why="Equal per-dollar returns mean no dollar can be moved to gain utility."),
 dict(q="If a consumer could raise total utility by shifting a dollar from good A to good B, then before the shift", choices=[
   "MUb/Pb was greater than MUa/Pa",
   "MUa/Pa was greater than MUb/Pb",
   "the two ratios were equal",
   "total utility was already maximized",
   "prices must have changed"], ans=0,
   why="A beneficial shift toward B means B offered more utility per dollar."),
 dict(q="Solving for utility-maximizing bundles of three or more goods is not required in AP Microeconomics because it", choices=[
   "is conceptually different",
   "requires multivariable calculus beyond the course",
   "has no solution",
   "contradicts the two-good rule",
   "depends on macroeconomics"], ans=1,
   why="The principle extends, but the math (multivariable optimization) exceeds the course."),
 dict(q="The phrase 'bang for your buck' corresponds to which formal concept?", choices=[
   "Total utility", "Marginal utility per dollar (MU/P)", "Opportunity cost", "Consumer surplus", "Price elasticity"], ans=1,
   why="MU/P is satisfaction gained per dollar spent."),
 dict(q="A consumer's willingness to keep buying a good falls as they buy more of it chiefly because", choices=[
   "their income rises",
   "the good's marginal utility diminishes",
   "prices always increase",
   "preferences reverse",
   "budgets expand"], ans=1,
   why="Diminishing MU lowers the value of additional units."),
 dict(q="If the price of good 1 rises while MU schedules stay the same, the consumer will generally", choices=[
   "buy more of good 1",
   "buy less of good 1, since its MU per dollar has fallen",
   "keep the same bundle",
   "buy less of good 2",
   "stop consuming good 2"], ans=1,
   why="A higher P1 lowers MU1/P1, shifting dollars toward the other good."),
 dict(q="Utility maximization problems commonly appear on AP Microeconomics free-response questions because they test", choices=[
   "memorization of formulas only",
   "the ability to apply marginal analysis to consumer decisions",
   "knowledge of banking",
   "national income accounting",
   "supply-side policy"], ans=1,
   why="They apply marginal reasoning (MU/P comparisons) to choices."),
 dict(q="When the last dollar spent on pizza yields 6 utils and the last dollar spent on soda yields 6 utils, and no income remains, the consumer has", choices=[
   "over-consumed pizza",
   "reached the utility-maximizing allocation",
   "violated diminishing marginal utility",
   "an incentive to reallocate spending",
   "made an error, since utils differ from dollars"], ans=1,
   why="Equal marginal utility per dollar across goods, budget spent — the optimum."),
 dict(q="Suppose the MU of the next unit of X is 20 utils and Px is $4, while the MU of the next unit of Y is 10 utils and Py is $2. The consumer", choices=[
   "should buy only X from now on",
   "should buy only Y from now on",
   "is indifferent between the two at the margin, since both give 5 utils per dollar",
   "cannot compare the goods",
   "should stop consuming"], ans=2,
   why="20/4 = 10/2 = 5 utils per dollar — a tie at the margin."),
 dict(q="Which change would make a consumer buy MORE of good Y without any price change in Y?", choices=[
   "A rise in Y's marginal utility schedule (Y becomes more enjoyable)",
   "A fall in income with normal goods",
   "A fall in the price of substitute good X",
   "A drop in Y's marginal utility",
   "Stricter budget limits"], ans=0,
   why="Higher MU raises Y's MU/P, drawing more dollars to Y."),
 dict(q="The two-good model's assumption that consumers spend all income implies", choices=[
   "saving is treated as a third good",
   "any unspent dollar could have added utility, so leaving income unspent is not maximizing",
   "borrowing is required",
   "prices adjust to income",
   "income is unlimited"], ans=1,
   why="With positive MU, an unspent dollar wastes potential satisfaction in this model."),
 dict(q="Marginal utility is defined as", choices=[
   "utility from all units consumed",
   "the change in total utility from consuming one more unit",
   "utility divided by income",
   "the utility of the first unit",
   "total utility divided by quantity"], ans=1,
   why="MU = ΔTU from one additional unit."),
 dict(q="If total utility from 3 units is 30 and from 4 units is 34, the marginal utility of the 4th unit is", choices=[
   "34", "30", "8", "4", "64"], ans=3,
   why="34 − 30 = 4 utils."),
 dict(q="In a table of marginal utilities, the total utility of consuming n units equals", choices=[
   "the MU of the nth unit",
   "the sum of the marginal utilities of units 1 through n",
   "n times the price",
   "the MU of the first unit times n",
   "the average MU"], ans=1,
   why="TU is the running sum of marginal utilities."),
 dict(q="Leah is deciding between one more song download ($1, MU 3 utils) and one more app ($3, MU 12 utils). With at least $3 available, her next purchase should be", choices=[
   "the song, because it is cheaper",
   "the app, because 4 utils per dollar beats 3",
   "the song, because 3 utils is positive",
   "neither, because utils differ",
   "both are equally good at the margin"], ans=1,
   why="App: 12/3 = 4 utils per dollar; song: 3/1 = 3."),
 dict(q="A store doubles the price of a snack overnight while the consumer's tastes are unchanged. At the old bundle, the snack's MU/P", choices=[
   "doubles",
   "halves, prompting the consumer to shift purchases toward other goods",
   "is unchanged",
   "becomes negative",
   "cannot be computed"], ans=1,
   why="Same MU over twice the price = half the bang per buck."),
 dict(q="Which sequence describes the standard method for utility-max problems when marginal utilities are given?", choices=[
   "Sum MU, divide by income, buy the cheaper good",
   "Compute MU/P for each unit, buy units in descending MU/P order until income is spent",
   "Buy alternating units of each good",
   "Buy the good with the higher price first",
   "Equalize total spending on each good"], ans=1,
   why="Rank by MU per dollar, purchase in order, stop when the budget runs out."),
 dict(q="If a problem's budget runs out just as the two goods' next-unit MU/P values become equal, the consumer stops because", choices=[
   "utility is now zero",
   "both the budget constraint and the equal-marginal principle are satisfied",
   "prices will fall tomorrow",
   "marginal utility has become negative",
   "the model fails"], ans=1,
   why="Income exhausted with equalized MU/P is exactly the optimum condition."),
 dict(q="The rule MU1/P1 = MU2/P2 is often called the", choices=[
   "law of demand",
   "equal marginal principle (utility-maximizing rule)",
   "invisible hand theorem",
   "law of supply",
   "profit-maximizing rule"], ans=1,
   why="It is the equal-marginal (utility-maximizing) condition."),
 dict(q="A consumer with $10 buys goods until every dollar earns 6 utils at the margin in each good, spending exactly $10. Total utility from the LAST dollar spent is", choices=[
   "60 utils", "10 utils", "6 utils", "unknown", "zero"], ans=2,
   why="The final dollar yields the marginal 6 utils in either good."),
 dict(q="Utility-maximization analysis treats consumers as solving what everyday problem?", choices=[
   "Choosing a career",
   "Getting the most satisfaction from a limited grocery budget",
   "Voting in elections",
   "Setting product prices",
   "Forecasting inflation"], ans=1,
   why="It formalizes stretching a limited budget across goods for maximum satisfaction."),
 dict(q="If the next unit of each of two goods offers the same MU but good A is cheaper, the consumer should", choices=[
   "buy good B",
   "buy good A, whose MU per dollar is higher",
   "be indifferent",
   "buy neither",
   "compare total utilities"], ans=1,
   why="Equal MU at a lower price means more satisfaction per dollar from A."),
 dict(q="Diminishing marginal utility guarantees that the process of always buying the highest-MU/P unit will", choices=[
   "never end",
   "eventually bring the goods' MU/P values toward each other",
   "concentrate all spending on one good forever",
   "raise prices",
   "reduce total utility"], ans=1,
   why="Each purchase lowers that good's MU/P, pushing ratios toward equality."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
