# 2.1 Demand — 50 questions
TOPIC = ("2.1", "Demand", 2)
QUESTIONS = [
 dict(q="The law of demand states that, holding all else constant,", choices=[
   "as the price of a good rises, the quantity demanded of that good falls",
   "as the price of a good rises, the quantity demanded of that good rises",
   "as consumer income rises, demand always falls",
   "price and quantity demanded are unrelated",
   "quantity demanded determines price"], ans=0,
   why="Price and quantity demanded move in opposite directions, all else equal."),
 dict(q="Demand differs from merely wanting a good because demand requires", choices=[
   "government approval of the purchase",
   "both the willingness AND the ability to pay",
   "that the good be a necessity",
   "that the buyer already own a substitute",
   "the price to be below the equilibrium price"], ans=1,
   why="Demand is willingness plus ability to pay — a wish without purchasing power is not demand."),
 dict(q="A demand schedule is", choices=[
   "a list of the quantities demanded at each of various prices",
   "a timetable for when goods will be delivered",
   "the total revenue a firm expects to earn",
   "a graph of costs against output",
   "the government's price ceiling policy"], ans=0,
   why="A demand schedule tabulates quantity demanded at each price."),
 dict(q="The demand curve slopes downward primarily because of", choices=[
   "rising production costs",
   "the substitution effect and the income effect",
   "government price controls",
   "increasing returns to scale",
   "the number of firms in the market"], ans=1,
   why="Lower prices make a good relatively cheaper (substitution) and raise real purchasing power (income)."),
 dict(q="A change in QUANTITY DEMANDED is caused by a change in", choices=[
   "consumer income",
   "the good's own price",
   "the price of a substitute",
   "consumer tastes",
   "the number of buyers"], ans=1,
   why="Only a change in the good's own price moves you along a fixed demand curve."),
 dict(q="A change in DEMAND (a shift of the whole curve) is caused by", choices=[
   "a change in the good's own price",
   "a movement along the existing curve",
   "a change in a determinant other than the good's own price",
   "a change in quantity supplied",
   "a change in the equilibrium quantity only"], ans=2,
   why="Non-price determinants shift the curve; own price moves along it."),
 dict(q="The substitution effect of a price decrease means consumers", choices=[
   "buy less of the good because it seems lower quality",
   "switch toward the now relatively cheaper good and away from alternatives",
   "buy more of every good in the economy",
   "reduce their total spending",
   "experience a fall in real income"], ans=1,
   why="A cheaper good becomes relatively more attractive than its substitutes."),
 dict(q="The income effect of a price decrease means that", choices=[
   "the consumer's nominal income rises",
   "the consumer's real purchasing power rises, allowing more to be bought",
   "the consumer earns higher wages",
   "the good becomes an inferior good",
   "demand for the good must fall"], ans=1,
   why="A lower price stretches the same income further, raising real purchasing power."),
 dict(q="Diminishing marginal utility helps explain the downward-sloping demand curve because consumers", choices=[
   "will pay less for each additional unit as satisfaction from extra units falls",
   "always value the last unit most",
   "gain more utility from each additional unit",
   "ignore price when consuming",
   "have unlimited income"], ans=0,
   why="Falling extra satisfaction means buyers only take more units at lower prices."),
 dict(q="Market demand is derived by", choices=[
   "averaging all individual demand curves",
   "summing the quantities demanded by all individual consumers at each price",
   "multiplying price by quantity",
   "taking the largest individual demand",
   "subtracting supply from demand"], ans=1,
   why="Market demand is the horizontal sum of individual demands at each price."),
 dict(q="Two goods are substitutes if a rise in the price of one causes", choices=[
   "a decrease in demand for the other",
   "an increase in demand for the other",
   "no change in demand for the other",
   "the other good to become inferior",
   "both goods' supply curves to shift"], ans=1,
   why="Substitutes replace each other, so a pricier X pushes buyers toward Y."),
 dict(q="Two goods are complements if a rise in the price of one causes", choices=[
   "an increase in demand for the other",
   "a decrease in demand for the other",
   "no change in demand for the other",
   "the other good's price to rise",
   "an increase in the supply of the other"], ans=1,
   why="Complements are consumed together, so a pricier X reduces demand for Y."),
 dict(q="Coffee and tea are substitutes. A sharp increase in the price of coffee will most likely", choices=[
   "shift the demand curve for tea to the right",
   "shift the demand curve for tea to the left",
   "cause a movement along the demand curve for tea",
   "leave the tea market unaffected",
   "shift the supply curve for tea to the right"], ans=0,
   why="Buyers substitute toward tea, increasing tea demand at every price."),
 dict(q="Printers and ink cartridges are complements. A fall in the price of printers will most likely", choices=[
   "decrease the demand for ink cartridges",
   "increase the demand for ink cartridges",
   "leave ink cartridge demand unchanged",
   "shift the supply of ink cartridges left",
   "cause a movement along the ink cartridge demand curve"], ans=1,
   why="Cheaper printers mean more printers owned, raising demand for cartridges."),
 dict(q="A normal good is one for which", choices=[
   "demand falls as consumer income rises",
   "demand rises as consumer income rises",
   "demand is unaffected by income",
   "the demand curve slopes upward",
   "there are no substitutes"], ans=1,
   why="Normal goods and income move in the same direction."),
 dict(q="An inferior good is one for which", choices=[
   "demand rises as consumer income rises",
   "demand falls as consumer income rises",
   "quality is objectively poor",
   "the law of demand does not apply",
   "supply is perfectly inelastic"], ans=1,
   why="Inferior goods are bought less as income grows — buyers trade up."),
 dict(q="During a recession in which incomes fall, demand for an inferior good such as generic store-brand food will most likely", choices=[
   "decrease",
   "increase",
   "stay exactly the same",
   "become perfectly elastic",
   "shift the supply curve"], ans=1,
   why="Falling income raises demand for inferior goods."),
 dict(q="If consumers expect the price of a good to rise sharply next month, current demand will most likely", choices=[
   "decrease today",
   "increase today as buyers purchase before the increase",
   "be unaffected",
   "become perfectly inelastic",
   "shift the supply curve rightward"], ans=1,
   why="Expected future price increases pull purchases into the present."),
 dict(q="An increase in the number of buyers in a market will", choices=[
   "shift market demand to the right",
   "shift market demand to the left",
   "cause a movement up along the demand curve",
   "reduce equilibrium price",
   "leave market demand unchanged"], ans=0,
   why="More buyers means a greater quantity demanded at every price."),
 dict(q="Which of the following would cause a movement ALONG a good's demand curve rather than a shift?", choices=[
   "A change in consumer tastes",
   "A change in the good's own price",
   "A change in the price of a substitute",
   "A change in consumer income",
   "A change in the number of buyers"], ans=1,
   why="Own-price changes move along the curve; everything else shifts it."),
 dict(q="A veterinarian's practice sees fewer patients after a new clinic opens nearby offering the same services at a lower price. For the original practice this is", choices=[
   "a decrease in demand caused by a substitute becoming cheaper",
   "a decrease in quantity demanded",
   "an increase in demand",
   "a movement along its own demand curve",
   "an increase in quantity demanded"], ans=0,
   why="The change came from another good's price, not this practice's own, so the whole curve shifts left."),
 dict(q="Demand for a good rises when the price of a substitute rises AND falls when consumer income rises. The good is", choices=[
   "a normal good", "an inferior good", "a complement to income", "a luxury good", "not a good at all"], ans=1,
   why="Demand moving opposite to income is exactly what defines an inferior good."),
 dict(q="At $5 a vendor sells 40 drinks a day; at $4 he sells 50. Between these two points the change is best described as", choices=[
   "an increase in demand",
   "an increase in quantity demanded along an unchanged demand curve",
   "a rightward shift of demand",
   "a leftward shift of demand",
   "a change in tastes"], ans=1,
   why="Only the good's own price changed, so the movement is along the curve."),
 dict(q="Which single event would shift the demand curve for umbrellas to the right?", choices=[
   "a fall in the price of umbrellas",
   "a forecast of an unusually wet season",
   "a rise in the price of umbrellas",
   "a new machine that makes umbrellas more cheaply",
   "a fall in the number of buyers"], ans=1,
   why="Expected weather changes what buyers want at every price; the others move price or supply."),
 dict(q="A good's demand curve shifts right at the same time its price falls. A student concludes the price fall caused the shift. This reasoning is", choices=[
   "correct, since price and demand move together",
   "incorrect, because a good's own price moves quantity demanded along the curve rather than shifting it",
   "correct, because demand always rises when price falls",
   "incorrect, because demand curves never shift",
   "correct only for normal goods"], ans=1,
   why="A change in the good's own price can never be the cause of a shift in its own demand."),
 dict(table=dict(headers=["Price", "Quantity demanded"],
   rows=[["$10", "20"], ["$8", "40"], ["$6", "60"], ["$4", "80"], ["$2", "100"]]),
   q="Using the demand schedule shown, a fall in price from $8 to $6 results in", choices=[
   "a decrease in demand of 20 units",
   "an increase in quantity demanded of 20 units",
   "a rightward shift of the demand curve",
   "an increase in demand of 60 units",
   "no change in quantity demanded"], ans=1,
   why="Quantity demanded rises 40 → 60; an own-price change is a movement, not a shift."),
 dict(table=dict(headers=["Price", "Quantity demanded"],
   rows=[["$10", "20"], ["$8", "40"], ["$6", "60"], ["$4", "80"], ["$2", "100"]]),
   q="Using the same schedule, this demand relationship is", choices=[
   "upward sloping, violating the law of demand",
   "downward sloping, consistent with the law of demand",
   "perfectly inelastic",
   "vertical",
   "impossible to determine"], ans=1,
   why="Quantity demanded rises as price falls — the law of demand."),
 dict(q="'Own-price' in the context of demand refers to", choices=[
   "the price of a substitute good",
   "the price of the good being analyzed itself",
   "the price paid by the producer for inputs",
   "the price after taxes",
   "the price the government sets"], ans=1,
   why="Own-price is the good's own price, the variable on the demand curve's axis."),
 dict(q="A merchant who lowers prices during a slow season and raises them during peak demand is applying", choices=[
   "the law of supply only",
   "the law of demand to make pricing and inventory decisions",
   "a price ceiling",
   "a government mandate",
   "diminishing returns"], ans=1,
   why="Merchants use the price-quantity relationship to manage sales and stock."),
 dict(q="Which of the following would shift the demand curve for hamburgers to the LEFT?", choices=[
   "A decrease in the price of hamburger buns (a complement)",
   "A report that hamburgers are unhealthy, reducing consumer preference",
   "An increase in consumer income, if hamburgers are normal",
   "An increase in the price of chicken sandwiches (a substitute)",
   "An increase in the population of the city"], ans=1,
   why="Weaker tastes reduce demand at every price, shifting the curve left."),
 dict(q="Which of the following would shift the demand curve for new cars to the RIGHT?", choices=[
   "A rise in the price of gasoline, a complement",
   "A fall in consumer income, if cars are normal goods",
   "An increase in the price of new cars",
   "An increase in the number of licensed drivers",
   "An expectation that car prices will fall next year"], ans=3,
   why="More potential buyers raises demand at every price."),
 dict(q="The income effect and the substitution effect can work AGAINST each other when", choices=[
   "the good is a normal good",
   "the good is an inferior good, since a lower price raises real income and buyers may shift away",
   "the good has no substitutes",
   "the price is fixed by law",
   "the good is perfectly elastic"], ans=1,
   why="For inferior goods the income effect pushes the opposite way from substitution."),
 dict(q="If a demand curve shifts rightward, then at every price consumers now wish to buy", choices=[
   "a smaller quantity",
   "a larger quantity",
   "the same quantity",
   "only the equilibrium quantity",
   "nothing at all"], ans=1,
   why="A rightward shift means more is demanded at each price."),
 dict(q="Which statement correctly distinguishes the two concepts?", choices=[
   "A change in demand is a movement along a fixed curve; a change in quantity demanded shifts it",
   "A change in quantity demanded is a movement along a fixed curve; a change in demand shifts it",
   "The two terms mean exactly the same thing",
   "Both involve shifts of the curve",
   "Neither involves price"], ans=1,
   why="Quantity demanded = movement along; demand = shift of the whole curve."),
 dict(q="Marginal utility is", choices=[
   "the total satisfaction from all units consumed",
   "the additional satisfaction from consuming one more unit",
   "the price of the last unit bought",
   "the cost of producing one more unit",
   "always constant across units"], ans=1,
   why="Marginal utility is the extra satisfaction from one additional unit."),
 dict(q="A student buys one backpack but not a second, even though backpacks are useful. This is best explained by", choices=[
   "the law of supply",
   "diminishing marginal utility from the second backpack",
   "an increase in income",
   "a price ceiling",
   "the substitution effect only"], ans=1,
   why="The second backpack adds far less satisfaction than the first."),
 dict(q="A demand curve is drawn holding constant all of the following EXCEPT", choices=[
   "consumer income",
   "the prices of related goods",
   "consumer tastes",
   "the good's own price",
   "the number of buyers"], ans=3,
   why="Own price is the variable plotted, so it is the one thing allowed to vary."),
 dict(q="If both a substitute's price rises AND consumer income rises for a normal good, demand for the good will", choices=[
   "definitely decrease",
   "definitely increase",
   "remain unchanged",
   "become perfectly inelastic",
   "be impossible to predict"], ans=1,
   why="Both changes raise demand, so they reinforce and the curve shifts right."),
 dict(q="If the price of a complement rises AND consumer income falls for a normal good, demand for the good will", choices=[
   "definitely increase",
   "definitely decrease",
   "remain unchanged",
   "shift right",
   "be impossible to predict"], ans=1,
   why="Both effects reduce demand, shifting the curve left."),
 dict(q="Consumer decision-making in the market involves choosing bundles that", choices=[
   "maximize satisfaction subject to income and prices",
   "minimize the number of goods purchased",
   "always spend the entire budget on one good",
   "ignore relative prices",
   "match the government's plan"], ans=0,
   why="Consumers maximize utility under budget and price constraints."),
 dict(q="Which of the following is NOT a determinant of demand?", choices=[
   "Consumer income",
   "Prices of related goods",
   "The cost of producing the good",
   "Consumer expectations",
   "The number of buyers"], ans=2,
   why="Production cost shifts supply, not demand."),
 dict(q="A demand curve for a normal good shifts left when income falls. This is because", choices=[
   "the good's own price rose",
   "lower purchasing power reduces the quantity buyers want at every price",
   "supply decreased",
   "the good became a substitute",
   "marginal utility rose"], ans=1,
   why="Less income means less is demanded at each price for a normal good."),
 dict(q="Suppose the demand for bicycles increases while nothing else changes. In the bicycle market this appears as", choices=[
   "a movement up along the demand curve",
   "a rightward shift of the demand curve",
   "a leftward shift of the supply curve",
   "a movement down along the demand curve",
   "a rotation of the supply curve"], ans=1,
   why="An increase in demand is a rightward shift of the demand curve."),
 dict(q="Which pair of goods are most likely complements?", choices=[
   "Butter and margarine",
   "Peanut butter and jelly",
   "Coke and Pepsi",
   "Bus rides and taxi rides",
   "Tea and coffee"], ans=1,
   why="Complements are consumed together; the rest are substitute pairs."),
 dict(q="Which pair of goods are most likely substitutes?", choices=[
   "Cars and gasoline",
   "Tennis rackets and tennis balls",
   "Beef and chicken",
   "Printers and ink",
   "Phones and phone cases"], ans=2,
   why="Beef and chicken replace each other in consumption."),
 dict(q="A well-functioning market system relies on prices to", choices=[
   "eliminate scarcity entirely",
   "signal information about relative scarcity and coordinate buyers and sellers",
   "guarantee that everyone can afford every good",
   "set production quotas",
   "prevent shifts in demand"], ans=1,
   why="Prices carry information and coordinate independent decisions."),
 dict(q="Suppose a good's price falls from $12 to $9 and quantity demanded rises from 100 to 130. This is best described as", choices=[
   "an increase in demand of 30 units",
   "an increase in quantity demanded of 30 units",
   "a leftward shift of demand",
   "a decrease in demand",
   "an increase in supply"], ans=1,
   why="A price-induced change is a movement along the curve — quantity demanded."),
 dict(q="Which of the following best explains why the demand curve cannot slope upward for ordinary goods?", choices=[
   "Producers refuse to sell at higher prices",
   "At higher prices consumers face reduced purchasing power and cheaper alternatives, so they buy less",
   "Governments forbid it",
   "Supply always increases with price",
   "Marginal utility increases with consumption"], ans=1,
   why="The income and substitution effects both push quantity demanded down as price rises."),
 dict(q="An increase in consumer preference for electric vehicles, with all else constant, will", choices=[
   "shift the EV demand curve right and, at the original price, create a shortage",
   "shift the EV demand curve left",
   "cause a movement down along the EV demand curve",
   "shift the EV supply curve right",
   "have no effect on the EV market"], ans=0,
   why="Stronger tastes raise demand; at the old price quantity demanded now exceeds quantity supplied."),
 dict(q="Which of the following statements about demand is TRUE?", choices=[
   "Demand and quantity demanded always change together in the same way",
   "Only a change in the good's own price can change demand",
   "Demand describes an entire relationship between price and quantity, not a single number",
   "Demand curves shift whenever price changes",
   "Market demand is smaller than any individual demand"], ans=2,
   why="Demand is the whole schedule/curve; quantity demanded is one point on it."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
