# 2.2 Supply — 50 questions
TOPIC = ("2.2", "Supply", 2)
QUESTIONS = [
 dict(q="The law of supply states that, all else equal,", choices=[
   "as the price of a good rises, the quantity supplied of that good rises",
   "as the price of a good rises, the quantity supplied falls",
   "supply and price are unrelated",
   "producers always supply the same quantity",
   "quantity supplied depends only on costs"], ans=0,
   why="Price and quantity supplied move in the same direction."),
 dict(q="The supply curve slopes upward primarily because", choices=[
   "consumers demand more at higher prices",
   "higher prices make it profitable to produce additional units whose marginal costs are higher",
   "governments require it",
   "firms have unlimited capacity",
   "costs fall as output rises"], ans=1,
   why="Rising marginal cost means firms need a higher price to justify extra output."),
 dict(q="A change in QUANTITY SUPPLIED results from a change in", choices=[
   "input prices",
   "the good's own price",
   "technology",
   "the number of sellers",
   "producer expectations"], ans=1,
   why="Own price moves you along the supply curve; everything else shifts it."),
 dict(q="A change in SUPPLY (a shift of the curve) results from", choices=[
   "a change in the good's own price",
   "a change in a non-price determinant such as input costs or technology",
   "a movement along the curve",
   "a change in quantity demanded",
   "a change in the equilibrium price only"], ans=1,
   why="Non-price determinants shift supply."),
 dict(q="An improvement in production technology will", choices=[
   "shift the supply curve left",
   "shift the supply curve right",
   "cause a movement up along the supply curve",
   "shift the demand curve left",
   "leave supply unchanged"], ans=1,
   why="Better technology lowers costs, so more is supplied at every price."),
 dict(q="An increase in the price of a key input, such as steel for car makers, will", choices=[
   "shift the supply of cars to the right",
   "shift the supply of cars to the left",
   "cause a movement along the car supply curve",
   "increase the supply of cars at every price",
   "shift the demand for cars left"], ans=1,
   why="Higher input costs reduce supply at every price."),
 dict(q="An increase in the number of sellers in a market will", choices=[
   "shift market supply right",
   "shift market supply left",
   "cause a movement along market supply",
   "reduce quantity supplied at every price",
   "shift demand right"], ans=0,
   why="More producers means more supplied at each price."),
 dict(q="If producers expect the price of their good to be much higher next month, current supply will most likely", choices=[
   "increase today",
   "decrease today as producers hold inventory back for the higher future price",
   "be unaffected",
   "become perfectly elastic",
   "shift demand instead"], ans=1,
   why="Withholding output for a better future price reduces supply today."),
 dict(q="A per-unit tax imposed on producers will", choices=[
   "shift the supply curve right",
   "shift the supply curve left (upward by the amount of the tax)",
   "shift the demand curve right",
   "cause only a movement along supply",
   "have no effect on the market"], ans=1,
   why="A tax raises the effective cost of each unit, decreasing supply."),
 dict(q="A per-unit subsidy paid to producers will", choices=[
   "shift the supply curve left",
   "shift the supply curve right",
   "shift the demand curve left",
   "have no effect on supply",
   "make supply perfectly inelastic"], ans=1,
   why="A subsidy lowers effective production cost, increasing supply."),
 dict(q="A supply schedule is", choices=[
   "a list of quantities producers will offer at each of various prices",
   "a firm's production timetable",
   "a list of consumer preferences",
   "a graph of utility against quantity",
   "the government's tax schedule"], ans=0,
   why="A supply schedule tabulates quantity supplied at each price."),
 dict(q="Market supply is found by", choices=[
   "averaging individual firms' supply curves",
   "summing the quantities supplied by all firms at each price",
   "taking the most efficient firm's supply",
   "subtracting demand from supply",
   "multiplying price by output"], ans=1,
   why="Market supply is the horizontal sum of individual firm supplies."),
 dict(q="Which of the following causes a movement ALONG the supply curve?", choices=[
   "A new production technology",
   "A change in the good's own price",
   "A change in input prices",
   "A change in the number of firms",
   "A new per-unit tax"], ans=1,
   why="Only own-price changes move along a fixed supply curve."),
 dict(table=dict(headers=["Price", "Quantity supplied"],
   rows=[["$2", "10"], ["$4", "30"], ["$6", "50"], ["$8", "70"], ["$10", "90"]]),
   q="Using the supply schedule shown, a rise in price from $4 to $8 causes", choices=[
   "an increase in supply of 40 units",
   "an increase in quantity supplied of 40 units",
   "a rightward shift of supply",
   "a decrease in quantity supplied",
   "no change"], ans=1,
   why="30 → 70 is a movement along the curve caused by the good's own price."),
 dict(q="Which of the following would shift the supply of wheat to the RIGHT?", choices=[
   "A drought destroying much of the crop",
   "An increase in the wages paid to farm workers",
   "Unusually favorable growing weather",
   "A new tax on wheat producers",
   "A decrease in the number of wheat farms"], ans=2,
   why="Good weather raises output at every price, increasing supply."),
 dict(q="Which of the following would shift the supply of gasoline to the LEFT?", choices=[
   "A new refining technology that cuts costs",
   "A large increase in the price of crude oil",
   "An increase in the number of refineries",
   "A government subsidy to refiners",
   "A decrease in the wages of refinery workers"], ans=1,
   why="A costlier key input decreases supply."),
 dict(q="The supply curve for a firm reflects, at each price, the quantity at which", choices=[
   "average total cost is minimized",
   "the firm is willing to produce given its marginal costs",
   "consumer utility is maximized",
   "total revenue is zero",
   "all fixed costs are recovered"], ans=1,
   why="Supply reflects firms' willingness to produce given rising marginal cost."),
 dict(q="Producers of both corn and soybeans find the price of soybeans has risen sharply. The supply of corn will most likely", choices=[
   "increase, shifting right",
   "decrease, shifting left as land moves into soybeans",
   "remain unchanged",
   "become perfectly elastic",
   "shift because corn's own price changed"], ans=1,
   why="Resources shift to the more profitable alternative product, cutting corn supply."),
 dict(q="A supply curve is drawn holding constant all of the following EXCEPT", choices=[
   "input prices",
   "technology",
   "the good's own price",
   "the number of sellers",
   "producer expectations"], ans=2,
   why="Own price is the variable on the axis, so it is allowed to vary."),
 dict(q="If supply shifts leftward, then at every price producers now offer", choices=[
   "a larger quantity",
   "a smaller quantity",
   "the same quantity",
   "only the equilibrium quantity",
   "an unlimited quantity"], ans=1,
   why="A leftward shift means less supplied at each price."),
 dict(q="Which statement correctly describes the difference between the two supply concepts?", choices=[
   "A change in supply is a movement along the curve",
   "A change in quantity supplied is a movement along the curve; a change in supply shifts it",
   "They are identical concepts",
   "Both are caused by own-price changes",
   "Neither involves price"], ans=1,
   why="Quantity supplied = movement along; supply = shift of the curve."),
 dict(q="The main reason a firm's marginal cost rises as output expands in the short run is", choices=[
   "economies of scale",
   "diminishing marginal returns to the variable input",
   "falling input prices",
   "increasing consumer demand",
   "government regulation"], ans=1,
   why="With fixed capital, added workers eventually add less output, raising marginal cost."),
 dict(q="A decrease in the wage rate paid by a firm's industry will most likely", choices=[
   "shift industry supply left",
   "shift industry supply right",
   "shift demand left",
   "cause a movement along supply only",
   "raise marginal costs"], ans=1,
   why="Lower input costs increase supply at every price."),
 dict(q="Which of the following is a determinant of supply rather than demand?", choices=[
   "Consumer income",
   "Consumer tastes",
   "Input prices",
   "Prices of substitute goods in consumption",
   "The number of buyers"], ans=2,
   why="Input prices affect producers' costs and shift supply."),
 dict(q="If a hurricane destroys many factories in an industry, the industry's supply curve will", choices=[
   "shift right",
   "shift left",
   "become horizontal",
   "not move, since price has not changed",
   "shift only if demand also shifts"], ans=1,
   why="Fewer productive facilities means less supplied at every price."),
 dict(q="Which of the following would cause the supply curve for smartphones to shift right?", choices=[
   "A rise in the wages of assembly workers",
   "A new tariff on imported components",
   "An automation breakthrough that lowers unit costs",
   "The exit of several manufacturers",
   "A new per-unit tax on smartphones"], ans=2,
   why="Cost-reducing technology increases supply."),
 dict(q="At a price of $0, the quantity supplied of most goods would be", choices=[
   "unlimited",
   "zero or near zero, since producers cannot cover costs",
   "the same as at any other price",
   "equal to quantity demanded",
   "determined by consumer tastes"], ans=1,
   why="Producers will not supply when price does not cover costs."),
 dict(q="Producer expectations affect supply because firms", choices=[
   "cannot store any output",
   "may adjust current production and inventories based on anticipated future prices",
   "must follow government quotas",
   "always ignore the future",
   "only respond to current costs"], ans=1,
   why="Expected future prices change the attractiveness of selling now versus later."),
 dict(q="Which of the following statements about the supply curve is TRUE?", choices=[
   "It shows the maximum consumers will pay",
   "It shows quantities producers are willing and able to offer at each price",
   "It always slopes downward",
   "It shifts when the good's own price changes",
   "It is identical to the demand curve"], ans=1,
   why="Supply is producers' willingness and ability to sell at each price."),
 dict(q="If both input prices fall AND the number of firms increases, market supply will", choices=[
   "definitely decrease",
   "definitely increase",
   "remain unchanged",
   "become vertical",
   "be impossible to predict"], ans=1,
   why="Both changes raise supply, reinforcing a rightward shift."),
 dict(q="If a new tax is imposed AND several firms exit the industry, market supply will", choices=[
   "definitely increase",
   "definitely decrease",
   "remain unchanged",
   "shift right",
   "be impossible to predict"], ans=1,
   why="Both changes reduce supply, shifting the curve left."),
 dict(q="Suppose the price of a good rises from $5 to $7 and quantity supplied rises from 200 to 260. This is", choices=[
   "an increase in supply of 60 units",
   "an increase in quantity supplied of 60 units",
   "a rightward shift of the supply curve",
   "a decrease in supply",
   "an increase in demand"], ans=1,
   why="An own-price change produces a movement along supply."),
 dict(q="A government regulation requiring expensive new pollution controls on producers will most likely", choices=[
   "shift supply right",
   "shift supply left by raising production costs",
   "shift demand right",
   "leave the market unchanged",
   "make supply perfectly elastic"], ans=1,
   why="Compliance costs raise production costs, decreasing supply."),
 dict(q="Which of the following pairs both shift SUPPLY?", choices=[
   "Consumer income and consumer tastes",
   "Input prices and technology",
   "The number of buyers and consumer expectations",
   "Prices of substitutes in consumption and income",
   "Population growth and advertising"], ans=1,
   why="Input costs and technology are classic supply shifters."),
 dict(q="If the supply curve shifts right while demand is unchanged, the equilibrium price will", choices=[
   "rise", "fall", "stay the same", "become undefined", "always double"], ans=1,
   why="More supply at every price pushes the equilibrium price down."),
 dict(q="If the supply curve shifts left while demand is unchanged, the equilibrium quantity will", choices=[
   "rise", "fall", "stay the same", "become zero", "be indeterminate"], ans=1,
   why="Reduced supply lowers the quantity traded in equilibrium."),
 dict(q="Firms in a competitive market decide how much to supply by comparing", choices=[
   "price with marginal cost",
   "total revenue with fixed cost",
   "average revenue with average fixed cost",
   "consumer utility with price",
   "market share with rivals"], ans=0,
   why="Competitive firms expand output while price exceeds marginal cost."),
 dict(q="Which of the following describes the relationship between the supply curve and marginal cost for a competitive firm?", choices=[
   "They are unrelated",
   "The firm's supply curve is essentially its marginal cost curve above average variable cost",
   "Supply is the inverse of marginal cost",
   "Supply is the average total cost curve",
   "Supply is fixed regardless of cost"], ans=1,
   why="A competitive firm supplies along MC above the shutdown point."),
 dict(q="Which event would NOT shift the supply of coffee?", choices=[
   "A frost destroying coffee plants",
   "A rise in the price of coffee itself",
   "A new tax on coffee growers",
   "Cheaper fertilizer for coffee farms",
   "New coffee farms entering the market"], ans=1,
   why="The good's own price moves along the curve rather than shifting it."),
 dict(q="A firm producing both leather jackets and leather boots sees the price of boots rise. Its supply of jackets will most likely", choices=[
   "increase",
   "decrease, as it shifts resources to boots",
   "stay identical",
   "become perfectly inelastic",
   "shift only if jacket prices change"], ans=1,
   why="Substitutes in production compete for the same resources."),
 dict(q="Which of the following best explains why quantity supplied rises with price in the short run?", choices=[
   "Firms have unlimited capacity at constant cost",
   "A higher price covers the higher marginal cost of additional units, making expansion profitable",
   "Consumers demand more",
   "Fixed costs fall as output rises",
   "The government mandates production increases"], ans=1,
   why="Higher prices justify producing units whose marginal cost is higher."),
 dict(q="An increase in the productivity of workers in an industry will", choices=[
   "shift supply left",
   "shift supply right by lowering the cost per unit of output",
   "shift demand right",
   "raise marginal costs",
   "cause only a movement along the supply curve"], ans=1,
   why="More output per worker lowers unit cost, increasing supply."),
 dict(q="If a supply curve is vertical, it indicates that quantity supplied", choices=[
   "rises sharply with price",
   "does not respond to price at all",
   "falls as price rises",
   "is unlimited",
   "equals quantity demanded"], ans=1,
   why="A vertical supply curve is perfectly inelastic — quantity is fixed."),
 dict(q="Supply is best defined as", choices=[
   "the amount a firm produces regardless of price",
   "the quantities producers are willing and able to sell at each possible price over a period of time",
   "the total inventory a firm holds",
   "the amount consumers wish to buy",
   "the market equilibrium quantity"], ans=1,
   why="Supply is the whole price-quantity relationship for sellers."),
 dict(q="A decrease in supply combined with unchanged demand will cause", choices=[
   "price to fall and quantity to rise",
   "price to rise and quantity to fall",
   "both price and quantity to rise",
   "both price and quantity to fall",
   "no change in either"], ans=1,
   why="Leftward supply shift raises price and lowers quantity."),
 dict(q="Which of the following is the best example of a change in quantity supplied?", choices=[
   "A bakery expands output when bread prices rise",
   "A bakery buys a cheaper flour supplier",
   "New bakeries open in town",
   "A tax is imposed on bakeries",
   "A bakery adopts a faster oven"], ans=0,
   why="Responding to the good's own price is a movement along supply."),
 dict(q="Which of the following is the best example of a change in supply?", choices=[
   "Producers sell more when the market price rises",
   "A cost-saving invention lets producers make more at every price",
   "Consumers buy more at lower prices",
   "Equilibrium quantity increases",
   "A firm moves up its existing supply curve"], ans=1,
   why="A non-price change affecting output at every price shifts supply."),
 dict(q="Why does a per-unit tax shift supply upward by exactly the amount of the tax?", choices=[
   "Because demand falls by that amount",
   "Because producers now require the old price plus the tax to supply the same quantity",
   "Because the government sets the new price",
   "Because marginal cost is unaffected",
   "Because consumers pay the entire tax"], ans=1,
   why="The tax adds to the price sellers must receive per unit."),
 dict(q="Two markets are identical except that Market A's producers can easily expand capacity and Market B's cannot. Compared with B, A's supply curve will be", choices=[
   "steeper and less responsive to price",
   "flatter and more responsive to price",
   "vertical",
   "downward sloping",
   "identical"], ans=1,
   why="Easier expansion means quantity supplied responds more to price."),
 dict(q="Which of the following statements about supply and demand determinants is correct?", choices=[
   "Input prices shift demand; consumer income shifts supply",
   "Technology shifts supply; consumer tastes shift demand",
   "Both technology and tastes shift supply",
   "Neither shifts either curve",
   "The good's own price shifts both curves"], ans=1,
   why="Technology is a supply shifter; tastes are a demand shifter."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
