# 2.6 Market Equilibrium and Consumer and Producer Surplus — 50 questions
# Surplus arithmetic verified: triangle area = 1/2 * base * height.
TOPIC = ("2.6", "Market Equilibrium and Consumer and Producer Surplus", 2)
QUESTIONS = [
 dict(q="Market equilibrium occurs at the price and quantity where", choices=[
   "quantity demanded equals quantity supplied",
   "total revenue is maximized",
   "consumer surplus is zero",
   "the government sets the price",
   "marginal cost equals zero"], ans=0,
   why="Equilibrium is where the demand and supply curves intersect."),
 dict(q="At the equilibrium price there is", choices=[
   "a shortage", "a surplus", "neither a shortage nor a surplus", "deadweight loss", "excess demand"], ans=2,
   why="The market clears — quantity demanded and supplied are equal."),
 dict(q="Consumer surplus is", choices=[
   "the amount consumers pay for a good",
   "the difference between what consumers are willing to pay and what they actually pay",
   "the profit firms earn",
   "total revenue minus total cost",
   "the quantity consumers buy"], ans=1,
   why="Consumer surplus is willingness to pay minus price paid."),
 dict(q="Producer surplus is", choices=[
   "the total revenue a firm earns",
   "the difference between the price producers receive and their minimum acceptable price",
   "the same as accounting profit",
   "the quantity produced",
   "consumer willingness to pay"], ans=1,
   why="Producer surplus is price received minus the marginal cost of supplying."),
 dict(q="On a supply and demand graph, consumer surplus is the area", choices=[
   "below the demand curve and above the price, up to the quantity traded",
   "above the supply curve and below the price",
   "below the supply curve",
   "between the axes and the equilibrium point only",
   "above the demand curve"], ans=0,
   why="Consumer surplus lies between the demand curve and the price line."),
 dict(q="On a supply and demand graph, producer surplus is the area", choices=[
   "below the demand curve and above the price",
   "above the supply curve and below the price, up to the quantity traded",
   "above the demand curve",
   "below the supply curve and below price",
   "the entire area under demand"], ans=1,
   why="Producer surplus lies between the price line and the supply curve."),
 dict(q="Total surplus (economic surplus) equals", choices=[
   "consumer surplus minus producer surplus",
   "consumer surplus plus producer surplus",
   "total revenue minus total cost",
   "quantity times price",
   "producer surplus only"], ans=1,
   why="Total surplus sums the gains to buyers and sellers."),
 dict(q="In a competitive market free of intervention, equilibrium maximizes", choices=[
   "consumer surplus only",
   "producer surplus only",
   "total surplus",
   "government revenue",
   "deadweight loss"], ans=2,
   why="The competitive equilibrium achieves allocative efficiency, maximizing total surplus."),
 dict(q="Allocative efficiency in a market occurs where", choices=[
   "price equals marginal cost, so marginal benefit equals marginal cost",
   "total revenue is maximized",
   "producer surplus is maximized",
   "quantity is largest",
   "price is lowest"], ans=0,
   why="At P = MC the value of the last unit to buyers equals its cost."),
 dict(q="A consumer willing to pay $50 buys a good at the market price of $30. Her consumer surplus is", choices=[
   "$80", "$50", "$30", "$20", "$0"], ans=3,
   why="$50 − $30 = $20."),
 dict(q="A producer willing to sell for a minimum of $12 sells at the market price of $20. Producer surplus is", choices=[
   "$32", "$20", "$12", "$8", "$0"], ans=3,
   why="$20 − $12 = $8."),
 dict(q="A linear demand curve hits the vertical axis at $60, and equilibrium price is $20 with quantity 40. Consumer surplus equals", choices=[
   "$800", "$1,200", "$400", "$2,400", "$600"], ans=0,
   why="½ × 40 × ($60 − $20) = ½ × 40 × 40 = $800."),
 dict(q="A linear supply curve starts at $10 on the vertical axis, and equilibrium price is $30 with quantity 50. Producer surplus equals", choices=[
   "$1,500", "$1,000", "$500", "$750", "$250"], ans=2,
   why="½ × 50 × ($30 − $10) = ½ × 50 × 20 = $500."),
 dict(q="If demand's vertical intercept is $100, supply's is $20, and equilibrium quantity is 40, total surplus equals", choices=[
   "$3,200", "$1,600", "$800", "$4,000", "$2,400"], ans=1,
   why="½ × 40 × ($100 − $20) = ½ × 40 × 80 = $1,600."),
 dict(q="When the market price is ABOVE equilibrium, the market experiences", choices=[
   "a shortage", "a surplus (excess supply)", "equilibrium", "deadweight loss only", "excess demand"], ans=1,
   why="Quantity supplied exceeds quantity demanded above the equilibrium price."),
 dict(q="When the market price is BELOW equilibrium, the market experiences", choices=[
   "a surplus", "a shortage (excess demand)", "equilibrium", "maximum total surplus", "excess supply"], ans=1,
   why="Quantity demanded exceeds quantity supplied below equilibrium."),
 dict(q="A surplus in an unregulated market creates pressure for price to", choices=[
   "rise", "fall", "stay fixed", "become zero", "double"], ans=1,
   why="Unsold goods push sellers to cut prices toward equilibrium."),
 dict(q="A shortage in an unregulated market creates pressure for price to", choices=[
   "fall", "rise", "stay fixed", "become zero", "halve"], ans=1,
   why="Competing buyers bid the price up toward equilibrium."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$10", "20", "80"], ["$8", "40", "60"], ["$6", "60", "60"], ["$4", "80", "40"], ["$2", "100", "20"]]),
   q="Using the table, the equilibrium price and quantity are", choices=[
   "$10 and 20", "$8 and 40", "$6 and 60", "$4 and 40", "$2 and 100"], ans=2,
   why="At $6, quantity demanded equals quantity supplied at 60."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$10", "20", "80"], ["$8", "40", "60"], ["$6", "60", "60"], ["$4", "80", "40"], ["$2", "100", "20"]]),
   q="Using the same table, at a price of $8 the market has", choices=[
   "a shortage of 20 units",
   "a surplus of 20 units",
   "equilibrium",
   "a shortage of 40 units",
   "a surplus of 40 units"], ans=1,
   why="Quantity supplied 60 exceeds quantity demanded 40 by 20 units."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$10", "20", "80"], ["$8", "40", "60"], ["$6", "60", "60"], ["$4", "80", "40"], ["$2", "100", "20"]]),
   q="Using the same table, at a price of $4 the market has", choices=[
   "a surplus of 40 units",
   "a shortage of 40 units",
   "equilibrium",
   "a surplus of 80 units",
   "a shortage of 20 units"], ans=1,
   why="Quantity demanded 80 exceeds quantity supplied 40 by 40 units."),
 dict(q="Deadweight loss is best defined as", choices=[
   "the revenue government collects from a tax",
   "the loss of total surplus from producing a quantity other than the efficient one",
   "the total cost of production",
   "consumer surplus alone",
   "the profit firms lose to competitors"], ans=1,
   why="Deadweight loss is surplus destroyed by an inefficient quantity."),
 dict(q="At the competitive equilibrium quantity, deadweight loss is", choices=[
   "at its maximum", "zero", "equal to consumer surplus", "equal to producer surplus", "negative"], ans=1,
   why="Efficient output leaves no unexploited gains from trade."),
 dict(q="Consumer surplus increases when", choices=[
   "the market price rises",
   "the market price falls, all else equal",
   "supply decreases",
   "demand decreases",
   "a price floor is imposed above equilibrium"], ans=1,
   why="A lower price widens the gap between willingness to pay and price paid."),
 dict(q="Producer surplus increases when", choices=[
   "the market price falls",
   "the market price rises, all else equal",
   "costs rise",
   "demand falls",
   "a price ceiling is imposed below equilibrium"], ans=1,
   why="A higher price widens the gap between price received and minimum acceptable price."),
 dict(q="An increase in demand with supply unchanged will", choices=[
   "raise equilibrium price and quantity",
   "lower equilibrium price and quantity",
   "raise price and lower quantity",
   "lower price and raise quantity",
   "leave the equilibrium unchanged"], ans=0,
   why="A rightward demand shift raises both equilibrium price and quantity."),
 dict(q="A decrease in supply with demand unchanged will", choices=[
   "lower price and raise quantity",
   "raise price and lower quantity",
   "raise both price and quantity",
   "lower both price and quantity",
   "leave price unchanged"], ans=1,
   why="A leftward supply shift raises price and reduces quantity."),
 dict(q="The demand curve can be interpreted as showing, for each unit,", choices=[
   "the marginal cost of production",
   "the marginal benefit or maximum willingness to pay of buyers",
   "the firm's profit",
   "total surplus",
   "government revenue"], ans=1,
   why="Demand traces marginal benefit / willingness to pay."),
 dict(q="The supply curve can be interpreted as showing, for each unit,", choices=[
   "buyers' willingness to pay",
   "the marginal cost of producing that unit",
   "consumer surplus",
   "total revenue",
   "the tax rate"], ans=1,
   why="Supply traces producers' marginal cost."),
 dict(q="If a market produces LESS than the equilibrium quantity, then for the units not produced", choices=[
   "marginal cost exceeds marginal benefit",
   "marginal benefit exceeds marginal cost, so surplus is lost",
   "surplus is maximized",
   "producers gain",
   "the market is efficient"], ans=1,
   why="Underproduction forgoes trades whose benefit exceeds cost — deadweight loss."),
 dict(q="If a market produces MORE than the equilibrium quantity, then for the extra units", choices=[
   "marginal benefit exceeds marginal cost",
   "marginal cost exceeds marginal benefit, reducing total surplus",
   "total surplus rises",
   "there is no deadweight loss",
   "consumer surplus is maximized"], ans=1,
   why="Overproduction adds units costing more than they are worth."),
 dict(q="A technological improvement that lowers production costs will", choices=[
   "decrease consumer surplus",
   "increase consumer surplus as price falls and quantity rises",
   "leave total surplus unchanged",
   "create deadweight loss",
   "shift demand left"], ans=1,
   why="Increased supply lowers price and expands trade, raising consumer surplus."),
 dict(q="Suppose equilibrium price is $15 and a buyer values the good at exactly $15. That buyer's consumer surplus is", choices=[
   "$15", "$30", "$0", "cannot be determined", "negative"], ans=2,
   why="The marginal buyer is indifferent — surplus on that unit is zero."),
 dict(q="Which of the following will increase TOTAL surplus in a competitive market?", choices=[
   "A binding price ceiling",
   "A binding price floor",
   "A per-unit tax",
   "A technological advance that increases supply",
   "A production quota below equilibrium"], ans=3,
   why="Greater supply expands mutually beneficial trade; the others restrict it."),
 dict(q="In equilibrium, the last unit traded has the property that", choices=[
   "willingness to pay far exceeds marginal cost",
   "willingness to pay equals marginal cost",
   "marginal cost is zero",
   "consumer surplus is maximized on that unit",
   "producer surplus is zero for all units"], ans=1,
   why="At the efficient quantity, marginal benefit equals marginal cost."),
 dict(q="Both demand and supply increase simultaneously. The effect on equilibrium quantity is", choices=[
   "an unambiguous increase",
   "an unambiguous decrease",
   "indeterminate",
   "always zero",
   "a decrease then increase"], ans=0,
   why="Both shifts push quantity up; only the price effect is ambiguous."),
 dict(q="Both demand and supply increase simultaneously. The effect on equilibrium PRICE is", choices=[
   "an unambiguous increase",
   "an unambiguous decrease",
   "indeterminate, depending on the relative sizes of the shifts",
   "always zero",
   "always a doubling"], ans=2,
   why="Demand pushes price up while supply pushes it down — the net effect depends on magnitudes."),
 dict(q="Demand increases while supply decreases. The effect on equilibrium price is", choices=[
   "an unambiguous increase",
   "an unambiguous decrease",
   "indeterminate",
   "always zero",
   "a fall then a rise"], ans=0,
   why="Both shifts raise price; the quantity effect is ambiguous."),
 dict(q="Demand increases while supply decreases. The effect on equilibrium quantity is", choices=[
   "an unambiguous increase",
   "an unambiguous decrease",
   "indeterminate, depending on the relative shift sizes",
   "always zero",
   "always negative"], ans=2,
   why="Demand raises quantity while supply lowers it — magnitudes decide."),
 dict(q="A market in which price is free to adjust will tend to eliminate shortages and surpluses because", choices=[
   "the government intervenes",
   "price changes alter quantity demanded and supplied until they are equal",
   "supply is fixed",
   "consumers stop buying",
   "firms exit the market"], ans=1,
   why="Price acts as the self-correcting signal that clears the market."),
 dict(q="Which statement about consumer surplus is TRUE?", choices=[
   "It equals the total amount spent on a good",
   "It measures the net benefit buyers receive beyond what they pay",
   "It is always zero in competitive markets",
   "It rises when price rises",
   "It equals producer surplus by definition"], ans=1,
   why="Consumer surplus is the net gain to buyers from trading."),
 dict(q="A rightward shift of supply with unchanged demand causes producer surplus to", choices=[
   "always increase",
   "always decrease",
   "change ambiguously — price falls but quantity rises",
   "become zero",
   "equal consumer surplus"], ans=2,
   why="Lower price cuts surplus per unit while greater quantity adds units."),
 dict(q="The efficiency of the competitive equilibrium means that", choices=[
   "everyone earns the same income",
   "no reallocation could make someone better off without making someone else worse off",
   "producers earn maximum profit",
   "prices are as low as possible",
   "all consumers pay the same willingness to pay"], ans=1,
   why="Maximum total surplus is the Pareto-efficient outcome."),
 dict(q="Equilibrium in a market is described as 'self-correcting' because", choices=[
   "government adjusts prices",
   "shortages and surpluses generate price pressures that restore balance",
   "supply never changes",
   "demand is fixed",
   "firms coordinate output"], ans=1,
   why="Excess demand or supply moves price back toward equilibrium."),
 dict(q="A buyer's willingness to pay is best described as", choices=[
   "the price actually paid",
   "the maximum amount the buyer would give up rather than go without the good",
   "the seller's cost",
   "the market price",
   "the average of all buyers' valuations"], ans=1,
   why="Willingness to pay is the buyer's maximum reservation price."),
 dict(q="A seller's cost, in the surplus framework, is", choices=[
   "the price received",
   "the minimum amount the seller must receive to be willing to sell",
   "total revenue",
   "the buyer's valuation",
   "government revenue"], ans=1,
   why="Seller cost is the reservation price below which no sale occurs."),
 dict(q="If a market moves from equilibrium to producing 20% less output, total surplus will", choices=[
   "increase", "decrease by the deadweight loss of the forgone trades", "stay the same", "become negative", "equal producer surplus"], ans=1,
   why="Forgone mutually beneficial trades destroy surplus."),
 dict(q="Which of the following statements about equilibrium is FALSE?", choices=[
   "At equilibrium there is no tendency for price to change",
   "At equilibrium quantity demanded equals quantity supplied",
   "At equilibrium total surplus is maximized in a competitive market",
   "At equilibrium consumer surplus is always larger than producer surplus",
   "At equilibrium the market clears"], ans=3,
   why="The split between consumer and producer surplus depends on elasticities, not a rule."),
 dict(q="If the equilibrium price of a good rises because demand increased, consumer surplus", choices=[
   "definitely increases",
   "may rise or fall — buyers pay more per unit but more units are traded and the curve has shifted",
   "definitely falls to zero",
   "is unaffected",
   "equals producer surplus"], ans=1,
   why="With a shifted demand curve, the surplus comparison is not a simple price effect."),
 dict(q="The primary reason competitive market equilibrium is called 'efficient' in AP Microeconomics is that", choices=[
   "it produces the lowest possible price",
   "it maximizes the sum of consumer and producer surplus with zero deadweight loss",
   "it guarantees equal distribution",
   "it maximizes firm profits",
   "it eliminates scarcity"], ans=1,
   why="Efficiency here means maximum total surplus, not fairness or low prices."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
