# 2.7 Market Disequilibrium and Changes in Equilibrium — 50 questions
TOPIC = ("2.7", "Market Disequilibrium and Changes in Equilibrium", 2)
QUESTIONS = [
 dict(q="Market disequilibrium exists whenever", choices=[
   "quantity demanded does not equal quantity supplied at the prevailing price",
   "the market price equals the equilibrium price",
   "total surplus is maximized",
   "supply and demand both shift",
   "firms earn zero profit"], ans=0,
   why="Disequilibrium means the market has not cleared."),
 dict(q="Excess demand is another name for", choices=[
   "a surplus", "a shortage", "equilibrium", "deadweight loss", "producer surplus"], ans=1,
   why="When quantity demanded exceeds quantity supplied there is a shortage."),
 dict(q="Excess supply is another name for", choices=[
   "a shortage", "a surplus", "equilibrium", "consumer surplus", "market clearing"], ans=1,
   why="Quantity supplied exceeding quantity demanded is a surplus."),
 dict(q="An increase in demand, holding supply constant, causes equilibrium price to ___ and quantity to ___.", choices=[
   "rise; rise", "rise; fall", "fall; rise", "fall; fall", "stay the same; rise"], ans=0,
   why="A rightward demand shift moves along supply, raising both price and quantity."),
 dict(q="A decrease in demand, holding supply constant, causes equilibrium price to ___ and quantity to ___.", choices=[
   "rise; rise", "rise; fall", "fall; rise", "fall; fall", "stay the same; fall"], ans=3,
   why="A leftward demand shift lowers both equilibrium price and quantity."),
 dict(q="An increase in supply, holding demand constant, causes equilibrium price to ___ and quantity to ___.", choices=[
   "rise; rise", "rise; fall", "fall; rise", "fall; fall", "stay the same; rise"], ans=2,
   why="A rightward supply shift lowers price and raises quantity."),
 dict(q="A decrease in supply, holding demand constant, causes equilibrium price to ___ and quantity to ___.", choices=[
   "rise; rise", "rise; fall", "fall; rise", "fall; fall", "fall; stay the same"], ans=1,
   why="A leftward supply shift raises price and lowers quantity."),
 dict(q="If both demand and supply increase, equilibrium quantity will", choices=[
   "definitely increase",
   "definitely decrease",
   "be indeterminate",
   "not change",
   "fall to zero"], ans=0,
   why="Both shifts raise quantity; the price effect is what is ambiguous."),
 dict(q="If both demand and supply increase, equilibrium price will", choices=[
   "definitely increase",
   "definitely decrease",
   "be indeterminate without knowing which shift is larger",
   "not change",
   "double"], ans=2,
   why="Demand pushes price up, supply pushes it down — magnitudes decide."),
 dict(q="If both demand and supply decrease, equilibrium quantity will", choices=[
   "definitely increase",
   "definitely decrease",
   "be indeterminate",
   "not change",
   "rise then fall"], ans=1,
   why="Both shifts reduce quantity traded."),
 dict(q="If both demand and supply decrease, equilibrium price will", choices=[
   "definitely increase",
   "definitely decrease",
   "be indeterminate",
   "not change",
   "always fall by half"], ans=2,
   why="Falling demand lowers price while falling supply raises it."),
 dict(q="If demand decreases and supply increases, equilibrium price will", choices=[
   "definitely increase",
   "definitely decrease",
   "be indeterminate",
   "not change",
   "rise slightly"], ans=1,
   why="Both changes push price down."),
 dict(q="If demand decreases and supply increases, equilibrium quantity will", choices=[
   "definitely increase",
   "definitely decrease",
   "be indeterminate, depending on shift magnitudes",
   "not change",
   "become zero"], ans=2,
   why="Falling demand cuts quantity while rising supply raises it."),
 dict(q="A binding price ceiling is set", choices=[
   "above the equilibrium price",
   "below the equilibrium price",
   "exactly at equilibrium",
   "at zero",
   "above the demand curve"], ans=1,
   why="Only a ceiling below equilibrium restricts the market and binds."),
 dict(q="A binding price ceiling creates", choices=[
   "a surplus", "a persistent shortage", "equilibrium", "excess supply", "higher producer surplus"], ans=1,
   why="Below equilibrium, quantity demanded exceeds quantity supplied."),
 dict(q="A binding price floor is set", choices=[
   "below equilibrium", "above the equilibrium price", "at equilibrium", "at zero", "below marginal cost"], ans=1,
   why="Only a floor above equilibrium binds."),
 dict(q="A binding price floor creates", choices=[
   "a shortage", "a persistent surplus", "equilibrium", "excess demand", "lower producer surplus"], ans=1,
   why="Above equilibrium, quantity supplied exceeds quantity demanded."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$12", "30", "90"], ["$10", "45", "75"], ["$8", "60", "60"], ["$6", "75", "45"], ["$4", "90", "30"]]),
   q="Using the table, if the government sets a price ceiling of $6, the result is", choices=[
   "a surplus of 30 units",
   "a shortage of 30 units",
   "equilibrium at 60 units",
   "no effect, since $6 is above equilibrium",
   "a shortage of 15 units"], ans=1,
   why="At $6 quantity demanded 75 exceeds quantity supplied 45 by 30."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$12", "30", "90"], ["$10", "45", "75"], ["$8", "60", "60"], ["$6", "75", "45"], ["$4", "90", "30"]]),
   q="Using the same table, a price floor of $10 produces", choices=[
   "a shortage of 30 units",
   "a surplus of 30 units",
   "equilibrium",
   "no effect",
   "a surplus of 45 units"], ans=1,
   why="At $10 quantity supplied 75 exceeds quantity demanded 45 by 30."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$12", "30", "90"], ["$10", "45", "75"], ["$8", "60", "60"], ["$6", "75", "45"], ["$4", "90", "30"]]),
   q="Using the same table, a price ceiling of $10 would", choices=[
   "cause a shortage of 30 units",
   "cause a surplus of 30 units",
   "have no effect, since it is above the equilibrium price of $8",
   "lower price to $8",
   "eliminate the market"], ans=2,
   why="A ceiling above equilibrium is non-binding."),
 dict(q="A severe drought hits the wheat-growing region. In the wheat market this will", choices=[
   "shift supply left, raising price and reducing quantity",
   "shift supply right, lowering price",
   "shift demand left",
   "shift demand right",
   "leave the market unchanged"], ans=0,
   why="Reduced harvests decrease supply."),
 dict(q="A popular new medical study reports that eating almonds improves heart health. In the almond market this will", choices=[
   "shift supply right",
   "shift demand right, raising both price and quantity",
   "shift demand left",
   "shift supply left",
   "cause a movement along demand only"], ans=1,
   why="Improved tastes increase demand."),
 dict(q="The price of steel, a key input for bicycles, falls sharply. In the bicycle market this will", choices=[
   "shift bicycle demand right",
   "shift bicycle supply right, lowering price and raising quantity",
   "shift bicycle supply left",
   "shift bicycle demand left",
   "have no effect"], ans=1,
   why="Cheaper inputs increase supply."),
 dict(q="Consumer incomes rise sharply in a market for a normal good, while a new technology also lowers production costs. Equilibrium quantity will", choices=[
   "definitely rise",
   "definitely fall",
   "be indeterminate",
   "stay the same",
   "fall to zero"], ans=0,
   why="Both demand and supply increase, so quantity unambiguously rises."),
 dict(q="In that same scenario (demand up, supply up), equilibrium price will", choices=[
   "definitely rise",
   "definitely fall",
   "depend on which shift is larger",
   "stay exactly the same",
   "become negative"], ans=2,
   why="Opposing price pressures leave the outcome dependent on magnitudes."),
 dict(q="Why do binding price ceilings often lead to long queues or rationing?", choices=[
   "Producers refuse to sell",
   "The shortage means some willing buyers cannot obtain the good at the legal price",
   "Demand becomes perfectly elastic",
   "Supply shifts right",
   "Prices adjust upward"], ans=1,
   why="With price prevented from rising, non-price rationing emerges."),
 dict(q="Rent control is a classic example of", choices=[
   "a price floor", "a binding price ceiling", "a per-unit tax", "a subsidy", "a quota"], ans=1,
   why="Rent control caps rents below equilibrium, creating housing shortages."),
 dict(q="A minimum wage set above the equilibrium wage is an example of", choices=[
   "a price ceiling", "a binding price floor in the labor market", "a subsidy", "a tax", "market equilibrium"], ans=1,
   why="It is a legal minimum price for labor, creating a surplus (unemployment)."),
 dict(q="Both a binding price ceiling and a binding price floor", choices=[
   "increase total surplus",
   "reduce the quantity actually traded and create deadweight loss",
   "eliminate deadweight loss",
   "raise producer surplus",
   "have no efficiency effects"], ans=1,
   why="Both prevent mutually beneficial trades, shrinking total surplus."),
 dict(q="Under a binding price ceiling, the quantity actually traded equals", choices=[
   "quantity demanded at the ceiling",
   "quantity supplied at the ceiling, the short side of the market",
   "the equilibrium quantity",
   "zero",
   "the average of the two quantities"], ans=1,
   why="Trade is limited by whichever side is smaller — here, supply."),
 dict(q="Under a binding price floor, the quantity actually traded equals", choices=[
   "quantity supplied at the floor",
   "quantity demanded at the floor, the short side",
   "the equilibrium quantity",
   "zero",
   "the sum of both"], ans=1,
   why="Buyers limit the trade when price is held above equilibrium."),
 dict(q="Which event would cause the equilibrium price of coffee to rise AND quantity to fall?", choices=[
   "A new coffee-growing technology",
   "A frost destroying coffee plants",
   "A rise in consumer income",
   "An increase in the number of coffee farms",
   "A fall in the price of tea"], ans=1,
   why="A supply decrease raises price and cuts quantity."),
 dict(q="Which event would cause the equilibrium price of tablets to fall AND quantity to rise?", choices=[
   "A tax on tablet producers",
   "A breakthrough that greatly reduces tablet manufacturing cost",
   "A surge in consumer demand",
   "The exit of several tablet makers",
   "A rise in component prices"], ans=1,
   why="An increase in supply lowers price and raises quantity."),
 dict(q="When a market is in disequilibrium with a shortage, the adjustment process involves", choices=[
   "price falling until quantity demanded rises",
   "price rising, which reduces quantity demanded and increases quantity supplied",
   "supply shifting right automatically",
   "demand shifting left automatically",
   "government intervention only"], ans=1,
   why="Rising price closes the gap from both sides."),
 dict(q="A market experiencing a surplus adjusts when", choices=[
   "price rises, reducing quantity supplied",
   "price falls, raising quantity demanded and reducing quantity supplied",
   "demand shifts right automatically",
   "the government buys the surplus",
   "supply shifts left automatically"], ans=1,
   why="Falling price eliminates excess supply from both sides."),
 dict(q="Suppose the price of a substitute good rises AND input costs for the good itself also rise. The equilibrium price of the good will", choices=[
   "definitely rise",
   "definitely fall",
   "be indeterminate",
   "not change",
   "fall then rise"], ans=0,
   why="Demand rises (substitute pricier) and supply falls (costlier inputs) — both raise price."),
 dict(q="In that same scenario (demand up, supply down), equilibrium quantity will", choices=[
   "definitely rise",
   "definitely fall",
   "be indeterminate, depending on shift magnitudes",
   "not change",
   "double"], ans=2,
   why="Demand raises quantity while reduced supply lowers it."),
 dict(q="A non-binding price ceiling has", choices=[
   "a large effect on the market",
   "no effect, because the equilibrium price is already below it",
   "the same effect as a binding one",
   "the effect of creating a surplus",
   "the effect of raising price"], ans=1,
   why="If the market price is already legal, the ceiling never binds."),
 dict(q="A non-binding price floor is one set", choices=[
   "above equilibrium",
   "below the equilibrium price, so the market clears normally",
   "at exactly equilibrium and still binding",
   "at zero and binding",
   "above the demand curve"], ans=1,
   why="A floor below equilibrium never constrains the market price."),
 dict(q="If a government wants to eliminate a shortage caused by a price ceiling without removing the ceiling, it could", choices=[
   "further lower the ceiling",
   "take steps to increase supply, such as subsidizing producers",
   "reduce the number of producers",
   "raise producers' costs",
   "restrict imports"], ans=1,
   why="Increasing supply raises quantity supplied at the capped price."),
 dict(q="Which of the following best describes what happens to consumer surplus under a binding price ceiling?", choices=[
   "It necessarily rises",
   "It may rise or fall — buyers who obtain the good pay less, but fewer units are available",
   "It always falls to zero",
   "It equals producer surplus",
   "It is unaffected"], ans=1,
   why="Lower price helps those who buy, but rationing removes buyers entirely."),
 dict(q="Producer surplus under a binding price ceiling", choices=[
   "rises", "falls, since both price and quantity sold decline", "is unchanged", "becomes negative", "equals total surplus"], ans=1,
   why="Sellers receive less per unit and sell fewer units."),
 dict(q="Black markets often emerge alongside binding price ceilings because", choices=[
   "supply is unlimited at the capped price",
   "some buyers value the good far above the ceiling and will pay more illegally",
   "the government encourages them",
   "demand disappears",
   "producer surplus is maximized"], ans=1,
   why="Unmet demand at a price above the cap creates illegal trading incentives."),
 dict(q="A simultaneous rightward shift of supply that is much larger than a rightward shift of demand will cause price to", choices=[
   "rise", "fall", "stay exactly the same", "become undefined", "double"], ans=1,
   why="When the supply shift dominates, its downward price pressure wins."),
 dict(q="Which change would leave equilibrium price unchanged but raise equilibrium quantity?", choices=[
   "Only demand increasing",
   "Only supply increasing",
   "Demand and supply increasing by exactly offsetting amounts in their price effects",
   "Demand decreasing and supply increasing",
   "Both decreasing"], ans=2,
   why="Equal and opposite price pressures leave price flat while both raise quantity."),
 dict(q="The 'short side of the market' rule says that in disequilibrium, the quantity traded equals", choices=[
   "the larger of quantity demanded and quantity supplied",
   "the smaller of quantity demanded and quantity supplied",
   "their average",
   "the equilibrium quantity",
   "zero"], ans=1,
   why="Trade requires both a willing buyer and a willing seller, so the smaller side limits it."),
 dict(q="Which of the following would cause an increase in both equilibrium price and equilibrium quantity in the market for electric cars?", choices=[
   "A government subsidy to EV manufacturers",
   "A large rise in gasoline prices, making EVs more attractive",
   "A fall in battery costs",
   "New EV factories opening",
   "A tax on EV buyers"], ans=1,
   why="A demand increase raises both price and quantity."),
 dict(q="An economist observes that a market's price rose while quantity fell. The most likely cause is", choices=[
   "an increase in demand",
   "a decrease in supply",
   "an increase in supply",
   "a decrease in demand",
   "a price ceiling"], ans=1,
   why="Only a leftward supply shift raises price while cutting quantity."),
 dict(q="An economist observes that a market's price fell while quantity rose. The most likely cause is", choices=[
   "a decrease in demand",
   "an increase in supply",
   "a decrease in supply",
   "an increase in demand",
   "a price floor"], ans=1,
   why="A rightward supply shift lowers price and raises quantity."),
 dict(q="Why can simultaneous shifts leave one equilibrium variable indeterminate?", choices=[
   "Because markets never clear",
   "Because the two shifts push that variable in opposite directions, so the outcome depends on their relative sizes",
   "Because elasticity is always zero",
   "Because price controls apply",
   "Because quantity cannot be measured"], ans=1,
   why="Opposing pressures on one variable make its net direction depend on magnitudes."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
