# 2.8 The Effects of Government Intervention in Markets — 50 questions
# Tax/subsidy arithmetic verified.
TOPIC = ("2.8", "The Effects of Government Intervention in Markets", 2)
QUESTIONS = [
 dict(q="A price ceiling is", choices=[
   "a legal maximum price at which a good may be sold",
   "a legal minimum price",
   "a tax on producers",
   "a subsidy to consumers",
   "a quantity limit"], ans=0,
   why="A ceiling caps how high the price may legally go."),
 dict(q="A price floor is", choices=[
   "a legal maximum price",
   "a legal minimum price at which a good may be sold",
   "a per-unit tax",
   "a production quota",
   "an import tariff"], ans=1,
   why="A floor sets a legal minimum price."),
 dict(q="A price ceiling only affects the market if it is set", choices=[
   "above equilibrium price", "below equilibrium price", "exactly at equilibrium", "at zero", "above the demand curve"], ans=1,
   why="Only a binding (below-equilibrium) ceiling changes the outcome."),
 dict(q="A binding price ceiling causes all of the following EXCEPT", choices=[
   "a shortage", "reduced quantity traded", "deadweight loss", "an increase in total surplus", "possible black markets"], ans=3,
   why="Binding ceilings reduce total surplus rather than increase it."),
 dict(q="Under a binding price floor, producer surplus", choices=[
   "always increases",
   "may rise or fall — sellers get a higher price but sell fewer units",
   "always falls to zero",
   "equals consumer surplus",
   "is unaffected"], ans=1,
   why="Higher price per unit competes against fewer units sold."),
 dict(q="A per-unit excise tax on producers shifts the supply curve", choices=[
   "right by the amount of the tax",
   "up/left by the amount of the tax",
   "down by the tax",
   "not at all",
   "into a vertical line"], ans=1,
   why="Sellers now need the old price plus the tax for each unit."),
 dict(q="Tax incidence refers to", choices=[
   "how often a tax is collected",
   "how the burden of a tax is divided between buyers and sellers",
   "the total revenue a tax raises",
   "the deadweight loss of a tax",
   "which agency collects the tax"], ans=1,
   why="Incidence is about who actually bears the economic burden."),
 dict(q="The economic burden of a tax falls more heavily on", choices=[
   "whichever side the law says must pay it",
   "the side of the market that is relatively more inelastic",
   "the side that is more elastic",
   "producers always",
   "consumers always"], ans=1,
   why="The less responsive side cannot escape the tax by changing quantity."),
 dict(q="If demand is perfectly inelastic, a per-unit tax on the good will be borne", choices=[
   "entirely by producers",
   "entirely by consumers",
   "equally by both",
   "by the government",
   "by nobody"], ans=1,
   why="Buyers who will not reduce quantity absorb the full tax in price."),
 dict(q="If supply is perfectly elastic, a per-unit tax will be borne", choices=[
   "entirely by producers",
   "entirely by consumers",
   "equally shared",
   "by the government",
   "by foreign buyers"], ans=1,
   why="Perfectly elastic supply means sellers will not accept any lower net price."),
 dict(q="Deadweight loss from a tax arises because", choices=[
   "the government spends the revenue",
   "the tax reduces quantity traded below the efficient level, eliminating beneficial trades",
   "producers earn less profit",
   "consumers pay more",
   "the tax is collected inefficiently"], ans=1,
   why="Lost mutually beneficial transactions are the source of the welfare loss."),
 dict(q="Tax revenue from a per-unit tax equals", choices=[
   "the tax per unit × the quantity traded after the tax",
   "the tax per unit × the original equilibrium quantity",
   "the deadweight loss",
   "consumer surplus lost",
   "total surplus"], ans=0,
   why="Revenue is the tax rate times the post-tax quantity."),
 dict(q="A $3 per-unit tax reduces quantity traded from 100 to 80 units. Government tax revenue is", choices=[
   "$300", "$240", "$60", "$180", "$540"], ans=1,
   why="$3 × 80 units traded after the tax = $240."),
 dict(q="A per-unit tax of $4 raises the price consumers pay from $20 to $23. The burden on consumers per unit is", choices=[
   "$4", "$3", "$1", "$23", "$0"], ans=1,
   why="Consumers pay $3 more, so producers absorb the remaining $1."),
 dict(q="Continuing that example ($4 tax, consumer price rises $20 → $23), producers receive per unit", choices=[
   "$23", "$20", "$19", "$16", "$4"], ans=2,
   why="Consumers pay $23, government takes $4, so sellers keep $19."),
 dict(q="A per-unit subsidy to producers shifts supply", choices=[
   "left by the subsidy amount",
   "right/down by the subsidy amount",
   "not at all",
   "into a vertical line",
   "up by the subsidy"], ans=1,
   why="A subsidy lowers effective cost, increasing supply."),
 dict(q="A per-unit subsidy generally causes equilibrium quantity to", choices=[
   "fall", "rise above the free-market level", "stay the same", "become zero", "be indeterminate"], ans=1,
   why="Subsidies encourage production beyond the market equilibrium."),
 dict(q="A subsidy in an otherwise efficient competitive market creates deadweight loss because", choices=[
   "it reduces quantity",
   "it pushes quantity beyond the efficient level, where marginal cost exceeds marginal benefit",
   "it raises consumer surplus",
   "it lowers producer surplus",
   "it eliminates trades"], ans=1,
   why="Overproduction adds units worth less than they cost."),
 dict(q="Under a binding price ceiling, the deadweight loss represents", choices=[
   "government revenue",
   "the value of mutually beneficial trades that no longer occur",
   "consumer surplus gained",
   "producer profit",
   "the size of the shortage in dollars"], ans=1,
   why="Deadweight loss is the surplus from transactions prevented by the policy."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$9", "40", "100"], ["$7", "60", "80"], ["$5", "80", "80"], ["$3", "100", "60"], ["$1", "120", "40"]]),
   q="Using the table, a price ceiling of $3 creates a shortage of", choices=[
   "20 units", "40 units", "60 units", "80 units", "no shortage"], ans=1,
   why="At $3, quantity demanded 100 exceeds quantity supplied 60 by 40 units."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$9", "40", "100"], ["$7", "60", "80"], ["$5", "80", "80"], ["$3", "100", "60"], ["$1", "120", "40"]]),
   q="Using the same table, a price floor of $7 creates a surplus of", choices=[
   "10 units", "20 units", "40 units", "60 units", "no surplus"], ans=1,
   why="At $7, quantity supplied 80 exceeds quantity demanded 60 by 20 units."),
 dict(table=dict(headers=["Price", "Quantity demanded", "Quantity supplied"],
   rows=[["$9", "40", "100"], ["$7", "60", "80"], ["$5", "80", "80"], ["$3", "100", "60"], ["$1", "120", "40"]]),
   q="Using the same table, with a price ceiling of $3 the quantity actually traded is", choices=[
   "100 units", "80 units", "60 units", "40 units", "zero"], ans=2,
   why="The short side limits trade: only 60 units are supplied."),
 dict(q="Rent control tends to cause which long-run problem?", choices=[
   "An oversupply of apartments",
   "Reduced quantity and quality of rental housing as landlords cut investment",
   "Falling demand for housing",
   "Higher landlord profits",
   "Elimination of shortages"], ans=1,
   why="Capped returns discourage maintenance and new construction."),
 dict(q="A minimum wage set above the market wage causes", choices=[
   "a labor shortage",
   "a surplus of labor — unemployment among low-skilled workers",
   "an increase in labor demand",
   "no effect on employment",
   "wages to fall"], ans=1,
   why="Quantity of labor supplied exceeds quantity demanded at the higher wage."),
 dict(q="Which group is most likely to be hurt by a binding minimum wage?", choices=[
   "Highly paid professionals",
   "Low-skilled workers who lose or cannot find jobs",
   "Employers of high-wage workers",
   "Consumers of luxury goods",
   "Retired workers"], ans=1,
   why="Those whose productivity is below the mandated wage lose employment opportunities."),
 dict(q="Agricultural price supports (floors) often require the government to", choices=[
   "lower the price further",
   "purchase or store the resulting surplus",
   "reduce supply by taxing consumers",
   "eliminate the floor",
   "ration the good"], ans=1,
   why="Someone must absorb the excess supply a floor creates."),
 dict(q="Which policy would eliminate a shortage caused by a price ceiling most directly?", choices=[
   "Lowering the ceiling",
   "Raising or removing the ceiling so price can rise toward equilibrium",
   "Taxing producers",
   "Reducing supply",
   "Restricting entry"], ans=1,
   why="Allowing price to rise equates quantity demanded and supplied."),
 dict(q="An excise tax placed legally on CONSUMERS rather than producers will", choices=[
   "shift demand down by the tax and produce the same economic incidence",
   "have a completely different economic effect",
   "be borne entirely by consumers",
   "raise total surplus",
   "eliminate deadweight loss"], ans=0,
   why="Statutory placement does not change who really bears the tax."),
 dict(q="The deadweight loss from a tax is LARGER when", choices=[
   "supply and demand are both very inelastic",
   "supply and demand are both relatively elastic",
   "the tax is very small",
   "quantity does not change",
   "demand is perfectly inelastic"], ans=1,
   why="Elastic sides cut quantity sharply, destroying more trades."),
 dict(q="The deadweight loss from a tax is SMALLER when", choices=[
   "demand is highly elastic",
   "demand is highly inelastic, so quantity barely changes",
   "the tax rate is very high",
   "supply is perfectly elastic",
   "both sides are elastic"], ans=1,
   why="If quantity barely moves, few trades are lost."),
 dict(q="Governments often tax goods like cigarettes and gasoline partly because", choices=[
   "their demand is elastic, so consumption falls sharply",
   "their demand is inelastic, so the tax raises steady revenue",
   "they have no consumers",
   "they are luxury goods",
   "supply is perfectly elastic"], ans=1,
   why="Inelastic demand keeps the tax base stable."),
 dict(q="Which of the following is a QUANTITY control rather than a price control?", choices=[
   "A price ceiling on rent",
   "A minimum wage",
   "A quota limiting the number of taxi licenses",
   "A per-unit tax",
   "A subsidy"], ans=2,
   why="A quota restricts quantity directly rather than setting a price."),
 dict(q="A binding quota that limits output below the equilibrium quantity will", choices=[
   "lower the price consumers pay",
   "raise the price consumers pay and create deadweight loss",
   "increase total surplus",
   "eliminate shortages",
   "have no effect"], ans=1,
   why="Restricted supply raises price and forgoes beneficial trades."),
 dict(q="After a per-unit tax, the difference between the price consumers pay and the price producers receive equals", choices=[
   "zero", "the amount of the tax", "the deadweight loss", "producer surplus", "consumer surplus"], ans=1,
   why="The tax drives a wedge exactly equal to its per-unit size."),
 dict(q="Total surplus after a tax equals", choices=[
   "consumer surplus + producer surplus + tax revenue",
   "consumer surplus + producer surplus only",
   "tax revenue only",
   "deadweight loss",
   "zero"], ans=0,
   why="Tax revenue is a transfer that still counts in total welfare accounting."),
 dict(q="A subsidy causes government expenditure equal to", choices=[
   "the subsidy per unit × quantity traded with the subsidy",
   "the subsidy per unit × original quantity",
   "the deadweight loss",
   "consumer surplus",
   "zero"], ans=0,
   why="Cost = subsidy rate × the subsidized quantity."),
 dict(q="A $2 per-unit subsidy raises quantity traded from 50 to 70 units. Government cost is", choices=[
   "$100", "$140", "$40", "$240", "$20"], ans=1,
   why="$2 × 70 subsidized units = $140."),
 dict(q="Which of the following results from a binding price ceiling but NOT from a per-unit tax?", choices=[
   "Reduced quantity traded",
   "Deadweight loss",
   "A persistent shortage with non-price rationing",
   "Lower producer surplus",
   "Changed consumer prices"], ans=2,
   why="A tax clears the market at a new price; a ceiling leaves unsatisfied demand."),
 dict(q="Government intervention in an efficient competitive market generally", choices=[
   "increases total surplus",
   "reduces total surplus, creating deadweight loss",
   "leaves surplus unchanged",
   "eliminates scarcity",
   "always benefits producers"], ans=1,
   why="If the market was already efficient, intervention moves output away from the optimum."),
 dict(q="A justification for intervening despite deadweight loss might be", choices=[
   "to maximize firm profits",
   "to pursue equity or correct a market failure such as an externality",
   "to eliminate all taxes",
   "to reduce the number of firms",
   "to raise prices for their own sake"], ans=1,
   why="Efficiency is only one goal; equity and market failure justify intervention."),
 dict(q="Under a binding price ceiling, which buyers are most likely to obtain the good?", choices=[
   "Those with the highest willingness to pay, automatically",
   "Those who queue longest or have connections, since price no longer rations",
   "All buyers equally",
   "Only producers",
   "Nobody"], ans=1,
   why="With price fixed, non-price rationing methods take over."),
 dict(q="If a tax is imposed in a market where demand is more elastic than supply, then", choices=[
   "consumers bear most of the burden",
   "producers bear most of the burden",
   "the burden is exactly equal",
   "the government bears the burden",
   "there is no burden"], ans=1,
   why="The more elastic side (consumers here) escapes more of the tax."),
 dict(q="Consumer surplus after a per-unit tax is", choices=[
   "larger than before",
   "smaller than before, since consumers pay a higher price and buy less",
   "unchanged",
   "equal to tax revenue",
   "zero"], ans=1,
   why="Higher consumer price and lower quantity both shrink consumer surplus."),
 dict(q="Which statement about price controls is TRUE?", choices=[
   "Price ceilings create surpluses and floors create shortages",
   "Price ceilings create shortages and floors create surpluses",
   "Both create shortages",
   "Both create surpluses",
   "Neither affects quantity"], ans=1,
   why="Ceilings hold price below equilibrium (shortage); floors hold it above (surplus)."),
 dict(q="Non-binding price controls", choices=[
   "always create deadweight loss",
   "have no effect on the market outcome",
   "create shortages",
   "create surpluses",
   "raise total surplus"], ans=1,
   why="If the market price is already legal, the control does not bind."),
 dict(q="A government imposes a $5 tax on a good with perfectly inelastic supply. The price consumers pay will", choices=[
   "rise by $5",
   "not change, since producers absorb the entire tax",
   "rise by $2.50",
   "fall by $5",
   "become zero"], ans=1,
   why="With fixed quantity supplied, sellers cannot pass the tax forward."),
 dict(q="Which policy is designed to raise incomes of producers in a market?", choices=[
   "A price ceiling", "A price floor such as an agricultural price support", "A per-unit tax", "A quota reduction", "Rent control"], ans=1,
   why="Price floors are intended to support producer revenues."),
 dict(q="Which policy is designed to make a good more affordable for consumers in the short run?", choices=[
   "A price floor", "A binding price ceiling such as rent control", "A tax on the good", "A production quota", "A tariff"], ans=1,
   why="Ceilings aim to keep prices low for buyers."),
 dict(q="After a per-unit tax, the reduction in total surplus that is NOT captured as government revenue is", choices=[
   "consumer surplus", "producer surplus", "the deadweight loss", "the tax wedge", "zero"], ans=2,
   why="Deadweight loss is surplus destroyed rather than transferred."),
 dict(q="Which of the following statements about tax incidence is CORRECT?", choices=[
   "The side legally required to pay always bears the burden",
   "Economic incidence depends on relative elasticities, not on who legally remits the tax",
   "Incidence is always split 50-50",
   "Only producers ever bear a tax",
   "Elasticity is irrelevant to incidence"], ans=1,
   why="Relative elasticity, not statute, determines the real burden."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
