# 2.9 International Trade and Public Policy — 50 questions
TOPIC = ("2.9", "International Trade and Public Policy", 2)
QUESTIONS = [
 dict(q="The world price of a good is the price", choices=[
   "set by a country's government",
   "prevailing in world markets, at which a country can trade internationally",
   "charged only by domestic firms",
   "after tariffs are added",
   "of the most expensive supplier"], ans=1,
   why="The world price is the international market price a small country takes as given."),
 dict(q="If the world price is BELOW a country's domestic (autarky) equilibrium price, the country will", choices=[
   "export the good",
   "import the good",
   "stop trading",
   "impose a price floor",
   "produce nothing"], ans=1,
   why="Cheaper foreign supply means the country buys from abroad."),
 dict(q="If the world price is ABOVE a country's domestic equilibrium price, the country will", choices=[
   "import the good",
   "export the good",
   "ban trade",
   "subsidize consumers",
   "experience a shortage of exports"], ans=1,
   why="Domestic producers can sell more profitably abroad."),
 dict(q="When a country opens to trade and becomes an IMPORTER, domestic consumers", choices=[
   "lose surplus",
   "gain surplus because the price falls",
   "are unaffected",
   "pay a higher price",
   "buy less"], ans=1,
   why="Imports lower the domestic price, benefiting buyers."),
 dict(q="When a country opens to trade and becomes an IMPORTER, domestic producers", choices=[
   "gain surplus",
   "lose surplus because the price falls and they sell less",
   "are unaffected",
   "export more",
   "raise their prices"], ans=1,
   why="Domestic sellers face a lower price and lose sales to imports."),
 dict(q="When a country opens to trade and becomes an EXPORTER, domestic consumers", choices=[
   "gain surplus",
   "lose surplus because the domestic price rises to the world price",
   "are unaffected",
   "pay lower prices",
   "consume more"], ans=1,
   why="Exporting raises the domestic price, hurting domestic buyers."),
 dict(q="In either case — importing or exporting — opening to trade causes total domestic surplus to", choices=[
   "fall", "rise", "stay the same", "become zero", "be indeterminate"], ans=1,
   why="Trade gains to winners exceed losses to losers, raising total surplus."),
 dict(q="A tariff is", choices=[
   "a tax on imported goods",
   "a limit on the quantity of imports",
   "a subsidy to exporters",
   "a ban on trade",
   "a domestic sales tax"], ans=0,
   why="A tariff taxes imports as they enter the country."),
 dict(q="An import quota is", choices=[
   "a tax on imports",
   "a legal limit on the quantity of a good that may be imported",
   "a subsidy to importers",
   "a price floor",
   "an export tax"], ans=1,
   why="A quota restricts import quantity directly."),
 dict(q="A tariff on an imported good causes the domestic price to", choices=[
   "fall below the world price",
   "rise above the world price by the amount of the tariff",
   "stay at the world price",
   "fall to zero",
   "equal the autarky price always"], ans=1,
   why="The tariff is added to the world price for domestic buyers."),
 dict(q="A tariff causes domestic production to ___ and imports to ___.", choices=[
   "rise; rise", "rise; fall", "fall; rise", "fall; fall", "stay the same; fall"], ans=1,
   why="The higher price draws out domestic supply and shrinks import volume."),
 dict(q="A tariff causes domestic consumer surplus to", choices=[
   "rise", "fall, since consumers pay a higher price and buy less", "stay the same", "become zero", "equal producer surplus"], ans=1,
   why="Higher price and lower quantity reduce consumer surplus."),
 dict(q="A tariff generates revenue for the government equal to", choices=[
   "the tariff per unit × total domestic consumption",
   "the tariff per unit × the quantity imported after the tariff",
   "the deadweight loss",
   "the entire loss in consumer surplus",
   "zero"], ans=1,
   why="Only imported units are taxed."),
 dict(q="The deadweight loss from a tariff comes from", choices=[
   "government revenue",
   "inefficient domestic overproduction and lost consumption",
   "gains to producers",
   "transfers to consumers",
   "the world price"], ans=1,
   why="High-cost domestic units replace cheap imports, and some consumption is forgone."),
 dict(q="Compared with a tariff that reduces imports by the same amount, an import QUOTA", choices=[
   "always raises more government revenue",
   "generates no tariff revenue — the extra value typically goes to license holders or foreign sellers",
   "creates no deadweight loss",
   "lowers the domestic price",
   "increases imports"], ans=1,
   why="A quota's price premium accrues to whoever holds import rights, not the treasury."),
 dict(table=dict(headers=["Price", "Domestic Qd", "Domestic Qs"],
   rows=[["$10", "40", "80"], ["$8", "60", "60"], ["$6", "80", "40"], ["$4", "100", "20"]]),
   q="Using the table, the domestic (no-trade) equilibrium price is", choices=[
   "$10", "$8", "$6", "$4", "cannot be determined"], ans=1,
   why="At $8 domestic quantity demanded equals quantity supplied at 60."),
 dict(table=dict(headers=["Price", "Domestic Qd", "Domestic Qs"],
   rows=[["$10", "40", "80"], ["$8", "60", "60"], ["$6", "80", "40"], ["$4", "100", "20"]]),
   q="Using the same table, if the world price is $4 and trade is free, imports equal", choices=[
   "20 units", "40 units", "60 units", "80 units", "100 units"], ans=3,
   why="At $4, Qd 100 minus domestic Qs 20 = 80 units imported."),
 dict(table=dict(headers=["Price", "Domestic Qd", "Domestic Qs"],
   rows=[["$10", "40", "80"], ["$8", "60", "60"], ["$6", "80", "40"], ["$4", "100", "20"]]),
   q="Using the same table, if a $2 tariff raises the effective price from $4 to $6, imports become", choices=[
   "80 units", "60 units", "40 units", "20 units", "zero"], ans=2,
   why="At $6, Qd 80 minus Qs 40 = 40 units imported — down from 80."),
 dict(table=dict(headers=["Price", "Domestic Qd", "Domestic Qs"],
   rows=[["$10", "40", "80"], ["$8", "60", "60"], ["$6", "80", "40"], ["$4", "100", "20"]]),
   q="With that $2 tariff and 40 units imported, government tariff revenue equals", choices=[
   "$40", "$80", "$160", "$200", "$320"], ans=1,
   why="$2 × 40 imported units = $80."),
 dict(q="Free trade based on comparative advantage raises world output because", choices=[
   "every country produces everything",
   "each good is produced where its opportunity cost is lowest",
   "tariffs collect revenue",
   "prices always fall",
   "labor becomes cheaper"], ans=1,
   why="Specialization by lowest opportunity cost expands total production."),
 dict(q="The 'infant industry' argument for protection claims that", choices=[
   "new industries need temporary protection to develop before facing global competition",
   "old industries deserve permanent subsidies",
   "trade always harms consumers",
   "tariffs raise total surplus",
   "quotas are more efficient than tariffs"], ans=0,
   why="It argues young industries need time to become competitive."),
 dict(q="A common economic criticism of the infant industry argument is that", choices=[
   "protection is always efficient",
   "protected industries often never become competitive and the protection becomes permanent",
   "it raises consumer surplus",
   "it eliminates deadweight loss",
   "it lowers domestic prices"], ans=1,
   why="Temporary protection tends to become entrenched without producing competitiveness."),
 dict(q="The 'national security' argument for trade restrictions holds that", choices=[
   "all imports are dangerous",
   "certain strategic industries should be maintained domestically even at higher cost",
   "tariffs raise revenue",
   "trade lowers prices",
   "quotas are efficient"], ans=1,
   why="It prioritizes domestic capacity in critical sectors over pure efficiency."),
 dict(q="Which group typically LOSES from a tariff on an imported good?", choices=[
   "Domestic producers of the good",
   "Domestic consumers of the good",
   "The domestic government",
   "Owners of import licenses",
   "Domestic workers in the protected industry"], ans=1,
   why="Consumers face higher prices and reduced quantity."),
 dict(q="Which group typically GAINS from a tariff on an imported good?", choices=[
   "Domestic consumers",
   "Domestic producers competing with imports",
   "Foreign exporters",
   "All households equally",
   "Nobody"], ans=1,
   why="Protection lets domestic firms sell more at a higher price."),
 dict(q="Trade restrictions are often politically popular even when inefficient because", choices=[
   "the benefits are concentrated among a visible group while the costs are spread thinly across many consumers",
   "they raise total surplus",
   "consumers demand them",
   "they eliminate deadweight loss",
   "economists support them"], ans=0,
   why="Concentrated benefits and diffuse costs shape the politics of protection."),
 dict(q="A country that is a 'small' participant in a world market is assumed to", choices=[
   "set the world price",
   "take the world price as given",
   "have no domestic producers",
   "always run a trade surplus",
   "be unable to trade"], ans=1,
   why="A small country's trade volume does not move the world price."),
 dict(q="When a country imports, the domestic quantity supplied by domestic firms", choices=[
   "increases",
   "decreases relative to autarky, since the price is lower",
   "stays the same",
   "becomes zero always",
   "equals domestic demand"], ans=1,
   why="At the lower world price, fewer domestic firms find production profitable."),
 dict(q="Imports equal", choices=[
   "domestic quantity supplied minus domestic quantity demanded at the world price",
   "domestic quantity demanded minus domestic quantity supplied at the world price",
   "total domestic production",
   "the world price times quantity",
   "domestic consumption only"], ans=1,
   why="The gap buyers want beyond domestic production is filled by imports."),
 dict(q="Exports equal", choices=[
   "domestic quantity demanded minus quantity supplied",
   "domestic quantity supplied minus domestic quantity demanded at the world price",
   "world production",
   "tariff revenue",
   "zero when the world price is high"], ans=1,
   why="Production beyond domestic consumption goes abroad."),
 dict(q="An export subsidy paid to domestic producers will", choices=[
   "lower the domestic price",
   "increase exports and raise the domestic price consumers pay",
   "eliminate deadweight loss",
   "reduce domestic production",
   "have no effect"], ans=1,
   why="Subsidized exporting diverts output abroad, raising the home price."),
 dict(q="Which policy would most directly reduce the quantity of a good imported without generating government revenue?", choices=[
   "A tariff", "An import quota", "An export subsidy", "A consumption tax", "A price ceiling"], ans=1,
   why="Quotas restrict quantity but collect no duty."),
 dict(q="Comparing autarky with free trade for an importing country, total surplus", choices=[
   "falls", "rises by the gains from trade triangle", "is unchanged", "becomes negative", "equals producer surplus"], ans=1,
   why="Consumer gains exceed producer losses, netting a surplus gain."),
 dict(q="A tariff's effect on total domestic surplus compared with free trade is", choices=[
   "an increase",
   "a decrease equal to the two deadweight loss triangles",
   "no change",
   "an increase equal to tariff revenue",
   "always zero"], ans=1,
   why="Production and consumption distortions each destroy surplus."),
 dict(q="'Dumping' refers to", choices=[
   "exporting a good at a price below its cost or below the home-market price",
   "importing too many goods",
   "imposing tariffs",
   "banning exports",
   "subsidizing consumers"], ans=0,
   why="Dumping is selling abroad below cost or below the domestic price."),
 dict(q="Which of the following is a NON-tariff barrier to trade?", choices=[
   "An import duty",
   "Complex licensing requirements and restrictive product standards on foreign goods",
   "An excise tax on all goods",
   "A domestic sales tax",
   "A price floor"], ans=1,
   why="Regulatory hurdles restrict trade without a formal tariff."),
 dict(q="Trade allows a country's consumption possibilities to exceed its production possibilities because", choices=[
   "it can produce more of everything",
   "it can specialize and exchange at terms of trade better than its own opportunity costs",
   "tariffs raise revenue",
   "prices fall to zero",
   "resources become unlimited"], ans=1,
   why="Favorable terms of trade let a country consume beyond its own PPC."),
 dict(q="An argument that trade restrictions protect domestic jobs overlooks that", choices=[
   "trade creates no jobs",
   "protection also raises costs for consumers and industries using the imported input, costing jobs elsewhere",
   "tariffs lower prices",
   "quotas raise revenue",
   "exports are unaffected"], ans=1,
   why="Jobs saved in one industry come at a cost to consumers and downstream firms."),
 dict(q="If the world price of steel is below the domestic price and a country imposes a steel tariff, domestic manufacturers who USE steel will", choices=[
   "benefit from cheaper inputs",
   "be hurt by higher input costs",
   "be unaffected",
   "export more",
   "gain tariff revenue"], ans=1,
   why="Protection of an input raises costs for downstream producers."),
 dict(q="Under free trade, the domestic price of a traded good equals", choices=[
   "the autarky price", "the world price", "the world price plus a tariff", "marginal cost only", "zero"], ans=1,
   why="With free trade, domestic and world prices converge."),
 dict(q="A tariff set so high that imports fall to zero is called", choices=[
   "a non-binding tariff",
   "a prohibitive tariff",
   "an export subsidy",
   "a quota",
   "a price floor"], ans=1,
   why="A prohibitive tariff blocks trade entirely, returning the market to autarky."),
 dict(q="A prohibitive tariff generates government revenue of", choices=[
   "a large amount",
   "zero, because no units are imported",
   "the full consumer surplus loss",
   "the deadweight loss",
   "the world price times quantity"], ans=1,
   why="No imports means no dutiable units."),
 dict(q="Which statement about tariffs and quotas is TRUE?", choices=[
   "Both raise the domestic price and reduce imports",
   "Tariffs raise price while quotas lower it",
   "Neither creates deadweight loss",
   "Quotas raise government revenue but tariffs do not",
   "Both increase total surplus"], ans=0,
   why="Both restrict imports and push the domestic price above the world price."),
 dict(q="Economists generally favor free trade because it", choices=[
   "benefits every individual equally",
   "increases total surplus and consumption possibilities, even though some groups lose",
   "eliminates all unemployment",
   "guarantees trade surpluses",
   "raises tariff revenue"], ans=1,
   why="Trade is efficiency-improving in aggregate, with distributional costs."),
 dict(q="The main distributional concern about free trade is that", choices=[
   "consumers pay more",
   "workers and firms in import-competing industries can face concentrated losses",
   "total surplus falls",
   "governments lose all revenue",
   "prices become unstable"], ans=1,
   why="Gains are widespread while losses concentrate in exposed industries."),
 dict(q="A policy response to help those hurt by trade, without abandoning free trade, is", choices=[
   "a permanent tariff",
   "trade adjustment assistance such as retraining and relocation support",
   "an import ban",
   "an export subsidy",
   "a price ceiling"], ans=1,
   why="Compensating losers preserves the aggregate gains from trade."),
 dict(q="When a country becomes an exporter after opening to trade, domestic producer surplus", choices=[
   "falls", "rises, since price increases and they sell more in total", "is unchanged", "becomes zero", "equals consumer surplus"], ans=1,
   why="Exporters gain from the higher world price and larger sales volume."),
 dict(q="Which of the following would increase a country's imports of a good?", choices=[
   "An increase in the tariff on that good",
   "A fall in the world price of the good",
   "A new import quota",
   "A rise in the domestic price of imports",
   "A prohibitive tariff"], ans=1,
   why="A lower world price widens the gap between domestic demand and domestic supply."),
 dict(q="The two deadweight loss triangles from a tariff represent", choices=[
   "government revenue and consumer surplus",
   "inefficient extra domestic production and forgone consumption",
   "producer surplus and tariff revenue",
   "the world price and domestic price",
   "imports and exports"], ans=1,
   why="One triangle is the production distortion, the other the consumption distortion."),
 dict(q="Which of the following best explains why a small importing country cannot improve its terms of trade with a tariff?", choices=[
   "It sets the world price",
   "Its trade volume is too small to affect the world price, so foreigners do not lower their price",
   "Tariffs are illegal",
   "It has no domestic producers",
   "Consumers do not respond to price"], ans=1,
   why="A price-taking country bears the whole tariff itself."),
]
assert len(QUESTIONS) == 50, len(QUESTIONS)
