# 3.3 Long-Run Production Costs — 50 questions
# Scale table verified: doubling both inputs
#   A: inputs x2 -> output x2.5 (increasing returns to scale, LRATC falling)
#   B: inputs x2 -> output x2   (constant returns to scale, LRATC flat)
#   C: inputs x2 -> output x1.6 (decreasing returns to scale, LRATC rising)
TOPIC = ("3.3", "Long-Run Production Costs", 3)
SCALE = dict(headers=["Firm", "Change in all inputs", "Change in output"],
             rows=[["A", "+100%", "+150%"], ["B", "+100%", "+100%"], ["C", "+100%", "+60%"]])
QUESTIONS = [
 dict(q="The long run in production is a period in which", choices=[
   "at least one input is fixed",
   "all inputs, including plant size, are variable",
   "output cannot be changed",
   "prices are fixed by contract",
   "no new firms may enter"], ans=1,
   why="The long run is defined by the absence of any fixed input."),
 dict(q="In the long run, a firm's fixed costs", choices=[
   "remain fixed forever",
   "no longer exist, because every input can be adjusted",
   "become marginal costs",
   "double",
   "are the only costs that matter"], ans=1,
   why="With all inputs variable there are no fixed costs in the long run."),
 dict(q="The long-run average total cost curve is best described as", choices=[
   "the sum of all short-run ATC curves",
   "an envelope showing the lowest attainable average cost for each output when plant size can be varied",
   "the marginal cost curve",
   "always horizontal",
   "identical to the short-run ATC curve"], ans=1,
   why="LRATC traces the minimum average cost achievable across all possible plant sizes."),
 dict(q="Economies of scale exist when", choices=[
   "long-run average total cost rises as output rises",
   "long-run average total cost falls as output rises",
   "long-run average total cost is constant",
   "marginal cost equals price",
   "total cost falls as output rises"], ans=1,
   why="Economies of scale mean a larger scale of operation lowers cost per unit."),
 dict(q="Diseconomies of scale exist when", choices=[
   "long-run average total cost falls as output rises",
   "long-run average total cost rises as output rises",
   "average fixed cost rises",
   "marginal product rises",
   "total cost falls"], ans=1,
   why="Beyond some size, per-unit cost increases as the firm expands."),
 dict(q="Constant returns to scale occur when", choices=[
   "output rises by a larger percentage than inputs",
   "output rises by the same percentage as all inputs",
   "output rises by a smaller percentage than inputs",
   "output does not change",
   "average fixed cost is constant"], ans=1,
   why="Proportional input and output changes leave average cost unchanged."),
 dict(q="Increasing returns to scale means that doubling all inputs", choices=[
   "less than doubles output",
   "more than doubles output",
   "exactly doubles output",
   "leaves output unchanged",
   "doubles average cost"], ans=1,
   why="Output grows faster than inputs, so cost per unit falls."),
 dict(q="Decreasing returns to scale means that doubling all inputs", choices=[
   "more than doubles output",
   "less than doubles output",
   "exactly doubles output",
   "halves output",
   "eliminates fixed cost"], ans=1,
   why="Output grows more slowly than inputs, so cost per unit rises."),
 dict(q="Using the table, Firm A is experiencing", table=SCALE, choices=[
   "constant returns to scale",
   "increasing returns to scale",
   "decreasing returns to scale",
   "diminishing marginal returns",
   "no returns to scale"], ans=1,
   why="Output rises 150% while inputs rise 100%, so output grows faster than inputs."),
 dict(q="Using the table, Firm B is experiencing", table=SCALE, choices=[
   "increasing returns to scale",
   "constant returns to scale",
   "decreasing returns to scale",
   "economies of scale",
   "diseconomies of scale"], ans=1,
   why="Inputs and output both rise 100%, so average cost is unchanged."),
 dict(q="Using the table, Firm C is experiencing", table=SCALE, choices=[
   "increasing returns to scale",
   "constant returns to scale",
   "decreasing returns to scale",
   "economies of scale",
   "increasing marginal returns"], ans=2,
   why="Output rises only 60% while inputs rise 100%, so cost per unit rises."),
 dict(q="Using the table, which firm's long-run average total cost is falling as it expands?", table=SCALE, choices=[
   "A", "B", "C", "both B and C", "none of them"], ans=0,
   why="Only Firm A gets proportionally more output than input."),
 dict(q="Using the table, which firm's long-run average total cost is unchanged as it expands?", table=SCALE, choices=[
   "A", "B", "C", "A and C", "none of them"], ans=1,
   why="Constant returns to scale leave LRATC flat."),
 dict(q="A common source of economies of scale is", choices=[
   "coordination problems in large organizations",
   "specialization of labor and more efficient use of large capital equipment",
   "diminishing marginal returns",
   "rising input prices",
   "an increase in fixed costs"], ans=1,
   why="Larger scale permits division of labor and use of equipment that is only cost-effective at high volume."),
 dict(q="A common source of diseconomies of scale is", choices=[
   "bulk purchasing discounts",
   "the difficulty of managing and coordinating a very large organization",
   "specialization of labor",
   "spreading fixed costs over more output",
   "improved technology"], ans=1,
   why="Communication and control costs rise disproportionately in very large firms."),
 dict(q="Which of the following distinguishes diminishing marginal returns from diseconomies of scale?", choices=[
   "They are the same concept.",
   "Diminishing marginal returns is a short-run idea with a fixed input; diseconomies of scale is a long-run idea with all inputs varying.",
   "Diminishing marginal returns applies only to capital.",
   "Diseconomies of scale occurs only in the short run.",
   "Diminishing marginal returns concerns average cost, not output."], ans=1,
   why="One holds an input fixed; the other scales every input together."),
 dict(q="The minimum efficient scale is the", choices=[
   "output at which marginal cost is zero",
   "smallest output at which long-run average total cost reaches its minimum",
   "largest output a firm can produce",
   "output at which total cost is lowest",
   "output at which fixed cost is zero"], ans=1,
   why="Minimum efficient scale is where economies of scale are exhausted."),
 dict(q="If minimum efficient scale is large relative to market demand, the industry is likely to have", choices=[
   "many small firms",
   "a small number of large firms",
   "perfectly elastic supply",
   "zero fixed costs",
   "constant returns to scale at all outputs"], ans=1,
   why="When only large firms can reach low costs, few firms can profitably serve the market."),
 dict(q="A natural monopoly arises when", choices=[
   "a firm owns a patent",
   "economies of scale persist over the entire relevant range of market demand, so one firm can serve the market at lowest cost",
   "the government forbids entry",
   "marginal cost is rising",
   "there are many close substitutes"], ans=1,
   why="Continuously falling LRATC makes a single producer the cheapest arrangement."),
 dict(q="The typical LRATC curve is U-shaped because", choices=[
   "fixed costs first fall then rise",
   "economies of scale operate at low output and diseconomies of scale eventually take over",
   "marginal product is always falling",
   "prices change with output",
   "the firm cannot vary its plant size"], ans=1,
   why="The two forces dominate at opposite ends of the output range."),
 dict(q="Each point on the LRATC curve corresponds to", choices=[
   "the same plant size",
   "the plant size that minimizes average cost for that particular output",
   "zero output",
   "the firm's marginal cost",
   "the maximum possible average cost"], ans=1,
   why="LRATC is built from the best short-run choice at every output."),
 dict(q="A short-run ATC curve can lie above the LRATC curve because", choices=[
   "short-run costs exclude fixed costs",
   "the firm may be stuck with a plant size that is not optimal for its current output",
   "the LRATC curve is always horizontal",
   "marginal cost exceeds average cost",
   "long-run costs ignore labor"], ans=1,
   why="Only at one output does a given plant achieve the long-run minimum."),
 dict(q="A short-run ATC curve can never lie below the LRATC curve because", choices=[
   "fixed costs are higher in the long run",
   "the long-run curve already reflects the cheapest possible plant size for every output",
   "marginal cost is lower in the short run",
   "output is smaller in the short run",
   "firms always make losses in the short run"], ans=1,
   why="LRATC is the minimum by construction."),
 dict(q="A firm producing in the region of economies of scale can lower its average cost by", choices=[
   "reducing output",
   "expanding its scale of operations",
   "raising its price",
   "hiring fewer workers only",
   "shutting down"], ans=1,
   why="LRATC is still falling, so a larger scale is cheaper per unit."),
 dict(q="If a firm doubles all inputs and its total cost doubles while output more than doubles, its long-run average cost", choices=[
   "rises", "falls", "stays the same", "becomes zero", "cannot be computed"], ans=1,
   why="Cost per unit falls when output grows faster than cost."),
 dict(q="A firm uses 10 workers and 5 machines to produce 100 units. It moves to 20 workers and 10 machines and produces 220 units. This firm has", choices=[
   "decreasing returns to scale",
   "increasing returns to scale",
   "constant returns to scale",
   "diminishing marginal returns",
   "no economies of scale"], ans=1,
   why="Inputs doubled but output rose 120%, more than proportionally."),
 dict(q="A firm uses 8 workers and 4 machines to make 200 units. With 16 workers and 8 machines it makes 400 units. This firm has", choices=[
   "increasing returns to scale",
   "constant returns to scale",
   "decreasing returns to scale",
   "diseconomies of scale",
   "diminishing marginal returns"], ans=1,
   why="Inputs and output both doubled."),
 dict(q="A firm uses 6 workers and 3 machines to make 90 units. With 12 workers and 6 machines it makes 150 units. This firm has", choices=[
   "increasing returns to scale",
   "constant returns to scale",
   "decreasing returns to scale",
   "economies of scale",
   "increasing marginal returns"], ans=2,
   why="Inputs doubled but output rose only about 67%."),
 dict(q="Which of the following is a long-run adjustment for a firm?", choices=[
   "hiring an extra shift of workers",
   "building a second factory",
   "buying more raw materials this week",
   "paying overtime",
   "running the existing machines longer"], ans=1,
   why="Changing plant size is the defining long-run decision."),
 dict(q="Which of the following is a short-run adjustment?", choices=[
   "closing one of three plants permanently",
   "adding a night shift at the existing plant",
   "constructing a new distribution center",
   "exiting the industry",
   "replacing the entire capital stock"], ans=1,
   why="Adding labor to a fixed plant is a short-run change."),
 dict(q="If LRATC is $8 at 1,000 units and $6 at 2,000 units, the firm is experiencing", choices=[
   "diseconomies of scale",
   "economies of scale",
   "constant returns to scale",
   "diminishing marginal returns",
   "rising marginal cost"], ans=1,
   why="Average cost falls as output rises."),
 dict(q="If LRATC is $5 at 5,000 units and $7 at 9,000 units, the firm is experiencing", choices=[
   "economies of scale",
   "diseconomies of scale",
   "constant returns to scale",
   "increasing returns to scale",
   "a fall in fixed cost"], ans=1,
   why="Average cost rises with output."),
 dict(q="In the long run, if a competitive firm cannot cover its total costs, it will", choices=[
   "continue producing indefinitely",
   "exit the industry",
   "raise its price above the market price",
   "reduce fixed cost to zero and stay",
   "increase output"], ans=1,
   why="With all costs avoidable in the long run, a loss means exit."),
 dict(q="Which of the following would shift a firm's LRATC curve downward?", choices=[
   "an increase in the wage rate",
   "a technological improvement that reduces the inputs needed per unit of output",
   "an increase in the price of capital",
   "a new tax on output",
   "a fall in market demand"], ans=1,
   why="Better technology lowers the cost of every output level."),
 dict(q="Which of the following would shift a firm's LRATC curve upward?", choices=[
   "cheaper raw materials",
   "an increase in the price of a key input",
   "a productivity-raising innovation",
   "expanding to minimum efficient scale",
   "a decrease in the wage rate"], ans=1,
   why="Higher input prices raise average cost at every output."),
 dict(q="Economies of scale are best measured by comparing", choices=[
   "total cost at two different prices",
   "long-run average total cost at two different levels of output",
   "marginal cost and marginal revenue",
   "average fixed cost and average variable cost",
   "total revenue and total cost"], ans=1,
   why="Scale economies are about how per-unit cost varies with the size of operations."),
 dict(q="Constant returns to scale over a wide range of output implies that", choices=[
   "only one firm can survive",
   "firms of many different sizes can compete on equal cost terms",
   "the LRATC curve slopes downward",
   "the industry is a natural monopoly",
   "marginal cost is zero"], ans=1,
   why="A flat LRATC gives no cost advantage to any particular size."),
 dict(q="Bulk discounts on inputs available only to large purchasers are a source of", choices=[
   "diseconomies of scale",
   "economies of scale",
   "diminishing marginal returns",
   "increasing marginal cost",
   "fixed cost"], ans=1,
   why="Lower input prices at high volume reduce average cost as the firm grows."),
 dict(q="An automaker's assembly line, which is only worth its cost at very high production volumes, illustrates", choices=[
   "diminishing returns",
   "economies of scale",
   "diseconomies of scale",
   "constant returns to scale",
   "a sunk cost"], ans=1,
   why="Expensive specialized capital lowers per-unit cost only at large scale."),
 dict(q="Layers of middle management slowing decisions at a very large corporation illustrates", choices=[
   "economies of scale",
   "diseconomies of scale",
   "increasing returns to scale",
   "minimum efficient scale",
   "diminishing marginal product of capital"], ans=1,
   why="Coordination costs that grow with size raise long-run average cost."),
 dict(q="If a firm is producing beyond its minimum efficient scale in the region of diseconomies, it could lower average cost by", choices=[
   "expanding further",
   "reducing its scale of operations",
   "raising its price",
   "increasing fixed cost",
   "hiring more managers"], ans=1,
   why="On the upward-sloping part of LRATC, shrinking moves the firm toward the minimum."),
 dict(q="In the long run, a competitive firm's plant size will tend toward the size that", choices=[
   "maximizes total output",
   "produces at the minimum of long-run average total cost",
   "maximizes fixed cost",
   "minimizes marginal cost",
   "eliminates variable cost"], ans=1,
   why="Competition drives price to minimum LRATC, so surviving firms operate there."),
 dict(q="A firm's total cost of producing 500 units in the long run is $10,000. Its long-run average total cost is", choices=[
   "$2", "$5", "$20", "$50", "$200"], ans=2,
   why="LRATC = 10,000/500 = $20."),
 dict(q="A firm's LRATC is $30 at 400 units. Its long-run total cost is", choices=[
   "$430", "$1,200", "$12,000", "$13.33", "$120"], ans=2,
   why="TC = 30 × 400 = $12,000."),
 dict(q="Which statement about the long run is correct?", choices=[
   "Some inputs remain fixed.",
   "Firms can enter or leave the industry.",
   "Marginal cost is always zero.",
   "Average fixed cost is positive.",
   "Plant size cannot be changed."], ans=1,
   why="Entry and exit are possible precisely because all commitments are adjustable."),
 dict(q="The distinction between the short run and the long run depends on", choices=[
   "a fixed number of calendar months",
   "whether the firm can adjust all of its inputs",
   "whether the firm earns a profit",
   "whether the market is competitive",
   "the level of market demand"], ans=1,
   why="The definition is about input flexibility, and its calendar length differs by industry."),
 dict(q="For a software firm that can rent additional server capacity within a day, the long run is", choices=[
   "many years",
   "very short, because its capital can be adjusted almost immediately",
   "exactly one year",
   "the same as for a steel mill",
   "undefined"], ans=1,
   why="The long run arrives as soon as every input becomes adjustable."),
 dict(q="Two firms in the same industry produce at very different scales and have the same average cost. This suggests", choices=[
   "strong economies of scale",
   "constant returns to scale over that range of output",
   "diseconomies of scale",
   "a natural monopoly",
   "diminishing marginal returns"], ans=1,
   why="Equal average cost at different sizes describes a flat LRATC."),
 dict(q="Which of the following best explains why LRATC lies below short-run ATC at most output levels?", choices=[
   "Long-run costs omit labor costs.",
   "In the long run the firm can choose the plant size best suited to the output it wants to produce.",
   "Fixed costs are higher in the long run.",
   "Marginal cost is lower in the long run.",
   "Output is always larger in the long run."], ans=1,
   why="Flexibility can only help, so the long-run cost is never higher."),
 dict(q="A firm currently producing at minimum efficient scale that expects permanent growth in demand should", choices=[
   "keep its plant unchanged and accept rising short-run costs",
   "consider building a larger plant only if LRATC does not rise at the higher output",
   "always build a larger plant regardless of LRATC",
   "exit the industry",
   "reduce output"], ans=1,
   why="Expansion lowers cost only where the long-run curve is flat or still falling."),
]
