# 4.4 Monopolistic Competition — 50 questions
TOPIC = ("4.4", "Monopolistic Competition", 4)
MCOMP = dict(headers=["Firm", "Price", "ATC", "Minimum ATC"],
             rows=[["J", "$14", "$11", "$9"], ["K", "$12", "$12", "$10"],
                   ["L", "$8", "$11", "$9"]])
QUESTIONS = [
 dict(q="Monopolistic competition is characterized by", choices=[
   "one seller and blocked entry",
   "many firms selling differentiated products with free entry and exit",
   "a few interdependent firms",
   "many firms selling identical products",
   "a single buyer"], ans=1,
   why="Many sellers, differentiated products, and easy entry define the structure."),
 dict(q="The feature that distinguishes monopolistic competition from perfect competition is", choices=[
   "the number of firms",
   "product differentiation, which gives each firm a downward-sloping demand curve",
   "free entry",
   "profit maximization",
   "the presence of fixed costs"], ans=1,
   why="Everything else is shared; differentiation is the difference."),
 dict(q="The feature that distinguishes monopolistic competition from monopoly is", choices=[
   "the downward-sloping demand curve",
   "free entry, which drives long-run economic profit to zero",
   "profit maximization at MR = MC",
   "the existence of marginal cost",
   "the ability to set a price"], ans=1,
   why="A monopoly is protected by barriers; a monopolistic competitor is not."),
 dict(q="A monopolistically competitive firm's demand curve is", choices=[
   "horizontal",
   "downward sloping but more elastic than a monopolist's, because close substitutes exist",
   "vertical",
   "perfectly inelastic",
   "identical to market demand"], ans=1,
   why="Rivals' similar products make buyers responsive to its price."),
 dict(q="In the short run, a monopolistically competitive firm can earn", choices=[
   "only zero economic profit",
   "positive economic profit, zero profit, or a loss",
   "only losses",
   "only positive profit",
   "no revenue"], ans=1,
   why="Before entry or exit occurs, any of the three outcomes is possible."),
 dict(q="In the long run, a monopolistically competitive firm earns", choices=[
   "positive economic profit", "zero economic profit", "large losses", "monopoly profit", "zero revenue"], ans=1,
   why="Free entry and exit competes economic profit away."),
 dict(q="Using the table, Firm J is currently", table=MCOMP, choices=[
   "earning zero economic profit", "earning a positive economic profit", "incurring a loss",
   "in long-run equilibrium", "producing at minimum ATC"], ans=1,
   why="Price of $14 exceeds average total cost of $11."),
 dict(q="Using the table, we expect the market containing Firm J to see", table=MCOMP, choices=[
   "firms exit", "new firms enter with similar products", "no change", "price rise further", "barriers to entry appear"], ans=1,
   why="Positive economic profit attracts entry when entry is free."),
 dict(q="Using the table, Firm K is", table=MCOMP, choices=[
   "earning a profit",
   "in long-run equilibrium, with price equal to average total cost",
   "incurring a loss",
   "producing at minimum average total cost",
   "about to shut down"], ans=1,
   why="P = ATC means zero economic profit."),
 dict(q="Using the table, Firm K is NOT productively efficient because", table=MCOMP, choices=[
   "it earns a profit",
   "its $12 average total cost is above its $10 minimum average total cost",
   "price exceeds marginal cost",
   "it has no fixed costs",
   "it produces too much"], ans=1,
   why="It operates on the downward-sloping part of ATC, left of the minimum."),
 dict(q="Using the table, Firm L is", table=MCOMP, choices=[
   "earning a profit", "incurring an economic loss", "in long-run equilibrium",
   "productively efficient", "allocatively efficient"], ans=1,
   why="Price of $8 is below average total cost of $11."),
 dict(q="Using the table, we expect the market containing Firm L to see", table=MCOMP, choices=[
   "entry of new firms", "exit of firms, raising the demand faced by those that remain", "no change",
   "prices fall further permanently", "barriers to entry rise"], ans=1,
   why="Losses drive exit, which shifts remaining firms' demand curves rightward."),
 dict(q="In long-run equilibrium, a monopolistically competitive firm's demand curve is", choices=[
   "above its average total cost curve",
   "tangent to its average total cost curve",
   "below its average total cost curve at every point",
   "horizontal",
   "identical to its marginal revenue curve"], ans=1,
   why="Tangency is exactly the condition P = ATC with no profit available anywhere."),
 dict(q="At the long-run equilibrium of a monopolistically competitive firm, price is", choices=[
   "equal to marginal cost",
   "above marginal cost, so the outcome is allocatively inefficient",
   "below marginal cost",
   "equal to marginal revenue",
   "at its minimum"], ans=1,
   why="MR = MC with MR below price leaves P above MC."),
 dict(q="Excess capacity in monopolistic competition means the firm produces", choices=[
   "more than the output at minimum average total cost",
   "less than the output at minimum average total cost",
   "exactly at minimum average total cost",
   "nothing at all",
   "at maximum average total cost"], ans=1,
   why="The tangency occurs on the falling portion of the ATC curve."),
 dict(q="Excess capacity arises in monopolistic competition because", choices=[
   "firms collude",
   "each firm faces a downward-sloping demand curve, so tangency with ATC occurs to the left of its minimum",
   "entry is blocked",
   "marginal cost is zero",
   "products are identical"], ans=1,
   why="A downward-sloping demand curve cannot be tangent to ATC at the minimum."),
 dict(q="Compared with perfect competition, monopolistic competition in the long run has", choices=[
   "lower prices and larger output per firm",
   "higher prices and smaller output per firm",
   "identical prices and output",
   "zero output",
   "larger economic profit"], ans=1,
   why="The markup over marginal cost and excess capacity are both present."),
 dict(q="Monopolistic competition is NOT productively efficient because firms", choices=[
   "earn positive long-run profit",
   "do not produce at the minimum of average total cost",
   "produce where P = MC",
   "have no fixed costs",
   "sell identical goods"], ans=1,
   why="Productive efficiency requires production at minimum ATC."),
 dict(q="Monopolistic competition is NOT allocatively efficient because", choices=[
   "firms earn profit in the long run",
   "price exceeds marginal cost at the chosen output",
   "average cost is minimized",
   "there are too few firms",
   "entry is blocked"], ans=1,
   why="Some units worth more than their cost go unproduced."),
 dict(q="One benefit of monopolistic competition that offsets its inefficiency is", choices=[
   "lower prices than perfect competition",
   "product variety, since differentiation gives consumers a range of choices",
   "the absence of advertising",
   "zero fixed costs",
   "guaranteed profits"], ans=1,
   why="Variety has genuine value even though it costs something in efficiency."),
 dict(q="Advertising in monopolistic competition is used mainly to", choices=[
   "reduce production costs",
   "differentiate the product and make the firm's demand curve less elastic",
   "eliminate market power",
   "increase competitors' sales",
   "lower the market price"], ans=1,
   why="Stronger brand attachment reduces buyers' sensitivity to the firm's price."),
 dict(q="Critics of advertising argue that it", choices=[
   "always lowers prices",
   "can raise costs and create artificial differences without improving the product",
   "eliminates product variety",
   "is required by law",
   "reduces market power"], ans=1,
   why="Resources spent on persuasion may add no real value."),
 dict(q="Defenders of advertising argue that it", choices=[
   "raises prices",
   "provides consumers with information and helps new entrants challenge incumbents",
   "reduces the number of firms",
   "eliminates competition",
   "always misleads consumers"], ans=1,
   why="Information lowers search costs and can make entry viable."),
 dict(q="A monopolistically competitive firm maximizes profit where", choices=[
   "price equals marginal cost",
   "marginal revenue equals marginal cost",
   "price equals average total cost",
   "total revenue is maximized",
   "average cost is minimized"], ans=1,
   why="MR = MC is the rule for every profit-maximizing firm."),
 dict(q="Which of the following is a real-world example of monopolistic competition?", choices=[
   "municipal water supply", "hair salons", "commercial aircraft manufacturing", "wheat farming", "electricity transmission"], ans=1,
   why="Many salons compete, each offering a somewhat distinct service."),
 dict(q="Which of the following is NOT an example of monopolistic competition?", choices=[
   "restaurants", "clothing boutiques", "the only piped water utility in a town", "coffee shops", "gyms"], ans=2,
   why="A sole water utility is a monopoly, not a market of many differentiated sellers."),
 dict(q="Entry into a monopolistically competitive market causes an existing firm's demand curve to", choices=[
   "shift rightward and become less elastic",
   "shift leftward and become more elastic",
   "become horizontal",
   "become vertical",
   "remain unchanged"], ans=1,
   why="New substitutes take away sales and make buyers more price-sensitive."),
 dict(q="Exit from a monopolistically competitive market causes a surviving firm's demand curve to", choices=[
   "shift leftward", "shift rightward, restoring profitability toward zero", "become horizontal", "disappear", "become perfectly elastic"], ans=1,
   why="Fewer substitutes means more demand for each remaining firm."),
 dict(q="A monopolistically competitive firm sells 300 units at $9 with an average total cost of $7. Its short-run profit is", choices=[
   "$2", "$300", "$600", "$2,100", "$2,700"], ans=2,
   why="(9 − 7) × 300 = $600."),
 dict(q="A monopolistically competitive firm sells 150 units at $10 with an average total cost of $13. It is", choices=[
   "earning $450", "losing $450", "breaking even", "earning $1,500", "losing $3"], ans=1,
   why="(10 − 13) × 150 = −$450."),
 dict(q="In long-run equilibrium a monopolistically competitive firm has price equal to", choices=[
   "marginal cost", "average total cost, though not the minimum of it", "marginal revenue", "average variable cost", "zero"], ans=1,
   why="Tangency of demand and ATC occurs left of the ATC minimum."),
 dict(q="Compared with a monopoly, a monopolistically competitive firm has", choices=[
   "more market power", "less market power, because close substitutes are available", "the same market power",
   "no market power at all", "a horizontal demand curve"], ans=1,
   why="Substitutes make its demand curve flatter."),
 dict(q="Compared with a perfectly competitive firm, a monopolistically competitive firm has", choices=[
   "no market power", "some market power, because its product is differentiated", "identical demand curves",
   "a horizontal demand curve", "less product variety"], ans=1,
   why="Differentiation allows it to raise price without losing every buyer."),
 dict(q="Non-price competition in monopolistic competition includes", choices=[
   "cutting price below marginal cost",
   "improving quality, service, location, and brand image",
   "colluding on price",
   "eliminating fixed costs",
   "producing at minimum average cost"], ans=1,
   why="Firms compete on the dimensions that differentiate them."),
 dict(q="A monopolistically competitive firm that raises its price will", choices=[
   "lose all its customers immediately",
   "lose some customers to close substitutes but retain those who prefer its product",
   "lose no customers",
   "gain customers",
   "be forced to exit"], ans=1,
   why="A downward-sloping but relatively elastic demand curve is exactly this situation."),
 dict(q="Product differentiation can be based on", choices=[
   "physical characteristics only",
   "physical characteristics, location, service, and perceived image",
   "price alone",
   "cost alone",
   "the number of firms"], ans=1,
   why="Anything that makes buyers see the products as distinct counts."),
 dict(q="The deadweight loss in monopolistic competition is generally", choices=[
   "larger than under monopoly",
   "smaller than under monopoly, because substitutes limit the markup",
   "zero",
   "the same as under monopoly",
   "negative"], ans=1,
   why="More elastic demand means a smaller gap between price and marginal cost."),
 dict(q="Which of the following is true in long-run equilibrium for both perfect competition and monopolistic competition?", choices=[
   "price equals marginal cost",
   "economic profit is zero",
   "firms produce at minimum average total cost",
   "products are identical",
   "demand curves are horizontal"], ans=1,
   why="Free entry gives both zero profit; only perfect competition also gives P = MC and minimum ATC."),
 dict(q="Which is true in long-run equilibrium for monopolistic competition but not perfect competition?", choices=[
   "zero economic profit",
   "price exceeds marginal cost",
   "firms maximize profit",
   "entry is free",
   "many firms operate"], ans=1,
   why="Differentiation is what puts a wedge between price and marginal cost."),
 dict(q="A monopolistically competitive firm's marginal revenue curve lies", choices=[
   "above its demand curve", "below its demand curve", "on its demand curve", "horizontally at price", "vertically"], ans=1,
   why="A downward-sloping demand curve always puts MR below P."),
 dict(q="If a monopolistically competitive market has too many firms relative to the efficient number, the result is", choices=[
   "lower prices",
   "excess capacity, with each firm producing below the minimum-cost scale",
   "productive efficiency",
   "zero variety",
   "monopoly profit"], ans=1,
   why="The market is split among more firms than the cost-minimizing scale would support."),
 dict(q="A firm in monopolistic competition earning short-run economic profit should expect that profit to", choices=[
   "persist indefinitely",
   "erode as new differentiated competitors enter",
   "grow over time",
   "become monopoly profit",
   "be protected by patents"], ans=1,
   why="Nothing prevents rivals from entering with their own version."),
 dict(q="The main reason a monopolistically competitive firm cannot behave like a monopolist in the long run is", choices=[
   "its costs are higher",
   "entry by rivals offering close substitutes limits how much it can charge",
   "it cannot set a price",
   "it faces horizontal demand",
   "it has no fixed costs"], ans=1,
   why="Free entry, not the demand curve's shape, is the binding constraint."),
 dict(q="A monopolistically competitive firm producing where MR = MC finds P > ATC. In the long run", choices=[
   "this profit persists",
   "entry shifts its demand curve left until price falls to average total cost",
   "the firm becomes a monopoly",
   "it must exit",
   "price rises further"], ans=1,
   why="Entry continues while a profit remains to be competed for."),
 dict(q="Total surplus in a monopolistically competitive market is", choices=[
   "maximized",
   "below the maximum, though the value consumers place on variety partly offsets this",
   "zero",
   "negative",
   "identical to a monopoly's"], ans=1,
   why="The P > MC markup costs surplus, but variety has value not captured in the simple comparison."),
 dict(q="A restaurant that develops a signature dish no competitor offers has effectively", choices=[
   "eliminated its fixed costs",
   "made its demand curve less elastic",
   "become a price taker",
   "achieved productive efficiency",
   "eliminated deadweight loss"], ans=1,
   why="A distinctive product reduces buyers' willingness to substitute away on price."),
 dict(q="Which of the following would make a monopolistically competitive firm's demand curve more elastic?", choices=[
   "a successful branding campaign",
   "the entry of several similar competitors nearby",
   "a patent on its design",
   "stronger customer loyalty",
   "the exit of a rival"], ans=1,
   why="More close substitutes make buyers more price-sensitive."),
 dict(q="In monopolistic competition, the number of firms in long-run equilibrium is determined by", choices=[
   "the government",
   "the point at which entry no longer offers a positive economic profit",
   "the largest firm",
   "the level of fixed cost alone",
   "the elasticity of supply"], ans=1,
   why="Entry stops when there is nothing left to gain."),
 dict(q="Compared with the socially efficient outcome, a monopolistically competitive market produces", choices=[
   "too much output at too low a price",
   "too little output at a price above marginal cost",
   "exactly the efficient output",
   "no output",
   "output at minimum average cost"], ans=1,
   why="P > MC means some worthwhile units are not produced."),
 dict(q="A key trade-off society faces with monopolistic competition is between", choices=[
   "profit and revenue",
   "productive efficiency and the variety of products available to consumers",
   "fixed and variable costs",
   "entry and exit",
   "price and quantity only"], ans=1,
   why="Producing many differentiated goods means none is made at minimum cost scale."),
]
