# 5.2 Changes in Factor Demand and Factor Supply — 50 questions
TOPIC = ("5.2", "Changes in Factor Demand and Factor Supply", 5)
SHIFT = dict(headers=["Event", "Market"],
             rows=[["Demand for the firm's output rises sharply", "labor market for its workers"],
                   ["A new machine doubles output per worker", "that firm's labor market"],
                   ["Immigration adds many workers with a given skill", "that skill's labor market"],
                   ["A licensing rule restricts entry into an occupation", "that occupation's labor market"]])
QUESTIONS = [
 dict(q="An increase in the demand for a firm's product will shift its labor demand curve", choices=[
   "leftward", "rightward", "not at all", "downward along itself", "vertically"], ans=1,
   why="Labor demand is derived from product demand."),
 dict(q="Using the table, the first event shifts labor demand", table=SHIFT, choices=[
   "leftward, lowering the wage", "rightward, raising the wage and employment", "not at all",
   "along the existing curve", "vertically to zero"], ans=1,
   why="Higher product demand raises marginal revenue product at every employment level."),
 dict(q="Using the table, the second event shifts labor demand", table=SHIFT, choices=[
   "leftward, because fewer workers are needed",
   "rightward, because each worker's marginal product and therefore MRP is higher",
   "not at all",
   "only in the long run",
   "downward to zero"], ans=1,
   why="Higher productivity makes each worker worth more to the firm."),
 dict(q="Using the table, the third event shifts labor", table=SHIFT, choices=[
   "demand rightward", "supply rightward, lowering the equilibrium wage", "supply leftward",
   "demand leftward", "neither curve"], ans=1,
   why="More workers available at every wage is an increase in supply."),
 dict(q="Using the table, the fourth event shifts labor", table=SHIFT, choices=[
   "supply rightward", "supply leftward, raising the equilibrium wage", "demand rightward",
   "demand leftward", "neither curve"], ans=1,
   why="A licensing barrier reduces the number of workers who may supply that labor."),
 dict(q="Using the table, which two events raise the equilibrium wage?", table=SHIFT, choices=[
   "the first and third", "the first and fourth", "the second and third", "the third and fourth", "all four"], ans=1,
   why="Rising demand and falling supply both push the wage up."),
 dict(q="An increase in labor demand, holding supply constant, causes the equilibrium wage to", choices=[
   "fall and employment to fall", "rise and employment to rise", "rise and employment to fall",
   "fall and employment to rise", "stay constant"], ans=1,
   why="Demand shifting right along an upward-sloping supply curve raises both."),
 dict(q="A decrease in labor demand, holding supply constant, causes", choices=[
   "the wage and employment to rise",
   "the wage and employment to fall",
   "the wage to rise and employment to fall",
   "no change",
   "supply to shift"], ans=1,
   why="Demand shifting left along the supply curve lowers both."),
 dict(q="An increase in labor supply, holding demand constant, causes", choices=[
   "the wage to rise and employment to fall",
   "the wage to fall and employment to rise",
   "both to rise",
   "both to fall",
   "no change"], ans=1,
   why="Supply shifting right moves down along the demand curve."),
 dict(q="A decrease in labor supply, holding demand constant, causes", choices=[
   "the wage to fall and employment to rise",
   "the wage to rise and employment to fall",
   "both to rise",
   "both to fall",
   "no change"], ans=1,
   why="Fewer workers available moves up along the demand curve."),
 dict(q="Which of the following shifts labor demand rather than labor supply?", choices=[
   "a change in the number of qualified workers",
   "a change in the productivity of workers",
   "immigration",
   "a change in workers' preferences for leisure",
   "a change in wages in a competing occupation"], ans=1,
   why="Productivity enters MRP, which is the demand curve."),
 dict(q="Which of the following shifts labor supply rather than labor demand?", choices=[
   "a change in the price of the firm's output",
   "a change in the number of workers with the required skill",
   "a change in worker productivity",
   "a change in the demand for the product",
   "a technological improvement raising output per worker"], ans=1,
   why="The number of available workers is a supply determinant."),
 dict(q="The three main determinants of labor demand are", choices=[
   "wages, hours, and benefits",
   "product demand, worker productivity, and the prices of other inputs",
   "immigration, education, and taxes",
   "the wage, the number of workers, and leisure",
   "supply, demand, and price"], ans=1,
   why="Each changes marginal revenue product or the attractiveness of substitutes."),
 dict(q="If the price of a machine that substitutes for labor falls sharply, labor demand will most likely", choices=[
   "rise", "fall, as firms substitute capital for workers", "stay the same", "become vertical", "become perfectly elastic"], ans=1,
   why="Cheaper substitutes draw firms away from labor."),
 dict(q="If a machine and labor are complements and the machine becomes cheaper, labor demand will most likely", choices=[
   "fall", "rise, because more machines mean more work for the workers who operate them", "stay the same",
   "become perfectly inelastic", "fall to zero"], ans=1,
   why="Complementary inputs are used together, so more of one raises demand for the other."),
 dict(q="An increase in the productivity of workers in an industry will", choices=[
   "lower the wage and employment",
   "raise labor demand, tending to raise the wage and employment",
   "shift labor supply left",
   "have no effect",
   "shift labor supply right"], ans=1,
   why="Higher MRP means each worker is worth more."),
 dict(q="Which of the following would increase the supply of nurses?", choices=[
   "stricter licensing requirements",
   "a large expansion in the number of nursing school places",
   "a fall in nurses' wages",
   "a rise in demand for healthcare",
   "an increase in nurse productivity"], ans=1,
   why="More trained entrants means more nurses available at every wage."),
 dict(q="Which of the following would decrease the supply of electricians?", choices=[
   "an increase in apprenticeship places",
   "a sharp rise in the wage in a competing trade that electricians could enter",
   "an increase in construction activity",
   "a rise in electrician productivity",
   "a fall in the cost of tools"], ans=1,
   why="Better opportunities elsewhere draw workers out of this occupation."),
 dict(q="A rise in the wage paid in a competing occupation will shift the supply of workers to the original occupation", choices=[
   "rightward", "leftward", "not at all", "vertically", "along the same curve"], ans=1,
   why="Some workers move to the better-paying alternative."),
 dict(q="Which of the following is a movement along the labor supply curve rather than a shift?", choices=[
   "immigration of new workers",
   "a change in the wage offered in this market",
   "a change in workers' preferences",
   "a new licensing requirement",
   "a change in training costs"], ans=1,
   why="The market's own wage is the variable on the axis."),
 dict(q="An increase in immigration of workers with a particular skill will, in that labor market,", choices=[
   "raise the wage", "lower the equilibrium wage and raise employment", "lower employment", "shift demand right", "have no effect"], ans=1,
   why="Supply shifting right moves down the demand curve."),
 dict(q="If both labor demand and labor supply increase, the equilibrium wage", choices=[
   "definitely rises", "may rise, fall, or stay the same depending on the relative sizes of the shifts", "definitely falls",
   "is unchanged", "becomes undefined"], ans=1,
   why="The two shifts push the wage in opposite directions while both raise employment."),
 dict(q="If both labor demand and labor supply increase, equilibrium employment", choices=[
   "definitely rises", "definitely falls", "is indeterminate", "is unchanged", "becomes zero"], ans=0,
   why="Both shifts raise the quantity of labor traded."),
 dict(q="If labor demand rises and labor supply falls, the equilibrium wage", choices=[
   "definitely falls", "definitely rises", "is indeterminate", "is unchanged", "becomes zero"], ans=1,
   why="Both shifts push the wage upward; employment is the indeterminate variable."),
 dict(q="If labor demand rises and labor supply falls, equilibrium employment", choices=[
   "definitely rises", "definitely falls", "is indeterminate", "is unchanged", "doubles"], ans=2,
   why="Demand pushes employment up while supply pushes it down."),
 dict(q="An increase in the cost of training for an occupation will, over time,", choices=[
   "increase supply and lower the wage",
   "decrease supply and raise the wage",
   "increase demand",
   "decrease demand",
   "have no effect"], ans=1,
   why="Fewer workers find the investment worthwhile."),
 dict(q="Occupations requiring long and costly training tend to pay more because", choices=[
   "demand is always higher",
   "the supply of qualified workers is limited by the cost and time of acquiring the skill",
   "governments mandate it",
   "productivity is irrelevant",
   "such jobs are always pleasant"], ans=1,
   why="Restricted supply raises the equilibrium wage."),
 dict(q="A compensating wage differential is extra pay offered for", choices=[
   "higher productivity",
   "undesirable job characteristics such as danger or unsociable hours",
   "longer tenure",
   "additional education",
   "working in a large firm"], ans=1,
   why="The extra pay compensates for the disamenity."),
 dict(q="Which of the following would most likely require a compensating wage differential?", choices=[
   "an office job with flexible hours",
   "underwater welding on offshore platforms",
   "a role with generous holidays",
   "a job near the worker's home",
   "a well-lit, comfortable workplace"], ans=1,
   why="Danger and difficult conditions reduce labor supply to that occupation at any given wage."),
 dict(q="A labor union that successfully restricts entry into an occupation will", choices=[
   "increase supply and lower the wage",
   "reduce supply and raise the wage for those employed",
   "increase demand",
   "have no effect on wages",
   "lower the wage and raise employment"], ans=1,
   why="Restricted supply moves up along the demand curve."),
 dict(q="A union that succeeds in raising productivity would shift labor", choices=[
   "supply rightward", "demand rightward, raising both wages and employment", "demand leftward",
   "supply leftward", "neither curve"], ans=1,
   why="Higher MRP raises what employers will pay at every employment level."),
 dict(q="An increase in the demand for houses would, in the market for construction workers,", choices=[
   "shift labor supply right", "shift labor demand right, raising wages", "shift labor demand left",
   "lower construction wages", "have no effect"], ans=1,
   why="Derived demand rises with the demand for the final product."),
 dict(q="A fall in the demand for printed newspapers would, in the market for print journalists,", choices=[
   "raise the wage", "shift labor demand leftward, lowering wages and employment", "shift supply right",
   "shift supply left", "have no effect"], ans=1,
   why="Falling product demand lowers derived labor demand."),
 dict(q="The market supply curve for labor may bend backward at very high wages because", choices=[
   "workers become less productive",
   "at high enough income, workers may choose more leisure rather than more hours",
   "firms stop hiring",
   "demand falls",
   "wages cannot rise further"], ans=1,
   why="The income effect can eventually outweigh the substitution effect."),
 dict(q="Along the upward-sloping portion of an individual's labor supply curve, the substitution effect", choices=[
   "is weaker than the income effect",
   "outweighs the income effect, so a higher wage brings more hours worked",
   "is zero",
   "makes leisure cheaper",
   "reduces hours worked"], ans=1,
   why="A higher wage makes leisure more expensive relative to work."),
 dict(q="A government subsidy paid to firms per worker hired will shift labor demand", choices=[
   "leftward", "rightward, raising employment", "not at all", "vertically to zero", "along the curve"], ans=1,
   why="The subsidy lowers the effective cost of each worker."),
 dict(q="A payroll tax paid by employers per worker will shift labor demand", choices=[
   "rightward", "leftward, reducing employment", "not at all", "vertically upward", "along the curve"], ans=1,
   why="It raises the cost of hiring at every wage."),
 dict(q="An improvement in general education levels in an economy will most likely", choices=[
   "reduce the supply of skilled workers",
   "increase the supply of skilled workers and raise their productivity",
   "reduce labor demand",
   "have no effect on any market",
   "lower total output"], ans=1,
   why="It changes both the number of qualified workers and their marginal product."),
 dict(q="A binding minimum wage set above the competitive equilibrium in a labor market causes", choices=[
   "a shortage of labor",
   "a surplus of labor, since quantity supplied exceeds quantity demanded",
   "no change in employment",
   "the demand curve to shift",
   "the supply curve to shift"], ans=1,
   why="A price floor above equilibrium leaves unemployed workers willing to work at that wage."),
 dict(q="A minimum wage set below the competitive equilibrium wage will", choices=[
   "cause unemployment", "have no effect on the market", "raise wages", "lower employment", "shift demand"], ans=1,
   why="A non-binding floor leaves the market at its own equilibrium."),
 dict(q="If the wage in a competitive labor market is above equilibrium, we expect", choices=[
   "a shortage that pushes the wage up",
   "a surplus that pushes the wage down toward equilibrium",
   "no adjustment",
   "demand to shift right",
   "supply to shift left"], ans=1,
   why="Excess supply of labor bids the wage down."),
 dict(q="A technological change that makes workers redundant in one industry generally", choices=[
   "raises labor demand in that industry",
   "lowers labor demand there while potentially raising it in industries that use the new technology",
   "has no effect anywhere",
   "raises wages in that industry",
   "shifts labor supply"], ans=1,
   why="Substitution reduces demand in one market and complementarity can raise it elsewhere."),
 dict(q="Wages differ across regions in the same occupation largely because of differences in", choices=[
   "the length of the workday",
   "local labor demand, local labor supply, and the cost of living",
   "national law only",
   "worker preferences alone",
   "the product price alone"], ans=1,
   why="Both sides of each regional market differ."),
 dict(q="The demand for capital, like the demand for labor, is determined by", choices=[
   "its own price only",
   "the marginal revenue product of capital compared with its rental price",
   "the wage rate",
   "the number of workers",
   "the level of fixed cost"], ans=1,
   why="The same MRP = input price rule applies to every factor."),
 dict(q="A firm will rent an additional machine as long as", choices=[
   "the machine's marginal product is positive",
   "the machine's marginal revenue product is at least its rental price",
   "the machine is cheaper than a worker",
   "output rises",
   "profit is positive"], ans=1,
   why="The comparison is between what the machine adds and what it costs."),
 dict(q="Economic rent to a factor is the payment above", choices=[
   "the factor's marginal product",
   "the minimum amount needed to keep the factor in its present use",
   "the market wage",
   "average revenue",
   "total cost"], ans=1,
   why="It is the surplus over the factor's opportunity cost."),
 dict(q="A factor in perfectly inelastic supply, such as a fixed quantity of land, earns", choices=[
   "no rent",
   "all of its payment as economic rent, since the quantity supplied does not respond to price",
   "only a normal return",
   "a wage",
   "zero income"], ans=1,
   why="With supply fixed, the whole payment is a surplus over the amount needed to supply it."),
 dict(q="A sudden increase in demand for a factor whose supply is perfectly inelastic will", choices=[
   "raise the quantity supplied",
   "raise its price with no change in quantity",
   "lower its price",
   "leave its price unchanged",
   "shift supply rightward"], ans=1,
   why="A vertical supply curve absorbs the whole demand shift in the price."),
 dict(q="In the long run, labor supply to a particular occupation is generally", choices=[
   "less elastic than in the short run",
   "more elastic than in the short run, since workers have time to train and relocate",
   "perfectly inelastic",
   "perfectly elastic always",
   "downward sloping"], ans=1,
   why="Adjustment takes time, so the long-run response is larger."),
 dict(q="The single best summary of what determines a competitive wage is", choices=[
   "government policy",
   "the interaction of workers' marginal revenue product with the supply of workers able to do the job",
   "firm size",
   "the length of the workweek",
   "the number of firms alone"], ans=1,
   why="Demand reflects productivity and supply reflects scarcity."),
]
