# 6.2 Externalities — 50 questions
# Table verified: negative production externality.
#   Q=80:  private MC $8,  external $3 -> MSC $11 = MB $11  -> socially efficient
#   Q=100: private MC $10, external $3 -> MSC $13 > MB $10
#          but private MC $10 = MB $10 -> this is the market equilibrium
#   Market produces 100, efficiency calls for 80, corrective tax = $3 per unit.
TOPIC = ("6.2", "Externalities", 6)
EXT = dict(headers=["Quantity", "Marginal private cost", "External cost", "Marginal benefit"],
           rows=[["80", "$8", "$3", "$11"], ["100", "$10", "$3", "$10"]])
QUESTIONS = [
 dict(q="An externality is", choices=[
   "a cost paid by the producer",
   "a cost or benefit that falls on someone other than the buyer or seller of a good",
   "a tax",
   "a government subsidy",
   "the price of a good"], ans=1,
   why="It is a spillover onto a third party."),
 dict(q="A negative externality imposes a cost on", choices=[
   "the producer only", "a third party not involved in the transaction", "the buyer only", "the government only", "no one"], ans=1,
   why="Pollution harming nearby residents is the standard example."),
 dict(q="A positive externality confers a benefit on", choices=[
   "the seller only", "a third party not involved in the transaction", "the buyer only", "the government only", "no one"], ans=1,
   why="A vaccinated person protects others who never bought the vaccine."),
 dict(q="With a negative externality, marginal social cost is", choices=[
   "less than marginal private cost",
   "greater than marginal private cost by the amount of the external cost",
   "equal to marginal private cost",
   "zero",
   "equal to marginal benefit"], ans=1,
   why="Society bears the producer's cost plus the spillover."),
 dict(q="With a positive externality, marginal social benefit is", choices=[
   "less than marginal private benefit",
   "greater than marginal private benefit by the amount of the external benefit",
   "equal to marginal private benefit",
   "zero",
   "equal to marginal cost"], ans=1,
   why="Society gains the buyer's benefit plus the spillover."),
 dict(q="A market with a negative externality will", choices=[
   "underproduce relative to the socially efficient quantity",
   "overproduce relative to the socially efficient quantity",
   "produce the efficient quantity",
   "produce nothing",
   "always be regulated"], ans=1,
   why="Producers ignore the external cost, so the good looks cheaper than it is."),
 dict(q="A market with a positive externality will", choices=[
   "overproduce relative to the socially efficient quantity",
   "underproduce relative to the socially efficient quantity",
   "produce the efficient quantity",
   "produce nothing",
   "always be taxed"], ans=1,
   why="Buyers ignore the benefit to others, so they buy too little."),
 dict(q="Using the table, the market equilibrium quantity is", table=EXT, choices=[
   "80", "100", "60", "120", "cannot be determined"], ans=1,
   why="At 100 units the $10 marginal private cost equals the $10 marginal benefit, and the market ignores the external cost."),
 dict(q="Using the table, once the external cost is counted, the quantity society should want is", table=EXT, choices=[
   "80", "100", "120", "60", "zero"], ans=0,
   why="At 80 units marginal social cost is $8 + $3 = $11, exactly the $11 marginal benefit."),
 dict(q="Using the table, marginal social cost at a quantity of 100 is", table=EXT, choices=[
   "$3", "$10", "$11", "$13", "$16"], ans=3,
   why="Private cost of $10 plus the $3 external cost."),
 dict(q="Using the table, at the market quantity of 100 the marginal social cost of $13 exceeds the marginal benefit of $10, which means", table=EXT, choices=[
   "too little is being produced",
   "too much is being produced from society's point of view",
   "the market is efficient",
   "the good should be subsidized",
   "there is no externality"], ans=1,
   why="Those last units cost society more than they are worth."),
 dict(q="Using the table, a corrective tax that would achieve the efficient outcome equals", table=EXT, choices=[
   "$10", "$3, the size of the external cost per unit", "$11", "$13", "$8"], ans=1,
   why="Taxing the externality makes the producer face the full social cost."),
 dict(q="Using the table, the externality shown is", table=EXT, choices=[
   "a positive consumption externality",
   "a negative production externality",
   "a positive production externality",
   "a public good",
   "not an externality"], ans=1,
   why="The spillover is an extra cost attached to producing the good."),
 dict(q="A corrective, or Pigouvian, tax is designed to", choices=[
   "raise revenue only",
   "make the private cost of an activity equal its social cost",
   "increase output",
   "eliminate the market",
   "subsidize producers"], ans=1,
   why="Internalizing the externality restores the efficient quantity."),
 dict(q="A corrective subsidy is used to address", choices=[
   "a negative externality",
   "a positive externality, by encouraging the activity toward the efficient level",
   "market power",
   "a public good only",
   "a price ceiling"], ans=1,
   why="It makes the private benefit equal the social benefit."),
 dict(q="A tax that exactly equals the marginal external cost of an activity will", choices=[
   "eliminate the market",
   "move production to the socially efficient quantity",
   "cause overproduction",
   "create a deadweight loss",
   "have no effect"], ans=1,
   why="It internalizes exactly the spillover and nothing more."),
 dict(q="Which of the following is an example of a negative externality?", choices=[
   "a homeowner planting a beautiful garden",
   "a factory releasing smoke that harms nearby residents",
   "a person getting vaccinated",
   "a student attending university",
   "a firm training its own workers"], ans=1,
   why="The harm falls on people outside the transaction."),
 dict(q="Which of the following is an example of a positive externality?", choices=[
   "traffic congestion",
   "a beekeeper's bees pollinating a neighbouring orchard",
   "noise from a nightclub",
   "water pollution from a plant",
   "second-hand smoke"], ans=1,
   why="The orchard owner benefits without paying for it."),
 dict(q="Second-hand smoke is an example of", choices=[
   "a positive externality", "a negative consumption externality", "a public good", "a subsidy", "market power"], ans=1,
   why="Consuming the cigarette imposes a cost on bystanders."),
 dict(q="Education is often cited as generating a positive externality because", choices=[
   "it costs money",
   "an educated population benefits others through higher productivity and civic participation",
   "students pay tuition",
   "schools are large employers",
   "it takes many years"], ans=1,
   why="Benefits accrue beyond the individual student."),
 dict(q="Vaccination generates a positive externality because", choices=[
   "it is expensive",
   "a vaccinated person reduces the risk of infection for others",
   "the government provides it",
   "it requires a doctor",
   "it is unpleasant"], ans=1,
   why="Others gain protection without buying the vaccine."),
 dict(q="In the presence of a negative externality, the deadweight loss arises from", choices=[
   "the units produced whose social cost exceeds their marginal benefit",
   "the tax revenue collected",
   "producer profit",
   "consumer surplus",
   "the units not produced"], ans=0,
   why="Overproduction beyond the efficient quantity destroys surplus."),
 dict(q="In the presence of a positive externality, the deadweight loss arises from", choices=[
   "overproduction",
   "the units not produced whose social benefit exceeds their cost",
   "government spending",
   "producer profit",
   "the subsidy itself"], ans=1,
   why="Underproduction forgoes valuable units."),
 dict(q="The Coase theorem states that if property rights are well defined and bargaining costs are low", choices=[
   "government regulation is always needed",
   "private parties can negotiate a solution to an externality on their own",
   "externalities cannot be resolved",
   "taxes are the only solution",
   "the market always fails"], ans=1,
   why="Bargaining can internalize the externality without government action."),
 dict(q="The Coase theorem is less useful in practice when", choices=[
   "there are only two parties",
   "many parties are affected and the costs of bargaining are high",
   "property rights are clear",
   "the externality is small",
   "information is perfect"], ans=1,
   why="Transaction costs rise steeply with the number of parties."),
 dict(q="Tradable pollution permits work by", choices=[
   "banning all pollution",
   "capping total emissions and letting firms trade the right to pollute, so reductions occur where they are cheapest",
   "taxing every firm equally",
   "subsidizing polluters",
   "ignoring the externality"], ans=1,
   why="Trading equalizes marginal abatement cost across firms."),
 dict(q="An advantage of tradable permits over a uniform emissions limit is that permits", choices=[
   "allow unlimited pollution",
   "achieve a given reduction at lower total cost",
   "raise no revenue",
   "are simpler to design",
   "eliminate the externality entirely"], ans=1,
   why="Firms with low abatement costs cut more and sell permits to those with high costs."),
 dict(q="Command-and-control regulation addresses externalities by", choices=[
   "using prices",
   "directly mandating or prohibiting specific behaviors or technologies",
   "subsidizing the activity",
   "creating a market for permits",
   "doing nothing"], ans=1,
   why="It specifies what firms must do rather than pricing the harm."),
 dict(q="A criticism of command-and-control regulation compared with a corrective tax is that it", choices=[
   "raises too much revenue",
   "does not let firms find the cheapest way to reduce the harm",
   "is always ineffective",
   "encourages more pollution",
   "requires no enforcement"], ans=1,
   why="A uniform mandate ignores differences in abatement costs."),
 dict(q="A firm producing a good with a negative externality faces a private marginal cost of $14 and an external cost of $6. Marginal social cost is", choices=[
   "$6", "$8", "$14", "$20", "$84"], ans=3,
   why="14 + 6 = $20."),
 dict(q="A good with a private marginal benefit of $9 and an external benefit of $4 has a marginal social benefit of", choices=[
   "$4", "$5", "$9", "$13", "$36"], ans=3,
   why="9 + 4 = $13."),
 dict(q="If the marginal external cost of a good is $5 per unit, the corrective tax should be", choices=[
   "$0", "$5 per unit", "$10 per unit", "$2.50 per unit", "as large as possible"], ans=1,
   why="The tax matches the external cost so private and social cost coincide."),
 dict(q="If the marginal external benefit of a good is $7 per unit, the corrective subsidy should be", choices=[
   "$0", "$7 per unit", "$14 per unit", "$3.50 per unit", "as large as possible"], ans=1,
   why="The subsidy matches the external benefit."),
 dict(q="A tax set larger than the marginal external cost will", choices=[
   "achieve the efficient quantity",
   "reduce output below the efficient quantity, creating a new deadweight loss",
   "have no effect",
   "increase output",
   "eliminate the externality"], ans=1,
   why="Over-correcting is as inefficient as not correcting."),
 dict(q="At the socially efficient quantity with an externality present", choices=[
   "marginal private benefit equals marginal private cost",
   "marginal social benefit equals marginal social cost",
   "the externality is zero",
   "total surplus is zero",
   "the market is unregulated"], ans=1,
   why="Efficiency uses the social curves, not the private ones."),
 dict(q="A negative externality causes the market supply curve to lie", choices=[
   "above the marginal social cost curve",
   "below the marginal social cost curve",
   "on the marginal social cost curve",
   "above the demand curve",
   "vertically"], ans=1,
   why="Producers count only their own costs."),
 dict(q="A positive consumption externality causes the market demand curve to lie", choices=[
   "above the marginal social benefit curve",
   "below the marginal social benefit curve",
   "on the marginal social benefit curve",
   "below the supply curve",
   "horizontally"], ans=1,
   why="Buyers count only their own benefit."),
 dict(q="Traffic congestion is an externality because each additional driver", choices=[
   "pays a toll",
   "slows down every other driver without bearing that cost",
   "reduces fuel use",
   "benefits other drivers",
   "buys a car"], ans=1,
   why="The delay imposed on others is not part of the driver's own calculation."),
 dict(q="A congestion charge on driving into a city centre is best described as", choices=[
   "a subsidy", "a corrective tax on a negative externality", "a price ceiling", "a quota on cars", "a public good"], ans=1,
   why="It makes drivers face the cost they impose on others."),
 dict(q="Research and development is often subsidized because", choices=[
   "firms lose money on it",
   "knowledge spills over to other firms, so the private return is below the social return",
   "it is a public good in every respect",
   "it is unprofitable",
   "governments prefer to fund it"], ans=1,
   why="Positive externalities mean the market underinvests."),
 dict(q="Which of the following is NOT an externality?", choices=[
   "pollution from a factory",
   "a rise in the price of coffee that makes coffee drinkers worse off",
   "a neighbour's loud music",
   "a beautiful garden visible from the street",
   "a vaccinated person reducing infection risk for others"], ans=1,
   why="A price change is a transfer within the market, not a spillover onto a third party."),
 dict(q="A pecuniary effect, such as a price change affecting other buyers, is not an externality because", choices=[
   "it has no effect on anyone",
   "it operates through the market price and is offset by gains to sellers",
   "it is always positive",
   "it is illegal",
   "it involves no money"], ans=1,
   why="Total surplus is unaffected, so there is nothing to correct."),
 dict(q="A market with a negative externality that is corrected by an appropriate tax will have", choices=[
   "a larger deadweight loss than before",
   "the deadweight loss eliminated and the efficient quantity produced",
   "no tax revenue",
   "higher output than before",
   "no change in output"], ans=1,
   why="The tax internalizes exactly the external cost."),
 dict(q="Assigning clear property rights over a resource can reduce externalities because", choices=[
   "it eliminates all costs",
   "the owner has an incentive to consider the resource's full value and can bargain over its use",
   "it raises tax revenue",
   "it bans the activity",
   "it lowers prices"], ans=1,
   why="Ownership internalizes what would otherwise be a spillover."),
 dict(q="The tragedy of the commons arises when", choices=[
   "a resource is privately owned",
   "a rival resource is open to all, so each user ignores the cost imposed on other users",
   "the government owns a resource",
   "a resource is abundant",
   "the resource is excludable"], ans=1,
   why="Non-excludability with rivalry leads to overuse."),
 dict(q="Overfishing in international waters is an example of", choices=[
   "a positive externality", "the tragedy of the commons", "a public good", "monopoly power", "a price floor"], ans=1,
   why="No one can be excluded, and each catch reduces what remains for others."),
 dict(q="A solution to the tragedy of the commons is to", choices=[
   "encourage more use",
   "establish enforceable property rights or usage limits",
   "subsidize the activity",
   "remove all regulation",
   "make the resource free"], ans=1,
   why="Excludability or a cap restores the incentive to conserve."),
 dict(q="A firm that pollutes and faces no penalty has private costs that are", choices=[
   "higher than social costs",
   "lower than social costs, so its output is too large",
   "equal to social costs",
   "zero",
   "the same as marginal benefit"], ans=1,
   why="The unpriced harm is missing from its cost calculation."),
 dict(q="The efficient level of pollution is generally", choices=[
   "zero",
   "positive, where the marginal cost of further abatement equals the marginal benefit of it",
   "as high as possible",
   "impossible to define",
   "determined solely by technology"], ans=1,
   why="Eliminating the last unit of pollution usually costs more than it is worth."),
 dict(q="The main economic argument for taxing an activity with a negative externality rather than banning it is that a tax", choices=[
   "raises more revenue",
   "lets the activity continue where its benefits exceed its full social costs",
   "is easier to enforce always",
   "eliminates the activity faster",
   "avoids all deadweight loss"], ans=1,
   why="A ban forgoes the units that are genuinely worth producing."),
]
