# 6.4 Effects of Government Intervention in Different Market Structures — 50 questions
# Table verified: natural monopoly with falling ATC.
#   Unregulated (MR = MC): Q = 20, P = $50
#   Fair-return (P = ATC):  Q = 40, P = $35, zero economic profit
#   Socially optimal (P = MC): Q = 50, P = $25, ATC $32 so the firm loses $7 per unit
TOPIC = ("6.4", "Effects of Government Intervention in Different Market Structures", 6)
REG = dict(headers=["Pricing rule", "Quantity", "Price", "ATC"],
           rows=[["Unregulated monopoly", "20", "$50", "$40"],
                 ["Fair-return pricing", "40", "$35", "$35"],
                 ["Socially optimal pricing", "50", "$25", "$32"]])
QUESTIONS = [
 dict(q="Antitrust policy is designed to", choices=[
   "protect firms from competition",
   "promote competition by limiting anticompetitive mergers and conduct",
   "set all prices",
   "guarantee firm profits",
   "raise government revenue"], ans=1,
   why="The aim is to preserve competitive market structures."),
 dict(q="A government breaking up a large firm into several competing firms is an example of", choices=[
   "price regulation", "antitrust enforcement", "a subsidy", "a corrective tax", "nationalization"], ans=1,
   why="Restructuring the market is a classic antitrust remedy."),
 dict(q="Blocking a merger between two of the three firms in a market is intended to prevent", choices=[
   "lower prices", "an increase in market concentration and market power", "entry", "innovation", "advertising"], ans=1,
   why="Fewer firms would make coordination easier and competition weaker."),
 dict(q="Using the table, the unregulated monopoly earns a per-unit profit of", table=REG, choices=[
   "$5", "$10", "$25", "$40", "$50"], ans=1,
   why="Price of $50 less average total cost of $40."),
 dict(q="Using the table, the unregulated monopoly's total profit is", table=REG, choices=[
   "$100", "$200", "$400", "$1,000", "$800"], ans=1,
   why="($50 − $40) × 20 = $200."),
 dict(q="Using the table, fair-return pricing sets price equal to", table=REG, choices=[
   "marginal cost", "average total cost", "marginal revenue", "zero", "the unregulated price"], ans=1,
   why="At $35 the price exactly covers average total cost."),
 dict(q="Using the table, under fair-return pricing the firm earns", table=REG, choices=[
   "a large profit", "zero economic profit, or a normal profit", "a loss of $7 per unit", "nothing at all", "the monopoly profit"], ans=1,
   why="Price equals average total cost, so economic profit is zero."),
 dict(q="Using the table, socially optimal pricing sets price equal to", table=REG, choices=[
   "average total cost", "marginal cost", "marginal revenue", "the monopoly price", "average variable cost"], ans=1,
   why="P = MC is the allocatively efficient rule."),
 dict(q="Using the table, under socially optimal pricing the firm", table=REG, choices=[
   "earns a profit of $7 per unit",
   "loses $7 per unit, since the $25 price is below the $32 average total cost",
   "breaks even",
   "earns the monopoly profit",
   "produces nothing"], ans=1,
   why="Marginal cost lies below average cost while average cost is falling."),
 dict(q="Using the table, socially optimal pricing requires a subsidy because", table=REG, choices=[
   "the firm is inefficient",
   "for a natural monopoly with falling average cost, price equal to marginal cost cannot cover average cost",
   "output is too low",
   "consumers refuse to pay",
   "marginal cost is above average cost"], ans=1,
   why="Otherwise the firm would exit rather than sustain the loss."),
 dict(q="Using the table, which pricing rule produces the largest quantity?", table=REG, choices=[
   "unregulated monopoly", "fair-return pricing", "socially optimal pricing", "all are equal", "none produces output"], ans=2,
   why="P = MC yields 50 units, the most of the three."),
 dict(q="Using the table, which pricing rule leaves the smallest deadweight loss?", table=REG, choices=[
   "unregulated monopoly", "fair-return pricing", "socially optimal pricing, which eliminates it", "all are equal", "none"], ans=2,
   why="Producing where price equals marginal cost is the efficient outcome."),
 dict(q="A natural monopoly is best regulated rather than broken up because", choices=[
   "regulation is always cheaper",
   "splitting it into smaller firms would raise average cost, since one firm can serve the market most cheaply",
   "the firm has no costs",
   "consumers prefer one firm",
   "competition is illegal"], ans=1,
   why="Economies of scale run across the whole market."),
 dict(q="A price ceiling imposed on a monopoly at the competitive price will", choices=[
   "reduce output",
   "increase output toward the efficient level",
   "have no effect",
   "cause a shortage immediately",
   "raise the price"], ans=1,
   why="It removes the monopolist's ability to gain by restricting output."),
 dict(q="Unlike in a competitive market, a well-chosen price ceiling in a monopoly can", choices=[
   "always cause a shortage",
   "raise both output and consumer surplus while reducing deadweight loss",
   "reduce output",
   "eliminate the firm's revenue",
   "have no effect on price"], ans=1,
   why="The monopolist was already producing below the efficient quantity."),
 dict(q="A price ceiling set below the monopolist's average total cost will", choices=[
   "raise output",
   "cause the firm to make losses and eventually exit or require a subsidy",
   "have no effect",
   "raise profit",
   "eliminate deadweight loss with no cost"], ans=1,
   why="A firm cannot sustain a price below its cost indefinitely."),
 dict(q="A per-unit tax imposed on a monopolist will", choices=[
   "increase output",
   "raise marginal cost, reducing output and raising price",
   "leave output unchanged",
   "eliminate profit entirely",
   "lower the price"], ans=1,
   why="The tax enters the cost of each unit produced."),
 dict(q="A lump-sum tax imposed on a monopolist will", choices=[
   "reduce output",
   "reduce profit while leaving price and output unchanged in the short run",
   "raise output",
   "raise the price",
   "have no effect on profit"], ans=1,
   why="A fixed payment does not change marginal cost."),
 dict(q="A per-unit tax in a competitive market will", choices=[
   "raise the quantity traded",
   "reduce the quantity traded and create deadweight loss",
   "have no effect",
   "lower the price buyers pay",
   "eliminate producer surplus"], ans=1,
   why="The tax wedge removes trades that were mutually beneficial."),
 dict(q="A per-unit subsidy in a competitive market with no externalities", choices=[
   "eliminates deadweight loss",
   "causes overproduction beyond the efficient quantity, creating deadweight loss",
   "has no effect",
   "reduces output",
   "raises the price buyers pay"], ans=1,
   why="Units whose cost exceeds their benefit get produced."),
 dict(q="A per-unit subsidy in a market with a positive externality can", choices=[
   "always create deadweight loss",
   "move output toward the socially efficient quantity",
   "reduce output",
   "have no effect",
   "eliminate the externality"], ans=1,
   why="It corrects an underproduction problem rather than causing overproduction."),
 dict(q="Which policy directly targets a negative externality?", choices=[
   "a lump-sum tax on the firm",
   "a per-unit tax equal to the marginal external cost",
   "an antitrust breakup",
   "a price ceiling",
   "a production subsidy"], ans=1,
   why="It prices the harm at the point where the decision is made."),
 dict(q="Which policy directly targets monopoly power?", choices=[
   "a corrective tax on pollution",
   "antitrust enforcement or price regulation",
   "a subsidy for education",
   "a tariff",
   "provision of a public good"], ans=1,
   why="These address the structure or conduct causing the markup."),
 dict(q="In a competitive market, a binding price ceiling causes", choices=[
   "a surplus", "a shortage and deadweight loss", "efficiency", "higher output", "no change"], ans=1,
   why="Quantity supplied falls below quantity demanded."),
 dict(q="In a monopoly, a price ceiling at the level where the demand curve meets marginal cost", choices=[
   "creates a shortage",
   "makes the firm behave like a price taker over the relevant range, producing the efficient quantity",
   "eliminates the firm's revenue",
   "reduces output",
   "has no effect"], ans=1,
   why="With a flat effective demand curve, marginal revenue equals the ceiling price."),
 dict(q="A government-imposed price floor in a competitive market causes", choices=[
   "a shortage", "a surplus and deadweight loss", "efficiency", "lower prices", "no effect"], ans=1,
   why="Quantity supplied exceeds quantity demanded at the higher price."),
 dict(q="Government intervention is most clearly justified on efficiency grounds when", choices=[
   "firms earn profit",
   "a market failure such as an externality, public good, or market power is present",
   "prices are high",
   "output is large",
   "consumers complain"], ans=1,
   why="Efficiency arguments require an identified failure of the market."),
 dict(q="Government failure refers to", choices=[
   "a market producing too little",
   "intervention that makes the outcome worse than the unregulated market",
   "a firm going bankrupt",
   "the absence of taxes",
   "an externality"], ans=1,
   why="Poor information, capture, or bad incentives can leave society worse off."),
 dict(q="Regulatory capture occurs when", choices=[
   "the government seizes a firm",
   "a regulator comes to serve the interests of the industry it regulates",
   "prices are capped",
   "a monopoly is broken up",
   "taxes are collected"], ans=1,
   why="It is a standard argument for caution about regulation."),
 dict(q="A tariff on imports in a competitive domestic market", choices=[
   "lowers the domestic price",
   "raises the domestic price, reduces imports, and creates deadweight loss",
   "eliminates deadweight loss",
   "raises consumer surplus",
   "has no effect"], ans=1,
   why="Both a production and a consumption distortion result."),
 dict(q="Which of the following is a transfer rather than a deadweight loss when a tax is imposed?", choices=[
   "the trades that no longer occur",
   "the revenue the government collects",
   "the reduction in quantity",
   "the change in behavior",
   "the excess burden"], ans=1,
   why="The revenue moves surplus rather than destroying it."),
 dict(q="Compared with an unregulated monopoly, fair-return regulation", choices=[
   "reduces output and raises price",
   "raises output, lowers price, and reduces but does not eliminate deadweight loss",
   "eliminates deadweight loss entirely",
   "causes the firm to lose money",
   "has no effect"], ans=1,
   why="Price still exceeds marginal cost when average cost is falling."),
 dict(q="Compared with fair-return regulation, socially optimal regulation", choices=[
   "produces less output",
   "produces more output at a lower price but requires a subsidy for a natural monopoly",
   "is always self-financing",
   "raises the firm's profit",
   "raises the price"], ans=1,
   why="Marginal-cost pricing reaches efficiency at the cost of the firm's solvency."),
 dict(q="A government that requires a monopolist to produce where P = MC without providing a subsidy risks", choices=[
   "excess profit", "the firm exiting the market, since it cannot cover its costs", "overproduction forever", "no change", "eliminating demand"], ans=1,
   why="A persistent loss is not sustainable."),
 dict(q="Which is the strongest efficiency argument for regulating a natural monopoly rather than allowing entry?", choices=[
   "competition is unfair",
   "duplicating the network would raise total cost without benefit",
   "regulation raises revenue",
   "consumers prefer one supplier",
   "monopolies innovate more"], ans=1,
   why="Two sets of pipes or wires serving the same street is pure waste."),
 dict(q="A per-unit tax on a monopolist is borne", choices=[
   "entirely by the firm",
   "partly by the firm and partly by consumers through a higher price",
   "entirely by consumers always",
   "by the government",
   "by no one"], ans=1,
   why="Incidence depends on the elasticity of demand, as in any market."),
 dict(q="Government provision of a public good addresses market failure by", choices=[
   "breaking up a monopoly",
   "using taxation to fund a good that free riding would otherwise leave undersupplied",
   "taxing an externality",
   "capping prices",
   "subsidizing producers"], ans=1,
   why="Compulsory payment solves the non-excludability problem."),
 dict(q="Which policy is best suited to a market with imperfect information rather than market power?", choices=[
   "an antitrust breakup",
   "mandatory disclosure or labelling requirements",
   "a price ceiling",
   "a corrective tax",
   "provision of a public good"], ans=1,
   why="The failure is missing information, so supplying it is the direct remedy."),
 dict(q="A licensing requirement for an occupation may reduce welfare if it", choices=[
   "improves quality",
   "restricts entry more than is needed to protect consumers, raising prices",
   "provides information",
   "lowers prices",
   "increases the number of providers"], ans=1,
   why="Excess restriction is a barrier to entry with little offsetting benefit."),
 dict(q="A subsidy to a monopolist per unit produced will", choices=[
   "reduce output",
   "lower its marginal cost, increasing output and lowering price",
   "have no effect on output",
   "raise the price",
   "eliminate its market power"], ans=1,
   why="It shifts marginal cost down, moving MR = MC to a larger quantity."),
 dict(q="Compared with a competitive market, the same per-unit tax in a monopoly will generally reduce quantity by", choices=[
   "exactly the same amount",
   "an amount that depends on the shape of demand and cost, and not necessarily the same amount",
   "always more",
   "always less",
   "zero"], ans=1,
   why="The monopolist's response depends on how marginal revenue slopes."),
 dict(q="Total surplus is maximized in a monopoly if regulation achieves", choices=[
   "price equal to average total cost",
   "price equal to marginal cost",
   "zero output",
   "the unregulated outcome",
   "maximum firm profit"], ans=1,
   why="P = MC is the allocative efficiency condition regardless of structure."),
 dict(q="The main practical difficulty in setting price equal to marginal cost for a regulated firm is", choices=[
   "consumers refuse",
   "the regulator must know the firm's true costs, which the firm has an incentive to overstate",
   "it always produces a profit",
   "it raises prices",
   "marginal cost does not exist"], ans=1,
   why="Information asymmetry is the central problem in cost-based regulation."),
 dict(q="A price cap that lets a regulated firm keep any cost savings is intended to", choices=[
   "eliminate profit",
   "give the firm an incentive to reduce its costs",
   "raise consumer prices",
   "reduce output",
   "remove all regulation"], ans=1,
   why="Cost-plus regulation blunts that incentive; a cap restores it."),
 dict(q="In a competitive market with no market failure, government intervention will generally", choices=[
   "increase total surplus",
   "reduce total surplus, since the unregulated outcome was already efficient",
   "have no effect",
   "eliminate deadweight loss",
   "raise output to the efficient level"], ans=1,
   why="There is nothing to correct, so a distortion is all that is added."),
 dict(q="The deadweight loss of monopoly can be reduced by", choices=[
   "raising the monopolist's price",
   "regulation or antitrust action that increases the quantity produced",
   "a lump-sum tax",
   "reducing output",
   "guaranteeing profit"], ans=1,
   why="The loss comes from restricted output, so raising output shrinks it."),
 dict(q="Which of the following does NOT reduce the deadweight loss caused by a monopoly?", choices=[
   "a well-set price ceiling",
   "a lump-sum tax on the firm's profit",
   "removing barriers to entry",
   "a per-unit subsidy on output",
   "antitrust action increasing competition"], ans=1,
   why="A lump-sum tax transfers profit without changing price or quantity."),
 dict(q="A government that taxes a monopolist's profit without changing its output has", choices=[
   "eliminated deadweight loss",
   "transferred surplus to itself while leaving the inefficiency in place",
   "raised output",
   "lowered the price",
   "created a shortage"], ans=1,
   why="The distortion is in the quantity, which a profit tax does not touch."),
 dict(q="A key trade-off in regulating natural monopolies is between", choices=[
   "price and quantity only",
   "allocative efficiency and the firm's ability to cover its costs",
   "profit and revenue",
   "fixed and variable costs",
   "entry and exit"], ans=1,
   why="Marginal-cost pricing achieves the first at the expense of the second."),
 dict(q="Government intervention in markets should be evaluated by comparing", choices=[
   "the intervention with a perfect ideal",
   "the outcome with intervention against the actual outcome without it, including the costs of intervening",
   "prices before and after only",
   "the firm's profit",
   "the number of firms"], ans=1,
   why="Both market failure and government failure are real possibilities."),
]
