# 6.5 Income and Wealth Inequality — 50 questions
# Table verified: quintile income shares summing to 100.
#   Bottom 20%: 4  | Second: 9  | Third: 15 | Fourth: 22 | Top 20%: 50
#   Cumulative: 4, 13, 28, 50, 100. Bottom 40% hold 13%; top 20% hold 50%,
#   which is more than the bottom 60% combined (28%).
TOPIC = ("6.5", "Income and Wealth Inequality", 6)
QUINT = dict(headers=["Quintile", "Share of total income"],
             rows=[["Bottom 20%", "4%"], ["Second 20%", "9%"], ["Third 20%", "15%"],
                   ["Fourth 20%", "22%"], ["Top 20%", "50%"]])
QUESTIONS = [
 dict(q="Income is best defined as", choices=[
   "the total value of what a person owns",
   "the flow of earnings a person receives over a period of time",
   "a person's savings",
   "the value of a house",
   "government spending"], ans=1,
   why="Income is a flow measured per period."),
 dict(q="Wealth is best defined as", choices=[
   "annual earnings",
   "the stock of assets a person owns, less their debts, at a point in time",
   "hourly wages",
   "government transfers",
   "consumption spending"], ans=1,
   why="Wealth is a stock measured at a moment."),
 dict(q="Wealth is typically distributed", choices=[
   "more equally than income",
   "less equally than income",
   "exactly like income",
   "equally across all households",
   "only by government"], ans=1,
   why="Assets accumulate over time and can be inherited, compounding differences."),
 dict(q="The Lorenz curve plots", choices=[
   "income against time",
   "the cumulative share of income received against the cumulative share of households",
   "prices against quantity",
   "wealth against age",
   "taxes against income"], ans=1,
   why="It is the standard graphical summary of a distribution."),
 dict(q="A Lorenz curve that lies along the 45-degree line represents", choices=[
   "complete inequality", "perfect equality of income", "a typical economy", "zero income", "maximum poverty"], ans=1,
   why="Each x% of households would receive exactly x% of income."),
 dict(q="The further a Lorenz curve bows away from the 45-degree line, the", choices=[
   "more equal the distribution", "more unequal the distribution", "higher total income", "lower total income", "smaller the population"], ans=1,
   why="A larger gap means income is more concentrated."),
 dict(q="The Gini coefficient measures", choices=[
   "average income",
   "income inequality on a scale from 0 to 1",
   "the unemployment rate",
   "total wealth",
   "the poverty line"], ans=1,
   why="It summarizes the Lorenz curve in one number."),
 dict(q="A Gini coefficient of 0 indicates", choices=[
   "perfect inequality", "perfect equality", "average inequality", "zero income", "maximum poverty"], ans=1,
   why="Everyone receives an identical share."),
 dict(q="A Gini coefficient of 1 indicates", choices=[
   "perfect equality", "perfect inequality, with one household receiving all income", "moderate inequality", "no income", "full employment"], ans=1,
   why="It is the theoretical extreme of concentration."),
 dict(q="A country whose Gini coefficient rises from 0.35 to 0.45 has become", choices=[
   "more equal", "more unequal", "richer", "poorer", "fully employed"], ans=1,
   why="A higher Gini means greater concentration of income."),
 dict(q="The Gini coefficient equals the area between the Lorenz curve and the line of equality divided by", choices=[
   "total income",
   "the entire area beneath the line of equality",
   "the population",
   "the Lorenz curve's length",
   "the poverty rate"], ans=1,
   why="That ratio normalizes the measure to lie between 0 and 1."),
 dict(q="Using the table, the bottom 40% of households receive", table=QUINT, choices=[
   "4%", "9%", "13%", "22%", "28%"], ans=2,
   why="4% + 9% = 13%."),
 dict(q="Using the table, the top 20% receive", table=QUINT, choices=[
   "22%", "28%", "50%", "72%", "100%"], ans=2,
   why="The table gives the top quintile a 50% share."),
 dict(q="Using the table, the top 20% receive more than", table=QUINT, choices=[
   "the bottom 20% only",
   "the bottom 60% combined, who receive 28%",
   "the fourth quintile only",
   "no other group",
   "the top 40%"], ans=1,
   why="4 + 9 + 15 = 28, well below 50."),
 dict(q="Using the table, the cumulative share received by the bottom 80% is", table=QUINT, choices=[
   "22%", "28%", "50%", "72%", "78%"], ans=2,
   why="4 + 9 + 15 + 22 = 50%."),
 dict(q="Using the table, this distribution is", table=QUINT, choices=[
   "perfectly equal",
   "unequal, since each quintile would receive 20% under perfect equality",
   "impossible",
   "the same as a Gini of zero",
   "evenly spread"], ans=1,
   why="The shares run from 4% to 50% rather than sitting at 20% each."),
 dict(q="Using the table, plotting these cumulative shares would produce a Lorenz curve that", table=QUINT, choices=[
   "lies on the 45-degree line",
   "bows below the 45-degree line",
   "lies above the 45-degree line",
   "is vertical",
   "is horizontal"], ans=1,
   why="Cumulative shares of 4, 13, 28, 50, 100 all fall below 20, 40, 60, 80, 100."),
 dict(q="Which of the following is a major source of income inequality?", choices=[
   "identical education across the population",
   "differences in human capital, skills, and education",
   "equal inheritance",
   "identical abilities",
   "uniform wages"], ans=1,
   why="Differences in productivity translate into differences in earnings."),
 dict(q="Human capital refers to", choices=[
   "physical machinery",
   "the knowledge, skills, and experience embodied in workers",
   "financial assets",
   "the number of workers",
   "company shares"], ans=1,
   why="It is the productive capacity people carry with them."),
 dict(q="Investment in education raises a worker's income mainly by", choices=[
   "reducing hours worked",
   "raising the worker's marginal revenue product",
   "lowering the firm's costs only",
   "increasing labor supply",
   "reducing taxes"], ans=1,
   why="More productive workers command higher wages."),
 dict(q="Discrimination in the labor market can create inequality by", choices=[
   "raising everyone's wages",
   "paying equally productive workers different wages based on characteristics unrelated to productivity",
   "eliminating market power",
   "increasing labor supply",
   "reducing prices"], ans=1,
   why="It breaks the link between productivity and pay."),
 dict(q="A progressive tax is one in which", choices=[
   "everyone pays the same amount",
   "the average tax rate rises as income rises",
   "the average tax rate falls as income rises",
   "the tax rate is constant",
   "only the poor pay tax"], ans=1,
   why="Higher earners pay a larger share of their income."),
 dict(q="A regressive tax is one in which", choices=[
   "the average tax rate rises with income",
   "the average tax rate falls as income rises",
   "the rate is constant",
   "no one pays tax",
   "only the rich pay tax"], ans=1,
   why="It takes a larger share of a low income than a high one."),
 dict(q="A proportional, or flat, tax is one in which", choices=[
   "the average rate rises with income",
   "everyone pays the same percentage of income",
   "the average rate falls with income",
   "the tax is a fixed dollar amount",
   "only wages are taxed"], ans=1,
   why="The average rate is constant across incomes."),
 dict(q="A sales tax on necessities is generally", choices=[
   "progressive", "regressive, since lower-income households spend a larger share of income on them", "proportional", "a transfer", "a subsidy"], ans=1,
   why="The same tax takes a bigger bite out of a smaller income."),
 dict(q="A household earning $30,000 pays $3,000 in tax and one earning $100,000 pays $25,000. This tax is", choices=[
   "regressive", "progressive", "proportional", "a lump sum", "a subsidy"], ans=1,
   why="Average rates are 10% and 25%, rising with income."),
 dict(q="A household earning $20,000 pays $2,400 in tax and one earning $80,000 pays $6,400. This tax is", choices=[
   "progressive", "regressive", "proportional", "a transfer", "a corrective tax"], ans=1,
   why="Average rates are 12% and 8%, falling as income rises."),
 dict(q="A household earning $50,000 pays $7,500 and one earning $150,000 pays $22,500. This tax is", choices=[
   "progressive", "regressive", "proportional at 15%", "a lump sum", "a subsidy"], ans=2,
   why="Both pay 15% of income."),
 dict(q="A transfer payment is", choices=[
   "a payment for goods or services",
   "a government payment to a household for which no good or service is exchanged",
   "a tax",
   "a wage",
   "a business subsidy only"], ans=1,
   why="Unemployment benefits and pensions are transfers."),
 dict(q="Transfer payments and progressive taxes tend to make the after-tax, after-transfer distribution of income", choices=[
   "less equal", "more equal than the market distribution", "identical to the market distribution", "perfectly equal", "unmeasurable"], ans=1,
   why="Both narrow the gap between the top and bottom."),
 dict(q="An in-kind transfer is", choices=[
   "a cash payment",
   "a transfer of goods or services rather than money, such as food assistance or healthcare",
   "a tax rebate",
   "a wage",
   "a loan"], ans=1,
   why="It provides a specific good instead of general purchasing power."),
 dict(q="Measured inequality often understates the effect of government policy because official income figures may exclude", choices=[
   "wages",
   "in-kind transfers and the effect of taxes",
   "interest income",
   "rent",
   "profit"], ans=1,
   why="Market income measured before taxes and non-cash benefits looks more unequal than living standards are."),
 dict(q="The poverty line is", choices=[
   "the average income",
   "an income threshold below which a household is classified as poor",
   "the median wage",
   "the Gini coefficient",
   "the minimum wage"], ans=1,
   why="It is a threshold, not an average."),
 dict(q="The poverty rate measures", choices=[
   "average income",
   "the percentage of the population with income below the poverty line",
   "total wealth",
   "the unemployment rate",
   "income inequality overall"], ans=1,
   why="It counts people below a threshold rather than describing the whole distribution."),
 dict(q="A country can have a falling poverty rate and rising inequality at the same time because", choices=[
   "the two measures are the same",
   "the poor may be getting better off while the very top pulls further ahead",
   "inequality cannot change",
   "poverty is not measurable",
   "the Gini is always zero"], ans=1,
   why="One measures a threshold, the other the shape of the whole distribution."),
 dict(q="A key trade-off in redistribution policy is between", choices=[
   "inflation and unemployment",
   "greater equality and the incentives to work, save, and invest",
   "imports and exports",
   "fixed and variable costs",
   "price and quantity"], ans=1,
   why="High marginal rates and benefit withdrawal can blunt incentives."),
 dict(q="The efficiency cost of redistribution arises because taxes and transfers", choices=[
   "raise total output",
   "change the incentives people face, altering behavior",
   "are impossible to collect",
   "are always regressive",
   "eliminate all income"], ans=1,
   why="Deadweight loss comes from behavioral responses."),
 dict(q="Which of the following would tend to reduce income inequality?", choices=[
   "cutting the top marginal tax rate",
   "expanding access to education and training for low-income households",
   "eliminating transfer payments",
   "making the tax system more regressive",
   "restricting entry into professions"], ans=1,
   why="Raising human capital at the bottom lifts market incomes there."),
 dict(q="Which of the following would tend to increase measured income inequality?", choices=[
   "expanding a progressive income tax",
   "a rise in the return to skills that only some workers possess",
   "raising in-kind transfers",
   "universal education",
   "reducing discrimination"], ans=1,
   why="Skill-biased change widens the gap between skilled and unskilled pay."),
 dict(q="The market distribution of income tends to be", choices=[
   "more equal than the after-tax distribution",
   "less equal than the distribution after taxes and transfers",
   "identical to it",
   "always perfectly equal",
   "unrelated to it"], ans=1,
   why="Redistribution compresses the distribution."),
 dict(q="Income mobility refers to", choices=[
   "moving between geographic regions",
   "the extent to which individuals or families move between income groups over time",
   "changes in the poverty line",
   "the Gini coefficient",
   "the unemployment rate"], ans=1,
   why="A snapshot of inequality says nothing about movement within it."),
 dict(q="High income mobility means that a given level of measured inequality is", choices=[
   "necessarily worse",
   "arguably less troubling, because individuals do not stay in the same position permanently",
   "impossible",
   "the same as zero inequality",
   "unmeasurable"], ans=1,
   why="Lifetime inequality is lower than a one-year snapshot suggests."),
 dict(q="Inheritance contributes to wealth inequality because", choices=[
   "it raises wages",
   "assets pass across generations, so advantages compound over time",
   "it reduces savings",
   "it is taxed at 100%",
   "it lowers returns to capital"], ans=1,
   why="Wealth begets wealth in a way annual earnings do not."),
 dict(q="A negative income tax or earned income credit is designed to", choices=[
   "tax the poor more heavily",
   "supplement low earnings while preserving an incentive to work",
   "eliminate all taxes",
   "reduce employment",
   "raise the poverty line"], ans=1,
   why="Phasing support out gradually avoids a sharp benefit cliff."),
 dict(q="A benefit that is withdrawn abruptly as income rises can create", choices=[
   "a strong incentive to earn more",
   "a high effective marginal tax rate that discourages additional earnings",
   "perfect equality",
   "a Gini of zero",
   "no behavioral effect"], ans=1,
   why="The loss of benefits can exceed the extra earnings."),
 dict(q="Compared with income inequality, wealth inequality is generally", choices=[
   "smaller", "larger in most economies", "identical", "zero", "impossible to measure"], ans=1,
   why="Accumulated stocks are more concentrated than annual flows."),
 dict(q="Which is the best single graphical summary of a country's income distribution?", choices=[
   "a supply and demand diagram",
   "a Lorenz curve",
   "a production possibilities curve",
   "a cost curve diagram",
   "a payoff matrix"], ans=1,
   why="It shows cumulative shares directly."),
 dict(q="Two countries with the same Gini coefficient", choices=[
   "must have identical income distributions",
   "may have differently shaped Lorenz curves that happen to produce the same summary number",
   "must have the same average income",
   "must have the same poverty rate",
   "cannot both exist"], ans=1,
   why="A single number cannot capture every feature of a distribution."),
 dict(q="An economist evaluating a redistribution policy would consider", choices=[
   "equity alone",
   "both its effect on the distribution of income and its effect on efficiency and incentives",
   "efficiency alone",
   "tax revenue alone",
   "the Gini coefficient alone"], ans=1,
   why="The trade-off between the two is the substance of the debate."),
 dict(q="The statement that a distribution is efficient tells us", choices=[
   "that it is fair",
   "nothing about whether it is fair, since efficiency concerns the size of total surplus rather than its division",
   "that it is equal",
   "that inequality is zero",
   "that redistribution is impossible"], ans=1,
   why="Efficiency and equity are distinct criteria."),
]
